#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Uniquery Support lib directory
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# JARs made by this makefile are used by more than one compenent of the
# Uniquery direcotry.


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/j2ee/uniquery/Support/lib

STATICS = commons-lang-2.3.jar lucene-core-2.3.1.jar 


# ---------------  Production Rules  ------------------------------------

# Use defualt rules 

include $(TOP)/make.default.rules
