#! /bin/perl -wT
# opt in A-Za-z0-9-_$+=~.,
$ENV{PATH} = "/bin:<!--|ROOT_PATH|-->/server_apps/sysexecs/encryptpass/";
# =~ tr/\&/ 
$ARGV[0] =~ m/([A-Za-z\d\-\_\$\+\=\~\.\,]+)/; 
my $pw = $1;
system("/bin/echo $pw | /bin/crypt 'dedicated to George Streisinger' | encode");

`echo "$pw" >! /tmp/tomc/foo`;