#! /usr/local/bin/perl -wT
# opt in A-Za-z0-9-_$+=~.,
$ENV{PATH} = "/bin:<!--|ROOT_PATH|-->/server_apps/sysexecs/encryptpass/";

$ARGV[0] =~  m/([A-Za-z\d\-\_\$\+\=\~\.\,\ ]+)/;
my $pw = substr("$1",0,8);

use Digest::MD5 qw(md5_hex); 
print md5_hex($pw.'{dedicated to George Streisinger}');
