#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Person related pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/personbrowser

GENERICS = new_person.apg persselect.apg \
	persupdate.apg persview.apg process-person.apg quickfindpers.apg \
	update-person.apg quickPersForm.apg updateaddress.apg \
	process_address_update.apg 
STATICS = persprintable.apg sourceview.apg 


# Use default rules for app page directories

include $(TOP)/make.default.apg.rules

