#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, WWW/home/ZFIN/help_files subdirectory
#
# $Source$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/help_files

GENERICS = label.html
STATICS  = fishselecthelp.html mut_intro.html help-fish.html \
	   generichelp.html mapperselecthelp.html international_characters.html \
	   sequence_tools_help.html

# --------------------------  Rules  ------------------------------------

# Use default rules

include $(TOP)/make.default.rules

