#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Publication editing APP pages.
#
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/pubbrowser/EDITpubs

STATICS =  edit_pub.apg process-pub.apg new_journal.apg \
	   do-jrnlupdate.apg process-journal.apg


# use default rules for app page directories

include $(TOP)/make.default.apg.rules

