#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Anatomy-48 hours Static web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/anatomy/48hrs

# All of the dynamics can be moved back under the statics after the initial 
# load.

STATICS = 48hrs.html S017.html S018.html S019.html S020.html S021.html \
	S022.html S023.html S024.html S025.html S026.html S027.html S028.html \
	S029.html S030.html S031.html S032.html S033.html S034.html S035.html \
	S036.html S037.html S038.html
#GENERICS = 



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
