#!/bin/bash

hookName="$(basename "$0")"

print () {
  echo "[$hookName] $1"
  echo ""
}

run_cmd () {
  print "running '$@'"
  "$@"
  status=$?
  if [ $status -ne 0 ]; then
    print "ABORTING! '$@' failed."
    exit $status
  fi
}
