#!/bin/bash

hookName="$(basename "$0")"

print () {
  echo "[$hookName] $1"
}

run_cmd () {
  print "running '$*'"
  "$@"
  status=$?
  if [ $status -ne 0 ]; then
    print "ABORTING! '$*' failed"
    exit $status
  fi
}

run_if_changes () {
	echo "$1" | grep --quiet "$2" && print "$2 changed" && run_cmd $3
}
