#!/bin/bash

source $(dirname "$0")/helpers

changed_files=$(git diff --cached --name-only --diff-filter=ACMR)

run_if_changes "$changed_files" home/javascript/react/ "npm run lint"

check_for_comment_marker "$changed_files"

exit 0
