#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Static web pages, Staging photos
# directory.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/images/staging_photos

STATICS = fig11.gif fig13.gif fig15.1.gif fig15.2.gif fig29.1.gif fig29.2.gif \
	fig29.3.gif fig3.gif fig30.gif fig31.gif fig39.1.epsf fig39.2.epsf \
	fig4.gif fig4.gifs fig41.gif fig8.gif fig8.gifs


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
