#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Anatomy-24 hours Static web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/anatomy/24hrs

# All of the generics can be moved back under the statics after the initial
# load.

STATICS = 24hrs.html 24hrsd1.html \
	S001.html S002.html S003.html S004.html S005.html S006.html S007.html \
	S008.html S009.html S010.html S011.html S012.html S013.html S014.html \
	S015.html S016.html
#GENERICS = 



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
