#!/bin/sh

cd gbrowse

mkdir -p $TARGETROOT/tmp
chmod o+w $TARGETROOT/tmp


rsync -r -C --exclude=.svn ./lib/Bio $LIBTARGET/Bio
#cp -R ./lib/Bio $LIBTARGET/Bio

#/private/bin/perl
/usr/bin/perl -I $LIBTARGET Makefile.PL APACHE=$TARGETROOT LIB=$LIBTARGET BIN=$TARGETROOT/bin PREFIX=$TARGETROOT HTDOCS=$TARGETROOT GBROWSE_ROOT=gbrowse CGIBIN=$TARGETROOT/cgi-perl CONF=$TARGETROOT/conf INSTALLSITEMAN1DIR=0 INSTALLSITEMAN3DIR=0 INFORMIXDIR=$INFORMIXDIR INFORMIXSERVER=$INFORMIXSERVER SQLHOSTS_FILE=$INFORMIXSQLHOSTS NONROOT=1 DO_XS=0

#cd gbrowse && 
make
#cd gbrowse && 
make install
