#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Anatomy-120 hours Static web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/anatomy/120hrs

# All of the generics can be moved back under statics after the initial load.

STATICS =  120hrs.html S058.html S059.html S059_5.html S060.html S061.html \
	S062.html S063.html S064.html S065.html S066.html S067.html S068.html \
	S069.html S070.html S071.html S072.html S073.html S074.html S075.html \
	S076.html S077.html
#GENERICS =



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
