#!/bin/tcsh

cp @BLASTSERVER_BLAST_DATABASE_PATH@/Current/LoadedMicroRNAMature.xn* @BLASTSERVER_BLAST_DATABASE_PATH@/Backup 
cp @BLASTSERVER_BLAST_DATABASE_PATH@/Current/LoadedMicroRNAStemLoop.xn* @BLASTSERVER_BLAST_DATABASE_PATH@/Backup 


cp @WEBHOST_BLAST_DATABASE_PATH@/Current/LoadedMicroRNAMature* @BLASTSERVER_BLAST_DATABASE_PATH@/Current/
cp @WEBHOST_BLAST_DATABASE_PATH@/Current/LoadedMicroRNAStemLoop* @BLASTSERVER_BLAST_DATABASE_PATH@/Current/

exit
