--liquibase formatted sql
--changeset rtaylor:ZFIN-8731.sql

INSERT INTO zdb_active_data (zactvd_zdb_id) VALUES ('ZDB-NCRNAG-030131-1');

insert into marker (mrkr_zdb_id, mrkr_name, mrkr_comments, mrkr_abbrev, mrkr_type, mrkr_owner, mrkr_name_order)
select 'ZDB-NCRNAG-030131-1', mrkr_name || '_temp', mrkr_comments, mrkr_abbrev || '_temp', 'NCRNAG', mrkr_owner, mrkr_name_order
from marker
where mrkr_zdb_id = 'ZDB-GENE-030131-3058';

-- updates as performed if running merge_markers.pl
update marker_history set mhist_mrkr_zdb_id = 'ZDB-NCRNAG-030131-1' where mhist_mrkr_zdb_id = 'ZDB-GENE-030131-3058';
update marker_history_audit set mha_mrkr_zdb_id = 'ZDB-NCRNAG-030131-1' where mha_mrkr_zdb_id = 'ZDB-GENE-030131-3058';
update marker_relationship set mrel_mrkr_1_zdb_id = 'ZDB-NCRNAG-030131-1' where mrel_mrkr_1_zdb_id = 'ZDB-GENE-030131-3058';
update data_alias set dalias_data_zdb_id = 'ZDB-NCRNAG-030131-1' where dalias_data_zdb_id = 'ZDB-GENE-030131-3058';
update db_link set dblink_linked_recid = 'ZDB-NCRNAG-030131-1' where dblink_linked_recid = 'ZDB-GENE-030131-3058';
update paneled_markers set zdb_id = 'ZDB-NCRNAG-030131-1' where zdb_id = 'ZDB-GENE-030131-3058';
update sequence_feature_chromosome_location_generated set sfclg_data_zdb_id = 'ZDB-NCRNAG-030131-1' where sfclg_data_zdb_id = 'ZDB-GENE-030131-3058';
update record_attribution set recattrib_data_zdb_id = 'ZDB-NCRNAG-030131-1' where recattrib_data_zdb_id = 'ZDB-GENE-030131-3058';

-- not in merge_markers.pl
 -- zfin_ensembl_gene table? not needed as it is regenerated by generateGff3
 -- SELECT * FROM zfin_ensembl_gene where zeg_gene_zdb_id = 'ZDB-GENE-030131-3058';

 -- zmap_pub_pan_mark table
 update zmap_pub_pan_mark set zdb_id= 'ZDB-NCRNAG-030131-1' where zdb_id = 'ZDB-GENE-030131-3058';

 -- unique_location table
 update unique_location set ul_data_zdb_id = 'ZDB-NCRNAG-030131-1' where ul_data_zdb_id = 'ZDB-GENE-030131-3058';

 -- updates table
 update updates set rec_id = 'ZDB-NCRNAG-030131-1' where rec_id = 'ZDB-GENE-030131-3058';

-- end of updates not in merge_markers.pl


-- create alias and nomenclature history (is this necessary for ID change? or only for name change?)
insert into zdb_active_data values('ZDB-DALIAS-230701-1');
insert into data_alias (dalias_zdb_id, dalias_data_zdb_id, dalias_alias, dalias_group_id)
values ('ZDB-DALIAS-230701-1', 'ZDB-NCRNAG-030131-1', 'si:ch211-273l18.4', '1');

insert into zdb_active_data values('ZDB-NOMEN-230701-1');
insert into marker_history (mhist_zdb_id, mhist_mrkr_zdb_id, mhist_event, mhist_reason, mhist_date,
                            mhist_mrkr_name_on_mhist_date, mhist_mrkr_abbrev_on_mhist_date, mhist_comments,mhist_dalias_zdb_id)
values ('ZDB-NOMEN-230701-1', 'ZDB-NCRNAG-030131-1', 'renamed', 'same marker', now(),
        'si:ch211-273l18.4', 'si:ch211-273l18.4', 'ID changed from ZDB-GENE-030131-3058 to ZDB-NCRNAG-030131-1', 'ZDB-DALIAS-230701-1');
-- end of alias / nomenclature

-- delete db_link for "AGR Gene" foreign DB
delete from zdb_active_data
where exists(select 1 from db_link
             where dblink_zdb_id = zactvd_zdb_id
               and dblink_linked_recid = 'ZDB-NCRNAG-030131-1'
               and dblink_acc_num = 'ZDB-GENE-030131-3058'
               and dblink_fdbcont_zdb_id = 'ZDB-FDBCONT-171018-1');


delete from zdb_replaced_data where zrepld_old_zdb_id = 'ZDB-GENE-030131-3058';
update zdb_replaced_data set zrepld_new_zdb_id = 'ZDB-NCRNAG-030131-1' where zrepld_new_zdb_id = 'ZDB-GENE-030131-3058';
delete from zdb_active_data where zactvd_zdb_id = 'ZDB-GENE-030131-3058';
insert into zdb_replaced_data (zrepld_old_zdb_id, zrepld_new_zdb_id) values ('ZDB-GENE-030131-3058', 'ZDB-NCRNAG-030131-1');

update marker set mrkr_name = 'si:ch211-273l18.4', mrkr_abbrev = 'si:ch211-273l18.4' where mrkr_zdb_id = 'ZDB-NCRNAG-030131-1';

select regen_genox_marker('ZDB-NCRNAG-030131-1');
------ end of changes by perl script

