--FILE: load_files.sql
--INPUT VARS: files must exist in /tmp/
--    fl_image_modified, fl_pdf_modified
--    These files are generated by a perl script: remove_orphan_files.pl
--OUTPUT: two files that contain filenames that exist in the filesystem
--    but not in the database.
--    Also outputs to unload files to the temp directory
--    /tmp/orphan_image_files.unl
--    /tmp/orphan_pdf_files.unl


--wrap all work in a transaction
begin work ;

--create 2 temp tables to hold the input files 

create temp table tmp_image_file_list (
	filename varchar(65)) 
with no log ;

--use an index to speed this up 

create unique index tmp_filename_primary_key_index
  on tmp_image_file_list (filename)
  using btree in idxdbs1 ;

create temp table tmp_pdf_file_list (
	filename varchar(65)) 
with no log ;

create unique index tmp_filename_pdf_primary_key_index
  on tmp_pdf_file_list (filename)
  using btree in idxdbs1 ;

--load the files existing in /tmp with proper permissions

load from /tmp/fl_image_modified insert into tmp_image_file_list ;
load from /tmp/fl_pdf_modified insert into tmp_pdf_file_list ;

--create temp tables to store the mismatches (one for pdfs, one for
--images. )

create temp table tmp_not_in_images (
	filename varchar(65)
) with no log ;

create temp table tmp_not_in_pub (
	filename varchar(65)
) with no log ;

create temp table tmp_not_in_image_files (
	filename varchar(65)
) with no log ;

create temp table tmp_not_in_pub_files (
	filename varchar(65)
) with no log ;


--do the inserts, create temp tables full of images not in the database
--from the list of images in the filesystem, and the inverse, images files
--listed in the database that are not listed in the filesystem.  Images
--not in the filesystem will just be sent to dba as an email, script that 
--calls this sql script will not deal with these automatically as they 
--indicate something very wrong with the upload world.

insert into tmp_not_in_images
  select filename
	from tmp_image_file_list
	where not exists (select 'x' 
				from image
				where filename = img_image);


insert into tmp_not_in_image_files
  select img_image 
	from image 
	where img_image not in (select filename
				   from tmp_image_file_list) ;


unload to /tmp/filesystem_images_not_in_database.unl
  select * from tmp_not_in_image_files ;

update statistics high for table tmp_pdf_file_list ;

insert into tmp_not_in_pub
  select filename
	from tmp_pdf_file_list
	where not exists (select 'x' from publication
				where pub_file = filename);

insert into tmp_not_in_pub_files
  select pub_file
	from publication
	where not exists (select 'x' from tmp_pdf_file_list
				where pub_file = filename)
	and pub_file is not null;

unload to /tmp/filesystem_pdfs_not_in_database.unl
  select * from tmp_not_in_pub_files ;


--produce the files not in the database

unload to /tmp/orphan_image_files.unl
  select * from tmp_not_in_images ;

unload to /tmp/orphan_pdf_files.unl
  select * from tmp_not_in_pub ;

commit work ;