#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Zebrafish News directory.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/news

# Subdirectories come and go as meetings come and go.


# List permanent files first -- files that will stay around no matter what
# announcements come and go.  Follow that list with files that will disappear
# when the meetings or jobs they go with will disappear.

VARIABLE_GENERICS = jobs.html mtgs.html curator.html

GENERICS = siteNews.html usersurvey2005.html ZFIN_jobs.html $(VARIABLE_GENERICS)



STATICS =  Newsletter_Summer04.pdf Madison_2004_poster.jpg RegistrationForm.pdf newsgroup.html funding_opps.html ISDB2005.pdf Newsletter_Winter05.pdf Newsletters.html Newsletter_Summer05.pdf Newsletter_Winter06.pdf Newsletter_Summer2006.pdf ANZZFWksp2007RegForm.doc

 




# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules


