#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Navigation app pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/navigation_files

# navigator.html is loaded into the database.  Treat it as an app page.
#  Therefore, treat it as if it were generic, even though its not.

GENERICS = 
SPECIFICS=navigator.html


# Use default rules for app page directories

include $(TOP)/make.default.apg.rules

