<%@ include file="/WEB-INF/jsp-include/tag-import.jsp" %>

<%@ attribute name="name" type='java.lang.String' required="true" %>
<%@ attribute name="fromChimericClone" type='java.lang.Boolean' required="false" %>

<c:if test="${fn:contains(name,':')}">
    <c:choose>
        <c:when test="${fn:startsWith(name,'WITHDRAWN:')}">
            <p>
                    ${ fromChimericClone ?
                            "This gene has been withdrawn because it was derived from a chimeric clone."
                            :
                            "This gene was based on a non-zebrafish clone and has been withdrawn."
                            }
                <img src="/images/warning-noborder.gif" title="Withdrawn" alt="Withdrawn" width="20" height="20" align="top">
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'ch:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'ch' indicates this gene
                is represented by an EST generated at Children's Hospital.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'df:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomencla
                ture based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'df' indicates this
                gene is represented by an EST generated at Dana-Farber Cancer Institute.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'gb:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature. The prefix 'gb' indicates this gene
                is represented by an EST from GenBank.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'id:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'id' indicates this
                gene is represented by an EST generated at National Institute of
                Child Health and Human Development, NIH.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'ig:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'ig' indicates this
                gene is represented by an EST generated at The Institute for Genomic
                Research.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'ik:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'im:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature. The prefix im: indicates this gene
                is represented by an EST generated by the I.M.A.G.E. Consortium.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'hm:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'hm' indicates this
                gene is represented by an EST generated at Harvard Medical School.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'mg:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'mg' indicates this
                gene is represented by an EST generated at Massachusetts General
                Hospital.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'mp:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'mp' indicates this
                gene is represented by an EST generated at Max-Planck-Institute
                fuer Molekulare Genetik.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'ns:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.   The prefix 'ns' indicates this
                gene is represented by an EST generated at National University of
                Singapore.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'sb:eu')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by a PCR fragment. When more is
                known about the gene, the current gene nomenclature based on the
                placeholder name will be replaced with more traditional zebrafish
                gene nomenclature. The prefix sb: indicates this gene is represented
                by a genomic sequence submitted by the Thisse Lab.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'sb:cb')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature. The prefix sb: indicates this gene
                is represented by an EST generated at the Thisse Lab.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'si:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is derived from the zebrafish genome sequencing and
                annotation project. When more is known about the gene, the current
                nomenclature will be replaced with more traditional zebrafish gene
                nomenclature. The prefix 'si:' indicates that this gene is represented
                by annotated genomic sequence from the Sanger Institute.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'wu:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature. The prefix wu: indicates this gene
                is represented by an EST generated at Washington University School
                of Medicine.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'sc:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by a cDNA or collection of cDNAs.
                When more is known about the gene, the current gene nomenclature
                based on the cDNA name will be replaced with more traditional
                zebrafish gene nomenclature. The prefix sc: indicates this gene
                is represented by a cDNA generated by a lab at the Sanger Institute,
                Cambridge
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'xx:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized solely by an EST or collection of ESTs.
                When more is known about the gene, the current gene nomenclature
                based on the EST name will be replaced with more traditional
                zebrafish gene nomenclature.
            </p>
        </c:when>
        <c:when test="${fn:startsWith(name,'zgc:')}">
            <p>
                <b>Nomenclature Note:</b>
                This gene is characterized by full length cDNAs isolated as part
                of the Zebrafish Gene Collection (ZGC). When more is known about
                the gene, the current nomenclature will be replaced with more
                traditional zebrafish gene nomenclature. The prefix `zgc:'
                indicates that this gene is represented by cDNAs generated by the
                ZGC project.
            </p>
        </c:when>

    </c:choose>
</c:if>