#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Miscellaneous HTML pages.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/misc_html
GENERICS  = error.html intro1.html intro_mapper.html tips.html \
            wrong_browser.html AB-Search.htm AB-Submission_2.htm \
            AB-Submission.htm antibody4.htm antibody5.htm
STATICS   = blank.html saycomposing.html saysearching.html



# --------------------------  Rules  ------------------------------------

# use default rules for directories withou app pages.

include $(TOP)/make.default.rules
