document.write("</td></tr></table>")
document.write("<table width=100% class=\"header\" cellpadding=0 cellspacing=0>");
document.write("  <tr>");
document.write("    <td class=\"footer\">");
document.write("      <table valign=center width=100%>");
document.write("        <tr>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/index.html\">Home</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("	     <a href=\"mailto:zfinadmn@zfin.org\">Email ZFIN</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/zf_info/dbase/db.html\">About ZFIN</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/ZFIN/misc_html/tips.html\">Helpful Hints</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/zf_info/citation.html\">Citing ZFIN</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("        </tr>");
document.write("      </table>");
document.write("    </td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align=center class=\"ack\">");
document.write("      <DIV class=\"ack\">");
document.write("      <A HREF=\"http://<!--|DOMAIN_NAME|-->/warranty.html\">Disclaimer,limitations, copyright</A> &copy <A HREF=\"http://www.uoregon.edu\">University of Oregon</a>, 1994-2007, <A HREF=\"http://www.ci.eugene.or.us/\">Eugene</a> , Oregon.");
document.write("      </DIV>");
document.write("    </td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align=center class=\"ack\">");
document.write("      <DIV class=\"ack\">");
document.write("      <font size=-2>ZFIN logo design by Kari Pape, </font> <A HREF=\"http://www.uoregon.edu\"><font size =-2>University of Oregon</font></a>");
document.write("      </DIV>");
document.write("    </td>");
document.write("  </tr>");
document.write("</table>");
document.write("</body>");
document.write("</html>");
