document.write("</td></tr></table>")
document.write("<table width=100% class=\"header\" cellpadding=0 cellspacing=0>");
document.write("  <tr>");
document.write("    <td class=\"footer\">");
document.write("      <table valign=center width=100%>");
document.write("        <tr>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/index.html\">Home</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("	     <a href=\"mailto:zfinadmn@zfin.org\">Email ZFIN</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/zf_info/dbase/db.html\">About ZFIN</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/ZFIN/misc_html/tips.html\">Helpful Hints</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("          <td align=center class=\"footer\">");
document.write("	   <DIV class=\"header\">");
document.write("            <A HREF=\"/zf_info/citation.html\">Citing ZFIN</a>");
document.write("	   </DIV>");
document.write("          </td>");
document.write("        </tr>");
document.write("      </table>");
document.write("    </td>");
document.write("  </tr>");
document.write("  <tr>");
document.write("    <td align=center>");
document.write("      Copyright &copy University of Oregon, 1994-2002.");
document.write("    </td>");
document.write("  </tr>");
document.write("</table>");
document.write("</body>");
document.write("</html>");
