--liquibase formatted sql
--changeset rtaylor:ZFIN-9295.sql


alter table fluorescent_protein add column fp_uuid varchar(8);

UPDATE fluorescent_protein SET fp_uuid = '4JYN3' WHERE fp_name = 'mTFP1-Y67W';
UPDATE fluorescent_protein SET fp_uuid = '671NA' WHERE fp_name = 'P4';
UPDATE fluorescent_protein SET fp_uuid = '6F9A8' WHERE fp_name = 'Maroon0.1';
UPDATE fluorescent_protein SET fp_uuid = '8TL1P' WHERE fp_name = 'AsRed2';
UPDATE fluorescent_protein SET fp_uuid = '9GUD2' WHERE fp_name = 'mBanana';
UPDATE fluorescent_protein SET fp_uuid = '9PBZV' WHERE fp_name = 'cpCitrine';
UPDATE fluorescent_protein SET fp_uuid = 'AJJAK' WHERE fp_name = 'TagRFP658';
UPDATE fluorescent_protein SET fp_uuid = 'AL871' WHERE fp_name = 'mGrape1';
UPDATE fluorescent_protein SET fp_uuid = 'AQ2DU' WHERE fp_name = 'mGinger1';
UPDATE fluorescent_protein SET fp_uuid = 'AYRSR' WHERE fp_name = 'miRFP2';
UPDATE fluorescent_protein SET fp_uuid = 'B72B1' WHERE fp_name = 'deGFP3';
UPDATE fluorescent_protein SET fp_uuid = 'BU5R3' WHERE fp_name = 'Sirius';
UPDATE fluorescent_protein SET fp_uuid = 'BUJNN' WHERE fp_name = 'dKeima570';
UPDATE fluorescent_protein SET fp_uuid = 'CC2YL' WHERE fp_name = 'RDSmCherry1';
UPDATE fluorescent_protein SET fp_uuid = 'FLO5T' WHERE fp_name = 'mHoneydew';
UPDATE fluorescent_protein SET fp_uuid = 'GSP4M' WHERE fp_name = 'mGinger2';
UPDATE fluorescent_protein SET fp_uuid = 'H6RGM' WHERE fp_name = 'mGrape2';
UPDATE fluorescent_protein SET fp_uuid = 'J5Y7Z' WHERE fp_name = 'RCaMP';
UPDATE fluorescent_protein SET fp_uuid = 'KCUBM' WHERE fp_name = 'GFPxm181uv';
UPDATE fluorescent_protein SET fp_uuid = 'LDZC9' WHERE fp_name = 'deGFP4';
UPDATE fluorescent_protein SET fp_uuid = 'LP3PQ' WHERE fp_name = 'HcRed';
UPDATE fluorescent_protein SET fp_uuid = 'NLF4R' WHERE fp_name = 'TagRFP675';
UPDATE fluorescent_protein SET fp_uuid = 'PG1ZQ' WHERE fp_name = 'phiLOV3';
UPDATE fluorescent_protein SET fp_uuid = 'Q5F5J' WHERE fp_name = 'SNIFP';
UPDATE fluorescent_protein SET fp_uuid = 'Q8TQ6' WHERE fp_name = 'mNeptune684';
UPDATE fluorescent_protein SET fp_uuid = 'QNUKK' WHERE fp_name = 'iq-mKate2';
UPDATE fluorescent_protein SET fp_uuid = 'REVUQ' WHERE fp_name = 'mNeptune681';
UPDATE fluorescent_protein SET fp_uuid = 'RFJ23' WHERE fp_name = 'alajGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'RO9XQ' WHERE fp_name = '10B';
UPDATE fluorescent_protein SET fp_uuid = 'RU9EF' WHERE fp_name = 'LSS-mKate2';
UPDATE fluorescent_protein SET fp_uuid = 'THWKH' WHERE fp_name = 'deGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'V25UH' WHERE fp_name = 'alajGFP3';
UPDATE fluorescent_protein SET fp_uuid = 'VAPCK' WHERE fp_name = 'apulFP483';
UPDATE fluorescent_protein SET fp_uuid = 'VGW8W' WHERE fp_name = 'amilFP497';
UPDATE fluorescent_protein SET fp_uuid = 'VQMW2' WHERE fp_name = 'amFP506';
UPDATE fluorescent_protein SET fp_uuid = 'W92N1' WHERE fp_name = '11';
UPDATE fluorescent_protein SET fp_uuid = 'WBLSA' WHERE fp_name = 'aceGFP-h';
UPDATE fluorescent_protein SET fp_uuid = 'XU2WO' WHERE fp_name = 'mPlum';
UPDATE fluorescent_protein SET fp_uuid = 'ZMWEJ' WHERE fp_name = 'Azurite';
UPDATE fluorescent_protein SET fp_uuid = 'MY788' WHERE fp_name = 'RSGFP4';
UPDATE fluorescent_protein SET fp_uuid = '3F18R' WHERE fp_name = 'Ultramarine';
UPDATE fluorescent_protein SET fp_uuid = '588N2' WHERE fp_name = 'mScarlet-H';
UPDATE fluorescent_protein SET fp_uuid = '7FXGZ' WHERE fp_name = 'eqFP670';
UPDATE fluorescent_protein SET fp_uuid = '9HU84' WHERE fp_name = 'ECGFP';
UPDATE fluorescent_protein SET fp_uuid = 'A77ZH' WHERE fp_name = 'td-RFP639';
UPDATE fluorescent_protein SET fp_uuid = 'ANK6E' WHERE fp_name = 'amFP495';
UPDATE fluorescent_protein SET fp_uuid = 'C2N5S' WHERE fp_name = 'TagRFP657';
UPDATE fluorescent_protein SET fp_uuid = 'CS45L' WHERE fp_name = 'RDSmCherry0.5';
UPDATE fluorescent_protein SET fp_uuid = 'D77WT' WHERE fp_name = 'A44-KR';
UPDATE fluorescent_protein SET fp_uuid = 'DAH3B' WHERE fp_name = 'AdRed';
UPDATE fluorescent_protein SET fp_uuid = 'DO6Z1' WHERE fp_name = 'SBFP1';
UPDATE fluorescent_protein SET fp_uuid = 'GLJ6S' WHERE fp_name = 'LSS-mKate1';
UPDATE fluorescent_protein SET fp_uuid = 'GW5EB' WHERE fp_name = 'AQ143';
UPDATE fluorescent_protein SET fp_uuid = 'HKDXH' WHERE fp_name = 'Jred';
UPDATE fluorescent_protein SET fp_uuid = 'JB7SD' WHERE fp_name = 'eechRFP';
UPDATE fluorescent_protein SET fp_uuid = 'JM7JP' WHERE fp_name = 'ShadowG';
UPDATE fluorescent_protein SET fp_uuid = 'LBAXM' WHERE fp_name = 'alajGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'O351D' WHERE fp_name = 'mGrape3';
UPDATE fluorescent_protein SET fp_uuid = 'P9LBW' WHERE fp_name = 'Sandercyanin';
UPDATE fluorescent_protein SET fp_uuid = 'Q3VS4' WHERE fp_name = 'amilFP512';
UPDATE fluorescent_protein SET fp_uuid = 'QEO8D' WHERE fp_name = 'mRojoA';
UPDATE fluorescent_protein SET fp_uuid = 'SDS4K' WHERE fp_name = 'BFP';
UPDATE fluorescent_protein SET fp_uuid = 'SXBT1' WHERE fp_name = 'mKeima';
UPDATE fluorescent_protein SET fp_uuid = 'T23T9' WHERE fp_name = 'sg11';
UPDATE fluorescent_protein SET fp_uuid = 'THMOX' WHERE fp_name = 'AdRed-C148S';
UPDATE fluorescent_protein SET fp_uuid = 'WQ5JF' WHERE fp_name = 'amilFP504';
UPDATE fluorescent_protein SET fp_uuid = 'XOVUP' WHERE fp_name = 'RDSmCherry0.2';
UPDATE fluorescent_protein SET fp_uuid = 'YV34T' WHERE fp_name = 'anm1GFP2';
UPDATE fluorescent_protein SET fp_uuid = '2YKB1' WHERE fp_name = 'amilFP597';
UPDATE fluorescent_protein SET fp_uuid = 'QX3LG' WHERE fp_name = 'mcFP503';
UPDATE fluorescent_protein SET fp_uuid = 'O1Z8P' WHERE fp_name = 'RSGFP3';
UPDATE fluorescent_protein SET fp_uuid = 'GXLGY' WHERE fp_name = '6C';
UPDATE fluorescent_protein SET fp_uuid = '2VPWT' WHERE fp_name = '(3-F)Tyr-EGFP';
UPDATE fluorescent_protein SET fp_uuid = '3FC3D' WHERE fp_name = 'rsTagRFP (ON)';
UPDATE fluorescent_protein SET fp_uuid = 'LY1S9' WHERE fp_name = 'moxMaple3 (Green)';
UPDATE fluorescent_protein SET fp_uuid = '6O8HW' WHERE fp_name = 'PS-CFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'PL518' WHERE fp_name = 'PAmCherry3 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'DTAXR' WHERE fp_name = 'PAmKate (On)';
UPDATE fluorescent_protein SET fp_uuid = '9EUJH' WHERE fp_name = 'rsFusionRed2 (On)';
UPDATE fluorescent_protein SET fp_uuid = '13ANW' WHERE fp_name = 'rsFusionRed3 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'Q8AAM' WHERE fp_name = 'rsCherry (On)';
UPDATE fluorescent_protein SET fp_uuid = '45EFN' WHERE fp_name = 'rsCherryRev (On)';
UPDATE fluorescent_protein SET fp_uuid = 'F5F6H' WHERE fp_name = 'AausFP4 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'GJDTN' WHERE fp_name = 'Dendra (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'GJDTN' WHERE fp_name = 'Dendra (Red)';
UPDATE fluorescent_protein SET fp_uuid = '7QYHY' WHERE fp_name = 'PA-GFP (On)';
UPDATE fluorescent_protein SET fp_uuid = '6O8HW' WHERE fp_name = 'PS-CFP (Cyan)';
UPDATE fluorescent_protein SET fp_uuid = '5ELUZ' WHERE fp_name = 'K-GECO1 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'JAAOP' WHERE fp_name = 'REX-GECO1 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'YPB84' WHERE fp_name = 'jREX-GECO1 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'CBTDK' WHERE fp_name = 'R-GECO1 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'TUAGZ' WHERE fp_name = 'jRGECO1a (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'NFDXY' WHERE fp_name = 'R-GECO1.2 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'TUAGZ' WHERE fp_name = 'jRGECO1a (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'NFDXY' WHERE fp_name = 'R-GECO1.2 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'WN1JX' WHERE fp_name = 'Pp2FbFPL30M';
UPDATE fluorescent_protein SET fp_uuid = 'FHG23' WHERE fp_name = 'AvicFP2 (pre-conversion)';
UPDATE fluorescent_protein SET fp_uuid = 'D4OFQ' WHERE fp_name = 'ECFPH148D';
UPDATE fluorescent_protein SET fp_uuid = 'F5GKU' WHERE fp_name = 'GCaMP6f (InabsenceofCa2+)';
UPDATE fluorescent_protein SET fp_uuid = '1E8G7' WHERE fp_name = 'GZnP3 (GZnP3(apostate))';
UPDATE fluorescent_protein SET fp_uuid = '3NV4W' WHERE fp_name = 'asCP562';
UPDATE fluorescent_protein SET fp_uuid = '3PP3A' WHERE fp_name = 'mKelly1';
UPDATE fluorescent_protein SET fp_uuid = '4YUEY' WHERE fp_name = 'GFPxm18uv';
UPDATE fluorescent_protein SET fp_uuid = '54TPA' WHERE fp_name = 'eGFP205C';
UPDATE fluorescent_protein SET fp_uuid = '5M9ZL' WHERE fp_name = 'GFPxm163';
UPDATE fluorescent_protein SET fp_uuid = '5NY15' WHERE fp_name = 'SCFP1';
UPDATE fluorescent_protein SET fp_uuid = '6XY7Q' WHERE fp_name = 'MfaG1';
UPDATE fluorescent_protein SET fp_uuid = '7AJCQ' WHERE fp_name = 'bfloGFPc1';
UPDATE fluorescent_protein SET fp_uuid = '7J2M8' WHERE fp_name = 'DstC1';
UPDATE fluorescent_protein SET fp_uuid = '9MM4N' WHERE fp_name = 'amilFP484';
UPDATE fluorescent_protein SET fp_uuid = '9PWLU' WHERE fp_name = 'mc3';
UPDATE fluorescent_protein SET fp_uuid = '9T6B1' WHERE fp_name = 'DspR1';
UPDATE fluorescent_protein SET fp_uuid = 'B53TZ' WHERE fp_name = 'iFP2.0';
UPDATE fluorescent_protein SET fp_uuid = 'CE7VU' WHERE fp_name = 'iLov';
UPDATE fluorescent_protein SET fp_uuid = 'CZPVJ' WHERE fp_name = 'HriCFP';
UPDATE fluorescent_protein SET fp_uuid = 'D41LA' WHERE fp_name = 'dis3GFP';
UPDATE fluorescent_protein SET fp_uuid = 'DANPD' WHERE fp_name = 'GFPxm19';
UPDATE fluorescent_protein SET fp_uuid = 'EKYG9' WHERE fp_name = 'hmGFP';
UPDATE fluorescent_protein SET fp_uuid = 'G413J' WHERE fp_name = 'avGFP514';
UPDATE fluorescent_protein SET fp_uuid = 'GR6FV' WHERE fp_name = 'KCY-R1-38L';
UPDATE fluorescent_protein SET fp_uuid = 'J9SCM' WHERE fp_name = 'atenFP';
UPDATE fluorescent_protein SET fp_uuid = 'JO1K2' WHERE fp_name = 'Katushka-9-5';
UPDATE fluorescent_protein SET fp_uuid = 'N2LZL' WHERE fp_name = 'mc2';
UPDATE fluorescent_protein SET fp_uuid = 'N33JN' WHERE fp_name = 'DsRed.M1';
UPDATE fluorescent_protein SET fp_uuid = 'NKT4V' WHERE fp_name = 'KCY-G4219-38L';
UPDATE fluorescent_protein SET fp_uuid = 'PEHFX' WHERE fp_name = 'avGFP510';
UPDATE fluorescent_protein SET fp_uuid = 'PHV2M' WHERE fp_name = 'GFPxm162';
UPDATE fluorescent_protein SET fp_uuid = 'PK2PN' WHERE fp_name = 'GFPxm161';
UPDATE fluorescent_protein SET fp_uuid = 'QPRJJ' WHERE fp_name = 'avGFP480';
UPDATE fluorescent_protein SET fp_uuid = 'SS15T' WHERE fp_name = 'pHuji';
UPDATE fluorescent_protein SET fp_uuid = 'T4B2J' WHERE fp_name = 'avGFP454';
UPDATE fluorescent_protein SET fp_uuid = 'T93PK' WHERE fp_name = 'McaG2';
UPDATE fluorescent_protein SET fp_uuid = 'UHFA9' WHERE fp_name = 'cgigGFP';
UPDATE fluorescent_protein SET fp_uuid = 'VBVAC' WHERE fp_name = 'mc1';
UPDATE fluorescent_protein SET fp_uuid = 'VWLEW' WHERE fp_name = 'CheGFP4';
UPDATE fluorescent_protein SET fp_uuid = 'WBK4U' WHERE fp_name = 'AQ14';
UPDATE fluorescent_protein SET fp_uuid = 'WSRVG' WHERE fp_name = 'iFP1.4';
UPDATE fluorescent_protein SET fp_uuid = 'WUW5F' WHERE fp_name = 'FP586';
UPDATE fluorescent_protein SET fp_uuid = 'XAQPR' WHERE fp_name = 'GFPxm19uv';
UPDATE fluorescent_protein SET fp_uuid = 'Z78XR' WHERE fp_name = 'KCY-R1-158A';
UPDATE fluorescent_protein SET fp_uuid = 'ZRLU4' WHERE fp_name = 'CFP';
UPDATE fluorescent_protein SET fp_uuid = '2EM4B' WHERE fp_name = 'cp-mKate';
UPDATE fluorescent_protein SET fp_uuid = '3G1CL' WHERE fp_name = 'iRFP713/V256C';
UPDATE fluorescent_protein SET fp_uuid = '55FPY' WHERE fp_name = 'miRFP702';
UPDATE fluorescent_protein SET fp_uuid = '5W398' WHERE fp_name = 'asFP499';
UPDATE fluorescent_protein SET fp_uuid = '6N98Z' WHERE fp_name = 'mcCFP';
UPDATE fluorescent_protein SET fp_uuid = '7HX6W' WHERE fp_name = 'FPrfl2.3';
UPDATE fluorescent_protein SET fp_uuid = '7NN4S' WHERE fp_name = 'GFPxm191uv';
UPDATE fluorescent_protein SET fp_uuid = '7XQBJ' WHERE fp_name = 'GFPxm16';
UPDATE fluorescent_protein SET fp_uuid = '7YHAN' WHERE fp_name = 'laesGFP';
UPDATE fluorescent_protein SET fp_uuid = '8EDYL' WHERE fp_name = 'miniSOG2';
UPDATE fluorescent_protein SET fp_uuid = 'C36M3' WHERE fp_name = 'mc5';
UPDATE fluorescent_protein SET fp_uuid = 'F3LOW' WHERE fp_name = 'CheGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'GBEZ4' WHERE fp_name = 'GFP-Tyr151pyz';
UPDATE fluorescent_protein SET fp_uuid = 'GVAVH' WHERE fp_name = 'Clomeleon';
UPDATE fluorescent_protein SET fp_uuid = 'GZCBS' WHERE fp_name = 'd-RFP618';
UPDATE fluorescent_protein SET fp_uuid = 'J5AWO' WHERE fp_name = 'Flamindo2';
UPDATE fluorescent_protein SET fp_uuid = 'JKD8V' WHERE fp_name = 'GCaMP2';
UPDATE fluorescent_protein SET fp_uuid = 'JWC7O' WHERE fp_name = 'KCY-R1-38H';
UPDATE fluorescent_protein SET fp_uuid = 'L1JAY' WHERE fp_name = 'GFP-151pyTyrCu';
UPDATE fluorescent_protein SET fp_uuid = 'LF3LJ' WHERE fp_name = 'TagRFP-T';
UPDATE fluorescent_protein SET fp_uuid = 'M3FBS' WHERE fp_name = 'asulCP';
UPDATE fluorescent_protein SET fp_uuid = 'MVN8T' WHERE fp_name = 'mECFP';
UPDATE fluorescent_protein SET fp_uuid = 'OMA2X' WHERE fp_name = 'W2';
UPDATE fluorescent_protein SET fp_uuid = 'P2PV8' WHERE fp_name = 'dfGFP';
UPDATE fluorescent_protein SET fp_uuid = 'PLVQM' WHERE fp_name = 'GFPxm18';
UPDATE fluorescent_protein SET fp_uuid = 'Q7SKD' WHERE fp_name = 'mc4';
UPDATE fluorescent_protein SET fp_uuid = 'QJSF2' WHERE fp_name = 'EaGFP';
UPDATE fluorescent_protein SET fp_uuid = 'SF8MO' WHERE fp_name = 'mcavFP';
UPDATE fluorescent_protein SET fp_uuid = 'UNRFC' WHERE fp_name = 'cEGFP';
UPDATE fluorescent_protein SET fp_uuid = 'WKCO7' WHERE fp_name = 'McaG1';
UPDATE fluorescent_protein SET fp_uuid = 'WL2YR' WHERE fp_name = 'avGFP509';
UPDATE fluorescent_protein SET fp_uuid = 'WPR7G' WHERE fp_name = 'avGFP523';
UPDATE fluorescent_protein SET fp_uuid = 'XBY8K' WHERE fp_name = 'HriGFP';
UPDATE fluorescent_protein SET fp_uuid = 'Y2WTN' WHERE fp_name = 'DrCBD';
UPDATE fluorescent_protein SET fp_uuid = 'YYN9U' WHERE fp_name = 'laGFP';
UPDATE fluorescent_protein SET fp_uuid = 'Z6R8B' WHERE fp_name = 'mc6';
UPDATE fluorescent_protein SET fp_uuid = '86LQ4' WHERE fp_name = 'mTFP0.5';
UPDATE fluorescent_protein SET fp_uuid = '9C29V' WHERE fp_name = 'mTFP0.6';
UPDATE fluorescent_protein SET fp_uuid = 'J862W' WHERE fp_name = 'mTFP0.8';
UPDATE fluorescent_protein SET fp_uuid = 'YBGRL' WHERE fp_name = 'mTFP0.9';
UPDATE fluorescent_protein SET fp_uuid = 'KQ1PU' WHERE fp_name = 'mTFP1-Y67H';
UPDATE fluorescent_protein SET fp_uuid = 'UEUCD' WHERE fp_name = 'mTurquoise-146G';
UPDATE fluorescent_protein SET fp_uuid = 'CDUWJ' WHERE fp_name = 'mTurquoise-146S';
UPDATE fluorescent_protein SET fp_uuid = 'Q6D19' WHERE fp_name = 'mTurquoise2-G';
UPDATE fluorescent_protein SET fp_uuid = 'XT1XP' WHERE fp_name = 'mTurquoise-GL';
UPDATE fluorescent_protein SET fp_uuid = '19O8J' WHERE fp_name = 'mTurquoise-GV';
UPDATE fluorescent_protein SET fp_uuid = '52QHC' WHERE fp_name = 'mTurquoise-RA';
UPDATE fluorescent_protein SET fp_uuid = 'PYHHJ' WHERE fp_name = 'mVermilion';
UPDATE fluorescent_protein SET fp_uuid = '7T72C' WHERE fp_name = 'NpR3784g';
UPDATE fluorescent_protein SET fp_uuid = '799YV' WHERE fp_name = 'Q80R';
UPDATE fluorescent_protein SET fp_uuid = 'SAK3D' WHERE fp_name = 'rfloGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'Q54M6' WHERE fp_name = 'RpBphP1';
UPDATE fluorescent_protein SET fp_uuid = 'AWD7D' WHERE fp_name = 'RpBphP2';
UPDATE fluorescent_protein SET fp_uuid = '84CGO' WHERE fp_name = 'rrGFP';
UPDATE fluorescent_protein SET fp_uuid = 'VAQHD' WHERE fp_name = 'YGFPuv (Default)';
UPDATE fluorescent_protein SET fp_uuid = 'JAAOP' WHERE fp_name = 'REX-GECO1 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'YPB84' WHERE fp_name = 'jREX-GECO1 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'ZJWZK' WHERE fp_name = 'AvicFP3 (pre-conversion)';
UPDATE fluorescent_protein SET fp_uuid = 'P9XBV' WHERE fp_name = 'BDFP2.0 (Fret)';
UPDATE fluorescent_protein SET fp_uuid = 'WH633' WHERE fp_name = 'BR1 (BR1)';
UPDATE fluorescent_protein SET fp_uuid = 'R3OET' WHERE fp_name = 'EnhancedCyan-EmittingGFP';
UPDATE fluorescent_protein SET fp_uuid = '25HRD' WHERE fp_name = 'KOFP-7 (KOFP-7)';
UPDATE fluorescent_protein SET fp_uuid = 'G4TXA' WHERE fp_name = 'miniSOGQ103V';
UPDATE fluorescent_protein SET fp_uuid = 'GNV89' WHERE fp_name = 'lanRFP-ΔS83l';
UPDATE fluorescent_protein SET fp_uuid = '3CN24' WHERE fp_name = 'SuperNovaGreen';
UPDATE fluorescent_protein SET fp_uuid = '1LZV9' WHERE fp_name = 'EBFP';
UPDATE fluorescent_protein SET fp_uuid = '1M48O' WHERE fp_name = 'amFP486';
UPDATE fluorescent_protein SET fp_uuid = '3OSEV' WHERE fp_name = 'mTFP*';
UPDATE fluorescent_protein SET fp_uuid = '4OC6N' WHERE fp_name = 'SiriusGFP';
UPDATE fluorescent_protein SET fp_uuid = '59R1F' WHERE fp_name = 'H9';
UPDATE fluorescent_protein SET fp_uuid = '7WEWT' WHERE fp_name = 'iRFP702';
UPDATE fluorescent_protein SET fp_uuid = '86QDA' WHERE fp_name = 'mRed7Q1S1BM';
UPDATE fluorescent_protein SET fp_uuid = '8HBTK' WHERE fp_name = 'PdaC1';
UPDATE fluorescent_protein SET fp_uuid = '8RSXF' WHERE fp_name = 'W1C';
UPDATE fluorescent_protein SET fp_uuid = 'A6N87' WHERE fp_name = 'BFP.A5';
UPDATE fluorescent_protein SET fp_uuid = 'AJLWS' WHERE fp_name = 'miRFP720';
UPDATE fluorescent_protein SET fp_uuid = 'CQCQT' WHERE fp_name = 'mRFP1-Q66S';
UPDATE fluorescent_protein SET fp_uuid = 'DKZQ7' WHERE fp_name = 'mStable';
UPDATE fluorescent_protein SET fp_uuid = 'DMJJX' WHERE fp_name = 'ptilGFP';
UPDATE fluorescent_protein SET fp_uuid = 'DP2EW' WHERE fp_name = 'R-FlincA';
UPDATE fluorescent_protein SET fp_uuid = 'DVDZZ' WHERE fp_name = 'SOPP2';
UPDATE fluorescent_protein SET fp_uuid = 'GNJK5' WHERE fp_name = 'emiRFP703';
UPDATE fluorescent_protein SET fp_uuid = 'HMOJG' WHERE fp_name = 'mRFP1.2';
UPDATE fluorescent_protein SET fp_uuid = 'HO9GG' WHERE fp_name = 'miRFP';
UPDATE fluorescent_protein SET fp_uuid = 'HQZZC' WHERE fp_name = 'GdT';
UPDATE fluorescent_protein SET fp_uuid = 'JVYE5' WHERE fp_name = 'RDSmCherry0.1';
UPDATE fluorescent_protein SET fp_uuid = 'LTFO5' WHERE fp_name = 'ZsYellow1';
UPDATE fluorescent_protein SET fp_uuid = 'MSYZC' WHERE fp_name = 'KillerRed';
UPDATE fluorescent_protein SET fp_uuid = 'N63O3' WHERE fp_name = 'mTangerine';
UPDATE fluorescent_protein SET fp_uuid = 'OORFP' WHERE fp_name = 'R3-2+PCB';
UPDATE fluorescent_protein SET fp_uuid = 'QGZZT' WHERE fp_name = 'shBFP';
UPDATE fluorescent_protein SET fp_uuid = 'R9DP6' WHERE fp_name = 'P11';
UPDATE fluorescent_protein SET fp_uuid = 'RATTD' WHERE fp_name = 'mMaroon1';
UPDATE fluorescent_protein SET fp_uuid = 'T9G4X' WHERE fp_name = 'mKelly2';
UPDATE fluorescent_protein SET fp_uuid = 'TJBUO' WHERE fp_name = 'mRed7Q1';
UPDATE fluorescent_protein SET fp_uuid = 'U5ALR' WHERE fp_name = 'mmGFP';
UPDATE fluorescent_protein SET fp_uuid = 'UN7HE' WHERE fp_name = 'P9';
UPDATE fluorescent_protein SET fp_uuid = 'V5FM2' WHERE fp_name = 'mRaspberry';
UPDATE fluorescent_protein SET fp_uuid = 'W4PW7' WHERE fp_name = 'SOPP3';
UPDATE fluorescent_protein SET fp_uuid = 'WPO9A' WHERE fp_name = 'iq-mApple';
UPDATE fluorescent_protein SET fp_uuid = 'XHBTX' WHERE fp_name = 'DsRed.T4';
UPDATE fluorescent_protein SET fp_uuid = 'YG5WM' WHERE fp_name = 'dsFP483';
UPDATE fluorescent_protein SET fp_uuid = 'Z3GLX' WHERE fp_name = 'Neptune';
UPDATE fluorescent_protein SET fp_uuid = 'ZVV1B' WHERE fp_name = 'W7';
UPDATE fluorescent_protein SET fp_uuid = '1KNNM' WHERE fp_name = 'miRFP670nano';
UPDATE fluorescent_protein SET fp_uuid = '27HOS' WHERE fp_name = 'ECFP';
UPDATE fluorescent_protein SET fp_uuid = '4LQJE' WHERE fp_name = 'mcavRFP';
UPDATE fluorescent_protein SET fp_uuid = '5YCFA' WHERE fp_name = 'mRFP1';
UPDATE fluorescent_protein SET fp_uuid = '7DP3C' WHERE fp_name = 'mGarnet2';
UPDATE fluorescent_protein SET fp_uuid = '9CEJ5' WHERE fp_name = 'P4-1';
UPDATE fluorescent_protein SET fp_uuid = '9GPWY' WHERE fp_name = 'pH-tdGFP';
UPDATE fluorescent_protein SET fp_uuid = '9TBLQ' WHERE fp_name = 'mRed7Q1S1';
UPDATE fluorescent_protein SET fp_uuid = 'BSK5M' WHERE fp_name = 'SCFP2';
UPDATE fluorescent_protein SET fp_uuid = 'DGXFA' WHERE fp_name = 'iRFP713';
UPDATE fluorescent_protein SET fp_uuid = 'EY2GX' WHERE fp_name = 'LSSmCherry1';
UPDATE fluorescent_protein SET fp_uuid = 'EY795' WHERE fp_name = 'mRFP1.1';
UPDATE fluorescent_protein SET fp_uuid = 'GCOU1' WHERE fp_name = 'miRFP670v1';
UPDATE fluorescent_protein SET fp_uuid = 'LKB4E' WHERE fp_name = 'P4-3E';
UPDATE fluorescent_protein SET fp_uuid = 'LMJV4' WHERE fp_name = 'dKeima';
UPDATE fluorescent_protein SET fp_uuid = 'LNY1F' WHERE fp_name = 'HcRed7';
UPDATE fluorescent_protein SET fp_uuid = 'MGNCD' WHERE fp_name = 'deGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'MSSUL' WHERE fp_name = 'mRFP1-Q66C';
UPDATE fluorescent_protein SET fp_uuid = 'O247C' WHERE fp_name = 'OFPxm';
UPDATE fluorescent_protein SET fp_uuid = 'OYSEV' WHERE fp_name = 'GGvT';
UPDATE fluorescent_protein SET fp_uuid = 'PS1S2' WHERE fp_name = 'mKG';
UPDATE fluorescent_protein SET fp_uuid = 'Q5DYR' WHERE fp_name = 'iRFP670';
UPDATE fluorescent_protein SET fp_uuid = 'RTMMX' WHERE fp_name = 'mCRISPRed';
UPDATE fluorescent_protein SET fp_uuid = 'X1DTP' WHERE fp_name = 'miRFP682';
UPDATE fluorescent_protein SET fp_uuid = 'YHJV5' WHERE fp_name = 'emiRFP670';
UPDATE fluorescent_protein SET fp_uuid = 'BKD94' WHERE fp_name = 'rsFolder (Green)';
UPDATE fluorescent_protein SET fp_uuid = '1B7TK' WHERE fp_name = 'miRFP703';
UPDATE fluorescent_protein SET fp_uuid = 'SV3XM' WHERE fp_name = 'PAmCherry2 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'MNH1D' WHERE fp_name = 'mMaple3 (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'T44HU' WHERE fp_name = 'IrisFP-M159A (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'SXSQ9' WHERE fp_name = 'mMaple (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'RDRFL' WHERE fp_name = 'PS-CFP2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'LY1S9' WHERE fp_name = 'moxMaple3 (Red)';
UPDATE fluorescent_protein SET fp_uuid = '6VV9O' WHERE fp_name = 'rsFolder2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'OMODZ' WHERE fp_name = 'PAmCherry1 (On)';
UPDATE fluorescent_protein SET fp_uuid = '77HQK' WHERE fp_name = 'rsFusionRed1 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'SEJ6N' WHERE fp_name = 'mMaple2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'SEJ6N' WHERE fp_name = 'mMaple2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = '31OK2' WHERE fp_name = 'Padron(star) (On)';
UPDATE fluorescent_protein SET fp_uuid = '37TVB' WHERE fp_name = 'O-GECO1 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'CBTDK' WHERE fp_name = 'R-GECO1 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'AQ8G3' WHERE fp_name = 'PSmOrange (Far-red)';
UPDATE fluorescent_protein SET fp_uuid = 'RDRFL' WHERE fp_name = 'PS-CFP2 (Cyan)';
UPDATE fluorescent_protein SET fp_uuid = 'U76BO' WHERE fp_name = 'PSmOrange2 (Far-red)';
UPDATE fluorescent_protein SET fp_uuid = 'SJT6S' WHERE fp_name = 'pHluorin2 (acidic)';
UPDATE fluorescent_protein SET fp_uuid = 'SJT6S' WHERE fp_name = 'pHluorin2 (alkaline)';
UPDATE fluorescent_protein SET fp_uuid = 'SXBT1' WHERE fp_name = 'mKeima (pH5)';
UPDATE fluorescent_protein SET fp_uuid = 'SXBT1' WHERE fp_name = 'mKeima (pH8)';
UPDATE fluorescent_protein SET fp_uuid = 'SXBT1' WHERE fp_name = 'mKeima (pH4)';
UPDATE fluorescent_protein SET fp_uuid = 'PV8DK' WHERE fp_name = 'mRhubarb720 (Pr)';
UPDATE fluorescent_protein SET fp_uuid = '1E8G7' WHERE fp_name = 'GZnP3 (GZnP3(Zn²⁺-bound))';
UPDATE fluorescent_protein SET fp_uuid = 'SBO48' WHERE fp_name = 'mK-GO (Early)';
UPDATE fluorescent_protein SET fp_uuid = 'SBO48' WHERE fp_name = 'mK-GO (Late)';
UPDATE fluorescent_protein SET fp_uuid = 'C69E5' WHERE fp_name = 'Montiporasp.#20-9115';
UPDATE fluorescent_protein SET fp_uuid = 'OZEBT' WHERE fp_name = 'mRhubarb713 (Pr)';
UPDATE fluorescent_protein SET fp_uuid = 'KPFB9' WHERE fp_name = 'pHluorin,ecliptic';
UPDATE fluorescent_protein SET fp_uuid = 'KPFB9' WHERE fp_name = 'pHluorin,ecliptic (acidic)';
UPDATE fluorescent_protein SET fp_uuid = 'XKELZ' WHERE fp_name = 'pHluorin,ratiometric (alkaline)';
UPDATE fluorescent_protein SET fp_uuid = '35N2E' WHERE fp_name = 'RFP618';
UPDATE fluorescent_protein SET fp_uuid = '3Q37R' WHERE fp_name = 'mCitrine';
UPDATE fluorescent_protein SET fp_uuid = '46ZQ7' WHERE fp_name = 'rfloRFP';
UPDATE fluorescent_protein SET fp_uuid = '5EU5J' WHERE fp_name = 'efasGFP';
UPDATE fluorescent_protein SET fp_uuid = '5LPGL' WHERE fp_name = 'ShG24';
UPDATE fluorescent_protein SET fp_uuid = '5YBHO' WHERE fp_name = 'ccalOFP1';
UPDATE fluorescent_protein SET fp_uuid = '6VP2A' WHERE fp_name = 'SHardonnay';
UPDATE fluorescent_protein SET fp_uuid = '7DEM9' WHERE fp_name = 'phiYFP';
UPDATE fluorescent_protein SET fp_uuid = '8MJ78' WHERE fp_name = 'mRuby2';
UPDATE fluorescent_protein SET fp_uuid = 'AHNXC' WHERE fp_name = 'TurboRFP';
UPDATE fluorescent_protein SET fp_uuid = 'B4SGV' WHERE fp_name = 'Rtms5';
UPDATE fluorescent_protein SET fp_uuid = 'C2FJQ' WHERE fp_name = 'AausFP1';
UPDATE fluorescent_protein SET fp_uuid = 'ESQ8O' WHERE fp_name = 'plobRFP';
UPDATE fluorescent_protein SET fp_uuid = 'FTKQU' WHERE fp_name = 'gtenCP';
UPDATE fluorescent_protein SET fp_uuid = 'GB9EO' WHERE fp_name = 'SYFP2';
UPDATE fluorescent_protein SET fp_uuid = 'HXP5A' WHERE fp_name = 'NowGFP';
UPDATE fluorescent_protein SET fp_uuid = 'JVUSZ' WHERE fp_name = 'Gamillus0.4';
UPDATE fluorescent_protein SET fp_uuid = 'N8PD5' WHERE fp_name = 'Blue102';
UPDATE fluorescent_protein SET fp_uuid = 'NJL9P' WHERE fp_name = 'scubGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'OM1OY' WHERE fp_name = 'rfloGFP';
UPDATE fluorescent_protein SET fp_uuid = 'PRMX6' WHERE fp_name = 'KikG';
UPDATE fluorescent_protein SET fp_uuid = 'QQJHZ' WHERE fp_name = 'dTFP0.2';
UPDATE fluorescent_protein SET fp_uuid = 'SXYKQ' WHERE fp_name = 'mAvicFP1';
UPDATE fluorescent_protein SET fp_uuid = 'SY6TH' WHERE fp_name = 'Topaz';
UPDATE fluorescent_protein SET fp_uuid = 'T5A9C' WHERE fp_name = 'afraGFP';
UPDATE fluorescent_protein SET fp_uuid = 'UHFSE' WHERE fp_name = 'ccalGFP3';
UPDATE fluorescent_protein SET fp_uuid = 'UPG56' WHERE fp_name = 'YFP3';
UPDATE fluorescent_protein SET fp_uuid = 'V7NZK' WHERE fp_name = 'WasCFP';
UPDATE fluorescent_protein SET fp_uuid = 'W1X8H' WHERE fp_name = 'anobGFP';
UPDATE fluorescent_protein SET fp_uuid = 'WK5F6' WHERE fp_name = 'LanYFP';
UPDATE fluorescent_protein SET fp_uuid = 'WRGL6' WHERE fp_name = 'obeYFP';
UPDATE fluorescent_protein SET fp_uuid = 'YQ25V' WHERE fp_name = 'h2-3';
UPDATE fluorescent_protein SET fp_uuid = 'ZE3SV' WHERE fp_name = 'roGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'ZWH88' WHERE fp_name = 'Citrine2';
UPDATE fluorescent_protein SET fp_uuid = '7XNWJ' WHERE fp_name = 'A1a';
UPDATE fluorescent_protein SET fp_uuid = '2DB3H' WHERE fp_name = 'dVFP';
UPDATE fluorescent_protein SET fp_uuid = '3W5ZV' WHERE fp_name = 'aacuGFP2';
UPDATE fluorescent_protein SET fp_uuid = '4GMRC' WHERE fp_name = 'oxVenus';
UPDATE fluorescent_protein SET fp_uuid = '6BXQP' WHERE fp_name = 'bfloGFPa1';
UPDATE fluorescent_protein SET fp_uuid = '8DX6R' WHERE fp_name = 'RFP611';
UPDATE fluorescent_protein SET fp_uuid = 'BH9MB' WHERE fp_name = 'vsfGFP-0';
UPDATE fluorescent_protein SET fp_uuid = 'BQFPM' WHERE fp_name = 'fabdGFP';
UPDATE fluorescent_protein SET fp_uuid = 'FM76L' WHERE fp_name = 'G3';
UPDATE fluorescent_protein SET fp_uuid = 'FWVH2' WHERE fp_name = 'stylGFP';
UPDATE fluorescent_protein SET fp_uuid = 'K487K' WHERE fp_name = 'TurboGFP-V197L';
UPDATE fluorescent_protein SET fp_uuid = 'KTFOJ' WHERE fp_name = 'roGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'LXWLT' WHERE fp_name = 'mVFP1';
UPDATE fluorescent_protein SET fp_uuid = 'OEVJT' WHERE fp_name = 'AausFP3';
UPDATE fluorescent_protein SET fp_uuid = 'OXU4P' WHERE fp_name = 'gfasCP';
UPDATE fluorescent_protein SET fp_uuid = 'S1LK3' WHERE fp_name = 'scubGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'U5JBT' WHERE fp_name = 'roGFP1-R8';
UPDATE fluorescent_protein SET fp_uuid = 'VDDDT' WHERE fp_name = 'amilFP593';
UPDATE fluorescent_protein SET fp_uuid = 'VR7EN' WHERE fp_name = 'Citrine';
UPDATE fluorescent_protein SET fp_uuid = 'WCSN6' WHERE fp_name = 'mVenus';
UPDATE fluorescent_protein SET fp_uuid = 'WVV8W' WHERE fp_name = 'ccalYFP1';
UPDATE fluorescent_protein SET fp_uuid = '2BK6M' WHERE fp_name = 'ppluGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'LZSRC' WHERE fp_name = 'aacuCP';
UPDATE fluorescent_protein SET fp_uuid = '24DHR' WHERE fp_name = 'acanFP';
UPDATE fluorescent_protein SET fp_uuid = 'QSSEE' WHERE fp_name = 'ahyaCP';
UPDATE fluorescent_protein SET fp_uuid = '87PXJ' WHERE fp_name = 'amilCP580';
UPDATE fluorescent_protein SET fp_uuid = 'VAFG4' WHERE fp_name = 'amilCP586';
UPDATE fluorescent_protein SET fp_uuid = 'YEF5F' WHERE fp_name = 'amilCP604';
UPDATE fluorescent_protein SET fp_uuid = 'S7VLN' WHERE fp_name = 'apulCP584';
UPDATE fluorescent_protein SET fp_uuid = '1U8Q1' WHERE fp_name = 'BFPsol';
UPDATE fluorescent_protein SET fp_uuid = 'QNUPG' WHERE fp_name = 'CFP4';
UPDATE fluorescent_protein SET fp_uuid = 'T83KT' WHERE fp_name = 'RSGFP1';
UPDATE fluorescent_protein SET fp_uuid = '46PO9' WHERE fp_name = 'RSGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'C2KOO' WHERE fp_name = 'RSGFP6';
UPDATE fluorescent_protein SET fp_uuid = '8HG8O' WHERE fp_name = 'RSGFP7';
UPDATE fluorescent_protein SET fp_uuid = 'C6XGJ' WHERE fp_name = 'scleFP1';
UPDATE fluorescent_protein SET fp_uuid = 'HQ36M' WHERE fp_name = 'scleFP2';
UPDATE fluorescent_protein SET fp_uuid = 'CFKTA' WHERE fp_name = 'sfCherry';
UPDATE fluorescent_protein SET fp_uuid = 'JT63R' WHERE fp_name = 'sfCherry3C';
UPDATE fluorescent_protein SET fp_uuid = '1AR75' WHERE fp_name = 'spisCP';
UPDATE fluorescent_protein SET fp_uuid = 'BLKRN' WHERE fp_name = 'stylCP';
UPDATE fluorescent_protein SET fp_uuid = 'VW66D' WHERE fp_name = 'TeAPCα';
UPDATE fluorescent_protein SET fp_uuid = 'HU2PW' WHERE fp_name = 'tPapaya0.01';
UPDATE fluorescent_protein SET fp_uuid = '35L95' WHERE fp_name = 'vsGFP';
UPDATE fluorescent_protein SET fp_uuid = 'CX52N' WHERE fp_name = 'Xpa';
UPDATE fluorescent_protein SET fp_uuid = 'YHQTQ' WHERE fp_name = 'yEGFP';
UPDATE fluorescent_protein SET fp_uuid = 'BNZOQ' WHERE fp_name = 'GFPhal';
UPDATE fluorescent_protein SET fp_uuid = '8OX5S' WHERE fp_name = 'hcriCP';
UPDATE fluorescent_protein SET fp_uuid = '6K8L3' WHERE fp_name = 'hfriFP';
UPDATE fluorescent_protein SET fp_uuid = 'R4WAG' WHERE fp_name = 'LEA';
UPDATE fluorescent_protein SET fp_uuid = 'L3C27' WHERE fp_name = 'Kohinoor (On)';
UPDATE fluorescent_protein SET fp_uuid = 'RD2N4' WHERE fp_name = 'mGeos-M (On)';
UPDATE fluorescent_protein SET fp_uuid = 'EC56T' WHERE fp_name = 'mEos4a (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'DKEXK' WHERE fp_name = 'mEosEM (Green)';
UPDATE fluorescent_protein SET fp_uuid = '3SXVB' WHERE fp_name = 'pcStar (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'V2GB1' WHERE fp_name = 'mEos4b (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'VVNZ5' WHERE fp_name = 'mGeos-C (On)';
UPDATE fluorescent_protein SET fp_uuid = 'D87D7' WHERE fp_name = 'rsKame (On)';
UPDATE fluorescent_protein SET fp_uuid = '1GO7S' WHERE fp_name = 'rsCherryRev1.4 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'O72EP' WHERE fp_name = 'SAASoti (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'DKEXK' WHERE fp_name = 'mEosEM (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'JTXCJ' WHERE fp_name = 'dendFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'B1GJH' WHERE fp_name = 'YGFPdp (Default)';
UPDATE fluorescent_protein SET fp_uuid = 'AQ8G3' WHERE fp_name = 'PSmOrange (Orange)';
UPDATE fluorescent_protein SET fp_uuid = 'N6ZHS' WHERE fp_name = 'FoldingReporterGFP';
UPDATE fluorescent_protein SET fp_uuid = 'F5GKU' WHERE fp_name = 'GCaMP6f (InpresenceofCa2+)';
UPDATE fluorescent_protein SET fp_uuid = 'H93B4' WHERE fp_name = 'GRvT (Redexcitation)';
UPDATE fluorescent_protein SET fp_uuid = 'PFYNU' WHERE fp_name = 'SH3 (SH3)';
UPDATE fluorescent_protein SET fp_uuid = '1M59L' WHERE fp_name = 'ShyRFP (Yellowstate)';
UPDATE fluorescent_protein SET fp_uuid = 'X8MG1' WHERE fp_name = 'spGFP11';
UPDATE fluorescent_protein SET fp_uuid = 'QJV5C' WHERE fp_name = 'stagRFP';
UPDATE fluorescent_protein SET fp_uuid = 'NFBGR' WHERE fp_name = 'SuperfoldermTurquoise2';
UPDATE fluorescent_protein SET fp_uuid = 'QEXW4' WHERE fp_name = 'SuperfoldermTurquoise2ox';
UPDATE fluorescent_protein SET fp_uuid = '9ZKVW' WHERE fp_name = 'Trp-lessGFP';
UPDATE fluorescent_protein SET fp_uuid = '1U9ZJ' WHERE fp_name = 'V127TSAASoti (Green)';
UPDATE fluorescent_protein SET fp_uuid = '1U9ZJ' WHERE fp_name = 'V127TSAASoti (Red)';
UPDATE fluorescent_protein SET fp_uuid = '4NRYW' WHERE fp_name = 'aeurGFP';
UPDATE fluorescent_protein SET fp_uuid = '4Z641' WHERE fp_name = 'Clover';
UPDATE fluorescent_protein SET fp_uuid = '5ULGG' WHERE fp_name = 'UnaG';
UPDATE fluorescent_protein SET fp_uuid = '782GK' WHERE fp_name = 'obeGFP';
UPDATE fluorescent_protein SET fp_uuid = '7GO5D' WHERE fp_name = 'RRvT';
UPDATE fluorescent_protein SET fp_uuid = '8DNLG' WHERE fp_name = 'EYFP';
UPDATE fluorescent_protein SET fp_uuid = 'AD4BK' WHERE fp_name = 'mEmerald';
UPDATE fluorescent_protein SET fp_uuid = 'ASSY9' WHERE fp_name = 'mTFP1';
UPDATE fluorescent_protein SET fp_uuid = 'DFXUK' WHERE fp_name = 'dimer2';
UPDATE fluorescent_protein SET fp_uuid = 'FE6UX' WHERE fp_name = 'mVenus-Q69M';
UPDATE fluorescent_protein SET fp_uuid = 'FRRJW' WHERE fp_name = 'pporRFP';
UPDATE fluorescent_protein SET fp_uuid = 'FVS3D' WHERE fp_name = 'mScarlet';
UPDATE fluorescent_protein SET fp_uuid = 'G1DQY' WHERE fp_name = 'dTomato';
UPDATE fluorescent_protein SET fp_uuid = 'G5OWS' WHERE fp_name = 'eqFP578';
UPDATE fluorescent_protein SET fp_uuid = 'G6HDH' WHERE fp_name = 'mOrange';
UPDATE fluorescent_protein SET fp_uuid = 'GLAD6' WHERE fp_name = 'Emerald';
UPDATE fluorescent_protein SET fp_uuid = 'H9KU1' WHERE fp_name = 'iq-mVenus';
UPDATE fluorescent_protein SET fp_uuid = 'KETFB' WHERE fp_name = 'OFP';
UPDATE fluorescent_protein SET fp_uuid = 'N6WUS' WHERE fp_name = 'meffGFP';
UPDATE fluorescent_protein SET fp_uuid = 'ND36H' WHERE fp_name = 'meffRFP';
UPDATE fluorescent_protein SET fp_uuid = 'NPCN7' WHERE fp_name = 'anobCFP1';
UPDATE fluorescent_protein SET fp_uuid = 'OVJRJ' WHERE fp_name = 'LSSmOrange';
UPDATE fluorescent_protein SET fp_uuid = 'P3DVP' WHERE fp_name = 'VFP';
UPDATE fluorescent_protein SET fp_uuid = 'QTBVW' WHERE fp_name = 'mWasabi';
UPDATE fluorescent_protein SET fp_uuid = 'S1U3D' WHERE fp_name = 'anm1GFP1';
UPDATE fluorescent_protein SET fp_uuid = 'S4HC8' WHERE fp_name = 'TagRFP';
UPDATE fluorescent_protein SET fp_uuid = 'SBLM5' WHERE fp_name = 'mEYFP';
UPDATE fluorescent_protein SET fp_uuid = 'T44E8' WHERE fp_name = 'ccalRFP1';
UPDATE fluorescent_protein SET fp_uuid = 'V3NZ1' WHERE fp_name = 'usGFP';
UPDATE fluorescent_protein SET fp_uuid = 'VB2NB' WHERE fp_name = 'E2-Red/Green';
UPDATE fluorescent_protein SET fp_uuid = 'VE1RL' WHERE fp_name = 'AvicFP1';
UPDATE fluorescent_protein SET fp_uuid = 'VPR4D' WHERE fp_name = 'ppluGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'WLCQP' WHERE fp_name = 'G2';
UPDATE fluorescent_protein SET fp_uuid = 'WQ6TU' WHERE fp_name = 'mCerulean2.N';
UPDATE fluorescent_protein SET fp_uuid = 'YUJWJ' WHERE fp_name = 'Venus';
UPDATE fluorescent_protein SET fp_uuid = '31NFQ' WHERE fp_name = 'eechGFP3';
UPDATE fluorescent_protein SET fp_uuid = '6VVTK' WHERE fp_name = 'mScarlet-I';
UPDATE fluorescent_protein SET fp_uuid = '73TKS' WHERE fp_name = 'meffCFP';
UPDATE fluorescent_protein SET fp_uuid = '9KYTB' WHERE fp_name = 'mCerulean2.D3';
UPDATE fluorescent_protein SET fp_uuid = 'A315M' WHERE fp_name = 'TurboGFP';
UPDATE fluorescent_protein SET fp_uuid = 'AJCVH' WHERE fp_name = 'scubRFP';
UPDATE fluorescent_protein SET fp_uuid = 'HC91W' WHERE fp_name = 'AzamiGreen';
UPDATE fluorescent_protein SET fp_uuid = 'MEFJC' WHERE fp_name = 'pmeaGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'MX4SD' WHERE fp_name = 'eechGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'PO1ML' WHERE fp_name = 'M355NA';
UPDATE fluorescent_protein SET fp_uuid = 'QB1DP' WHERE fp_name = 'mmilCFP';
UPDATE fluorescent_protein SET fp_uuid = 'QS3XQ' WHERE fp_name = 'GFPmut2';
UPDATE fluorescent_protein SET fp_uuid = 'RYFE4' WHERE fp_name = 'mClover3';
UPDATE fluorescent_protein SET fp_uuid = 'SZYEK' WHERE fp_name = 'SEYFP';
UPDATE fluorescent_protein SET fp_uuid = 'UWMXB' WHERE fp_name = 'meleRFP';
UPDATE fluorescent_protein SET fp_uuid = 'W7ZR3' WHERE fp_name = 'pporGFP';
UPDATE fluorescent_protein SET fp_uuid = 'XZJ98' WHERE fp_name = 'EYFP-Q69K';
UPDATE fluorescent_protein SET fp_uuid = '6Z58E' WHERE fp_name = 'CheGFP3';
UPDATE fluorescent_protein SET fp_uuid = '1L4BP' WHERE fp_name = 'tdKatushka2';
UPDATE fluorescent_protein SET fp_uuid = 'T2E43' WHERE fp_name = 'Cy11.5';
UPDATE fluorescent_protein SET fp_uuid = '9YVT9' WHERE fp_name = 'dClavGR1.6';
UPDATE fluorescent_protein SET fp_uuid = 'OMXYJ' WHERE fp_name = 'dClover2';
UPDATE fluorescent_protein SET fp_uuid = 'U7WYN' WHERE fp_name = 'dhorGFP';
UPDATE fluorescent_protein SET fp_uuid = 'GWQB2' WHERE fp_name = 'dhorRFP';
UPDATE fluorescent_protein SET fp_uuid = 'ZRNCZ' WHERE fp_name = 'dPapaya0.1';
UPDATE fluorescent_protein SET fp_uuid = 'NW2SG' WHERE fp_name = 'Dronpa-C62S';
UPDATE fluorescent_protein SET fp_uuid = '55DQE' WHERE fp_name = 'DsRed-Timer';
UPDATE fluorescent_protein SET fp_uuid = '7BYS6' WHERE fp_name = 'echFP';
UPDATE fluorescent_protein SET fp_uuid = '7ABAY' WHERE fp_name = 'echiFP';
UPDATE fluorescent_protein SET fp_uuid = 'KN52A' WHERE fp_name = 'EYFP-F46L';
UPDATE fluorescent_protein SET fp_uuid = 'H691P' WHERE fp_name = 'fcFP';
UPDATE fluorescent_protein SET fp_uuid = 'VVMUR' WHERE fp_name = 'fcomFP';
UPDATE fluorescent_protein SET fp_uuid = '59JAS' WHERE fp_name = 'Fpaagar';
UPDATE fluorescent_protein SET fp_uuid = '5W635' WHERE fp_name = 'Fpag_frag';
UPDATE fluorescent_protein SET fp_uuid = 'T939F' WHERE fp_name = 'Fpcondchrom';
UPDATE fluorescent_protein SET fp_uuid = 'AC8R8' WHERE fp_name = 'FPmann';
UPDATE fluorescent_protein SET fp_uuid = 'X8H9P' WHERE fp_name = 'FPmcavgr7.7';
UPDATE fluorescent_protein SET fp_uuid = 'E5GAC' WHERE fp_name = 'Gamillus0.5';
UPDATE fluorescent_protein SET fp_uuid = 'B45Y7' WHERE fp_name = 'mcFP497';
UPDATE fluorescent_protein SET fp_uuid = 'Q1DLH' WHERE fp_name = 'mcFP506';
UPDATE fluorescent_protein SET fp_uuid = 'Z7ZOF' WHERE fp_name = 'mCherry1.5';
UPDATE fluorescent_protein SET fp_uuid = '68QLV' WHERE fp_name = 'mClavGR1.1';
UPDATE fluorescent_protein SET fp_uuid = 'KMYOV' WHERE fp_name = 'mClavGR1.8';
UPDATE fluorescent_protein SET fp_uuid = 'DQDUN' WHERE fp_name = 'mClover1.5';
UPDATE fluorescent_protein SET fp_uuid = 'C7XMS' WHERE fp_name = 'meffCP';
UPDATE fluorescent_protein SET fp_uuid = '8NMUD' WHERE fp_name = 'mEos2-NA';
UPDATE fluorescent_protein SET fp_uuid = 'JWJMF' WHERE fp_name = 'meruFP';
UPDATE fluorescent_protein SET fp_uuid = 'LJPJE' WHERE fp_name = 'mKate2.5';
UPDATE fluorescent_protein SET fp_uuid = 'DUY7T' WHERE fp_name = 'mOFP.T.8';
UPDATE fluorescent_protein SET fp_uuid = 'JMD8M' WHERE fp_name = 'montFP';
UPDATE fluorescent_protein SET fp_uuid = 'AJ9R9' WHERE fp_name = 'moxEos3.2';
UPDATE fluorescent_protein SET fp_uuid = '6P54P' WHERE fp_name = 'mPapaya0.3';
UPDATE fluorescent_protein SET fp_uuid = 'NYTRE' WHERE fp_name = 'mPapaya0.6';
UPDATE fluorescent_protein SET fp_uuid = '5OR4S' WHERE fp_name = 'mRFP1.3';
UPDATE fluorescent_protein SET fp_uuid = 'MO63Q' WHERE fp_name = 'mRFP1.5';
UPDATE fluorescent_protein SET fp_uuid = 'VUXRF' WHERE fp_name = 'mEos3.2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = '5WALF' WHERE fp_name = 'mGeos-E (On)';
UPDATE fluorescent_protein SET fp_uuid = 'WBU2Y' WHERE fp_name = 'mEosFP-M159A (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'U9LQE' WHERE fp_name = 'mGeos-S (On)';
UPDATE fluorescent_protein SET fp_uuid = 'OTXRQ' WHERE fp_name = 'mEos2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'H8UXC' WHERE fp_name = 'mGeos-F (On)';
UPDATE fluorescent_protein SET fp_uuid = 'WV3Q7' WHERE fp_name = 'pcDronpa (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'SXSQ9' WHERE fp_name = 'mMaple (Red)';
UPDATE fluorescent_protein SET fp_uuid = '11G2Y' WHERE fp_name = 'Skylan-S (On)';
UPDATE fluorescent_protein SET fp_uuid = 'JTXCJ' WHERE fp_name = 'dendFP (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'XKDOQ' WHERE fp_name = 'Dendra2-T69A (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'Q31FH' WHERE fp_name = 'Kaede (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'V2GB1' WHERE fp_name = 'mEos4b (Red)';
UPDATE fluorescent_protein SET fp_uuid = '8QC31' WHERE fp_name = 'mGeos-L (On)';
UPDATE fluorescent_protein SET fp_uuid = 'RK5BV' WHERE fp_name = 'CpYGFP (Default)';
UPDATE fluorescent_protein SET fp_uuid = 'KECCG' WHERE fp_name = 'eYGFPuv (Default)';
UPDATE fluorescent_protein SET fp_uuid = 'A8RF9' WHERE fp_name = 'CyRFP1 (CyRFP1)';
UPDATE fluorescent_protein SET fp_uuid = 'T4DJM' WHERE fp_name = 'dClover2A206K';
UPDATE fluorescent_protein SET fp_uuid = 'H93B4' WHERE fp_name = 'GRvT (FRETexcitation)';
UPDATE fluorescent_protein SET fp_uuid = 'B4SOW' WHERE fp_name = 'sfGFP';
UPDATE fluorescent_protein SET fp_uuid = 'B28N7' WHERE fp_name = 'αGFP';
UPDATE fluorescent_protein SET fp_uuid = '5WSHL' WHERE fp_name = 'CGFP';
UPDATE fluorescent_protein SET fp_uuid = '6ORKJ' WHERE fp_name = 'AcGFP1';
UPDATE fluorescent_protein SET fp_uuid = '7G47U' WHERE fp_name = 'iq-mEmerald';
UPDATE fluorescent_protein SET fp_uuid = '8XMCL' WHERE fp_name = 'cerFP505';
UPDATE fluorescent_protein SET fp_uuid = '963OH' WHERE fp_name = 'Aquamarine';
UPDATE fluorescent_protein SET fp_uuid = '97MBQ' WHERE fp_name = 'KillerOrange';
UPDATE fluorescent_protein SET fp_uuid = 'A2OWC' WHERE fp_name = 'GFPmut3';
UPDATE fluorescent_protein SET fp_uuid = 'AQACH' WHERE fp_name = 'YPet';
UPDATE fluorescent_protein SET fp_uuid = 'FRM5D' WHERE fp_name = 'DsRed.T3';
UPDATE fluorescent_protein SET fp_uuid = 'GJETS' WHERE fp_name = 'TagGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'GQRF2' WHERE fp_name = 'aceGFP';
UPDATE fluorescent_protein SET fp_uuid = 'JJV3D' WHERE fp_name = 'oxGFP';
UPDATE fluorescent_protein SET fp_uuid = 'KKQNA' WHERE fp_name = 'meleCFP';
UPDATE fluorescent_protein SET fp_uuid = 'LO7EL' WHERE fp_name = 'amilFP513';
UPDATE fluorescent_protein SET fp_uuid = 'LS1K6' WHERE fp_name = 'SGFP2(206A)';
UPDATE fluorescent_protein SET fp_uuid = 'MHMQX' WHERE fp_name = 'anobCFP2';
UPDATE fluorescent_protein SET fp_uuid = 'MZMFB' WHERE fp_name = 'mRuby3';
UPDATE fluorescent_protein SET fp_uuid = 'OADBJ' WHERE fp_name = 'mNeptune2.5';
UPDATE fluorescent_protein SET fp_uuid = 'OSFMK' WHERE fp_name = 'efasCFP';
UPDATE fluorescent_protein SET fp_uuid = 'QKFJN' WHERE fp_name = 'mEGFP';
UPDATE fluorescent_protein SET fp_uuid = 'QRBKZ' WHERE fp_name = 'mAzamiGreen';
UPDATE fluorescent_protein SET fp_uuid = 'QX7D1' WHERE fp_name = 'oxBFP';
UPDATE fluorescent_protein SET fp_uuid = 'R5RQ5' WHERE fp_name = 'eqFP611';
UPDATE fluorescent_protein SET fp_uuid = 'R9NL8' WHERE fp_name = 'EGFP';
UPDATE fluorescent_protein SET fp_uuid = 'RSDF7' WHERE fp_name = 'BFP5';
UPDATE fluorescent_protein SET fp_uuid = 'T41NE' WHERE fp_name = 'ccalGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'T9CO9' WHERE fp_name = 'LanFP1';
UPDATE fluorescent_protein SET fp_uuid = 'TDA9A' WHERE fp_name = 'eforCP';
UPDATE fluorescent_protein SET fp_uuid = 'TPB93' WHERE fp_name = 'moxCerulean3';
UPDATE fluorescent_protein SET fp_uuid = 'TWJXO' WHERE fp_name = 'mCerulean3';
UPDATE fluorescent_protein SET fp_uuid = 'U69HK' WHERE fp_name = 'psamCFP';
UPDATE fluorescent_protein SET fp_uuid = 'UQH8C' WHERE fp_name = 'mCyRFP1';
UPDATE fluorescent_protein SET fp_uuid = 'UVJD2' WHERE fp_name = 'DsRed-Max';
UPDATE fluorescent_protein SET fp_uuid = 'UEQO7' WHERE fp_name = 'mTFP0.4';
UPDATE fluorescent_protein SET fp_uuid = '134NN' WHERE fp_name = 'mKO2';
UPDATE fluorescent_protein SET fp_uuid = '296AF' WHERE fp_name = 'RFP630';
UPDATE fluorescent_protein SET fp_uuid = '2P4CB' WHERE fp_name = 'KCY';
UPDATE fluorescent_protein SET fp_uuid = '2V75Y' WHERE fp_name = 'TagGFP';
UPDATE fluorescent_protein SET fp_uuid = '39D4R' WHERE fp_name = 'FR-1';
UPDATE fluorescent_protein SET fp_uuid = '49YLM' WHERE fp_name = 'SGFP2(E222Q)';
UPDATE fluorescent_protein SET fp_uuid = '4E21X' WHERE fp_name = 'Katushka2S';
UPDATE fluorescent_protein SET fp_uuid = '514KE' WHERE fp_name = 'EBFP1.2';
UPDATE fluorescent_protein SET fp_uuid = '5GR1V' WHERE fp_name = 'mOrange2';
UPDATE fluorescent_protein SET fp_uuid = '5LCAQ' WHERE fp_name = 'mPapaya';
UPDATE fluorescent_protein SET fp_uuid = '7AV5G' WHERE fp_name = 'mTurquoise2';
UPDATE fluorescent_protein SET fp_uuid = '9ALF8' WHERE fp_name = 'mCerulean.B2';
UPDATE fluorescent_protein SET fp_uuid = '9FQLJ' WHERE fp_name = 'tdimer2(12)';
UPDATE fluorescent_protein SET fp_uuid = 'BFJKS' WHERE fp_name = 'TagBFP';
UPDATE fluorescent_protein SET fp_uuid = 'BL164' WHERE fp_name = 'SGFP2(T65G)';
UPDATE fluorescent_protein SET fp_uuid = 'CN92E' WHERE fp_name = 'mCherry2';
UPDATE fluorescent_protein SET fp_uuid = 'DVMQ7' WHERE fp_name = 'EBFP2';
UPDATE fluorescent_protein SET fp_uuid = 'G4VP2' WHERE fp_name = 'Sapphire';
UPDATE fluorescent_protein SET fp_uuid = 'G5H29' WHERE fp_name = 'laRFP';
UPDATE fluorescent_protein SET fp_uuid = 'GHNRL' WHERE fp_name = 'td-RFP611';
UPDATE fluorescent_protein SET fp_uuid = 'GSCT9' WHERE fp_name = 'moxNeonGreen';
UPDATE fluorescent_protein SET fp_uuid = 'H99SX' WHERE fp_name = 'moxGFP';
UPDATE fluorescent_protein SET fp_uuid = 'S6A7A' WHERE fp_name = 'FusionRed';
UPDATE fluorescent_protein SET fp_uuid = 'SKHT2' WHERE fp_name = 'dLanYFP';
UPDATE fluorescent_protein SET fp_uuid = 'SSTDU' WHERE fp_name = 'moxBFP';
UPDATE fluorescent_protein SET fp_uuid = 'TL112' WHERE fp_name = 'CyOFP1';
UPDATE fluorescent_protein SET fp_uuid = 'TR5BB' WHERE fp_name = 'SGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'TXLFX' WHERE fp_name = 'DsRed2';
UPDATE fluorescent_protein SET fp_uuid = 'UHNQV' WHERE fp_name = 'AausFP2';
UPDATE fluorescent_protein SET fp_uuid = 'UUTXN' WHERE fp_name = 'frFAST';
UPDATE fluorescent_protein SET fp_uuid = 'V534T' WHERE fp_name = 'CyPet';
UPDATE fluorescent_protein SET fp_uuid = 'V7M33' WHERE fp_name = 'TagYFP';
UPDATE fluorescent_protein SET fp_uuid = 'YAH6C' WHERE fp_name = 'cfSGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'ZWK6V' WHERE fp_name = 'oxCerulean';
UPDATE fluorescent_protein SET fp_uuid = '1UZQ4' WHERE fp_name = '22G';
UPDATE fluorescent_protein SET fp_uuid = '8M1M5' WHERE fp_name = 'cpasCP';
UPDATE fluorescent_protein SET fp_uuid = '2BECV' WHERE fp_name = 'gdjiCP';
UPDATE fluorescent_protein SET fp_uuid = '16WGJ' WHERE fp_name = 'EosFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'JY7XC' WHERE fp_name = 'Dreiklang (On)';
UPDATE fluorescent_protein SET fp_uuid = 'RHTPG' WHERE fp_name = 'mKikGR (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'N8HMF' WHERE fp_name = 'mEosFP (Red)';
UPDATE fluorescent_protein SET fp_uuid = '81ENW' WHERE fp_name = 'mEosFP-F173S (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'OB7P5' WHERE fp_name = 'KikGR1 (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'OTXRQ' WHERE fp_name = 'mEos2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'XJO9Z' WHERE fp_name = 'rsFastLime (On)';
UPDATE fluorescent_protein SET fp_uuid = '2HEJS' WHERE fp_name = 'mTFP0.7 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'CQ4QL' WHERE fp_name = 'Dendra2-M159A (Green)';
UPDATE fluorescent_protein SET fp_uuid = '7UFQR' WHERE fp_name = 'PATagRFP1314 (On)';
UPDATE fluorescent_protein SET fp_uuid = '162KQ' WHERE fp_name = 'Padron (On)';
UPDATE fluorescent_protein SET fp_uuid = 'MRKZY' WHERE fp_name = 'SPOON (on)';
UPDATE fluorescent_protein SET fp_uuid = '7P38V' WHERE fp_name = 'Dronpa (On)';
UPDATE fluorescent_protein SET fp_uuid = 'KDHFJ' WHERE fp_name = 'mIrisFP (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'GE6KO' WHERE fp_name = 'Dendra2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = '42Q3E' WHERE fp_name = 'Dronpa-3 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'L1ZEW' WHERE fp_name = 'Kohinoor2.0 (On)';
UPDATE fluorescent_protein SET fp_uuid = '4Z6XY' WHERE fp_name = 'rsEGFP2 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'Y46HX' WHERE fp_name = 'moxDendra2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = '6LRFZ' WHERE fp_name = 'mClavGR2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'JYYJ1' WHERE fp_name = 'rsEGFP (On)';
UPDATE fluorescent_protein SET fp_uuid = '21E2G' WHERE fp_name = 'eYGPdp (Default)';
UPDATE fluorescent_protein SET fp_uuid = 'CQ4QL' WHERE fp_name = 'Dendra2-M159A (Orange)';
UPDATE fluorescent_protein SET fp_uuid = '7VM5E' WHERE fp_name = 'jRCaMP1a (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'U76BO' WHERE fp_name = 'PSmOrange2 (Orange)';
UPDATE fluorescent_protein SET fp_uuid = '5ELUZ' WHERE fp_name = 'K-GECO1 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = '87UEF' WHERE fp_name = 'NijiFP (Orange)';
UPDATE fluorescent_protein SET fp_uuid = 'ALL3F' WHERE fp_name = 'eqFP611V124T';
UPDATE fluorescent_protein SET fp_uuid = 'B6J33' WHERE fp_name = 'GFP(S65T)';
UPDATE fluorescent_protein SET fp_uuid = '2VONA' WHERE fp_name = 'sg50';
UPDATE fluorescent_protein SET fp_uuid = '37XMD' WHERE fp_name = 'eechGFP2';
UPDATE fluorescent_protein SET fp_uuid = '437NM' WHERE fp_name = 'KCY-R1';
UPDATE fluorescent_protein SET fp_uuid = '498LC' WHERE fp_name = 'aacuGFP1';
UPDATE fluorescent_protein SET fp_uuid = '4O71N' WHERE fp_name = 'mNectarine';
UPDATE fluorescent_protein SET fp_uuid = '5DP2R' WHERE fp_name = 'DsRed-Express2';
UPDATE fluorescent_protein SET fp_uuid = '6KLAW' WHERE fp_name = 'mRuby';
UPDATE fluorescent_protein SET fp_uuid = '886AH' WHERE fp_name = 'AzaleaB5';
UPDATE fluorescent_protein SET fp_uuid = '8BUQQ' WHERE fp_name = 'pmeaGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'A3B6M' WHERE fp_name = 'E2-Orange';
UPDATE fluorescent_protein SET fp_uuid = 'ACXOE' WHERE fp_name = 'vsfGFP-9';
UPDATE fluorescent_protein SET fp_uuid = 'B3LN6' WHERE fp_name = 'RFP639';
UPDATE fluorescent_protein SET fp_uuid = 'CVUYM' WHERE fp_name = 'Cerulean';
UPDATE fluorescent_protein SET fp_uuid = 'F1MW1' WHERE fp_name = 'tKeima';
UPDATE fluorescent_protein SET fp_uuid = 'G1VL1' WHERE fp_name = 'mGreenLantern';
UPDATE fluorescent_protein SET fp_uuid = 'GUFES' WHERE fp_name = 'mVFP';
UPDATE fluorescent_protein SET fp_uuid = 'HXBWE' WHERE fp_name = 'LanFP2';
UPDATE fluorescent_protein SET fp_uuid = 'JGCGO' WHERE fp_name = 'obeCFP';
UPDATE fluorescent_protein SET fp_uuid = 'KSK4V' WHERE fp_name = 'mT-Sapphire';
UPDATE fluorescent_protein SET fp_uuid = 'MLHQR' WHERE fp_name = 'Achilles';
UPDATE fluorescent_protein SET fp_uuid = 'NLY5P' WHERE fp_name = 'T-Sapphire';
UPDATE fluorescent_protein SET fp_uuid = 'NYYN4' WHERE fp_name = 'mBlueberry2';
UPDATE fluorescent_protein SET fp_uuid = 'ORBRD' WHERE fp_name = 'mCerulean.B';
UPDATE fluorescent_protein SET fp_uuid = 'PX32J' WHERE fp_name = 'iq-mCerulean3';
UPDATE fluorescent_protein SET fp_uuid = 'Q2ZO7' WHERE fp_name = 'Katushka';
UPDATE fluorescent_protein SET fp_uuid = 'QB9WJ' WHERE fp_name = 'mKillerOrange';
UPDATE fluorescent_protein SET fp_uuid = 'QNZSY' WHERE fp_name = 'pdae1GFP';
UPDATE fluorescent_protein SET fp_uuid = 'QXJO4' WHERE fp_name = 'iq-EBFP2';
UPDATE fluorescent_protein SET fp_uuid = 'SEJPD' WHERE fp_name = 'anm2CP';
UPDATE fluorescent_protein SET fp_uuid = 'T5UGO' WHERE fp_name = 'mApple';
UPDATE fluorescent_protein SET fp_uuid = 'T7XX8' WHERE fp_name = 'MiCy';
UPDATE fluorescent_protein SET fp_uuid = 'TN3DM' WHERE fp_name = 'mStrawberry';
UPDATE fluorescent_protein SET fp_uuid = 'TZ5KN' WHERE fp_name = 'SGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'U97V7' WHERE fp_name = 'pmimGFP2';
UPDATE fluorescent_protein SET fp_uuid = 'VXEVZ' WHERE fp_name = 'mNeptune2';
UPDATE fluorescent_protein SET fp_uuid = 'W8LAG' WHERE fp_name = 'ZsGreen';
UPDATE fluorescent_protein SET fp_uuid = 'WRF55' WHERE fp_name = 'mKate';
UPDATE fluorescent_protein SET fp_uuid = 'XBGJO' WHERE fp_name = 'EBFP1.5';
UPDATE fluorescent_protein SET fp_uuid = '1K2R7' WHERE fp_name = 'BrUSLEE';
UPDATE fluorescent_protein SET fp_uuid = '243P7' WHERE fp_name = 'mCerulean.B24';
UPDATE fluorescent_protein SET fp_uuid = '2D7XF' WHERE fp_name = 'cgfmKate2';
UPDATE fluorescent_protein SET fp_uuid = '7ZG25' WHERE fp_name = 'sg25';
UPDATE fluorescent_protein SET fp_uuid = '8PKAY' WHERE fp_name = 'mTFP0.3';
UPDATE fluorescent_protein SET fp_uuid = 'ASMG7' WHERE fp_name = 'gfasGFP';
UPDATE fluorescent_protein SET fp_uuid = 'D7QYG' WHERE fp_name = 'AausGFP';
UPDATE fluorescent_protein SET fp_uuid = 'DF1S4' WHERE fp_name = 'mAmetrine';
UPDATE fluorescent_protein SET fp_uuid = 'E3FDV' WHERE fp_name = 'FusionRed-M';
UPDATE fluorescent_protein SET fp_uuid = 'F35B7' WHERE fp_name = 'FusionRed-MQV';
UPDATE fluorescent_protein SET fp_uuid = 'G9FG2' WHERE fp_name = '5B';
UPDATE fluorescent_protein SET fp_uuid = 'HFE84' WHERE fp_name = 'SCFP3A';
UPDATE fluorescent_protein SET fp_uuid = 'J2JWA' WHERE fp_name = 'mCerulean';
UPDATE fluorescent_protein SET fp_uuid = 'J325F' WHERE fp_name = 'SBFP2';
UPDATE fluorescent_protein SET fp_uuid = 'KBERH' WHERE fp_name = 'Turquoise-GL';
UPDATE fluorescent_protein SET fp_uuid = 'LGDN9' WHERE fp_name = 'mPapaya0.7';
UPDATE fluorescent_protein SET fp_uuid = 'O2UFD' WHERE fp_name = 'G1';
UPDATE fluorescent_protein SET fp_uuid = 'OW4TY' WHERE fp_name = 'pmimGFP1';
UPDATE fluorescent_protein SET fp_uuid = 'QNYK6' WHERE fp_name = 'BDFP1.6';
UPDATE fluorescent_protein SET fp_uuid = 'QVF1F' WHERE fp_name = 'RFP637';
UPDATE fluorescent_protein SET fp_uuid = 'RFW2X' WHERE fp_name = 'sg42';
UPDATE fluorescent_protein SET fp_uuid = 'TUONH' WHERE fp_name = 'mKalama1';
UPDATE fluorescent_protein SET fp_uuid = 'VAXZZ' WHERE fp_name = 'amilFP490';
UPDATE fluorescent_protein SET fp_uuid = 'WRK8K' WHERE fp_name = 'TagCFP';
UPDATE fluorescent_protein SET fp_uuid = 'YVJ5E' WHERE fp_name = 'SCFP3B';
UPDATE fluorescent_protein SET fp_uuid = 'ZS5CR' WHERE fp_name = 'mMiCy';
UPDATE fluorescent_protein SET fp_uuid = '8B9TX' WHERE fp_name = 'spGFP1-10';
UPDATE fluorescent_protein SET fp_uuid = 'OMXT2' WHERE fp_name = 'zGFP';
UPDATE fluorescent_protein SET fp_uuid = '1S3QB' WHERE fp_name = 'Clover1.5';
UPDATE fluorescent_protein SET fp_uuid = 'VUXRF' WHERE fp_name = 'mEos3.2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'YJY7C' WHERE fp_name = 'mEos2-A69T (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'RHTPG' WHERE fp_name = 'mKikGR (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'Q31FH' WHERE fp_name = 'Kaede (Red)';
UPDATE fluorescent_protein SET fp_uuid = '1SEDF' WHERE fp_name = 'd2EosFP (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'XQCPX' WHERE fp_name = 'PATagRFP1297 (On)';
UPDATE fluorescent_protein SET fp_uuid = '87UEF' WHERE fp_name = 'NijiFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'KDHFJ' WHERE fp_name = 'mIrisFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'OAKV5' WHERE fp_name = 'PATagRFP (On)';
UPDATE fluorescent_protein SET fp_uuid = 'YLRRG' WHERE fp_name = 'd1EosFP (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'GGUJF' WHERE fp_name = 'pcDronpa2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = '9U6KU' WHERE fp_name = 'ffDronpa (On)';
UPDATE fluorescent_protein SET fp_uuid = '73GT1' WHERE fp_name = 'mEos3.1 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'EC56T' WHERE fp_name = 'mEos4a (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'GGUJF' WHERE fp_name = 'pcDronpa2 (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'MNH1D' WHERE fp_name = 'mMaple3 (Green)';
UPDATE fluorescent_protein SET fp_uuid = '16WGJ' WHERE fp_name = 'EosFP (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'DOGBN' WHERE fp_name = 'bsDronpa (On)';
UPDATE fluorescent_protein SET fp_uuid = 'GE6KO' WHERE fp_name = 'Dendra2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'PA6OT' WHERE fp_name = 'IrisFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'FM4GO' WHERE fp_name = 'Padron0.9 (On)';
UPDATE fluorescent_protein SET fp_uuid = '3SXVB' WHERE fp_name = 'pcStar (Red)';
UPDATE fluorescent_protein SET fp_uuid = '73GT1' WHERE fp_name = 'mEos3.1 (Red)';
UPDATE fluorescent_protein SET fp_uuid = '52ADP' WHERE fp_name = 'Dronpa-2 (On)';
UPDATE fluorescent_protein SET fp_uuid = 'PA6OT' WHERE fp_name = 'IrisFP (Orange)';
UPDATE fluorescent_protein SET fp_uuid = 'WZXU4' WHERE fp_name = 'CAR-GECO1 (calciumsaturated)';
UPDATE fluorescent_protein SET fp_uuid = 'YJY7C' WHERE fp_name = 'mEos2-A69T (Orange)';
UPDATE fluorescent_protein SET fp_uuid = '37TVB' WHERE fp_name = 'O-GECO1 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = 'MQNBX' WHERE fp_name = 'eYGFP (Default)';
UPDATE fluorescent_protein SET fp_uuid = 'XKDOQ' WHERE fp_name = 'Dendra2-T69A (Orange)';
UPDATE fluorescent_protein SET fp_uuid = '26VNF' WHERE fp_name = 'mKateM41GS158C';
UPDATE fluorescent_protein SET fp_uuid = 'W34KB' WHERE fp_name = 'mKateS158C';
UPDATE fluorescent_protein SET fp_uuid = 'D9JZ4' WHERE fp_name = 'rsGreen1 (Bright)';
UPDATE fluorescent_protein SET fp_uuid = 'UNETX' WHERE fp_name = 'mGold';
UPDATE fluorescent_protein SET fp_uuid = 'UQX41' WHERE fp_name = 'muGFP';
UPDATE fluorescent_protein SET fp_uuid = '1NW9S' WHERE fp_name = 'mRed7';
UPDATE fluorescent_protein SET fp_uuid = '1SBTT' WHERE fp_name = 'mcavGFP';
UPDATE fluorescent_protein SET fp_uuid = '1XF1B' WHERE fp_name = 'avGFP';
UPDATE fluorescent_protein SET fp_uuid = '1ZQEX' WHERE fp_name = 'HcRed1-Blue';
UPDATE fluorescent_protein SET fp_uuid = '24DFB' WHERE fp_name = 'cgigCP';
UPDATE fluorescent_protein SET fp_uuid = '2KWB9' WHERE fp_name = 'moxVenus';
UPDATE fluorescent_protein SET fp_uuid = '3KHK4' WHERE fp_name = 'KCY-G4219';
UPDATE fluorescent_protein SET fp_uuid = '4LKQ5' WHERE fp_name = 'shBFP-N158S/L173I';
UPDATE fluorescent_protein SET fp_uuid = '4UCC6' WHERE fp_name = 'PlamGFP';
UPDATE fluorescent_protein SET fp_uuid = '5E826' WHERE fp_name = 'mTurquoise';
UPDATE fluorescent_protein SET fp_uuid = '63KQB' WHERE fp_name = 'CheGFP1';
UPDATE fluorescent_protein SET fp_uuid = '6LJKY' WHERE fp_name = 'mRojoB';
UPDATE fluorescent_protein SET fp_uuid = '7EWEM' WHERE fp_name = 'mCardinal';
UPDATE fluorescent_protein SET fp_uuid = '85KA4' WHERE fp_name = 'phiYFPv';
UPDATE fluorescent_protein SET fp_uuid = '8KFSR' WHERE fp_name = 'amFP515';
UPDATE fluorescent_protein SET fp_uuid = 'AE8QV' WHERE fp_name = 'mGarnet';
UPDATE fluorescent_protein SET fp_uuid = 'AW33C' WHERE fp_name = 'Gamillus0.1';
UPDATE fluorescent_protein SET fp_uuid = 'C5398' WHERE fp_name = 'hcriGFP';
UPDATE fluorescent_protein SET fp_uuid = 'DBBO8' WHERE fp_name = 'mKate2';
UPDATE fluorescent_protein SET fp_uuid = 'EEJ9Q' WHERE fp_name = 'mCerulean2.N(T65S)';
UPDATE fluorescent_protein SET fp_uuid = 'EGE3L' WHERE fp_name = 'DsRed';
UPDATE fluorescent_protein SET fp_uuid = 'ENFU4' WHERE fp_name = 'cgreGFP';
UPDATE fluorescent_protein SET fp_uuid = 'GHBKT' WHERE fp_name = 'D10';
UPDATE fluorescent_protein SET fp_uuid = 'HGBNQ' WHERE fp_name = 'smURFP';
UPDATE fluorescent_protein SET fp_uuid = 'HGZ48' WHERE fp_name = 'zoan2RFP';
UPDATE fluorescent_protein SET fp_uuid = 'JF6E7' WHERE fp_name = 'McaG1ea';
UPDATE fluorescent_protein SET fp_uuid = 'JXVU8' WHERE fp_name = 'mRouge';
UPDATE fluorescent_protein SET fp_uuid = 'L5QET' WHERE fp_name = 'amCyan1';
UPDATE fluorescent_protein SET fp_uuid = 'LTRTO' WHERE fp_name = 'AvicFP4';
UPDATE fluorescent_protein SET fp_uuid = 'MZOGH' WHERE fp_name = 'TDsmURFP';
UPDATE fluorescent_protein SET fp_uuid = 'N3G27' WHERE fp_name = 'iRFP682';
UPDATE fluorescent_protein SET fp_uuid = 'ORVNV' WHERE fp_name = 'dis2RFP';
UPDATE fluorescent_protein SET fp_uuid = 'OX75X' WHERE fp_name = 'iRFP720';
UPDATE fluorescent_protein SET fp_uuid = 'PGG5S' WHERE fp_name = 'tdTomato';
UPDATE fluorescent_protein SET fp_uuid = 'PQRLE' WHERE fp_name = 'secBFP2';
UPDATE fluorescent_protein SET fp_uuid = 'RAKQZ' WHERE fp_name = 'miRFP680';
UPDATE fluorescent_protein SET fp_uuid = 'RR1M4' WHERE fp_name = 'mKO';
UPDATE fluorescent_protein SET fp_uuid = 'T33XW' WHERE fp_name = 'phiLOV2.1';
UPDATE fluorescent_protein SET fp_uuid = 'T972V' WHERE fp_name = 'sg12';
UPDATE fluorescent_protein SET fp_uuid = 'TCPO9' WHERE fp_name = 'mPlum-E16P';
UPDATE fluorescent_protein SET fp_uuid = 'UDAAK' WHERE fp_name = 'mCerulean2';
UPDATE fluorescent_protein SET fp_uuid = 'UOJ8M' WHERE fp_name = 'sREACh';
UPDATE fluorescent_protein SET fp_uuid = 'V6A1P' WHERE fp_name = 'Wi-Phy';
UPDATE fluorescent_protein SET fp_uuid = 'VWTNO' WHERE fp_name = 'HcRed-Tandem';
UPDATE fluorescent_protein SET fp_uuid = 'ZERB6' WHERE fp_name = 'mCherry';
UPDATE fluorescent_protein SET fp_uuid = 'ZO7NN' WHERE fp_name = 'mTagBFP2';
UPDATE fluorescent_protein SET fp_uuid = 'ZRKRV' WHERE fp_name = 'mNeonGreen';
UPDATE fluorescent_protein SET fp_uuid = 'ZZHSE' WHERE fp_name = 'miniSOG';
UPDATE fluorescent_protein SET fp_uuid = '3BHUX' WHERE fp_name = 'mTurquoise-DR';
UPDATE fluorescent_protein SET fp_uuid = 'XTCUL' WHERE fp_name = 'PDM1-4';
UPDATE fluorescent_protein SET fp_uuid = '6ZODM' WHERE fp_name = 'RpBphP6';
UPDATE fluorescent_protein SET fp_uuid = '15MYG' WHERE fp_name = 'zFP538';
UPDATE fluorescent_protein SET fp_uuid = '18KQQ' WHERE fp_name = 'amilCP';
UPDATE fluorescent_protein SET fp_uuid = '1BEMJ' WHERE fp_name = 'sarcGFP';
UPDATE fluorescent_protein SET fp_uuid = '1KUE6' WHERE fp_name = 'miRFP670-2';
UPDATE fluorescent_protein SET fp_uuid = '1LT8G' WHERE fp_name = 'mNeptune';
UPDATE fluorescent_protein SET fp_uuid = '2BJM7' WHERE fp_name = 'dTFP0.1';
UPDATE fluorescent_protein SET fp_uuid = '2EG15' WHERE fp_name = 'miRFP713';
UPDATE fluorescent_protein SET fp_uuid = '2ERUG' WHERE fp_name = 'mBeRFP';
UPDATE fluorescent_protein SET fp_uuid = '6HML4' WHERE fp_name = 'rrenGFP';
UPDATE fluorescent_protein SET fp_uuid = 'A8BXL' WHERE fp_name = 'KO';
UPDATE fluorescent_protein SET fp_uuid = 'BXYZE' WHERE fp_name = 'mUkG';
UPDATE fluorescent_protein SET fp_uuid = 'C16U6' WHERE fp_name = 'eGFP203C';
UPDATE fluorescent_protein SET fp_uuid = 'DCYCK' WHERE fp_name = 'DsRed-Express';
UPDATE fluorescent_protein SET fp_uuid = 'DH5VX' WHERE fp_name = 'aceGFP-G222E-Y220L';
UPDATE fluorescent_protein SET fp_uuid = 'DP999' WHERE fp_name = 'miRFP670';
UPDATE fluorescent_protein SET fp_uuid = 'FD244' WHERE fp_name = 'mRtms5';
UPDATE fluorescent_protein SET fp_uuid = 'G9U12' WHERE fp_name = 'cgfTagRFP';
UPDATE fluorescent_protein SET fp_uuid = 'JS838' WHERE fp_name = 'eqFP650';
UPDATE fluorescent_protein SET fp_uuid = 'LDVKW' WHERE fp_name = 'mIFP';
UPDATE fluorescent_protein SET fp_uuid = 'LG377' WHERE fp_name = 'mCarmine';
UPDATE fluorescent_protein SET fp_uuid = 'LQXJ6' WHERE fp_name = 'Gamillus0.3';
UPDATE fluorescent_protein SET fp_uuid = 'O8SH6' WHERE fp_name = 'cFP484';
UPDATE fluorescent_protein SET fp_uuid = 'P4KRD' WHERE fp_name = 'mRFP1-Q66T';
UPDATE fluorescent_protein SET fp_uuid = 'Q6V69' WHERE fp_name = 'miRFP709';
UPDATE fluorescent_protein SET fp_uuid = 'VSU6B' WHERE fp_name = 'E2-Crimson';
UPDATE fluorescent_protein SET fp_uuid = 'VVQ8D' WHERE fp_name = 'SOPP';
UPDATE fluorescent_protein SET fp_uuid = 'WLNHW' WHERE fp_name = 'Gamillus0.2';
UPDATE fluorescent_protein SET fp_uuid = 'WNJAS' WHERE fp_name = 'mBlueberry1';
UPDATE fluorescent_protein SET fp_uuid = 'Y8A5R' WHERE fp_name = 'roGFP1-R1';
UPDATE fluorescent_protein SET fp_uuid = 'ZC4KN' WHERE fp_name = 'dimer1';
UPDATE fluorescent_protein SET fp_uuid = 'UHMHB' WHERE fp_name = 'sfCherry2';
UPDATE fluorescent_protein SET fp_uuid = 'O7UJT' WHERE fp_name = 'sympFP';
UPDATE fluorescent_protein SET fp_uuid = '4PHX7' WHERE fp_name = 'zRFP';
UPDATE fluorescent_protein SET fp_uuid = '9BUDR' WHERE fp_name = 'mClavGR1';
UPDATE fluorescent_protein SET fp_uuid = 'X26SE' WHERE fp_name = 'mcRFP';
UPDATE fluorescent_protein SET fp_uuid = 'B55T2' WHERE fp_name = 'mOFP.T.12';
UPDATE fluorescent_protein SET fp_uuid = 'NPU85' WHERE fp_name = 'mPA-GFP';
UPDATE fluorescent_protein SET fp_uuid = 'NWMCV' WHERE fp_name = 'mRFP1.4';
UPDATE fluorescent_protein SET fp_uuid = 'WADLS' WHERE fp_name = 'psupFP';
UPDATE fluorescent_protein SET fp_uuid = '5N1DD' WHERE fp_name = 'KFP1 (On)';
UPDATE fluorescent_protein SET fp_uuid = '6LRFZ' WHERE fp_name = 'mClavGR2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = '81ENW' WHERE fp_name = 'mEosFP-F173S (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'O72EP' WHERE fp_name = 'SAASoti (Red)';
UPDATE fluorescent_protein SET fp_uuid = 'N8HMF' WHERE fp_name = 'mEosFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'WV3Q7' WHERE fp_name = 'pcDronpa (Green)';
UPDATE fluorescent_protein SET fp_uuid = '1SEDF' WHERE fp_name = 'd2EosFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'YLRRG' WHERE fp_name = 'd1EosFP (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'OB7P5' WHERE fp_name = 'KikGR1 (Green)';
UPDATE fluorescent_protein SET fp_uuid = 'VPDTG' WHERE fp_name = 'Skylan-NS (On)';
UPDATE fluorescent_protein SET fp_uuid = 'Y46HX' WHERE fp_name = 'moxDendra2 (Green)';
UPDATE fluorescent_protein SET fp_uuid = '21PQ5' WHERE fp_name = 'Gamillus (On)';
UPDATE fluorescent_protein SET fp_uuid = 'WZXU4' WHERE fp_name = 'CAR-GECO1 (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = '1EOAR' WHERE fp_name = 'GFP(E222G) (Default)';
UPDATE fluorescent_protein SET fp_uuid = '7VM5E' WHERE fp_name = 'jRCaMP1a (calciumfree)';
UPDATE fluorescent_protein SET fp_uuid = '4BUSQ' WHERE fp_name = 'Pp2FbFP';
UPDATE fluorescent_protein SET fp_uuid = '4RWBQ' WHERE fp_name = 'Channelrhodopsin2 (C1)';
UPDATE fluorescent_protein SET fp_uuid = 'SXBT1' WHERE fp_name = 'mKeima (pH6)';
UPDATE fluorescent_protein SET fp_uuid = '6EEUG' WHERE fp_name = 'SuperNovaRed';
UPDATE fluorescent_protein SET fp_uuid = 'AJWMF' WHERE fp_name = 'cpT-Sapphire174-173';
UPDATE fluorescent_protein SET fp_uuid = 'BRFP4' WHERE fp_name = 'mKateS158A';
UPDATE fluorescent_protein SET fp_uuid = 'HMK8R' WHERE fp_name = 'mKOκ';
UPDATE fluorescent_protein SET fp_uuid = 'TUP2T' WHERE fp_name = 'mRhubarb719 (Pr)';
UPDATE fluorescent_protein SET fp_uuid = 'XKELZ' WHERE fp_name = 'pHluorin,ratiometric (acidic)';