#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Stock Center Mutant submission directory
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/stckctr/submission

GENERICS = submit.html  request.html

STATICS = index.html reasons.html submit.txt husbandry.html marker.html links.html \
zfinId.jpg zfinGene.jpg zdbId.html zdbGeneId.html thankyou.html grant.html\
request.txt  success.html

# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
