#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Stock Center Mutant submission directory
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/stckctr/submission

GENERICS = index.html\
requestAnimals2.html\
requestAntibodies2.html\
requestBooks.html\
requestESTs2.html\
submit.html\
submitMTAform.html

STATICS = background.html\
bgblank.gif\
bgbtm.jpg\
bgimage.jpg\
bgtop.jpg\
grant.html\
husbandry.html\
links.html\
marker.html\
pcr.js\
provider.html\
reasons.html\
request.html\
request.txt\
requestAnimals.html\
requestAnimals.txt\
requestAntibodies.html\
requestAntibodies.txt\
requestBooks.txt\
requestESTs.html\
requestESTs.txt\
requestThankyou.html\
submit.txt\
submitMTAdefined.html\
submitMTApdf.html\
submitPCR.html\
submitSuccess.html\
submitTerms.html\
submitTerms2.html\
submitTryAgain.html\
zdb-est-id.jpg\
zdb-fish-id.jpg\
zdbGeneId.html\
zdbId.html\
zfinGene.jpg\
zfinId.jpg\
zirc.css\
zirc.js\
zircCC.html\
zircCC.pdf

# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
