#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Static web pages high resolution
# sketches images directory.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/images/high_res_sketches

STATICS = 0.2h.gif 0.75h.gif 01.0h.gif 01.25h.gif 01.5h.gif 01.75h.gif \
	02.0h.gif 02.25h.gif 02.5h.gif 02.75h.gif 03.0h.gif 03.3h.gif \
	03.7h.gif 04.0h.gif 04.3h.gif 04.7h.gif 05.3h.gif 05.7h.gif 06h.gif \
	08h.gif 09h.gif 10h.gif 11h.gif 12h.gif 14h.gif 160h.gif 16h.gif \
	18h.gif 19.5h.gif 22h.gif 25h.gif 31h.gif 35h.gif 42h.gif 48h.gif \
	60h.gif 72h.gif


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
