begin work ;

select distinct mrkr_comments from marker
where mrkr_type like '%GENE%';

-- first, the generic note, then the specific part of the rest of the notes


update marker
set mrkr_comments = replace (mrkr_comments, "This gene is characterized solely by an EST or collection of ESTs. When more is known about the gene, the current gene nomenclature based on the EST name will be replaced with more traditional zebrafish gene nomenclature.","") 
where mrkr_type like '%GENE%';

-- a second take on the generic note

update marker
set mrkr_comments = replace (mrkr_comments, "This gene is derived from the zebrafish genome sequencing and annotation project. When more is known about the gene, the current nomenclature will be replaced with more traditional zebrafish gene nomenclature.","") 
where mrkr_type like '%GENE%';

-- appears identical to first one, but apparently isn't:

update marker
set mrkr_comments = replace (mrkr_comments, "This gene is characterized solely by an EST or collection of ESTs. When more is known about the gene, the current gene nomenclature based on the EST name will be replaced with more traditional zebrafish gene nomenclature.","") 
where mrkr_type like '%GENE%';



-- ch:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'ch' indicates this gene is represented by an EST generated at Children's Hospital.","")
where mrkr_type = 'GENE';



-- df:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'df' indicates this gene is represented by an EST generated at Dana-Farber Cancer Institute.","")
where mrkr_type = 'GENE';


-- gb: 

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'gb' indicates this gene is represented by an EST from GenBank.","")
where mrkr_type = 'GENE';

-- id:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'id' indicates this gene is represented by an EST generated at National Institute of Child Health and Human Development, NIH.","")
where mrkr_type = 'GENE';

-- ig: 

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'ig' indicates this gene is represented by an EST generated at The Institute for Genomic Research.","")
where mrkr_type = 'GENE';

-- ik: uses default blurb

-- im:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix im: indicates this gene is represented by an EST generated by the I.M.A.G.E. Consortium.","")
where  mrkr_type = 'GENE';

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix im: indicates this gene is represented by an EST generated at the Thisse's Lab","")
where mrkr_type = 'GENE';

-- hm:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'hm' indicates this gene is represented by an EST generated at Harvard Medical School.","")
where  mrkr_type = 'GENE';

-- mg: 

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'mg' indicates this gene is represented by an EST generated at Massachusetts General Hospital.","")
where mrkr_type = 'GENE';

-- mp:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'mp' indicates this gene is represented by an EST generated at Max-Planck-Institute fuer Molekulare Genetik.","")
where  mrkr_type = 'GENE';

-- ns:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'ns' indicates this gene is represented by an EST generated at National University of Singapore.","")
where mrkr_type = 'GENE';

-- sb:eu

update marker
set mrkr_comments = replace (mrkr_comments, "This gene is characterized solely by a PCR fragment. When more is known about the gene, the current gene nomenclature based on the placeholder name will be replaced with more traditional zebrafish gene nomenclature. The prefix sb: indicates this gene is represented by a genomic sequence submitted by the Thisse Lab.","")
where mrkr_type = 'GENE';

-- sb:cb

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix sb: indicates this gene is represented by an EST generated at the Thisse Lab.","")
where mrkr_type = 'GENE';

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'sb:' indicates this gene is represented by an EST generated at the Thisse Lab.","")
where mrkr_type = 'GENE';

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'sb:' indicates this gene is represented by an EST generated at the Thisse's Lab.","")
where mrkr_type = 'GENE';


-- si: --  some si pseudogenes have the gene disclaimer, so I'll do a like match for this whole section

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'si:' indicates that this gene is represented by annotated genomic sequence from the Sanger Institute.","")
where mrkr_type like '%GENE%';

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix'si:' indicates that this gene is represented by annotated genomic sequence from the Sanger Institute.","")
where mrkr_type like '%GENE%';

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix `si:' indicates that this gene is represented by annotated genomic sequence from the Sanger Institute.","")
where mrkr_type like '%GENE%';


-- si: psuedogenes

update marker
set mrkr_comments = replace (mrkr_comments, "This pseudogene is derived from the zebrafish genome sequencing and annotation project. When more is known about the pseudogene, the current nomenclature will be replaced with more traditional zebrafish gene nomenclature. The prefix 'si:' indicates that this pseudogene is represented by annotated genomic sequence from the Sanger Institute.","")
where  mrkr_type = 'GENEP';

update marker
set mrkr_comments = replace (mrkr_comments, "This pseudogene is derived from the zebrafish genome sequencing and annotation project. When more is known about the pseudogene, the current nomenclature will be replaced with more traditional zebrafish gene nomenclature. The prefix `si:' indicates that this pseudogene is represented by annotated genomic sequence from the Sanger Institute.","")
where mrkr_type = 'GENEP';


-- wu:

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix wu: indicates this gene is represented by an EST generated at Washington University School of Medicine.","")
where  mrkr_type = 'GENE';

-- no period

update marker
set mrkr_comments = replace (mrkr_comments, "The prefix wu: indicates this gene is represented by an EST generated at Washington University School of Medicine","")
where  mrkr_type = 'GENE';

-- ?
update marker
set mrkr_comments = replace (mrkr_comments, "The prefix 'wu' indicates this gene is represented by an EST generated at Washington University School of Medicine.","")
where mrkr_type = 'GENE';


update marker
set mrkr_comments = replace (mrkr_comments, "This gene is characterized solely by an EST or collection of ESTs. When more is known about the gene, the current gene nomenclature based on the EST name will be replaced with more traditional zebrafish gene nomenclature. The prefix 'wu' indicates this gene is represented by an EST generated at Washington University School of Medicine.","")
where mrkr_type = 'GENE';



-- xx: is just the default note


-- zgc note

update marker
  set mrkr_comments = replace (mrkr_comments, "This gene is characterized by full length cDNAs isolated as part of the Zebrafish Gene Collection (ZGC). When more is known about the gene, the current nomenclature will be replaced with more traditional zebrafish gene nomenclature. The prefix `zgc:' indicates that this gene is represented by cDNAs generated by the ZGC project.", "")
where  mrkr_type = 'GENE';


-- at least one has a <br> tag, it should go away

update marker
  set mrkr_comments = replace (mrkr_comments, "<br>", "")
where  mrkr_type like '%GENE%';

-- clean up empties

update marker
  set mrkr_Comments = null
  where mrkr_comments = '';


-- show result

select distinct mrkr_comments from marker
where mrkr_type like '%GENE%';

--rollback work ;
commit work;