#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Stock Center directory
#
# $Source$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../..
include $(TOP)/make.include

SUBDIRS = 

TARGETDIR = $(TARGETROOT)/home/zf_info/stckctr/dis_man/Disease_images

GENERICS = 

STATICS = BigHeartGross4.jpg              MicrosporHisto4_small.jpg \
	BigHeartGross4_small.jpg        MycoBactImprints4.jpg   \
	MycoBactImprints4_small.jpg \
	CapFig54.jpg                    MycobacteGross4.jpg \
	CapFig54_small.jpg              MycobacteGross4_small.jpg \
	CapillariaWetMounts4.jpg        NeprhocalX104.jpg \
	CapillariaWetMounts4_small.jpg  NeprhocalX104_small.jpg \
	EAIF4.jpg                       Oodinium4.jpg \
	EAIF4_small.jpg                 Oodinium4_small.jpg \
	GasBubDisHisto4.jpg             PericardialHisto4.jpg \
	GasBubDisHisto4_small.jpg       PericardialHisto4_small.jpg \
	GasBubbleDis4.jpg               PseudolFungiFlorFluorCNS4.jpg \
	GasBubbleDis4_small.jpg         SpincleCellGrossB4.jpg \
	GrossSeminoma4.jpg              SpincleCellGrossB4_small.jpg \
	GrossSeminoma4_small.jpg        SpindleCellEye4.jpg \
	HepaticMeg4.jpg                 SpindleCellEye4_small.jpg \
	HepaticMeg4_small.jpg           SpindleCellGrossA4.jpg \
	HepatocelCar4.jpg               SpindleCellGrossA4_small.jpg \
	HepatocelCar4_small.jpg         SpindleCellLowMag4.jpg \
	IchSockeye4.jpg                 SpindleCellLowMag4_small.jpg \
	IchSockeye4_small.jpg           TailRot4.jpg \
	IchWetMount4.jpg                TailRot4_small.jpg \
	IchWetMount4_small.jpg          bacterialgilldis4.jpg \
	IntestinalTumors4.jpg           bacterialgilldis4_small.jpg \
	IntestinalTumors4_small.jpg     capillariaHemangEye4.jpg \
	IntestinalTumorsB4.jpg          capillariaHemangEye4_small.jpg \
	IntestinalTumorsB4_small.jpg    mycobactHisto4.jpg \
	LiverTumorsDMBA4.jpg            mycobactHisto4_small.jpg \
	LiverTumorsDMBA4_small.jpg      seminoma24.jpg \
	seminoma24_small.jpg \
	MicroHistoOther4.jpg            skinny4.jpg \
	MicroHistoOther4_small.jpg      skinny4_small.jpg \
	MicroWetGiemsa4.jpg             thyroidHisto4.jpg \
	MicroWetGiemsa4_small.jpg       thyroidHisto4_small.jpg \
	MicrosporHisto4.jpg             ultimobranchialTumors4.jpg \



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
