//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 11:23:15 AM PST 
//


package org.zfin.webservice.schema;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="genes" type="{http://localhost/webservice/definitions}Gene" maxOccurs="100" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "genes"
})
@XmlRootElement(name = "GeneSearchResponse")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-02-15T11:23:15-08:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class GeneSearchResponse {

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-02-15T11:23:15-08:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<Gene> genes;

    /**
     * Gets the value of the genes property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genes property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenes().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Gene }
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-02-15T11:23:15-08:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<Gene> getGenes() {
        if (genes == null) {
            genes = new ArrayList<Gene>();
        }
        return this.genes;
    }

}
