//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.15 at 11:23:15 AM PST 
//


package org.zfin.webservice.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.zfin.webservice.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GeneExpressionAnatomyWildTypeRequest_QNAME = new QName("http://localhost/webservice/definitions", "GeneExpressionAnatomyWildTypeRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.zfin.webservice.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeneSearchResponse }
     * 
     */
    public GeneSearchResponse createGeneSearchResponse() {
        return new GeneSearchResponse();
    }

    /**
     * Create an instance of {@link Gene }
     * 
     */
    public Gene createGene() {
        return new Gene();
    }

    /**
     * Create an instance of {@link GeneExpressionAnatomyWildTypeResponse }
     * 
     */
    public GeneExpressionAnatomyWildTypeResponse createGeneExpressionAnatomyWildTypeResponse() {
        return new GeneExpressionAnatomyWildTypeResponse();
    }

    /**
     * Create an instance of {@link Anatomy }
     * 
     */
    public Anatomy createAnatomy() {
        return new Anatomy();
    }

    /**
     * Create an instance of {@link GeneSearchRequest }
     * 
     */
    public GeneSearchRequest createGeneSearchRequest() {
        return new GeneSearchRequest();
    }

    /**
     * Create an instance of {@link GeneRetrieveRequest }
     * 
     */
    public GeneRetrieveRequest createGeneRetrieveRequest() {
        return new GeneRetrieveRequest();
    }

    /**
     * Create an instance of {@link GeneRetrieveResponse }
     * 
     */
    public GeneRetrieveResponse createGeneRetrieveResponse() {
        return new GeneRetrieveResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://localhost/webservice/definitions", name = "GeneExpressionAnatomyWildTypeRequest")
    public JAXBElement<String> createGeneExpressionAnatomyWildTypeRequest(String value) {
        return new JAXBElement<String>(_GeneExpressionAnatomyWildTypeRequest_QNAME, String.class, null, value);
    }

}
