# load the authorization token from external file
source authorization.txt

echo "Validating BGI file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_BGI_ZFIN=@ZFIN_1.0.1.4_basicGeneInformation.json"
echo ""

echo ""
echo "Validating Allele file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_ALLELE_ZFIN=@ZFIN_1.0.1.4_allele.json"
echo ""
echo ""
echo "Validating STR file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_SQTR_ZFIN=@ZFIN_1.0.1.4_STR.json"
echo ""
echo ""
echo "Validating Disease file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_DAF_ZFIN=@ZFIN_1.0.1.4_disease.daf.json"
echo ""
echo ""
echo "Validating Construct file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_CONSTRUCT_ZFIN=@ZFIN_1.0.1.4_Construct.json"
echo ""
echo ""
echo "Validating HTP Data Set file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_HTPDATASET_ZFIN=@ZFIN_1.0.1.4_HTP_Dataset.json"
echo ""
echo ""
echo "Validating HTP Data Sample file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_HTPDATASAMPLE_ZFIN=@ZFIN_1.0.1.4_HTP_DatasetSample.json"
echo ""
echo ""
echo "Validating Phenotype file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_PHENOTYPE_ZFIN=@ZFIN_1.0.1.4_phenotype.json"
echo ""
echo ""
echo "Validating AGM / FISH file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_AGM_ZFIN=@ZFIN_1.0.1.4_AGM.json"
echo ""
echo ""
echo "Validating Expression file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_EXPRESSION_ZFIN=@ZFIN_1.0.1.4_expression.json"
echo ""
echo ""
echo "Validating Variant file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_VARIATION_ZFIN=@ZFIN_1.0.1.4_variant.json"
echo ""
echo ""
echo "Validating GFF3 file..."
curl -H "Authorization: Bearer $AUTHORIZATION" -X POST "https://fms.alliancegenome.org/api/data/validate" -F "4.1.0_GFF_ZFIN=@zfin_genes.gff3"
echo ""
