#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Zebrafish Book Chapter 7 web pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/zfbook/chapt7

STATICS = 7-11.gif 7-20.gif 7-21.gif 7-22.gif 7-5.gif 8-3.gif 8-7.gif 7.2.html 7.3.html 7.4.html 7.5.html 7.52.html 7.55.html \
	7.6.html 7.7.html 7.8.html 7.9.html 7.10.html 7.11.html

GENERICS = 7.1.html



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
