-- updateZebrafishGeneNames.sql
-- input file: updated_zf_gene_names.unl and existing_zf_gene_names.unl, which are generated by updateZFgeneNames.pl
-- do updating of the zebrafish gene names based on input

begin work;

create table geneNameUpdate (
    gene_zdb_id   varchar(50) not null,
    symbol  varchar(150) not null,
    updated_name  varchar(255)  not null  
);

create index geneNameUpdate_gene_zdb_id_idx on geneNameUpdate(gene_zdb_id) in idxdbs3;
create index geneNameUpdate_symbol_idx on geneNameUpdate(symbol) in idxdbs3;
create index geneNameUpdate_name_idx on geneNameUpdate(updated_name) in idxdbs3;

--!echo 'Load from updated_zf_gene_names.unl'
load from updated_zf_gene_names.unl insert into geneNameUpdate;


create table geneNamesBeforeUpdating (
    e_gene_zdb_id   varchar(50) not null,
    e_symbol  varchar(150) not null,
    e_gene_name  varchar(255)  not null  
);

create index geneNamesBeforeUpdating_gene_zdb_id_idx on geneNamesBeforeUpdating(e_gene_zdb_id) in idxdbs3;
create index geneNamesBeforeUpdating_symbol_idx on geneNamesBeforeUpdating(e_symbol) in idxdbs3;
create index geneNamesBeforeUpdating_name_idx on geneNamesBeforeUpdating(e_gene_name) in idxdbs3;

--!echo 'Load from existing_zf_gene_names.unl'
load from existing_zf_gene_names.unl insert into geneNamesBeforeUpdating;

select * from geneNamesBeforeUpdating where e_gene_zdb_id = "ZDB-GENE-060824-3"; 


create temp table pre_marker_history
(
   tmp_history_id    varchar(50),
   tmp_gene_id       varchar(50),
   tmp_new_name      varchar(255),
   tmp_old_name      varchar(255)
)
with no log;

insert into pre_marker_history (tmp_history_id, tmp_gene_id, tmp_new_name, tmp_old_name)
select get_id('NOMEN'), gene_zdb_id, updated_name, e_gene_name
  from geneNameUpdate, geneNamesBeforeUpdating, marker
 where gene_zdb_id = mrkr_zdb_id
   and gene_zdb_id = e_gene_zdb_id
   and symbol = mrkr_abbrev
   and symbol = e_symbol
   and updated_name != mrkr_name
   and updated_name != ""
   and updated_name != e_gene_name
   and e_gene_name = mrkr_name;
   
   
--!echo 'update gene names'

 update marker set mrkr_name = (
 select tmp_new_name
   from pre_marker_history
  where mrkr_zdb_id = tmp_gene_id
    and tmp_new_name != ""
) where mrkr_type = "GENE"
    and exists (select "x" from pre_marker_history u1
                 where u1.tmp_gene_id = mrkr_zdb_id)
    and not exists (select "x" from pre_marker_history u2
                     where u2.tmp_new_name = mrkr_name);      
                     

--!echo 'update updates table'
insert into updates (rec_id,field_name,new_value,old_value,when,comments) 
select tmp_gene_id,"mrkr_name",tmp_new_name,tmp_old_name,current,"gene renamed by Ken and orthology script according to NCBI orthology data" 
  from pre_marker_history;

insert into zdb_active_data(zactvd_zdb_id)
select tmp_history_id
  from pre_marker_history;

--!echo 'update marker_history table'
insert into marker_history (mhist_zdb_id,mhist_mrkr_zdb_id,mhist_event,mhist_reason,mhist_date,mhist_mrkr_name_on_mhist_date,mhist_mrkr_abbrev_on_mhist_date,mhist_mrkr_prev_name,mhist_comments) 
select tmp_history_id,tmp_gene_id,"renamed","renamed to conform with zebrafish guidelines",current,current,current,tmp_old_name,"renamed by Ken and orthology script according to NCBI orthology data" 
  from pre_marker_history;
  
unload to 'geneNamesUpdatedReport'
select tmp_gene_id, tmp_old_name, tmp_new_name 
  from pre_marker_history;

drop table geneNameUpdate;
drop table geneNamesBeforeUpdating;

--rollback work;

commit work;



