-- updateZebrafishGeneNames.sql
-- input file: namesToUpdate.unl, which is generated by updateZFgeneNames.pl
-- do updating of the zebrafish gene names based on input
-- insert records into updates and marker_history tables as well

begin work;

create table geneNameUpdate (
    gene_zdb_id   varchar(50) not null,
    existing_name varchar(50) not null,
    updated_name  varchar(255)  not null  
);

create index geneNameUpdate_gene_zdb_id_idx on geneNameUpdate(gene_zdb_id) in idxdbs3;
create index geneNameUpdate_existing_name_idx on geneNameUpdate(existing_name) in idxdbs3;
create index geneNameUpdate_updated_name_idx on geneNameUpdate(updated_name) in idxdbs3;

--!echo 'Load from namesToUpdate.unl'
load from namesToUpdate.unl insert into geneNameUpdate;


alter table geneNameUpdate add nomen_zdb_id varchar(50);

update geneNameUpdate set nomen_zdb_id = get_id('NOMEN');
   
--!echo 'update gene names'

update marker set mrkr_name = (
 select updated_name
   from geneNameUpdate
  where mrkr_zdb_id = gene_zdb_id
) where mrkr_type = "GENE"
    and exists (select "x" from geneNameUpdate
                 where gene_zdb_id = mrkr_zdb_id);      
                     

--!echo 'insert updates table'
insert into updates (rec_id,field_name,new_value,old_value,when,comments) 
select gene_zdb_id,"mrkr_name",updated_name,existing_name,current,"gene renamed by Ken and the orthology script according to NCBI orthology data" 
  from geneNameUpdate;

insert into zdb_active_data(zactvd_zdb_id)
select nomen_zdb_id
  from geneNameUpdate;

--!echo 'update marker_history table'
insert into marker_history (mhist_zdb_id,mhist_mrkr_zdb_id,mhist_event,mhist_reason,mhist_date,mhist_mrkr_name_on_mhist_date,mhist_mrkr_abbrev_on_mhist_date,mhist_mrkr_prev_name,mhist_comments) 
select nomen_zdb_id,gene_zdb_id,"renamed","renamed to conform with zebrafish guidelines",current,current,current,existing_name,"renamed by Ken and orthology script according to NCBI orthology data" 
  from geneNameUpdate;
  
unload to 'geneNamesUpdatedReport'
select * 
  from geneNameUpdate;

drop table geneNameUpdate;

--rollback work;

commit work;



