
-- updateOrthologyNames.sql
-- input file: orthNamesUpdateList.unl, which is generated by NCBIorthology.pl
-- do updating of the orthologue.ortho_name based on input

begin work;

create table orthologyNameUpdate (
    gene_zdb_id    varchar(50) not null,
    species  varchar(30) not null,
    current_name      varchar(255),  
    updated_name  varchar(255)  not null  
);

create index orthoNameUpdate_gene_zdb_id_idx on orthologyNameUpdate(gene_zdb_id) in idxdbs3;
create index orthoNameUpdate_species_idx on orthologyNameUpdate(species) in idxdbs3;

--!echo 'Load from orthNamesUpdateList.unl'
load from orthNamesUpdateList.unl insert into orthologyNameUpdate;

--!echo 'update orthologue.ortho_name for those ortho_name is not null'
update orthologue set ortho_name = (
 select updated_name
   from orthologyNameUpdate
  where c_gene_id = gene_zdb_id
    and organism = species
    and ortho_name = current_name
) where ortho_name is not null
    and exists (select "x" from orthologyNameUpdate
                 where gene_zdb_id = c_gene_id
                   and species = organism 
                   and current_name is not null
                   and current_name = ortho_name);       
                   

--!echo 'update orthologue.ortho_name for those ortho_name is null'
update orthologue set ortho_name = (
 select updated_name
   from orthologyNameUpdate
  where c_gene_id = gene_zdb_id
    and organism = species
) where ortho_name is null
    and exists (select "x" from orthologyNameUpdate
                 where gene_zdb_id = c_gene_id
                   and species = organism 
                   and current_name is null);                     
    
--!echo 'update updates table'
insert into updates (rec_id,field_name,new_value,old_value,when) 
select gene_zdb_id,"ortho_name",updated_name,current_name,current 
  from orthologyNameUpdate;

drop table orthologynameupdate;

--rollback work;

commit work;



