#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, ZFIN BIG Animated Images directory
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# 


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

# None of the images in this directory are in use as of 2000/10/05.
# However, copy them to the target dir anyway, just so the folks who work
# on the static pages can see them if they want to use them in the future.

# See ../Makefile for further discussion of this directory.

TARGETDIR = $(TARGETROOT)/home/images/BIG_ANIMATED

STATICS := $(shell echo *.gif)


# --------------------------  Rules  ------------------------------------

# Use default rules

include $(TOP)/make.default.rules

