--liquibase formatted sql
--changeset sierra:ZFIN-6074

create table feature_community_contribution (fcc_pk_id serial8 not null primary key,
                                             fcc_feature_zdb_id text not null,
                                             fcc_functional_consequence text,
                                             fcc_adult_viable boolean not null default 'f',
                                             fcc_maternal_zygosity_examined boolean not null default 'f',
                                             fcc_currently_available boolean not null default 'f', 
                                             fcc_other_line_information text,
                                             fcc_date_added date not null default now(),
                                             fcc_added_by text not null);

create index fcc_feature_zdb_id_index
 on feature_community_contribution (fcc_feature_zdb_id);

alter table feature_community_contribution
 add constraint fcc_feature_zdb_id_foreign_key
 foreign key (fcc_feature_zdb_id)
 references feature on delete cascade; 

CREATE TABLE post_AUD
(
    id      BIGINT NOT NULL,
    REV     INTEGER NOT NULL,
    REVTYPE INTEGER,
    title   text,
    PRIMARY KEY ( id, REV )
);
 
CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT
             AS IDENTITY ( START WITH 1 ),
    revtstmp BIGINT,
    PRIMARY KEY ( rev )
)  ;
 
ALTER TABLE post_aud
ADD CONSTRAINT
    fkllaf9w93qaiooguo8mfvwtwbg
FOREIGN KEY ( REV ) REFERENCES revinfo ;
