#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Tech Report describing ZFIN database
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/dbase/PAPERS/WWW6

GENERICS = WWW6-97.html

STATICS = Fig1.gif Fig2.gif Fig3.gif Fig4a.gif Fig4b.gif Fig5a.gif Fig5b.gif \
	Fig6a.gif Fig6b.gif Fig7a.gif Fig7b.gif Fig7c.gif Fig8a.gif Fig8b.gif \
	Fig9.gif


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
