#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Company related pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/company_files

STATICS = companyselect.apg  companyupdate.apg companyview.apg do-companyupdate.apg \
	new_company.apg process-company.apg companyprintable.apg update-company.apg \
	setup-new-company.apg 

# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules

