#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, ZFIN LOCAL Images directory
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# Images in this directory are specific to ZFIN.  In other words they are 
# things like fish and not things like arrows or dots.
# 


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

# See ../Makefile for a discussion of this directory.

TARGETDIR = $(TARGETROOT)/home/images/LOCAL

STATICS := $(shell echo *.gif *.jpeg)

# --------------------------  Rules  ------------------------------------

# Use default rules

include $(TOP)/make.default.rules

