#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Mutant/Fish related pages.
#
# $Source$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/fish_files

SUBDIRS = UPDATING

GENERICS = fishselect.apg fishview.apg new-fish.apg \
	process-fish-aux.apg process-fish.apg setup-new-fish.apg \
	update-fish.apg wtlist.apg genotypeview.apg \
	phenotype_miniview.apg phenotype_note.apg \
	alleleDesigNums.apg genotype_name_match.apg genotype_mo_match.apg \
	wildtypePhenoAnat.apg

# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules

