package org.zfin.gbrowse;

import java.io.Serializable;

/**
 * This class is a direct mapping of the name table in the Bio::Seqfeature::Store schema
 * <p/>
 * The real name of a feature will have displayName == true, aliases with have false
 */
public class GBrowseName implements Serializable {
    private Integer featureId;
    private GBrowseFeature feature;
    private String name;
    private Boolean displayName;

    public Integer getFeatureId() {
        return featureId;
    }

    public void setFeatureId(Integer featureId) {
        this.featureId = featureId;
    }

    public GBrowseFeature getFeature() {
        return feature;
    }

    public void setFeature(GBrowseFeature feature) {
        this.feature = feature;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getDisplayName() {
        return displayName;
    }

    public void setDisplayName(Boolean displayName) {
        this.displayName = displayName;
    }

    //generated by intellij

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GBrowseName)) return false;

        GBrowseName that = (GBrowseName) o;

        if (!displayName.equals(that.displayName)) return false;
        if (!feature.equals(that.feature)) return false;
        if (!featureId.equals(that.featureId)) return false;
        if (!name.equals(that.name)) return false;

        return true;
    }

    //generated by intellij    

    @Override
    public int hashCode() {
        int result = featureId.hashCode();
        result = 31 * result + feature.hashCode();
        result = 31 * result + name.hashCode();
        result = 31 * result + displayName.hashCode();
        return result;
    }
}