if ("`whoami`" == "root") then
    set Prompt="# "
else
    set Prompt="% "
endif

if ($?tcsh) then
 set prompt = "%m [%c3]$Prompt"
else
  alias setprompt set prompt = '"`hostname` [$cwd]${Prompt}"'
  alias cd chdir \!\#\* \; setprompt
  setprompt
endif

umask 002
sudo /bin/chown gradle /run/host-services/ssh-auth.sock
sudo /bin/chown gradle /var/run/docker.sock
/opt/zfin/source_roots/zfin.org/docker/compile/generate_base.sh
cd /opt/zfin/source_roots/zfin.org
source commons/env/docker.env
alias restartTomcatDebug="cd docker && docker compose down tomcatdebug && docker compose up -d tomcatdebug && cd -"
alias restartTomcat="cd docker && docker compose down tomcat && docker compose up -d tomcat && cd -"