create index afg_geno_name_index on affected_gene_group(afg_geno_name);
create index afg_geno_zdb_index on affected_gene_group(afg_geno_zdb_id);
create index afg_genox_zdb_index on affected_gene_group(afg_genox_zdb_id);
create index affected_gene_group_member_group_id_index on affected_gene_group_member(afgm_group_id);
create index affected_gene_group_member_id_index on affected_gene_group_member(afgm_member_id);
create unique index alias_group_primary_key_index on alias_group(aliasgrp_name);
create index allanatcon_contained_zdb_id_index on all_anatomy_contains(allanatcon_contained_zdb_id);
create index allanatcon_container_zdb_id_index on all_anatomy_contains(allanatcon_container_zdb_id);
create index allmapnm_name_lower_index on all_map_names(allmapnm_name_lower);
create index all_term_contains_new_primary_key_index on all_term_contains_new(alltermcon_contained_zdb_id);
create index all_term_contains_new_primary_key_index on all_term_contains_new(alltermcon_container_zdb_id);
create index anatdisp_item_name_index on anatomy_display(anatdisp_item_name);
create unique index anatomy_stats_primary_key_index on anatomy_stats(anatstat_object_type);
create index anatstat_term_zdb_id_index on anatomy_stats(anatstat_term_zdb_id);
create unique index anatomy_stats_primary_key_index on anatomy_stats(anatstat_term_zdb_id);
create index api_curator_zdb_id_fk_index on apato_infrastructure(api_curator_zdb_id);
create index api_pub_zdb_id_fk_index on apato_infrastructure(api_pub_zdb_id);
create unique index bl_plate_tracking_unique_blpt_plate_index on bl_plate_tracking(blpt_plate);
create index cnd_mrkr_type_foreign_key_index on candidate(cnd_mrkr_type);
create unique index candidate_cnd_suggested_name_idx on candidate(cnd_suggested_name);
create index clone_probelib_zdb_id_index on clone(clone_probelib_zdb_id);
create index construct_component_component_index on construct_component(cc_component);
create index cc_component_type_index on construct_component(cc_component_type);
create index ccs_cons_id_foreign_key_index on construct_component_search(ccs_cons_id);
create index ccs_gene_zdb_id_index on construct_component_search(ccs_gene_zdb_id);
create unique index ccs_primary_key_index on construct_component_search(ccs_pk_id);
create index ccsb_cons_id_foreign_key_index on construct_component_search_backup(ccs_cons_id);
create index ccsb_gene_zdb_id_index on construct_component_search_backup(ccs_gene_zdb_id);
create unique index ccsb_primary_key_index on construct_component_search_backup(ccs_pk_id);
create index ccst_cons_id_foreign_key_index on construct_component_search_temp(ccs_cons_id);
create index ccst_gene_zdb_id_index on construct_component_search_temp(ccs_gene_zdb_id);
create unique index ccst_primary_key_index on construct_component_search_temp(ccs_pk_id);
create index cgfrv_allele_gene_zdb_id_index on construct_gene_feature_result_view(cgfrv_allele_gene_zdb_id);
create index cgfrv_cs_id_foreign_key_index on construct_gene_feature_result_view(cgfrv_cs_id);
create unique index cgfrv_primary_key_index on construct_gene_feature_result_view(cgfrv_pk_id);
create index cgfrvb_allele_gene_zdb_id_index on construct_gene_feature_result_view_backup(cgfrv_allele_gene_zdb_id);
create index cgfrvb_cs_id_foreign_key_index on construct_gene_feature_result_view_backup(cgfrv_cs_id);
create unique index cgfrvb_primary_key_index on construct_gene_feature_result_view_backup(cgfrv_pk_id);
create index cgfrvt_allele_gene_zdb_id_index on construct_gene_feature_result_view_temp(cgfrv_allele_gene_zdb_id);
create index cgfrvt_cs_id_foreign_key_index on construct_gene_feature_result_view_temp(cgfrv_cs_id);
create unique index cgfrvt_primary_key_index on construct_gene_feature_result_view_temp(cgfrv_pk_id);
create index cg_geno_name_index on construct_group(cg_geno_name);
create index cg_geno_zdb_index on construct_group(cg_geno_zdb_id);
create index cg_genox_zdb_index on construct_group(cg_genox_zdb_id);
create unique index cons_alternate_key_index on construct_search(cons_construct_zdb_id);
create unique index cons_pk_id_primary_key_index on construct_search(cons_pk_id);
create unique index consp_alternate_key_index on construct_search_backup(cons_construct_zdb_id);
create unique index consp_pk_id_primary_key_index on construct_search_backup(cons_pk_id);
create unique index const_alternate_key_index on construct_search_temp(cons_construct_zdb_id);
create unique index const_pk_id_primary_key_index on construct_search_temp(cons_pk_id);
create unique index curator_session_primary_key_index on curator_session(cs_data_zdb_id);
create unique index curator_session_primary_key_index on curator_session(cs_field_name);
create unique index curator_session_primary_key_index on curator_session(cs_person_zdb_id);
create index dalias_alias_lower_index on data_alias(dalias_alias_lower);
create index dalias_alias_lower_index on data_alias(dalias_data_zdb_id);
create index db_link_acc_num_index on db_link(dblink_acc_num);
create unique index ensm_alternate_key on ensdar_mapping(ensm_ensdarg_id);
create unique index ensm_alternate_key on ensdar_mapping(ensm_ensdart_id);
create unique index entrez_gene_alternate_key_index on entrez_gene(eg_acc_num);
create unique index entrez_gene_alternate_key_index on entrez_gene(eg_name);
create unique index entrez_gene_alternate_key_index on entrez_gene(eg_symbol);
create unique index ep_alternate_key_index on entrez_to_protein(ep_entrez_acc_num);
create unique index ep_alternate_key_index on entrez_to_protein(ep_organism_common_name);
create unique index ep_primary_key_index on entrez_to_protein(ep_pk_id);
create unique index ep_alternate_key_index on entrez_to_protein(ep_protein_acc_num);
create index ep_protein_acc_num_index on entrez_to_protein(ep_protein_acc_num);
create index ex_xref_index on entrez_to_xref(ex_xref);
create index eg_genox_zdb_index on environment_group(eg_genox_zdb_id);
create index eg_group_name_index on environment_group(eg_group_name);
create unique index experiment_alternate_key_index on experiment(exp_name);
create index experiment_name_index on experiment(exp_name);
create unique index experiment_alternate_key_index on experiment(exp_source_zdb_id);
create index experiment_condition_cdt_fk_index on experiment_condition(expcond_cdt_zdb_id);
create index experiment_condition_zeco_term_zdb_id_foreign_key_index on experiment_condition(expcond_zeco_term_zdb_id);
create index xpatex_atb_zdb_id_index on expression_experiment(xpatex_atb_zdb_id);
create index xpatex_gene_zdb_id_foreign_key_index on expression_experiment(xpatex_gene_zdb_id);
create index xpatex_featexp_zdb_id_foreign_key_index on expression_experiment(xpatex_genox_zdb_id);
create index expression_experiment_marker_foreign_key_index on expression_experiment(xpatex_probe_feature_zdb_id);
create index expression_experiment_source_foreign_key_index on expression_experiment(xpatex_source_zdb_id);
create unique index expression_experiment_primary_key_index on expression_experiment(xpatex_zdb_id);
create index efs_end_stg_fk_index on expression_figure_stage(efs_end_stg_zdb_id);
create index efs_fig_fk_index on expression_figure_stage(efs_fig_zdb_id);
create index efs_start_stg_fk_index on expression_figure_stage(efs_start_stg_zdb_id);
create index expression_pattern_figure_fig_foreign_key on expression_pattern_figure(xpatfig_fig_zdb_id);
create index expression_pattern_figure_xpatres_foreign_key_index on expression_pattern_figure(xpatfig_xpatres_zdb_id);
create unique index expression_phenotype_alternate_key on expression_phenotype_term(ept_quality_term_zdb_id);
create unique index expression_phenotype_alternate_key on expression_phenotype_term(ept_xpatres_id);
create index expression_result_end_stg_foreign_key_index on expression_result(xpatres_end_stg_zdb_id);
create index expression_result_start_stg_foreign_key_index on expression_result(xpatres_start_stg_zdb_id);
create index expression_result_subterm_foreign_key_index on expression_result(xpatres_subterm_zdb_id);
create index expression_result_superterm_foreign_key_index on expression_result(xpatres_superterm_zdb_id);
create index expression_result_xpatex_foreign_key_index on expression_result(xpatres_xpatex_zdb_id);
create unique index expression_result_primary_key_index on expression_result(xpatres_zdb_id);
create unique index xpatres_alternate_key_index on expression_result2(xpatres_efs_id);
create unique index xpatres_alternate_key_index on expression_result2(xpatres_expression_found);
create unique index xpatres_alternate_key_index on expression_result2(xpatres_subterm_zdb_id);
create unique index xpatres_alternate_key_index on expression_result2(xpatres_superterm_zdb_id);
create index etfs_term_zdb_id_index on expression_term_fast_search(etfs_term_zdb_id);
create unique index feature_abbrev_alternate_key on feature(feature_abbrev);
create index feature_assay_mutagee_foreign_key_index on feature_assay(featassay_mutagee);
create index feature_assay_mutagen_foreign_key_index on feature_assay(featassay_mutagen);
create index fdmd_gene_localization_term_zdb_id_fk_index on feature_dna_mutation_detail(fdmd_gene_localization_term_zdb_id);
create index fg_geno_name_index on feature_group(fg_geno_name);
create index fg_geno_zdb_index on feature_group(fg_geno_zdb_id);
create index fg_genox_zdb_index on feature_group(fg_genox_zdb_id);
create index feature_group_member_genotype_id_index on feature_group_member(fgm_genotype_id);
create index feature_group_member_group_id_index on feature_group_member(fgm_group_id);
create index feature_group_member_id_index on feature_group_member(fgm_member_id);
create index fpmd_mutant_or_stop_protein_term_zdb_id_foreign_key_index on feature_protein_mutation_detail(fpmd_mutant_or_stop_protein_term_zdb_id);
create index fpmd_wt_protein_term_zdb_id_foreign_key_index on feature_protein_mutation_detail(fpmd_wt_protein_term_zdb_id);
create index fstat_feat_fk_index on feature_stats_old(fstat_feat_zdb_id);
create index fstat_fig_fk_index on feature_stats_old(fstat_fig_zdb_id);
create index fstat_gene_fk_index on feature_stats_old(fstat_gene_zdb_id);
create index fstat_img_fk_index on feature_stats_old(fstat_img_zdb_id);
create unique index fstat_pk_id_index on feature_stats_old(fstat_pk_id);
create index fstat_pub_fk_index on feature_stats_old(fstat_pub_zdb_id);
create index fstat_subterm_fk_index on feature_stats_old(fstat_subterm_zdb_id);
create index fstat_superterm_fk_index on feature_stats_old(fstat_superterm_zdb_id);
create index feature_type_ordering_name on feature_type_ordering(fto_name);
create index fig_label_index on figure(fig_label);
create index figure_term_construct_search_cs_id_fk_index on figure_term_construct_search(ftcs_cs_id);
create unique index figure_term_construct_search_pk_index on figure_term_construct_search(ftcs_pk_id);
create index figure_term_construct_searchb_cs_id_fk_index on figure_term_construct_search_backup(ftcs_cs_id);
create unique index figure_term_construct_searchb_pk_index on figure_term_construct_search_backup(ftcs_pk_id);
create index figure_term_construct_searcht_cs_id_fk_index on figure_term_construct_search_temp(ftcs_cs_id);
create index figure_term_construct_searcht_fig_id_index on figure_term_construct_search_temp(ftcs_fig_zdb_id);
create index ftcst_genox_zdb_id_index on figure_term_construct_search_temp(ftcs_genox_zdb_id);
create unique index figure_term_construct_searcht_pk_index on figure_term_construct_search_temp(ftcs_pk_id);
create unique index fish_components_alternate_key_index on fish_components(fc_affector_zdb_id);
create index fc_affector_zdb_id_index on fish_components(fc_affector_zdb_id);
create index fc_construct_zdb_id_index on fish_components(fc_construct_zdb_id);
create unique index fish_components_alternate_key_index on fish_components(fc_construct_zdb_id);
create unique index fish_components_alternate_key_index on fish_components(fc_fish_zdb_id);
create index fc_fish_zdb_id_index on fish_components(fc_fish_zdb_id);
create unique index fish_components_alternate_key_index on fish_components(fc_gene_zdb_id);
create index fc_gene_zdb_id_index on fish_components(fc_gene_zdb_id);
create index fc_genotype_zdb_id_index on fish_components(fc_genotype_zdb_id);
create unique index fc_pk_id_index on fish_components(fc_pk_id);
create index genotype_experiment_exp_zdb_id_foreign_key_index on fish_experiment(genox_exp_zdb_id);
create unique index fm_fish_pub_zdb_id_index on fishmisfortune(fm_fish_zdb_id);
create index fm_fish_zdb_id_index on fishmisfortune(fm_fish_zdb_id);
create unique index fm_fish_pub_zdb_id_index on fishmisfortune(fm_genox_zdb_id);
create index fm_misfortune_count_index on fishmisfortune(fm_misfortune_count);
create index fm_misfortune_count_minus_one_index on fishmisfortune(fm_misfortune_count_minus_one);
create index fm_pub_zdb_id_index on fishmisfortune(fm_pub_zdb_id);
create unique index fm_fish_pub_zdb_id_index on fishmisfortune(fm_pub_zdb_id);
create unique index foreign_db_alternate_key_index on foreign_db(fdb_db_name);
create index fdbcg_group_name_index on foreign_db_contains_display_group(fdbcdg_name);
create index fdbcdgm_fdbcont_zdb_id_foreign_key_index on foreign_db_contains_display_group_member(fdbcdgm_fdbcont_zdb_id);
create unique index foreign_db_data_type_alternate_key_index on foreign_db_data_type(fdbdt_data_type);
create unique index foreign_db_data_type_alternate_key_index on foreign_db_data_type(fdbdt_super_type);
create index fa_geno_handle_index on functional_annotation(fa_geno_handle);
create index fa_geno_name_index on functional_annotation(fa_geno_name);
create index fa_geno_index on functional_annotation(fa_geno_zdb_id);
create index fa_genox_zdb_id_index on functional_annotation(fa_genox_zdb_id);
create index fa_str_group_index on functional_annotation(fa_str_group);
create unique index gsc_alternate_key_index on genotype_component_significance(gcs_fmrel_type);
create unique index gsc_alternate_key_index on genotype_component_significance(gcs_ftr_type);
create unique index gsc_alternate_key_index on genotype_component_significance(gcs_mrkr_type);
create index gcs_mrkr_type_index on genotype_component_significance(gcs_mrkr_type);
create unique index gsc_alternate_key_index on genotype_component_significance(gcs_significance);
create index genotype_figure_fast_search_pg_id_foreign_key_index on genotype_figure_fast_search(gffs_pg_id);
create index genotype_figure_fast_search_psg_id_foreign_key_index on genotype_figure_fast_search(gffs_psg_id);
create index genotype_handle_index on genotype_group(gg_geno_handle);
create index genotype_group_member_group_id_index on genotype_group_member(ggm_group_id);
create index genotype_group_member_id_index on genotype_group_member(ggm_member_id);
create index genoxfas_fas_id on genox_fish_annotation_search(genoxfas_fas_id);
create index genoxfas_genox_zdb_id_index on genox_fish_annotation_search(genoxfas_genox_zdb_id);
create index genoxfasb_fas_id on genox_fish_annotation_search_bkup(genoxfas_fas_id);
create index genoxfasb_genox_zdb_id_index on genox_fish_annotation_search_bkup(genoxfas_genox_zdb_id);
create index genoxfast_fas_id on genox_fish_annotation_search_temp(genoxfas_fas_id);
create index genoxfast_genox_zdb_id_index on genox_fish_annotation_search_temp(genoxfas_genox_zdb_id);
create index gg_group_name_index on genox_group(gg_group_name);
create unique index gg_group_primary_key_index on genox_group(gg_group_pk_id);
create unique index ggm_group_primary_key_index on genox_group_member(ggm_pk_id);
create index ngff3_gff_feature_idx on gff3(gff_feature);
create index ngff3_gff_name_gff_idx on gff3(gff_name);
create index ngff3_gff_parent_idx on gff3(gff_parent);
create index ngff3_gff_source_idx on gff3(gff_source);
create index image_img_image_index on image(img_image);
create index ifat_fdbcont_zdb_id_foreign_key_index on int_fdbcont_analysis_tool(ifat_fdbcont_zdb_id);
create index lnkgs_source_zdb_id_index on linkage(lnkg_source_zdb_id);
create index lnkgmem_member_zdb_id_index on linkage_member(lnkgmem_member_zdb_id);
create unique index lnkgm_alternate_key_index on linkage_membership(lnkgm_linkage_zdb_id);
create index lnkgm_linkage_zdb_id_fk_index on linkage_membership(lnkgm_linkage_zdb_id);
create unique index lnkgm_alternate_key_index on linkage_membership(lnkgm_member_1_zdb_id);
create unique index lnkgm_alternate_key_index on linkage_membership(lnkgm_member_2_zdb_id);
create unique index lms_ak_index on linkage_membership_search(lms_lnkgmem_id);
create index lms_lnkgmem_id_index on linkage_membership_search(lms_lnkgmem_id);
create unique index lms_ak_index on linkage_membership_search(lms_member_1_zdb_id);
create unique index lms_ak_index on linkage_membership_search(lms_member_2_zdb_id);
create unique index lms_ak_index on linkage_membership_search(lms_pk_id);
create unique index lms_pk_id_index on linkage_membership_search(lms_pk_id);
create index lmsb_lnkg_zdb_id_index on linkage_membership_search_bkup(lms_lnkg_zdb_id);
create index lmsb_lnkgmem_id_index on linkage_membership_search_bkup(lms_lnkgmem_id);
create unique index lmsb_ak_index on linkage_membership_search_bkup(lms_lnkgmem_id);
create unique index lmsb_ak_index on linkage_membership_search_bkup(lms_member_1_zdb_id);
create unique index lmsb_ak_index on linkage_membership_search_bkup(lms_member_2_zdb_id);
create unique index lmsb_pk_id_index on linkage_membership_search_bkup(lms_pk_id);
create unique index lmsb_ak_index on linkage_membership_search_bkup(lms_pk_id);
create index lmst_lnkg_zdb_id_index on linkage_membership_search_temp(lms_lnkg_zdb_id);
create unique index lmst_ak_index on linkage_membership_search_temp(lms_lnkgmem_id);
create index lmst_lnkgmem_id_index on linkage_membership_search_temp(lms_lnkgmem_id);
create unique index lmst_ak_index on linkage_membership_search_temp(lms_member_1_zdb_id);
create unique index lmst_ak_index on linkage_membership_search_temp(lms_member_2_zdb_id);
create unique index lmst_ak_index on linkage_membership_search_temp(lms_pk_id);
create unique index lmst_pk_id_index on linkage_membership_search_temp(lms_pk_id);
create index mapped_marker_marker_type_index on mapped_marker(marker_type);
create unique index mrkr_abbrev_index on marker(mrkr_abbrev);
create unique index mrkrgoevcb_alternate_key_index on marker_go_term_evidence_annotation_created_by_source(mrkrgoevcb_name);
create unique index obsolete_term_replacement_repernate_key_index on obsolete_term_replacement(obstermrep_term_replacement_zdb_id);
create unique index obsolete_term_replacement_repernate_key_index on obsolete_term_replacement(obstermrep_term_zdb_id);
create unique index ooa_dblink_acc_num_index on one_to_one_accession(ooa_dblink_acc_num);
create unique index ontology_name_unique on ontology(ont_ontology_name);
create index panelcnt_mrkr_type_index on panel_count(panelcnt_mrkr_type);
create index paneled_markers_mtype_index_a on paneled_markers(mtype);
create index paneled_markers_target_abbrev_etc_index_a on paneled_markers(mtype);
create index paneled_markers_target_abbrev_etc_index_a on paneled_markers(or_lg);
create index paneled_markers_target_abbrev_etc_index_a on paneled_markers(target_abbrev);
create index paneled_markers_target_abbrev_etc_index_a on paneled_markers(zdb_id);
create index ptfs_end_stg_index on pheno_term(pt_end_stg_zdb_id);
create index ptfs_fig_index on pheno_term(pt_fig_zdb_id);
create index ptfs_geno_index on pheno_term(pt_geno_zdb_id);
create index ptfs_genox_index on pheno_term(pt_genox_zdb_id);
create index ptfs_entity_index on pheno_term(pt_pheno_entity);
create index ptfs_pub_index on pheno_term(pt_pub_zdb_id);
create index ptfs_start_stg_index on pheno_term(pt_start_stg_zdb_id);
create index ptfs_tag_index on pheno_term(pt_tag);
create index pt_end_stg_index on pheno_term_old(pt_end_stg_zdb_id);
create index pt_fig_index on pheno_term_old(pt_fig_zdb_id);
create index pt_geno_index on pheno_term_old(pt_geno_zdb_id);
create index pt_genox_index on pheno_term_old(pt_genox_zdb_id);
create index pt_entity_index on pheno_term_old(pt_pheno_entity);
create index pt_pub_index on pheno_term_old(pt_pub_zdb_id);
create index pt_start_stg_index on pheno_term_old(pt_start_stg_zdb_id);
create index pt_tag_index on pheno_term_old(pt_tag);
create index pfigg_geno_handle_index on phenotype_figure_group(pfigg_geno_handle);
create index pfigg_geno_name_index on phenotype_figure_group(pfigg_geno_name);
create index pfigg_genox_zdb_index on phenotype_figure_group(pfigg_genox_zdb_id);
create index pfigg_group_name_index on phenotype_figure_group(pfigg_group_name);
create index pfig_group_id_index on phenotype_figure_group_member(pfiggm_group_id);
create index pfig_group_member_id_index on phenotype_figure_group_member(pfiggm_member_id);
create index pgcm_pg_id_index on phenotype_generated_curated_mapping(pgcm_pg_id);
create index pgcm_source_id_index on phenotype_generated_curated_mapping(pgcm_source_id);
create index phenotype_observation_generated_e1a_zdb_index on phenotype_observation_generated(psg_e1a_zdb_id);
create index phenotype_observation_generated_e1b_zdb_index on phenotype_observation_generated(psg_e1b_zdb_id);
create index phenotype_observation_generated_e2a_zdb_index on phenotype_observation_generated(psg_e2a_zdb_id);
create index phenotype_observation_generated_e2b_zdb_index on phenotype_observation_generated(psg_e2b_zdb_id);
create unique index phenotype_observation_generated_pk_id_index on phenotype_observation_generated(psg_id);
create index phenotype_observation_generated_mrkr_zdb_index on phenotype_observation_generated(psg_mrkr_zdb_id);
create index phenotype_observation_generated_psg_pg_id_index on phenotype_observation_generated(psg_pg_id);
create index phenotype_observation_generated_quality_zdb_index on phenotype_observation_generated(psg_quality_zdb_id);
create index phenotype_source_generated_fig_index on phenotype_source_generated(pg_fig_zdb_id);
create index phenotype_source_generated_genox_index on phenotype_source_generated(pg_genox_zdb_id);
create unique index phenotype_source_generated_pk_index on phenotype_source_generated(pg_id);
create index pubcse_recipient_group_id_foreign_key_index on pub_correspondence_sent_email(pubcse_recipient_group);
create unique index pub_db_xref_alternate_key_index on pub_db_xref(pdx_accession_number);
create unique index pub_db_xref_alternate_key_index on pub_db_xref(pdx_fdbcont_zdb_id);
create unique index pub_db_xref_alternate_key_index on pub_db_xref(pdx_pub_zdb_id);
create index recattrib_source_zdb_id_index on record_attribution(recattrib_source_zdb_id);
create index sfclb_chromosome_index on sequence_feature_chromosome_location_bkup(sfcl_chromosome);
create unique index sfclb_pk_index on sequence_feature_chromosome_location_bkup(sfcl_chromosome);
create unique index sfclb_pk_index on sequence_feature_chromosome_location_bkup(sfcl_data_zdb_id);
create index sfclb_data_index on sequence_feature_chromosome_location_bkup(sfcl_data_zdb_id);
create unique index sfclb_pk_index on sequence_feature_chromosome_location_bkup(sfcl_end);
create unique index sfclb_pk_index on sequence_feature_chromosome_location_bkup(sfcl_location_source);
create unique index sfclb_pk_index on sequence_feature_chromosome_location_bkup(sfcl_location_subsource);
create unique index sfclb_pk_index on sequence_feature_chromosome_location_bkup(sfcl_start);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_acc_num);
create index sfclg_chromosome_index on sequence_feature_chromosome_location_generated(sfclg_chromosome);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_chromosome);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_data_zdb_id);
create index sfclg_mrkr_index on sequence_feature_chromosome_location_generated(sfclg_data_zdb_id);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_end);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_location_source);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_location_subsource);
create unique index sfclg_pk_index on sequence_feature_chromosome_location_generated(sfclg_start);
create unique index sfclgb_pk_index on sequence_feature_chromosome_location_generated_bkup(sfclg_chromosome);
create index sfclgb_chromosome_index on sequence_feature_chromosome_location_generated_bkup(sfclg_chromosome);
create unique index sfclgb_pk_index on sequence_feature_chromosome_location_generated_bkup(sfclg_data_zdb_id);
create index sfclgb_data_index on sequence_feature_chromosome_location_generated_bkup(sfclg_data_zdb_id);
create unique index sfclgb_pk_index on sequence_feature_chromosome_location_generated_bkup(sfclg_end);
create unique index sfclgb_pk_index on sequence_feature_chromosome_location_generated_bkup(sfclg_location_source);
create unique index sfclgb_pk_index on sequence_feature_chromosome_location_generated_bkup(sfclg_location_subsource);
create unique index sfclgb_pk_index on sequence_feature_chromosome_location_generated_bkup(sfclg_start);
create unique index sfclgt_pk_index on sequence_feature_chromosome_location_generated_temp(sfclg_chromosome);
create index sfclgt_chromosome_index on sequence_feature_chromosome_location_generated_temp(sfclg_chromosome);
create index sfclgt_data_index on sequence_feature_chromosome_location_generated_temp(sfclg_data_zdb_id);
create unique index sfclgt_pk_index on sequence_feature_chromosome_location_generated_temp(sfclg_data_zdb_id);
create unique index sfclgt_pk_index on sequence_feature_chromosome_location_generated_temp(sfclg_end);
create unique index sfclgt_pk_index on sequence_feature_chromosome_location_generated_temp(sfclg_location_source);
create unique index sfclgt_pk_index on sequence_feature_chromosome_location_generated_temp(sfclg_location_subsource);
create unique index sfclgt_pk_index on sequence_feature_chromosome_location_generated_temp(sfclg_start);
create index chmst_chromosome_index on sequence_feature_chromosome_location_temp(sfcl_chromosome);
create unique index sfclt_pk_index on sequence_feature_chromosome_location_temp(sfcl_chromosome);
create index sfclt_data_index on sequence_feature_chromosome_location_temp(sfcl_data_zdb_id);
create unique index sfclt_pk_index on sequence_feature_chromosome_location_temp(sfcl_data_zdb_id);
create unique index sfclt_pk_index on sequence_feature_chromosome_location_temp(sfcl_end);
create unique index sfclt_pk_index on sequence_feature_chromosome_location_temp(sfcl_location_source);
create unique index sfclt_pk_index on sequence_feature_chromosome_location_temp(sfcl_location_subsource);
create unique index sfclt_pk_index on sequence_feature_chromosome_location_temp(sfcl_start);
create unique index source_alias_alternate_key_index on source_alias(salias_alias);
create unique index source_alias_alternate_key_index on source_alias(salias_source_zdb_id);
create unique index stg_obo_id_index on stage(stg_obo_id);
create index strg_genox_zdb_index on str_group(strg_genox_zdb_id);
create index strg_group_name_index on str_group(strg_group_name);
create unique index sag_aggid on sysaggregates(aggid);
create unique index sag_name_owner on sysaggregates(name);
create unique index sag_name_owner on sysaggregates(owner);
create unique index amid on sysams(am_id);
create unique index amname on sysams(am_name);
create unique index amname on sysams(am_owner);
create unique index sat_xtd_id_seqno on sysattrtypes(extended_id);
create index sat_xtd_id on sysattrtypes(extended_id);
create unique index sat_xtd_id_seqno on sysattrtypes(seqno);
create index sat_xtd_type_id on sysattrtypes(xtd_type_id);
create unique index satl_dbsname on sysautolocate(dbsname);
create index sysbldobjindex on sysbldobjects(create_order);
create unique index blobtabcol on sysblobs(colno);
create unique index blobtabcol on sysblobs(tabid);
create unique index sct_fromtotype on syscasts(argument_type);
create unique index sct_fromtotype on syscasts(argument_xid);
create index sct_totype on syscasts(result_type);
create unique index sct_fromtotype on syscasts(result_type);
create unique index sct_fromtotype on syscasts(result_xid);
create index sct_totype on syscasts(result_xid);
create unique index checkid on syschecks(constrid);
create unique index checkid on syschecks(seqno);
create unique index checkid on syschecks(type);
create unique index colattribs on syscolattribs(colno);
create unique index colattribs on syscolattribs(sbspace);
create unique index colattribs on syscolattribs(tabid);
create unique index colgtor on syscolauth(colno);
create unique index colgtor on syscolauth(grantee);
create index colgtee on syscolauth(grantee);
create unique index colgtor on syscolauth(grantor);
create unique index colgtor on syscolauth(tabid);
create index colgtee on syscolauth(tabid);
create unique index cdpconstrid on syscoldepend(colno);
create index tabcol on syscoldepend(colno);
create unique index cdpconstrid on syscoldepend(constrid);
create unique index cdpconstrid on syscoldepend(tabid);
create index tabcol on syscoldepend(tabid);
create unique index column on syscolumns(colno);
create index col_xtd_id on syscolumns(extended_id);
create unique index column on syscolumns(tabid);
create unique index constrid on sysconstraints(constrid);
create unique index constrname on sysconstraints(constrname);
create unique index constrname on sysconstraints(owner);
create index constrtabid on sysconstraints(tabid);
create unique index deftabid on sysdefaults(class);
create unique index deftabid on sysdefaults(colno);
create unique index deftabid on sysdefaults(tabid);
create index btabid on sysdepend(btabid);
create index dtabid on sysdepend(dtabid);
create unique index sed_hashcode on sysdirectives(active);
create unique index sed_id on sysdirectives(active);
create unique index sed_hashcode on sysdirectives(hashcode);
create unique index sed_id on sysdirectives(id);
create unique index distrib on sysdistrib(colno);
create unique index distrib on sysdistrib(seqno);
create unique index distrib on sysdistrib(tabid);
create unique index se_mchunk on syserrors(level);
create unique index se_mchunk on syserrors(locale);
create unique index se_mchunk on syserrors(seqno);
create unique index se_mchunk on syserrors(sqlstate);
create index xcltabid on sysextcols(tabid);
create index xdftabid on sysextdfiles(tabid);
create unique index xtbtabid on sysexternal(tabid);
create unique index fragtor on sysfragauth(fragment);
create index fragtee on sysfragauth(grantee);
create unique index fragtor on sysfragauth(grantee);
create unique index fragtor on sysfragauth(grantor);
create unique index fragtor on sysfragauth(tabid);
create index fragtee on sysfragauth(tabid);
create unique index fragdist on sysfragdist(colno);
create index tabfragdist on sysfragdist(fragid);
create unique index fragdist on sysfragdist(fragid);
create unique index fragdist on sysfragdist(tabid);
create index tabfragdist on sysfragdist(tabid);
create index fraginfo on sysfragments(evalpos);
create index fraginfo on sysfragments(fragtype);
create index fraginfo on sysfragments(indexname);
create index fraginfo on sysfragments(tabid);
create unique index idxname on sysindices(idxname);
create unique index idxname on sysindices(owner);
create unique index idxname on sysindices(tabid);
create index idxtab on sysindices(tabid);
create index sih_child on sysinherits(child);
create index sih_parent on sysinherits(parent);
create unique index sla_langtor on syslangauth(grantee);
create index sla_langtee on syslangauth(grantee);
create unique index sla_langtor on syslangauth(grantor);
create index sla_langtee on syslangauth(langid);
create unique index sla_langtor on syslangauth(langid);
create unique index slm_tabid_fragid on syslogmap(fragid);
create unique index slm_tabid_fragid on syslogmap(tabid);
create unique index slm_tabloc on syslogmap(tabloc);
create unique index objdesc on sysobjstate(name);
create unique index objdesc on sysobjstate(objtype);
create unique index objdesc on sysobjstate(owner);
create index objtab on sysobjstate(tabid);
create unique index objdesc on sysobjstate(tabid);
create unique index opclaid on sysopclasses(opclassid);
create unique index opclaname on sysopclasses(opclassname);
create unique index opclaname on sysopclasses(owner);
create unique index opclstr on sysopclstr(clstrname);
create unique index opclstr on sysopclstr(owner);
create index optabid on sysopclstr(tabid);
create unique index procgtor on sysprocauth(grantee);
create index procgtee on sysprocauth(grantee);
create unique index procgtor on sysprocauth(grantor);
create index procgtee on sysprocauth(procid);
create unique index procgtor on sysprocauth(procid);
create unique index procbody on sysprocbody(datakey);
create unique index procbody on sysprocbody(procid);
create unique index procbody on sysprocbody(seqno);
create unique index spc_paramid on sysproccolumns(paramid);
create unique index spc_paramid on sysproccolumns(procid);
create index routinesign on sysprocedures(isproc);
create index routinesign on sysprocedures(numargs);
create index specificidx on sysprocedures(owner);
create index routinesign on sysprocedures(owner);
create unique index routineididx on sysprocedures(procid);
create index routinesign on sysprocedures(procname);
create index specificidx on sysprocedures(specificname);
create unique index procplan on sysprocplan(datakey);
create unique index procplan on sysprocplan(planid);
create unique index procplan on sysprocplan(procid);
create unique index procplan on sysprocplan(seqno);
create unique index refid on sysreferences(constrid);
create index refprimary on sysreferences(primary);
create unique index gteerole on sysroleauth(grantee);
create unique index rolegtee on sysroleauth(grantee);
create unique index rolegtee on sysroleauth(rolename);
create unique index gteerole on sysroleauth(rolename);
create index srl_langname on sysroutinelangs(langname);
create unique index ssla_gtee_policyid on sysseclabelauth(grantee);
create unique index ssla_gtee_policyid on sysseclabelauth(secpolicyid);
create index sslce_compid_pelem on sysseclabelcomponentelements(compid);
create unique index sslce_compid_elem on sysseclabelcomponentelements(compid);
create unique index sslce_compid_elem on sysseclabelcomponentelements(element);
create index sslce_compid_pelem on sysseclabelcomponentelements(parentelement);
create unique index sslc_compid on sysseclabelcomponents(compid);
create unique index sslc_compname on sysseclabelcomponents(compname);
create unique index ssln_policyid_labelname on sysseclabelnames(seclabelname);
create unique index ssln_policyid_labelname on sysseclabelnames(secpolicyid);
create unique index ssl_policyid_labelenc on sysseclabels(seclabelencoding);
create unique index ssl_policyid_labelid on sysseclabels(seclabelid);
create unique index ssl_policyid_labelid on sysseclabels(secpolicyid);
create unique index ssl_policyid_labelenc on sysseclabels(secpolicyid);
create unique index ssp_policyid on syssecpolicies(secpolicyid);
create unique index ssp_policyname on syssecpolicies(secpolicyname);
create unique index sspc_policyid_compid_compno on syssecpolicycomponents(compid);
create unique index sspc_policyid_compid_compno on syssecpolicycomponents(compno);
create unique index sspc_policyid_compid_compno on syssecpolicycomponents(secpolicyid);
create unique index sspe_gtee_policyid on syssecpolicyexemptions(grantee);
create unique index sspe_gtee_policyid on syssecpolicyexemptions(secpolicyid);
create unique index ssq_seqid on syssequences(seqid);
create unique index ssq_tabid on syssequences(tabid);
create unique index ssa_tuser_suser on syssurrogateauth(surrogateuser);
create unique index ssa_tuser_suser on syssurrogateauth(trusteduser);
create unique index synonym on syssynonyms(owner);
create unique index synonym on syssynonyms(synname);
create index syntabid on syssynonyms(tabid);
create index synnbtabid on syssyntable(btabid);
create unique index synntabid on syssyntable(tabid);
create unique index stmid on systabamdata(tabid);
create index tabgtee on systabauth(grantee);
create unique index tabgtor on systabauth(grantee);
create unique index tabgtor on systabauth(grantor);
create unique index tabgtor on systabauth(tabid);
create index tabgtee on systabauth(tabid);
create unique index tabname on systables(owner);
create unique index tabid on systables(tabid);
create unique index tabname on systables(tabname);
create unique index stc_clid on systraceclasses(classid);
create unique index stc_clname on systraceclasses(name);
create unique index strm_msgname on systracemsgs(locale);
create unique index strm_msgid on systracemsgs(msgid);
create unique index strm_msgname on systracemsgs(name);
create unique index trigbody on systrigbody(datakey);
create unique index trigbody on systrigbody(seqno);
create unique index trigbody on systrigbody(trigid);
create unique index trigname on systriggers(owner);
create index trigtabid on systriggers(tabid);
create unique index trigid on systriggers(trigid);
create unique index trigname on systriggers(trigname);
create unique index users on sysusers(username);
create unique index view on sysviews(seqno);
create unique index view on sysviews(tabid);
create unique index diatab on sysviolations(diatid);
create unique index targettab on sysviolations(targettid);
create unique index viotab on sysviolations(viotid);
create unique index sxa_datasrc_name on sysxadatasources(xa_datasrc_name);
create unique index sxa_datasrc_name on sysxadatasources(xa_datasrc_owner);
create unique index sxa_datasrc_id on sysxadatasources(xa_datasrc_rmid);
create unique index sxa_source_name on sysxasourcetypes(xa_source_name);
create unique index sxa_source_name on sysxasourcetypes(xa_source_owner);
create unique index sxa_source_typeid on sysxasourcetypes(xa_source_typeid);
create index sxd_xtd_id on sysxtddesc(extended_id);
create index sxd_xtd_id on sysxtddesc(seqno);
create index sxa_gtee on sysxtdtypeauth(grantee);
create unique index sxa_gtor on sysxtdtypeauth(grantee);
create unique index sxa_gtor on sysxtdtypeauth(grantor);
create index sxa_gtee on sysxtdtypeauth(type);
create unique index sxa_gtor on sysxtdtypeauth(type);
create unique index xtd_id on sysxtdtypes(extended_id);
create index sxt_locator on sysxtdtypes(locator);
create index xtd_domain on sysxtdtypes(name);
create index xtd_domain on sysxtdtypes(owner);
create index sxt_source on sysxtdtypes(source);
create index sxt_source on sysxtdtypes(type);
create index term_name_index on term(term_name);
create index term_ontology_index on term(term_ontology);
create index term_geno_handle_index on term_group(tg_geno_handle);
create index term_geno_name_index on term_group(tg_geno_name);
create unique index tg_genox_zdb_index on term_group(tg_genox_group);
create unique index term_relationship_alternate_key_index on term_relationship(termrel_term_1_zdb_id);
create unique index term_relationship_alternate_key_index on term_relationship(termrel_term_2_zdb_id);
create unique index term_relationship_alternate_key_index on term_relationship(termrel_type);
create unique index term_stage_primary_key_index on term_stage(ts_term_zdb_id);
create index tmp_acc_num_index on tmp_db_link(tmp_acc_num);
create index tmp_db_name_index on tmp_db_link(tmp_db_name);
create index tmp_linked_recid_index on tmp_db_link(tmp_linked_recid);
create index genox_idx on tmp_genox(genox_zdb_id);
create unique index ult_pk_index on unique_location(ul_chromosome);
create index ul_chromosome_index on unique_location(ul_chromosome);
create index ul_data_index on unique_location(ul_data_zdb_id);
create unique index ult_pk_index on unique_location(ul_data_zdb_id);
create index update_sort_index on updates(field_name);
create index update_sort_index on updates(rec_id);
create index update_sort_index on updates(submitter_id);
create unique index update_primary_key_index on updates(upd_pk_id);
create index update_sort_index on updates(when);
create index wd_new_zdb_id_index on withdrawn_data(wd_new_zdb_id);
create index xedg_assay_name_foreign_ky_index on xpat_exp_details_generated(xedg_assay_name);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_assay_name);
create index xedg_atb_zdb_id_index on xpat_exp_details_generated(xedg_atb_zdb_id);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_atb_zdb_id);
create index xedg_dblink_foreign_ky on xpat_exp_details_generated(xedg_dblink_zdb_id);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_dblink_zdb_id);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_fig_zdb_id);
create index xedg_source_foreign_ky_index on xpat_exp_details_generated(xedg_fig_zdb_id);
create index xedg_gene_zdb_id_foreign_ky_index on xpat_exp_details_generated(xedg_gene_zdb_id);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_gene_zdb_id);
create index xedg_featexp_zdb_id_foreign_ky_index on xpat_exp_details_generated(xedg_genox_zdb_id);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_genox_zdb_id);
create unique index xedg_primary_ky_index on xpat_exp_details_generated(xedg_pk_id);
create unique index xedg_alternate_ky_index on xpat_exp_details_generated(xedg_probe_feature_zdb_id);
create index xedg_marker_foreign_ky_index on xpat_exp_details_generated(xedg_probe_feature_zdb_id);
create index xfigg_geno_handle_index on xpat_figure_group(xfigg_geno_handle);
create index xfigg_genox_zdb_index on xpat_figure_group(xfigg_genox_zdb_id);
create unique index xfigg_group_id_index on xpat_figure_group(xfigg_group_pk_id);
create index xfiggm_group_id_index on xpat_figure_group_member(xfiggm_group_id);
create index xfiggm_member_id_index on xpat_figure_group_member(xfiggm_member_id);
create unique index xfigg_pk_id_index on xpat_figure_group_member(xfiggm_pk_id);
create index xrg_end_stg_foreign_key_index on xpat_results_generated(xrg_end_stg_zdb_id);
create unique index xrg_alternate_key_index on xpat_results_generated(xrg_end_stg_zdb_id);
create unique index xrg_alternate_key_index on xpat_results_generated(xrg_expression_found);
create unique index xrg_primary_key_index on xpat_results_generated(xrg_pk_id);
create index xrg_start_stg_foreign_key_index on xpat_results_generated(xrg_start_stg_zdb_id);
create unique index xrg_alternate_key_index on xpat_results_generated(xrg_start_stg_zdb_id);
create index xrg_subterm_foreign_key_index on xpat_results_generated(xrg_subterm_zdb_id);
create unique index xrg_alternate_key_index on xpat_results_generated(xrg_subterm_zdb_id);
create index xrg_suggested_anatomy_foreign_key_index on xpat_results_generated(xrg_suggested_anatomy_item);
create unique index xrg_alternate_key_index on xpat_results_generated(xrg_superterm_zdb_id);
create index xrg_superterm_foreign_key_index on xpat_results_generated(xrg_superterm_zdb_id);
create unique index xrg_alternate_key_index on xpat_results_generated(xrg_xedg_id);
create index xrg_xedg_foreign_key_index on xpat_results_generated(xrg_xedg_id);
create unique index etfs_pk_id_index on xpatfs_old(etfs_pk_id);
create index expression_term_fast_search_term_id_index on xpatfs_old(etfs_term_zdb_id);
create unique index etfs_alternate_key_index on xpatfs_old(etfs_term_zdb_id);
create index expression_term_fast_search_xpatres_id_index on xpatfs_old(etfs_xpatres_pk_id);
create unique index etfs_alternate_key_index on xpatfs_old(etfs_xpatres_pk_id);
create unique index za_sequence_number_alternate_key_index on zfin_accession_number(za_sequence_number);
create index zmap_pub_pan_mark_mname_index on zmap_pub_pan_mark(mname);
create index zmap_pub_pan_mark_mtype_index on zmap_pub_pan_mark(mtype);
create index zmap_pub_pan_mark_panel_abbrev_index on zmap_pub_pan_mark(panel_abbrev);
