#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Linkage app pages.
#
# $Source$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/linkage

GENERICS = add_linkage.apg add_linkage_members.apg insert_linkage.apg add_linkage_distance.apg detailview.apg detailframe.apg edit_linkage.apg modify_linkage.apg modify_distance.apg
STATICS =showdetails.apg 

# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules

