<div class="popup-header">
    Target Location Note
</div>
<div class="popup-body">
    The Knockdown Reagent track is generated by first applying <a href="http://bowtie-bio.sourceforge.net/">Bowtie</a>
    to knockdown reagent sequence data. End-to-end alignment is performed, allowing up to two mismatches. Only
    alignments with the fewest mismatches for a given sequence are reported.
</div>