#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, ZFIN Backgrounds directory
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# 


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

# See ../Makefile for a discussion of this directory.

TARGETDIR = $(TARGETROOT)/home/images/BACKGROUNDS

# ZFIN_back is currently a copy of blumarb.jpg.

STATICS := $(shell echo *.gif *.jpg) ZFIN_back


# --------------------------  Rules  ------------------------------------

# Use default rules

include $(TOP)/make.default.rules

