#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Feature pages
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/feature_files

GENERICS = new_feature.apg  featcuration.apg featcurupdate.apg featureedit.apg featrelationships.apg record_web_update.apg new_constrct.apg  constrctcuration.apg constrctrelationships.apg
# use default rules for app page directories

include $(TOP)/make.default.apg.rules

