#!/local/bin/bash

export ANT_HOME="/opt/apache/apache-ant"
export ANT_OPTS="-Xms256m -Xmx4096m -Dgwt.persistentunitcache=false"
export CATALINA_BASE="/opt/zfin/catalina_bases/beagle"
export CATALINA_HOME="/opt/apache/apache-tomcat"
export CATALINA_PID="/opt/zfin/catalina_bases/beagle/catalina_pid"
export CURATION_DBNAME="false"
export CURATION_INSTANCE="false"
export DBNAME="beagdb"
export DB_NAME="beagdb"
export DEFAULT_EMAIL="informix@zfin.org"
export DOMAIN_NAME="beagle.zfin.org"
export DOWNLOAD_DIRECTORY="/research/zunloads/download-files/beagdb"
export GBROWSE_PATH_FROM_ROOT="action/gbrowse/"
export GC_LOGGING_OPTS="-verbose:gc -verbose:sizes -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:/opt/zfin/catalina_bases/beagle/logs/gc.log"
export GRADLE_USER_HOME="~/.gradle"
export HAS_PARTNER="false"
export IMAGE_LOAD="/imageLoadUp"
export INDEXER_UNLOAD_DIRECTORY="/research/zunloads/indexes/beagdb"
export INDEXER_WIKI_HOSTNAME="devwiki.zfin.org"
export INDEXER_WIKI_PASSWORD="dan1orer1o"
export INDEXER_WIKI_USERNAME="webservice"
export INSPECTLET_ID="0000000000"
export INSTANCE="beagle"
export JAVA_HOME="/usr/lib/jvm/java-openjdk"
export JENKINS_HOME="/research/zcentral/www_homes/beagle/server_apps/jenkins/jenkins-home"
export JENKINS_PORT="9443"
export JPDA_ADDRESS="9343"
export LOADUP_FULL_PATH="/opt/zfin/loadUp"
export MUTANT_NAME="beagle"
export PARTNER_DBNAME="false"
export PARTNER_INTERNAL_INSTANCE="false"
export PGDATABASE=""
export PRIMARY_COLOR="#c2185b"
export ROOT_PATH="/research/zcentral/www_homes/beagle"
export SHARED_DOMAIN_NAME="false"
export SOLR_CORE="site_index_beagle"
export SOLR_HOME="/var/solr/data/site_index_beagle"
export SOLR_PORT="8983"
export SOURCEROOT="/research/zusers/beagle/ZFIN_WWW_trunk"
export SQLHOSTS_FILE="sqlhosts"
export SQLHOSTS_HOST="zygotix.zfin.org"
export SWISSPROT_EMAIL_ERR="informix@zfin.org"
export TARGETCGIBIN="beagle"
export TARGETFTPROOT="/research/zcentral/ftp"
export TARGETROOT="/research/zcentral/www_homes/beagle"
export USER="informix"
export VALIDATION_EMAIL_DBA="informix@zfin.org"
export WEBHOST_BLASTDB_TO_COPY="/research/crick/blastdb"
export WIKI_HOST="wiki.zfin.org"
export ZFIN_ADMIN="informix@zfin.org"

export PATH=/opt/misc/groovy/bin:$PATH

export PATH=/opt/postgres/postgresql/bin:/opt/postrgres/postgresql/include:$PATH

export PATH=/opt/ab-blast:$PATH

# Prompt
export PROMPT_DIRTRIM=2
export PS1="${MUTANT_NAME}:\w\$ "
