#!/local/bin/bash

export ANT_HOME="/opt/apache/apache-ant"
export ANT_OPTS="-Xms256m -Xmx4096m -Dgwt.persistentunitcache=false"
export CATALINA_BASE="/opt/zfin/catalina_bases/lucky"
export CATALINA_HOME="/opt/apache/apache-tomcat"
export CATALINA_PID="/opt/zfin/catalina_bases/lucky/catalina_pid"
export CLIENT_LOCALE="en_US.utf8"
export CURATION_DBNAME="false"
export CURATION_INSTANCE="false"
export DBNAME="luckdb"
export DB_LOCALE="en_US.utf8"
export DB_NAME="luckdb"
export DB_UNLOADS_PATH="/research/zunloads/databases/zfindb"
export DEFAULT_EMAIL="annee@zfin.org"
export DOMAIN_NAME="lucky.zfin.org"
export DOWNLOAD_DIRECTORY="/research/zunloads/download-files/luckdb"
export GBROWSE_PATH_FROM_ROOT="action/gbrowse/"
export GC_LOGGING_OPTS="-verbose:gc -verbose:sizes -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:/opt/zfin/catalina_bases/lucky/logs/gc.log"
export GRADLE_USER_HOME="~/.gradle"
export GROOVY_CLASSPATH="/opt/zfin/www_homes/lucky/home/WEB-INF/lib*:/research/zusers/mochla/projects/ZFIN_WWW_this/lib/Java/*:/opt/zfin/www_homes/lucky/home/WEB-INF/classes:/opt/misc/groovy/lib/*"
export HAS_PARTNER="false"
export IMAGE_LOAD="/imageLoadUp"
export INDEXER_UNLOAD_DIRECTORY="/research/zunloads/indexes/luckdb"
export INDEXER_WIKI_HOSTNAME="devwiki.zfin.org"
export INDEXER_WIKI_PASSWORD="dan1orer1o"
export INDEXER_WIKI_USERNAME="webservice"
export INSPECTLET_ID="0000000000"
export INSTANCE="lucky"
export JAVA_HOME="/usr/lib/jvm/java-openjdk"
export JENKINS_HOME="/opt/zfin/www_homes/lucky/server_apps/jenkins/jenkins-home"
export JENKINS_PORT="9412"
export JPDA_ADDRESS="9312"
export LOADUP_FULL_PATH="/research/zcentral/loadUp/pubs"
export MUTANT_NAME="lucky"
export NODE_ENV="development"
export PARTNER_DBNAME="false"
export PARTNER_INTERNAL_INSTANCE="false"
export PARTNER_SOURCEROOT="false"
export PGBINDIR="/opt/postgres/postgresql/bin"
export PGDATA="/opt/postgres/data"
export PGDATABASE="luckdb"
export PGHOST="localhost"
export PRIMARY_COLOR="#388e3c"
export ROOT_PATH="/opt/zfin/www_homes/lucky"
export SHARED_DOMAIN_NAME="false"
export SOLR_CORE="site_index_lucky"
export SOLR_HOME="/var/solr/data/site_index_lucky"
export SOLR_MEMORY="8g"
export SOLR_PORT="8983"
export SOLR_UNLOADS_PATH="/research/zunloads/solr/zfindb"
export SOURCEROOT="/research/zusers/mochla/projects/ZFIN_WWW_this"
export SQLHOSTS_FILE="sqlhosts"
export SQLHOSTS_HOST="shmoo.zfin.org"
export SWISSPROT_EMAIL_ERR="annee@zfin.org"
export TARGETCGIBIN="cgi-bin"
export TARGETFTPROOT="/opt/zfin/ftp/test/lucky"
export TARGETROOT="/opt/zfin/www_homes/lucky"
export USER="annee"
export VALIDATION_EMAIL_DBA="annee@zfin.org"
export WEBHOST_BLASTDB_TO_COPY="/research/crick/blastdb"
export WIKI_HOST="devwiki.zfin.org"
export ZFIN_ADMIN="annee@zfin.org"

export PATH=/opt/misc/groovy/bin:$PATH

export PATH=/opt/postgres/postgresql/bin:/opt/postrgres/postgresql/include:$PATH

export PATH=/opt/ab-blast:$PATH

# Prompt
export PROMPT_DIRTRIM=2
export PS1="${MUTANT_NAME}:\w\$ "
