#!/local/bin/bash

export ANT_HOME="/usr/share/ant"
export ANT_OPTS="-Xms256m -Xmx4096m -Dgwt.persistentunitcache=false"
export CATALINA_BASE="/opt/zfin//catalina_bases/zfin.org"
export CATALINA_HOME="/usr/local/tomcat"
export CATALINA_PID="/opt/zfin//catalina_bases/zfin.org/catalina_pid"
export CLIENT_LOCALE="en_US.utf8"
export CONVERT_BINARY_PATH="/usr/bin/convert"
export CURATION_DBNAME="false"
export CURATION_INSTANCE="false"
export DBNAME="zfindb"
export DB_LOCALE="en_US.utf8"
export DB_NAME="zfindb"
export DB_UNLOADS_PATH="/opt/zfin/unloads/db"
export DEFAULT_EMAIL="informix@zfin.org"
export DOMAIN_NAME="zfin.org"
export DOWNLOAD_DIRECTORY="/opt/zfin/download-files"
export GBROWSE_PATH_FROM_ROOT="action/gbrowse/"
export GC_LOGGING_OPTS="-verbose:gc -verbose:sizes -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:/opt/zfin//catalina_bases/zfin.org/logs/gc.log"
export GRADLE_USER_HOME="$HOME/.gradle"
export GROOVY_CLASSPATH="/opt/zfin//catalina_bases/zfin.org/webapps/ROOT/WEB-INF/lib/*:/opt/zfin//source_roots/zfin.org/lib/Java/*:/opt/zfin//catalina_bases/zfin.org/webapps/ROOT/WEB-INF/classes:/opt/misc/groovy/lib/*:/usr/local/tomcat/endorsed/*"
export HAS_PARTNER="false"
export IMAGE_LOAD="/imageLoadUp"
export INDEXER_UNLOAD_DIRECTORY="/research/zunloads/indexes/zfindb"
export INDEXER_WIKI_HOSTNAME="devwiki.zfin.org"
export INDEXER_WIKI_PASSWORD="dan1orer1o"
export INDEXER_WIKI_USERNAME="webservice"
export INSPECTLET_ID="0000000000"
export INSTANCE="trunk"
export JAVA_HOME="/opt/java/openjdk"
export JENKINS_HOME="/opt/zfin//www_homes/zfin.org/server_apps/jenkins/jenkins-home"
export JENKINS_PORT="9499"
export JPDA_ADDRESS="5000"
export LOADUP_FULL_PATH="/opt/zfin/loadUp/pubs"
export MUTANT_NAME="zfin.org"
export NODE_ENV="production"
export PARTNER_DBNAME="false"
export PARTNER_INTERNAL_INSTANCE="false"
export PARTNER_SOURCEROOT="false"
export PGBINDIR="/usr/bin"
export PGDATA="/opt/postgres/data"
export PGDATABASE=""
export PGHOST="db"
export PRIMARY_COLOR="#f57c00"
export ROOT_PATH="/opt/zfin//www_homes/zfin.org"
export SHARED_DOMAIN_NAME="false"
export SMTP_HOST="smtp.uoregon.edu"
export SOLR_CORE="site_index"
export SOLR_HOME="/var/solr/data/site_index"
export SOLR_MEMORY="8g"
export SOLR_PORT="8983"
export SOLR_UNLOADS_PATH="/opt/zfin/unloads/solr"
export SOURCEROOT="/opt/zfin//source_roots/zfin.org"
export SQLHOSTS_FILE="sqlhosts"
export SQLHOSTS_HOST="zfin.org"
export SWISSPROT_EMAIL_ERR="informix@zfin.org"
export SWISSPROT_EMAIL_REPORT="informix@zfin.org"
export TARGETCGIBIN="cgi-bin"
export TARGETFTPROOT="/opt/zfin//ftp/test/trunk"
export TARGETROOT="/opt/zfin//www_homes/zfin.org"
export USER="docker"
export VALIDATION_EMAIL_DBA="informix@zfin.org"
export WAR_WEB_INF_DIR="/opt/zfin//catalina_bases/zfin.org/webapps/ROOT/WEB-INF"
export WEBHOST_BLASTDB_TO_COPY="/research/crick/blastdb"
export WIKI_HOST="devwiki.zfin.org"
export ZFIN_ADMIN="informix@zfin.org"
export ZFIN_PROPERTIES_PATH="/opt/zfin//catalina_bases/zfin.org/webapps/ROOT/WEB-INF/zfin.properties"

export PATH=/opt/misc/groovy/bin:$PATH

export PATH=/opt/postgres/postgresql/bin:$PATH

export PATH=/opt/ab-blast:$PATH

# Prompt
export PROMPT_DIRTRIM=2
export PS1="${INSTANCE}:\w\$ "
