#!/local/bin/bash

export ANT_HOME="/opt/apache/apache-ant"
export ANT_OPTS="-Xms256m -Xmx4096m -Dgwt.persistentunitcache=false"
export CATALINA_BASE="/opt/zfin/catalina_bases/zezem"
export CATALINA_HOME="/opt/apache/apache-tomcat"
export CATALINA_PID="/opt/zfin/catalina_bases/zezem/catalina_pid"
export CLIENT_LOCALE="en_US.utf8"
export CURATION_DBNAME="false"
export CURATION_INSTANCE="false"
export DBNAME="zezdb"
export DB_LOCALE="en_US.utf8"
export DB_NAME="zezdb"
export DB_UNLOADS_PATH="/research/zunloads/databases/zfindb"
export DEFAULT_EMAIL="cmpich@zfin.org"
export DOMAIN_NAME="zezem.zfin.org"
export DOWNLOAD_DIRECTORY="/research/zunloads/download-files/zezdb"
export GBROWSE_PATH_FROM_ROOT="action/gbrowse/"
export GC_LOGGING_OPTS="-verbose:gc -verbose:sizes -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -Xloggc:/opt/zfin/catalina_bases/zezem/logs/gc.log"
export GRADLE_USER_HOME="~/.gradle"
export GROOVY_CLASSPATH="/opt/zfin/www_homes/zezem/home/WEB-INF/lib*:/opt/zfin/source_roots/zezem/lib/Java/*:/opt/zfin/www_homes/zezem/home/WEB-INF/classes:/opt/misc/groovy/lib/*"
export HAS_PARTNER="false"
export IMAGE_LOAD="/imageLoadUp"
export INDEXER_UNLOAD_DIRECTORY="/research/zunloads/indexes/zezdb"
export INDEXER_WIKI_HOSTNAME="devwiki.zfin.org"
export INDEXER_WIKI_PASSWORD="dan1orer1o"
export INDEXER_WIKI_USERNAME="webservice"
export INSPECTLET_ID="0000000000"
export INSTANCE="zezem"
export JAVA_HOME="/usr/lib/jvm/java-openjdk"
export JENKINS_HOME="/opt/zfin/www_homes/zezem/server_apps/jenkins/jenkins-home"
export JENKINS_PORT="9426"
export JPDA_ADDRESS="9326"
export LOADUP_FULL_PATH="/research/zcentral/loadUp/pubs"
export MUTANT_NAME="zezem"
export NODE_ENV="development"
export PARTNER_DBNAME="false"
export PARTNER_INTERNAL_INSTANCE="false"
export PARTNER_SOURCEROOT="false"
export PGBINDIR="/opt/postgres/postgresql/bin"
export PGDATA="/opt/postgres/data"
export PGDATABASE="zezdb"
export PGHOST="localhost"
export PRIMARY_COLOR="#1976d2"
export ROOT_PATH="/opt/zfin/www_homes/zezem"
export SHARED_DOMAIN_NAME="false"
export SOLR_CORE="site_index_zezem"
export SOLR_HOME="/var/solr/data/site_index_zezem"
export SOLR_MEMORY="8g"
export SOLR_PORT="8983"
export SOLR_UNLOADS_PATH="/research/zunloads/solr/zfindb"
export SOURCEROOT="/opt/zfin/source_roots/zezem"
export SQLHOSTS_FILE="sqlhosts"
export SQLHOSTS_HOST="aria.zfin.org"
export SWISSPROT_EMAIL_ERR="cmpich@zfin.org"
export TARGETCGIBIN="cgi-bin"
export TARGETFTPROOT="/opt/zfin/ftp/test/zezem"
export TARGETROOT="/opt/zfin/www_homes/zezem"
export USER="cmpich"
export VALIDATION_EMAIL_DBA="cmpich@zfin.org"
export WEBHOST_BLASTDB_TO_COPY="/research/crick/blastdb"
export WIKI_HOST="devwiki.zfin.org"
export ZFIN_ADMIN="cmpich@zfin.org"

export PATH=/opt/misc/groovy/bin:$PATH

export PATH=/opt/postgres/postgresql/bin:/opt/postrgres/postgresql/include:$PATH

export PATH=/opt/ab-blast:$PATH

# Prompt
export PROMPT_DIRTRIM=2
export PS1="${MUTANT_NAME}:\w\$ "
