#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Mutant/Fish related pages.
#
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------


TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/xpat_files


GENERICS = xpatview.apg xpatlister_parts.apg xpatselect.apg xpatupdateAssay.apg do-xpatupdateAssay.apg xpatupdatePubs.apg do-xpatupdatePubs.apg xpatupdateDescription.apg do-xpatupdateDescription.apg xpatupdateComments.apg do-xpatupdateComments.apg


# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules

