#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Expression pattern files
#
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------


TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/xpat_files

GENERICS = anatomy_captures.apg curation.apg experimentcuration.apg \
figurecuration.apg fxallfigures.apg fxfiganatlist.apg fxfiggenelist.apg \
 fxfigphenogenolist.apg \
fxfigprobelist.apg fxfigureview.apg fxinfo.apg fxlabelinfo.apg fxphenoinfo.apg \
fxprobefig.apg fxpubdisplay.apg genocurbuilder.apg genocursearch.apg \
genocursummary.apg genosearchresulttable.apg pheno_summary.apg xpatcurcondition.apg \
xpatcurexperiment.apg xpatcurfigure.apg xpatcurimage.apg xpatcurpermission.apg \
 xpatselect.apg \
xpatselect_detailedresults.apg xpatselect_note.apg xpatselect_summaryresults.apg \
xpatselectanatverify.apg xpatselectrowdisplay.apg

STATICS = fxfigphenoanatlist.apg xpatexpcdnsummary.apg xpatexpcdnlist.apg xpatselectquery.apg xpatcuration.apg xpatexdisplayname.apg xpatcurupdate.apg \
fxfigstgrng.apg fxassayabbrev.apg fxfigassaylist.apg fxfigfishlist.apg xpatfeatexp.apg \
fxgenestgrng.apg record_web_update.apg do-addcanmrkr.apg genotypecuration.apg attribupdate.apg \
genoupdate.apg patocuration.apg fxfigphenostgrng.apg xpatcurreset.apg \
wordcompletion.apg xpatcurupdatecondition.apg gocuration.apg xpatselect_resultsasimages.apg \
xpatfeatexpcondn.apg xpatview.apg

# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules

