#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Expression pattern files
#
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------


TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/xpat_files

GENERICS = xpatview.apg xpatselect.apg anatdict.apg anatomy_item.apg \
	xpatindexview.apg anatomy_captures.apg xpatselect_note.apg \
	xpatselectquery.apg xpatselectrowdisplay.apg xpatcuration.apg \
	xpatexdisplayname.apg getPubStructureListItem.apg xpatselectanatverify.apg \
	xpatcurexpssdisplayname.apg xpatcurupdate.apg xpatcurimage.apg \
	xpatcurexperiment.apg xpatcurcondition.apg xpatcurfigure.apg \
	xpatcurexpression.apg xpatcurpanel.apg xpatcurstructure.apg  \
	fxpubdisplay.apg fxfigureview.apg  fxfiggenelist.apg \
	fxfiganatlist.apg  fxfigstgrng.apg fxallfigures.apg \
	fxassayabbrev.apg xpatselect_summaryresults.apg xpatselect_detailedresults.apg \
	fxfigassaylist.apg fxfigfishlist.apg fxinfo.apg xpatselect_resultsbygene.apg \
	xpatexpcdnsummary.apg xpatselect_resultsasimages.apg \
	xpatexpcdndisplay.apg xpatfeatexp.apg fxprobefig.apg xpatcurpermission.apg \
	fxfigprobelist.apg fxgenestgrng.apg


# Use default rules for app page directories. 

include $(TOP)/make.default.apg.rules

