#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Zebrafish Book web pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/zfbook

SUBDIRS = chapt1 chapt2 chapt3 chapt4 chapt5 chapt7 chapt8 chapt9 stages

STATICS = streis.gif chapt6.html chapt10.html cont.html zfbk.html \
	zfmabs.html zfrefs.html 

GENERICS = zfstrn.html lab_desig.html

# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
