package org.zfin.gwt.root.event;

public enum AjaxCallEventType {
    // @formatter:off
            GET_DNA_CHANGE_LIST_START,
                GET_DNA_CHANGE_LIST_STOP(GET_DNA_CHANGE_LIST_START),
            GET_DNA_LOCALIZATION_CHANGE_LIST_START,
                GET_DNA_LOCALIZATION_CHANGE_LIST_STOP(GET_DNA_LOCALIZATION_CHANGE_LIST_START),
            GET_PROTEIN_CONSEQUENCE_LIST_START,
                GET_PROTEIN_CONSEQUENCE_LIST_STOP(GET_PROTEIN_CONSEQUENCE_LIST_START),
            GET_AMINO_ACID_LIST_START,
                GET_AMINO_ACID_LIST_STOP(GET_AMINO_ACID_LIST_START),
            GET_TRANSCRIPT_CONSEQUENCE_LIST_START,
                GET_TRANSCRIPT_CONSEQUENCE_LIST_STOP(GET_TRANSCRIPT_CONSEQUENCE_LIST_START),
            GET_LABS_OF_ORIGIN_WITH_PREFIX_START,
                GET_LABS_OF_ORIGIN_WITH_PREFIX_STOP(GET_LABS_OF_ORIGIN_WITH_PREFIX_START),
            GET_FEATURE_LIST_START,
                GET_FEATURE_LIST_STOP(GET_FEATURE_LIST_START),
            READ_ANTIBODIES_BY_GENE_START,
                READ_ANTIBODIES_BY_GENE_STOP(READ_ANTIBODIES_BY_GENE_START),
            READ_GENES_BY_ANTIBODY_START,
                READ_GENES_BY_ANTIBODY_STOP(READ_GENES_BY_ANTIBODY_START),
            READ_GENBANK_ACCESSIONS_START,
                READ_GENBANK_ACCESSIONS_STOP(READ_GENBANK_ACCESSIONS_START),
            DELETE_PUBLIC_NOTE_START,
                DELETE_PUBLIC_NOTE_STOP(DELETE_PUBLIC_NOTE_START),
            CREATE_PUBLIC_NOTE_START,
                CREATE_PUBLIC_NOTE_STOP(CREATE_PUBLIC_NOTE_START),
            SAVE_PUBLIC_NOTE_START,
                SAVE_PUBLIC_NOTE_STOP(SAVE_PUBLIC_NOTE_START),
            SAVE_CURATOR_NOTE_START,
                SAVE_CURATOR_NOTE_STOP(SAVE_CURATOR_NOTE_START),
            DELETE_CURATOR_NOTE_START,
                DELETE_CURATOR_NOTE_STOP(DELETE_CURATOR_NOTE_START),
            CREATE_CURATOR_NOTE_START,
                CREATE_CURATOR_NOTE_STOP(CREATE_CURATOR_NOTE_START),
            GET_GENOTYPE_LIST_START,
                GET_GENOTYPE_LIST_STOP(GET_GENOTYPE_LIST_START),
            GET_FISH_LIST_START,
                GET_FISH_LIST_STOP(GET_FISH_LIST_START),
            GET_EXPERIMENTS_BY_FILTER_START,
                GET_EXPERIMENTS_BY_FILTER_STOP(GET_EXPERIMENTS_BY_FILTER_START),
            UPDATE_EXPRESSIONS_EXPERIMENTS_START,
                UPDATE_EXPRESSIONS_EXPERIMENTS_STOP(UPDATE_EXPRESSIONS_EXPERIMENTS_START),
            GET_CHILD_MAP_START,
                GET_CHILD_MAP_STOP(GET_CHILD_MAP_START),
            GET_STR_LIST_START,
                GET_STR_LIST_STOP(GET_STR_LIST_START),
            GET_EXPERIMENT_LIST_START,
                GET_EXPERIMENT_LIST_STOP(GET_EXPERIMENT_LIST_START),
            GET_FIGURE_LIST_START,
                GET_FIGURE_LIST_STOP(GET_FIGURE_LIST_START),
            COPY_CONDITION_START,
                COPY_CONDITION_STOP(COPY_CONDITION_START),
            CREATE_CONDITION_START,
                CREATE_CONDITION_STOP(CREATE_CONDITION_START),
            DELETE_CONDITION_START,
                DELETE_CONDITION_STOP(CREATE_CONDITION_START),
            CREATE_GENOTYPE_FISH_START,
                CREATE_GENOTYPE_FISH_STOP(DELETE_CONDITION_START),
            GET_BACKGROUND_GENOTYPES_START,
                GET_BACKGROUND_GENOTYPES_STOP(GET_BACKGROUND_GENOTYPES_START),
            GET_FEATURE_MARKER_RELATIONSHIPS_FOR_PUB_START,
                GET_FEATURE_MARKER_RELATIONSHIPS_FOR_PUB_STOP(GET_FEATURE_MARKER_RELATIONSHIPS_FOR_PUB_START),
            GET_RELATIONSHIP_TYPES_FOR_FEATURE_TYPE_START,
                GET_RELATIONSHIP_TYPES_FOR_FEATURE_TYPE_STOP(GET_RELATIONSHIP_TYPES_FOR_FEATURE_TYPE_START),
            GET_MARKERS_FOR_FEATURE_RELATION_AND_SOURCE_START,
                GET_MARKERS_FOR_FEATURE_RELATION_AND_SOURCE_STOP(GET_MARKERS_FOR_FEATURE_RELATION_AND_SOURCE_START),
            GET_CONSTRUCT_MARKER_RELATIONSHIPS_FOR_PUB_START,
                GET_CONSTRUCT_MARKER_RELATIONSHIPS_FOR_PUB_STOP(GET_CONSTRUCT_MARKER_RELATIONSHIPS_FOR_PUB_START),
            GET_CONSTRUCTS_FOR_PUB_START,
                GET_CONSTRUCTS_FOR_PUB_STOP(GET_CONSTRUCTS_FOR_PUB_START),
            ADD_CONSTRUCT_MARKER_RELATIONSHIP_START,
                ADD_CONSTRUCT_MARKER_RELATIONSHIP_STOP(ADD_CONSTRUCT_MARKER_RELATIONSHIP_START),
            GET_GENE_LIST_START,
                GET_GENE_LIST_STOP(GET_GENE_LIST_START),
            GET_ANTIBODY_LIST_START,
                GET_ANTIBODY_LIST_STOP(GET_ANTIBODY_LIST_START),
            GET_ENVIRONMENT_LIST_START,
                GET_ENVIRONMENT_LIST_STOP(GET_ENVIRONMENT_LIST_START),
            DELETE_EXPRESSION_EXPERIMENT_START,
                DELETE_EXPRESSION_EXPERIMENT_STOP(DELETE_EXPRESSION_EXPERIMENT_START),
            GET_EXPRESSIONS_BY_FILTER_START,
                GET_EXPRESSIONS_BY_FILTER_STOP(GET_EXPRESSIONS_BY_FILTER_START),
            GET_STAGE_LIST_START,
                GET_STAGE_LIST_STOP(GET_STAGE_LIST_START),
            IS_STAGE_SELECTOR_SINGLE_MODE_START,
                IS_STAGE_SELECTOR_SINGLE_MODE_STOP(IS_STAGE_SELECTOR_SINGLE_MODE_START),
            GET_EXPRESSION_AS_PHENOTYPE_START,
                GET_EXPRESSION_AS_PHENOTYPE_STOP(GET_EXPRESSION_AS_PHENOTYPE_START),
            CREATE_PHENOTYPE_EXPERIMENT_START,
                CREATE_PHENOTYPE_EXPERIMENT_STOP(CREATE_PHENOTYPE_EXPERIMENT_START),
            DELETE_FIGURE_ANNOTATION_START,
                DELETE_FIGURE_ANNOTATION_STOP(DELETE_FIGURE_ANNOTATION_START),
            GET_PHENOTYPE_PILE_STRUCTURES_START,
                GET_PHENOTYPE_PILE_STRUCTURES_STOP(GET_PHENOTYPE_PILE_STRUCTURES_START),
            GET_TERM_INFO_START,
                GET_TERM_INFO_STOP(GET_TERM_INFO_START),
            GET_TERM_BY_NAME_START,
                GET_TERM_BY_NAME_STOP(GET_TERM_BY_NAME_START),
            GET_FILTER_VALUES_START,
                GET_FILTER_VALUES_STOP(GET_FILTER_VALUES_START),
            GET_HUMAN_DISEASE_ANNOTATIONS_START,
                GET_HUMAN_DISEASE_ANNOTATIONS_STOP(GET_HUMAN_DISEASE_ANNOTATIONS_START),
            GET_HUMAN_DISEASE_LIST_START,
                GET_HUMAN_DISEASE_LIST_STOP(GET_HUMAN_DISEASE_LIST_START),
            DELETE_DISEASE_MODEL_START,
                DELETE_DISEASE_MODEL_STOP(DELETE_DISEASE_MODEL_START),
            DELETE_DISEASE_ANNOTATION_MODEL_START,
                DELETE_DISEASE_ANNOTATION_MODEL_STOP(DELETE_DISEASE_ANNOTATION_MODEL_START),
            ADD_HUMAN_DISEASE_ANNOTATIONS_START,
                ADD_HUMAN_DISEASE_ANNOTATIONS_STOP(ADD_HUMAN_DISEASE_ANNOTATIONS_START),
    // @formatter:on
    ;
    private AjaxCallEventType mate;

    AjaxCallEventType() {
    }

    AjaxCallEventType(AjaxCallEventType mate) {
        this.mate = mate;
    }

    public boolean isStart() {
        return mate == null;
    }

    public boolean isStop() {
        return !isStart();
    }

    public boolean isStartMate(AjaxCallEventType type) {
        if (type == null)
            return false;
        return mate.equals(type);
    }

    public AjaxCallEventType getStartMate() {
        return mate;
    }
}
