#!/bin/sh  -x
# A script to start up the Java server for Illustra
# ted Feb. 28, 1998.

SERVER_HOME=/export/fish/www/java/javaserver
cd $SERVER_HOME

#  For Illustra
MI_HOME=/export/fish/Illustra
MI_SYSPARAMS=$MI_HOME/MiParams
MI_DATABASE=template1

export MI_HOME MI_SYSPARAMS MI_DATABASE

case "$1" in 
  'start')

	#  The server will load a *.so file, so we need to tell loader where to find it
	LD_LIBRARY_PATH=$SERVER_HOME

	#  For access reasons, we connect to Illustra the same way as Webdriver
	MI_USER=webuser
	MI_PASSWORD=zfish

	export LD_LIBRARY_PATH MI_USER MI_PASSWORD
	/local/apps/jdk/bin/java Server >> Server.out 2>&1 &
	
	echo $! > javaServerPid
	
	;;

    'stop')
	kill -9 `cat javaServerPid`
	;;

    *)
	echo "usage: $0 {start|stop}"
 	;;
esac
