#!/bin/sh
#
# $Source$
# $Id$
#
# A script to start up the Java server for Illustra
# ted Feb. 28, 1998.
# Hacked on by clif 12/23/99
# 2000/10/05 DPC: Modified file in preparation to genericizing it.

# Note: The version of Java we run the Java Server under
#	must match the version we compiled the libMISQL.so library
#       under.  See the Makefile for the Java Server for details.
# Use the /usr filesystem so that we are assured it is mounted when 
# this script is run in rc3.d
JAVA_DIR=/usr/java1.1

SERVER_HOME=<!--|JAVASERVER_PATH|-->
cd $SERVER_HOME

INFORMIXDIR=<!--|INFORMIX_DIR|-->
INFORMIXSERVER=<!--|INFORMIX_SERVER|-->
INFORMIXSQLHOSTS=$INFORMIXDIR/etc/<!--|SQLHOSTS_FILE|-->

export INFORMIXDIR INFORMIXSERVER INFORMIXSQLHOSTS

case "$1" in 
  'start')
	#  The server will load a *.so file, so we need to tell loader where to find it
	LD_LIBRARY_PATH=$SERVER_HOME:$INFORMIXDIR/lib:$INFORMIXDIR/lib/esql:$INFORMIXDIR/lib/dmi
	#  Now that we're using SU, we don't gain anything from exporting this (see below),
	#  but I retained this statement to observe the form of the thing.
	export LD_LIBRARY_PATH

	#  To detect if we're running during startup, we look at the _INIT_RUN_LEVEL environment variable.
	#  This is set to 3 when this routine is called during startup (and not set at all when
	#  called outside of startup.

	#  Informix apparently won't allow root to connect as a client (strange, but apparently so).
	#  So we have to SU as <!--|APP_PAGE_USER|--> to run the server.  And since SU won't allow the environment
	#  variable LD_LIBRARY_PATH to be exported into its subprocess (a security restriction),
	#  we must explicitly set the variable INSIDE the new subprocess.
	if [ "${_INIT_RUN_LEVEL}" = "3" ] ; then 
	    /bin/su <!--|APP_PAGE_USER|--> -c '$SERVER_HOME/runServer $LD_LIBRARY_PATH "$JAVA_DIR/bin/java Server <!--|DB_NAME|--> <!--|JAVA_SERVER_PORT|-->"' >> Server.out 2>&1 &
	else 
	    $SERVER_HOME/runServer $LD_LIBRARY_PATH "$JAVA_DIR/bin/java Server <!--|DB_NAME|--> <!--|JAVA_SERVER_PORT|-->" >> Server.out 2>&1 &
	fi
	;;

    'stop')
	kill -9 `cat javaServerPid`
	;;

    *)
	echo "usage: $0 {start|stop}" >> <!--|JAVASERVER_PATH|-->/Server.out
 	;;
esac
