#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Publication related APP pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/pubbrowser

SUBDIRS = EDITpubs

GENERICS = REFERinfo.apg enterpubs.apg link_authors.apg link_authors_update.apg \
	pubprintable.apg pubselect2.apg pubview2.apg \
	showpubs.apg miniref_display.apg curate_ortho_select.apg pubcuration.apg \
	pubtopic_close.apg pubtopic_open.apg pubtopic_unclaim.apg pubtopic_found.apg \
	pubtopic_reassign.apg pnote_new.apg pnote_editor.apg notif_frame.apg \
	notif_content.apg journalselect.apg journalview.apg journalupdate.apg pubacknowledgement.apg \
	js-delete_attrib.apg pub_rowdisplay.apg citselectlist.apg citfish.apg \
	citjtypeoption.apg citlink.apg citgeneric.apg cittotalcount.apg \
	externalredirect.apg  externallink.apg insertelsevierstat.apg  \
	pubmedredirect.apg pubmedlink.apg 


# use default rules for app page directories.

include $(TOP)/make.default.apg.rules

