#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Publication related APP pages.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/pubbrowser

SUBDIRS = EDITpubs inc_MEDLINE

GENERICS = REFERinfo.apg curatepub.apg enterpubs.apg link_authors.apg \
	pubprintable.apg pubselect2.apg pubview2.apg \
	showpubs.apg


# use default rules for app page directories.

include $(TOP)/make.default.apg.rules

