#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Publication related APP pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/pubbrowser

SUBDIRS = EDITpubs

GENERICS = notif_frame.apg pnote_editor.apg pubacknowledgement.apg \
	pubcuration.apg pubview2.apg showpubs.apg showsnppubs.apg

STATICS = citlink.apg curate_ortho_select.apg enterpubs.apg journalselect.apg \
	journalupdate.apg journalview.apg js-delete_attrib.apg link_authors.apg \
	miniref_display.apg notif_content.apg pub_rowdisplay.apg REFERinfo.apg \
	pubprintable.apg pubtopic_close.apg pubtopic_open.apg pubtopic_unclaim.apg \
	pubtopic_found.apg pubtopic_reassign.apg pnote_new.apg link_authors_update.apg \
	citselectlist.apg citfish.apg externallink.apg pubmedlink.apg citjtypeoption.apg \
	citgeneric.apg cittotalcount.apg 

# use default rules for app page directories.

include $(TOP)/make.default.apg.rules

