<%@ include file="/WEB-INF/jsp-include/tag-import.jsp" %>
<z:page title="ZFIN Hatching Stages">
<div><table align="center" bgcolor="#ffcccc" width="50%"> <tr><td class="small"> This material is from the 4th edition of The Zebrafish Book.  The 5th edition is available <a href="http://zebrafish.org/zirc/orders/buyBookQ.php?item=Book&id=book&detail=The%20Zebrafish%20Book">in print</a> and within the <a href="https://wiki.zfin.org/display/prot/ZFIN+Protocol+Wiki">ZFIN Protocol Wiki</a>.  </td></tr> <table>
<h3>Stages During the Hatching Period</h3>
<p><i>Modified from: 
<a href="stages.html">Kimmel et al., 1995. 
Developmental Dynamics 203:253-310</a>. Copyright &#169; 1995 Wiley-Liss, Inc.
Reprinted only by permission of Wiley-Liss, a subsidiary of John Wiley &
Sons, Inc.
</i>
</p><p>
<a name="Long-pec"><b>Long-pec stage (48 h)</b>:</a>
EL = 3.1 mm, HTA = 45 degrees, OVL = 1/2.  The OVL changes only little hereafter, so this value of 1/2 is a good initial indication that the embryo has reached some stage during the hatching period, vs. some earlier stage.  	</p><p>
As the stage name indicates, the pectoral fin buds now are quite elongated, stretching to a height-to-width ratio of about 2 <a href="figs/fig37.html">(Fig. 37C)</a>.  The buds curve posteriorly and have a prominently pointed shape, with the apical ectodermal ridge at the point. They still do not look fin-like, and the apical ridge is yet more prominent than earlier, its expansion accounting for a considerable portion of the lengthening of the bud.  More proximally, the central region of the bud forms forms a compact mesenchymal condensation, visible in <a href="figs/fig37.html">Fig. 37C</a>, that heralds development of the supportive girdle of the fin.  Here, the first cartilage in the embryo begins to differentiate morphologically at this stage, and with Nomarski optics the chondrocytes may be recognized by their cobblestone arrangement and bright appearance.	</p><p>
Because of both yolk depletion and growth of the head, now, as viewed from the side, the yolk ball approximately equals the volume of the head.  However, in a dorsal view the yolk ball is slightly wider than the head; the widths become about equal at 51 h.  The yolk extension has a taper along nearly its whole length, giving it a shallow conical rather than a cylindrical shape.  	</p><p>
The olfactory placodes are at the anterior borders of the eyes, and Nomarski reveals they have beating cilia.  Morphogenesis in the dorsal part of the otic vesicle produces the rudiments of the semicircular canals.  Hair cells have differentiated in the sensory maculae of the otic vesicle, and neuromasts, complete with protruding sensory hairs, have differentiated in the head (a prominent one is positioned between the ear and the eye), and along the posterior lateral line.  The notochord has vacuolated differentiating cells to its caudal tip.  With some difficulty one can visualize early precartilage condensations in the developing mandibular and hyoid arches, but not in the branchial arches. 	</p><p>
The dorsal stripe of melanophores is now very well defined and densely populated, present along the midline of the anterior trunk and tail, but as bilateral rows of cells in the posterior trunk.  In the head the dorsal stripe also avoids the midline, where over the brain a dorsal view reveals that it takes the form of an open posteriorly pointing V.  A side view reveals that the dorsal and ventral stripes join together at the tail tip into another posterior-pointing V that is rather completely filled with pigment, save for a small ventral gap.  Further, a second component of the ventral stripe now forms in the tail medially to the earlier stripe, and associated with the caudal (and the axial) vein.  At this stage melanophores only sparsely populate this median ventral stripe, but by the early larval period the two parts of the ventral stripe will neatly frame the vein.  Over the yolk ball, the bilateral ventral melanophore rows join in the midline as a distinctive patch at the location of the developing swim bladder.  The lateral stripe along the horizontal myoseptum is now quite clear, and contains a small and variable number of melanophores (as described in detail by Milos and Dingle, 1978).  Xanthophore differentiation gives the head a very distinct but still very pale yellow cast <a href="figs/fig39.html">(Fig. 39A)</a>.  The dorsal aspect of the trunk and tail is a fainter yellow.  The iridophores are scattered over the retina, as earlier, but now many more appear, some arranged in a discontinuous ring of individual cells or small reflective cell groups around the lens, where the iris will develop.  Most long-pec embryos have other iridophores associated with the dorsal stripe in the tail, and occasional feebly reflective ones that appear on the dorsolateral yolk sac.  These foreshadow development of distinctive iridophore patches ("lateral patches") that flank the position where the swim bladder forms. 	</p><p>
The shrinking yolk sac makes the pericardial cavity conspicuous.  The vigorous beat of the heart easily shows that the heart tube is bending to bring the atrium to a position dorsal to the ventricle.  Nomarski optics reveal that the definitive six pairs of aortic arches are now all present, but typically at the long-pec stage not all of them are carrying circulating blood.  Generally, the more anterior arches, especially aortic arches 1-3, join the circulation earlier, but participation varies.  Circulation is now strong in most segmental vessels along the trunk and tail.  There is a single channel associated with each segment, but, as can be determined by following the course of the blood flow, an artery in one segment leading from the dorsal aorta alternates with veins in the adjacent segments leading to the axial vein.  There is no blood circulation in the pectoral fin bud until about 52 h, more consistently at 54 h.  At this point one can find the <b>subclavian</b> vessel looping around the bud at the base of the ridge, and without a clear distinction between the arterial and venous side of the loop.  The common cardinal vein on the yolk ball is fan-shaped, narrower at its origin and broadening more ventrally.	</p><p>
When at rest, dechorionated embryos are beginning to assume a dorsal-up body position.  Some come to rest dorsal-up upon completion of a swimming episode.

</p><p>
<a name="Pec-fin"><b>Pec-fin stage (60 h)</b>:</a>
EL = 3.3 mm, HTA = 55 degrees.  The pectoral fin now has a flat flange or blade.  The blade is confined to the distal part, where the ridge was earlier, and now it makes the distal part of the rudiment considerably wider than the base, opposite to the situation at the long-pec stage.  The fin is held back along the side of the body, and extends posteriorly to cover more than half of the yolk ball. <b> </b>Nomarski optics reveals the presence of actinotrichia in the pectoral fin, as well as continued differentiation of cartilage in the proximal part of the rudiment.  	</p><p>
A dorsal view reveals that the width of the head at the eyes, but not the ears, now exceeds the width of the yolk ball.  The taper of the yolk extension is more prominent and meets the yolk ball without a sharp angle being present where the two regions of the yolk cell join, such as was present at earlier times.	</p><p>
A ventral view shows that the mouth is open to the exterior <a href="figs/fig40.html">(Fig. 40)</a>, but not gaping.  It lies entirely behind the anterior limit of the eye at this stage.  Precartilage condensations are distinctive in the mandibular and hyoid arches, and short stretches of differentiating cartilage cells can be identified in these arches as well, particularly in Meckel's cartilage and the ceratohyal cartilage.  Jaws muscles are also differentiating.  The earliest mesenchymal precartilage condensations now appear in the first one or two branchial arches (pharyngeal arches 3 and 4), but probably distinctive cartilage cells are not yet present in this region.  The rudiments of the gill filaments now appear as shallow buds along the posterior surfaces of the anterior gill arches.	</p><p>
A partition is forming in the otic vesicle that will separate two otolith-containing chambers, ventral to the more well-formed semicircular canals.  In a side view with the dissecting microscope the gut tract can now be visualized along part, but typically not all, of its length. A lumen appears within the hindgut. 	</p><p>
Pigmentation of the retina is now so dense that, using transmitted illumination, its opacity nearly hides the lens.  Iridophores in the eye fill out a rather complete brightly reflective ring around the lens (e.g. <a href="figs/fig39.html">Fig. 39G</a>).  Other reflective regions occur outside of the ring, mostly as contiguous patches of cells rather than as scattered individual cells.  	</p><p>
On the trunk and tail, up to about ten melanophores occupy each lateral stripe <a href="figs/fig39.html">(Fig. 39C)</a>.  Where the dorsal stripe is bilateral, in the posterior trunk and anterior tail, the melanophores now neatly flank reflective iridophores present in the midline.  Bilateral patches of reflectivity, the <b>lateral patches</b>, also have formed on the dorsal yolk sac, just to either side of the median black patch marking the location of the developing swim bladder.  A few scattered iridophores appear elsewhere on the yolk sac, but only variably in a distinctive ventral median row that accompanies the melanophore <b>yolk stripe</b> at the same location.  Xanthophore development continues, producing a rich yellow color on the head, and a still somewhat paler yellow cast to the dorsal trunk and tail  <a href="figs/fig39.html">(Fig. 39C)</a>.	</p><p>
The heart is prominent, beating strongly, and full of circulating blood.  Blood flows in all of the aortic arches and through the subclavian loop.  The common cardinal vein no longer has a fan-shape, but remains narrow along its length, as it takes a direct course, anterior to most of the yolk, towards the heart.	</p><p>
Most dechorionated embryos now rest in a dorsal-up attitude and nearly always finish a bout of swimming in this attitude.  The contractions during the escape response occur so rapidly that one cannot resolve them by eye.


</p><hr>
<a href="index.html">Return to Developmental Stages Contents</a>
<script>
  if (window.name=='popup'){
    call_close();
  }
</script>
<p>
</p></table></table></div>
</z:page>
