<%@ include file="/WEB-INF/jsp-include/tag-import.jsp" %>
<z:page title="ZFIN Segmentation Stages">
<div><table align="center" bgcolor="#ffcccc" width="50%"> <tr><td class="small"> This material is from the 4th edition of The Zebrafish Book.  The 5th edition is available <a href="http://zebrafish.org/zirc/orders/buyBookQ.php?item=Book&id=book&detail=The%20Zebrafish%20Book">in print</a> and within the <a href="https://wiki.zfin.org/display/prot/ZFIN+Protocol+Wiki">ZFIN Protocol Wiki</a>.  </td></tr> <table>
<h3>Stages During the Segmentation Period</h3>
<p><i>Modified from: 
<a href="stages.html">Kimmel et al., 1995. 
Developmental Dynamics 203:253-310</a>. Copyright &#169; 1995 Wiley-Liss, Inc.
Reprinted only by permission of Wiley-Liss, a subsidiary of John Wiley &
Sons, Inc.
</i>
</p><p>
<a name="1-somite"><b>1-4 somites stage (10 1/3 h)</b>:</a>
The first somitic furrow forms, usually, but not invariably, after both completion of epiboly and the initial appearance of the tail bud <a href="figs/fig15.html">(Fig. 15A)</a>.  This furrow marks the boundary between what will become the first and second somites.  Viewing the embryo along the axis from the anterior pole reveals the now very prominent polster deep to the neural plate <a href="figs/fig15.html">(Fig. 15C, arrow)</a>.

</p><p>
<a name="5-somite"><b>5-9 somites stage (11 2/3 h)</b>:</a>
The first 5-6 somites appear at the rate of about 3 per hour.  The length of the embryo is about 0.8 mm, the same as the zygote.	</p><p>
The brain primordium has now distinctively thickened into the neural keel <a href="figs/fig15.html">(Fig. 15E, F)</a>, and beginning at the 4- or 5-somite stage one can first distinguish the <b>optic primordium</b> from a side view (<a href="figs/fig15.html">Fig. 15D</a> and <a href="figs/fig24.html">Fig. 24</a>) or a dorsal view.  In the trunk the neural plate is still present, and sections reveal that it has three pronounced thickenings at this stage, a bilateral pair flanking a median one.  Neural keel formation occurs in the anterior trunk between the 6- and 10-somite stages (Schmitz et al., 1993).	<b></b></p><p>
Kupffer's vesicle makes its appearance deep to the tail bud (<a href="figs/fig15.html">Fig. 15F</a>, arrow; <a href="figs/fig28.html">Fig. 28B</a>)  This structure, found only in teleost embryos, is transient, and its significance has been debated in the older literature.  Kupffer, who discovered it, thought it might be an allantoic rudiment (see Brummett and Dumont, 1978).  Recent fate mapping studies show that the epithelial cells lining the vesicle will later form tail mesodermal derivatives, including notochord and muscle (Melby et al, 1993).		</p><p>

By the 8-somite stage Nomarski optics reveal the early rudiment of the pronephros, and migration of cephalic neural crest cells.

</p><p>
<a name="14-somite"><b>14-19 somites stage (16 h)</b>:</a>
Extension of the tail rudiment barely begins to elongate the embryo (<a href="figs/fig15.html">Fig. 15H, 15I</a>, <a href="figs/fig16.html">Fig. 16</a>); its length (EL) is about 0.9 mm.  The small trigeminal placode <a href="figs/fig26.html">(Fig. 26A)</a> and more distinctive <b>otic placode</b> <a href="figs/fig27.html">(Fig. 27A)</a> are present beside the hindbrain rudiment, the latter about midway between the optic vesicle and the first somite.  One can readily distinguish four prominent subdivisions of the brain, the telencephalon, diencephalon, midbrain and hindbrain.  The fourth ventricle barely begins to inflate the dorsal hindbrain, and five rhombomeres, r2-r6, become visible in a dorsolateral view <a href="figs/fig25.html">(Fig. 25)</a>.  Rhombomere r5 lies deep to otic placodes.  In the trunk the neural keel rounds into the neural rod, still without a cavity, but now overridden by adjacent epidermis (Papan and Campos-Ortega, 1994).  Neural crest migration is underway in both the head (<a href="figs/fig26.html">Fig. 26</a>; Schilling and Kimmel, 1994) and the trunk (Raible et al., 1992; Raible and Eisen, 1994).  	</p><p>
Somites now form at a rate of about 2 per hour <a href="figs/fig28.html">(Fig. 18)</a>, and older ones begin to develop the myotomes.  They take on the V-shaped appearance that indicates the future division of the myotomes into the dorsal (epaxial) and ventral (hypaxial) muscle masses <a href="figs/fig17.html">(Fig. 17C)</a>.  In the center of the anterior myotomes a view with polarized light reveals early birefringence, due to myofibrillar development, of 2-6 elongated differentiating muscle pioneer cells (Felsenfeld et al., 1991).  	</p><p>
The notochord becomes more distinguishable from the ventral part of the neural keel, as can be appreciated in a dissecting microscope view along the axis.  With Nomarski optics one can see that the notochord cells show a characteristic 'stack-of-pennies' appearance (<a href="figs/fig21.html">Fig. 21</a>, also see <a href="figs/fig28.html">Fig. 28C</a> for the tail tip at a later developmental stage).	</p><p>
 A characteristic constriction that is important for staging appears in the posterior region of the yolk, where the tail bud ends, and gives the yolk a kidney-bean shape <a href="figs/fig15.html">(Fig. 15H)</a>.  The constriction rapidly becomes more prominent <a href="figs/fig15.html">(Fig. 15J)</a> and squeezes progressively more anteriorwards <a href="figs/fig15.html">(Fig. 15L)</a>. The constricted region develops into the thinner and cylindrically-shaped posterior elongation of the yolk sac, the <b>yolk extension</b> (Milos and Dingle, 1978).  The shape of the yolk extension will continue to distinguish it from the anterior region, the <b>yolk ball</b>. 	</p><p>
The tail bud now begins to protrude away from the body of the embryo, and Kupffer's vesicle is a prominent feature at its base (<a href="figs/fig15.html">Figs. 15 H, J (arrow), K</a>, <a href="figs/fig28.html">Fig. 28B</a>).

</p><p>
<a name="20-somite"><b>20-25 somites stage (19 h)</b>:</a><a>
Morphogenesis associated with the constriction of the yolk begins to straighten out the posterior trunk, and this, along with continued development of the tail, produces a marked increase in the length of the embryo to an EL of 1.4 mm </a><a href="figs/fig15.html">(Fig. 15 M)</a>.  The length of the yolk extension is now more than half the diameter of the yolk ball.  The lens placode appears and the otic placode hollows into the <b>otic vesicle</b> (<a href="figs/fig15.html">Fig. 15</a>M (arrow), <a href="figs/fig25.html">Fig. 25</a>, and <a href="figs/fig27.html">Fig. 27B</a>) which contains two otoliths that are so tiny at this time it requires Nomarski optics to see them <a href="figs/fig25.html">(Fig. 25)</a>.  The brain now also becomes a hollow structure, with ventricles present along its length, and with Nomarski optics one can first recognize the rudiment of the cerebellum.  Seven rhombomeres are much more prominent in some embryos than others (compare <a href="figs/fig25.html">Fig. 25</a> with <a href="figs/fig30.html">Fig. 30A</a>, below).  Hollowing from the neural rod into the neural tube is also now nearly complete throughout the length of the trunk.  The primordium of the postotic or posterior lateral line resides as an ectodermal placode between the otic vesicle and the first somite.  A substantial part of the primordium will soon begin to migrate posteriorly, and will be important for staging, as we describe below.  Neurons, including spinal primary motoneurons, trigeminal ganglion neurons <a href="figs/fig26.html">(Fig. 26B)</a>, and Rohon-Beard neurons, have growing axons.	</p><p>
Nearly all of the trunk somites now exhibit the myotomal chevron shape, and the trunk myotomes produce weak <b>muscular contractions</b>.  Nomarski reveals that anterior muscle pioneers have cross-striations.  The first contractions, occurring at the 17-somite stage, involve individual (unilateral) myotomes, and, as mentioned earlier, are correlated with the ingrowth of axons from first developing primary motoneurons (Hanneman and Westerfield, 1989).  Progressively the contractions begin to involve series of myotomes and become stronger, more coordinated, and more frequent.  	</p><p>
Anterior notochord cells have vacuoles <a href="figs/fig21.html">(Fig. 21)</a>.  The pronephric duct extends through the whole length of the trunk and curves ventrally around the yolk extension, showing where the anus will eventually develop in the ventral midline at the level of somite 17, and serving to define the boundary between the trunk and tail.  (Later, due to morphogenetic rearrangements, the position of the anus shifts to the level of somite 15).  	</p><p>
Just posterior and dorsal to the end of the pronephric duct  in the ventral tail rudiment, mesenchyme accumulates in a so-called intermediate mass of mesoderm, the early forerunner of the hematopoietic blood island (<a href="figs/fig17.html">Fig. 17D</a>, and <a href="figs/fig20.html">Fig. 20A</a>).

</p><p>
<a name="26-somite"><b>26+ somites stage (22 h)</b>:</a>
EL = 1.6 mm.  Straightening of the posterior trunk is nearly complete, but the elongating tail still curves ventrally <a href="figs/fig20.html">(Fig. 15 N, O)</a>.  The yolk extension is now nearly the length of the yolk ball.  The cerebellar primordium is prominent, and one can recognize the rudiments of both the epiphysis and hypothalamus in the diencephalon <a href="figs/fig23.html">(Fig. 23C)</a>.  The olfactory placodes thicken anterior and dorsal to the forebrain, and one can now easily see the two otoliths in each otic vesicle with just the dissecting microscope.  With Nomarski optics the early posteriorwards migration of the posterior lateral line primordium is evident; the advancing tip of the primordium is located over the third somite (hence, as will be explained below, we might call this stage the prim-3 stage).  	</p><p>
The last somites of the series form more slowly than the others (not shown in the idealized curve of <a href="figs/fig18.html">Fig. 18</a>), and the total number that eventually forms is variable, from 30 to 34 pairs.  The blood island is now a distinctive nest of dividing and differentiating blood cells.  The rudiment of the unpaired median finfold appears in the dorsal midline, along the length of the tail <a href="figs/fig28.html">(Fig. 28C)</a>, sometimes at 22 h, but more frequently at 23 h (28-somite stage).  	</p><p>
The spontaneous myotomal contractions now produce a lashing from side to side, and their frequency increases transiently upon dechorionation.
</p><hr>
<a href="index.html">Return to Developmental Stages Contents</a>
<script>
  if (window.name=='popup'){
    call_close();
  }
</script>
</table></table></div>
</z:page>
