<%@ include file="/WEB-INF/jsp-include/tag-import.jsp" %>
<z:page title="ZFIN Pharyngula Period Description">
<div><table align="center" bgcolor="#ffcccc" width="50%"> <tr><td class="small"> This material is from the 4th edition of The Zebrafish Book.  The 5th edition is available <a href="http://zebrafish.org/zirc/orders/buyBookQ.php?item=Book&id=book&detail=The%20Zebrafish%20Book">in print</a> and within the <a href="https://wiki.zfin.org/display/prot/ZFIN+Protocol+Wiki">ZFIN Protocol Wiki</a>.  </td></tr> <table>
<h3>PHARYNGULA PERIOD  (24-48 h)</h3>
<p><i>Modified from: 
<a href="stages.html">Kimmel et al., 1995. 
Developmental Dynamics 203:253-310</a>. Copyright &#169; 1995 Wiley-Liss, Inc.
Reprinted only by permission of Wiley-Liss, a subsidiary of John Wiley &
Sons, Inc.
</i>
</p><p>
Ballard (1981) coined the term "pharyngula" to refer to the embryo that has developed to the phyolotypic stage, when it posesses the classic vertebrate bauplan.   According to von Baer's famous laws (discussed by Gould, 1977) this is the time of development when one can most readily compare the morphologies of embryos of diverse vertebrates, and for the zebrafish we approximate the period as the second of the three days of embryonic development <a href="figs/fig29.html">(Fig. 29)</a>.  The embryo is most evidently now a bilaterally organized creature, entering the pharyngula period with a well-developed notochord, and a newly-completed set of somites that extend to the end of a long post-anal tail.  The nervous system is hollow and expanded anteriorly.  With the rapid cerebellar morphogenesis of the metencephalon <a href="figs/fig30.html">(Fig. 30A)</a><b>,</b> just preceding the pharyngula period, the brain is now sculptured into 5 lobes <a href="figs/fig23.html">(Fig. 23C)</a>.		</p><p>

The period name focuses attention on the primordia of the pharyngeal arches, present but at early times difficult to distinguish individually.  The pharyngeal arches develop rapidly during this second day from a primordial region that can be visualized ventral to, and about twice as long as the otic vesicle <a href="figs/fig31.html">(Fig. 31)</a>.  Seven pharyngeal arches in all develop from this primordium, a prominent boundary within it (arrow in <a href="figs/fig31.html">Fig. 31</a>) occurring between pharyngeal arches 2 and 3.  This boundary is important, for later the arches anterior to it (the mandibular and hyoid arches) form the jaws and the operculum, and arches (branchial arches) posterior to it will form the gills. 		</p><p>

The cells of the hatching gland, with their brightly refractile cytoplasmic granules, are prominent features of the pericardial region throughout the pharyngula period <a href="figs/fig32.html">(Fig. 32)</a>. 		</p><p>

During the first few hours of the pharyngula period the embryo continues the rapid lengthening that started at 15 h, but then the rate of lengthening abruptly decreases.  The time of the change, at 31-32 h, correlates approximately with the end of the rapid morphogenetic straightening of the tail, discussed above.  The new rate of lengthening is maintained throughout the rest of embryogenesis <a href="figs/fig16.html">(Fig. 16)</a>.</p><p>
 	The head also straightens out.  It lifts dorsalwards fairly rapidly during the pharyngula period and then more slowly, and one can use this change to quickly determine the approximate stage of the embryo <a href="figs/fig33.html">(Fig. 33)</a>.  We imagine two lines from a side view:  One, a line through the middle of the ear and eye, is the head axis. The other, along the notochord, and parallel to the horizontal myosepta at about somites 5-10, is the trunk axis.  A way to estimate the angle between the two lines, the <b>head-trunk angle (HTA)</b>, is to position the embryo in its dish with its tail pointing towards the observor, and mentally superimpose a clock face upon it.  One of the hands of the clock, the trunk axis, points towards 6 o'clock.  The position of the other hand, the head axis, changes with developmental time as as shown in <a href="figs/fig33.html">Fig. 33</a>.		</p><p>

The morphogenesis accompanying head-straightening dramatically shortens the head, in absolute terms, making it more compact along the anterior-posterior axis.  As can be seen from <a href="figs/fig1.html">Fig. 1</a>, the rudiments of the eye and the ear approach one another rapidly, thus providing a second new staging index.  Simply estimate the number of additional otic vesicles that could fit between the eye and the otic vesicle.  We term this number "<b>otic vesicle length (OVL)</b>".  It decreases from about 5 at the beginning of the pharyngula period to less than 1 at the end.	</p><p>
During most of the period, until about 40 h, the most precise staging method, and the most difficult, depends on using Nomarski optics to locate the leading tip of the migrating portion of the posterior lateral line primordium, as it moves steadily along the length of the trunk and tail <a href="figs/fig34.html">(Fig. 34A)</a>.  It leaves behind cells that form the ganglion of the lateral nerve, and as it moves it deposits cells that form the neuromasts along the nerve.  The primordium migrates in the skin, superficially to the horizontal myoseptum <a href="figs/fig34.html">(Fig. 34B)</a>, on each side of the body, at an approximately linear rate of 100 &#181;m/hour (Metcalfe, 1985), or 1.7 myotomes/hour.  Determine which myotome, from 1-30, the advancing  (posterior) tip of the primordium overlies.  We define <b>primordium ("prim") stages</b> by this index <a href="figs/fig35.html">(Fig. 35)</a>.  The method is tedious, and the migrations of the primordia on both sides of a single embryo are not always synchronous.  After 40 h the primordium is far posterior, small, and indistinct.		</p><p>

In addition to these general features, and novel ones that characterize particular stages, there are several important developments during the pharyngula period that we now outline below, and then, following the same order of presentation and setting each topic off into a paragraph of its own, we add details in the stage descriptions.	</p><p>
The fins begin to form. The median fin fold, barely present at the onset of the period, becomes prominent, and forms collagenous strengthening fin rays, or actinotrichia <a href="figs/fig28.html">(Fig. 28D)</a>.  The rudiments of the bilaterally paired pectoral fins begin their morphogenesis:  Mesenchymal cells gather together to form fin buds that serve as probably the single-most useful staging feature during the second half of the pharyngula period (<a href="figs/fig36.html">Fig. 36</a>, and <a href="figs/fig37.html">Fig. 37</a>).  As the buds develop, an apical ectodermal ridge becomes prominent at their tips.  Whether the ridge plays a morphogenetic role similar to that of the limb bud of tetrapods is unknown, but a hint that it might do so comes from the fact that it is positioned at the exact boundary of the ventrally located expression domain of the <i>engrailed1 </i>gene (Hatta et al., 1991a; Ekker et al., 1992).  A most significant connection between the zebrafish fin bud and the tetrapod limb bud is the domain posterior mesenchymal domain of <i>sonic hedgehog</i> gene expression in both, corresponding to the zone of polarizing activity (ZPA; see Krauss et al., 1993). 		</p><p>

Pigment cells differentiate.  They are easy to see and we use them for staging landmarks. The pigmented retinal epithelium, and the neural crest-derived melanophores begin to differentiate at the onset of the period, and pigmentation gets rather far along during the period <a href="figs/fig29.html">(see Fig. 29)</a>.  The melanophores begin to arrange themselves in a characteristic pattern that includes a well-defined set of longitudinal body-stripes (Milos and Dingle, 1978).	</p><p>
The circulatory system forms (Reib, 1973).  The heart begins to beat just at the onset of the period, and forms well delineated chambers.  Blood begins to circulate though a closed set of channels.  A bilateral pair of aortic arches appears just at the outset of the pharyngula period, this is aortic arch #1, the earliest and most anterior arch of the eventual serial set of six.  The others develop rapidly near the end of the period.  The blood flows into each side of the head from the anterior two arches via the carotid artery and returns via the anterior cardinal veins.  The more posterior aortic arches (arches #3-6) also connect to the left and right radices (roots) of the dorsal aortae, which anastomose in the trunk to form an unpaired midline vessel lying just ventral to the notochord.  The dorsal aorta is renamed the caudal artery as it enters the tail (Reib, 1973).  At a point along the tail the channel makes a smooth ventrally directed 180 degree turn to form the caudal vein, returning the blood to the trunk.  The vein continues in the posterior trunk as the unpaired median axial vein, lying just ventral to the dorsal aorta.  Just posterior to the heart, the vein then splits into the paired left and right posterior cardinal veins.  In turn, each posterior cardinal joins with the anterior cardinal to form the common cardinal vein (or duct of Cuvier) that leads directly to the heart's sinus venous.  The name sometimes used for the common cardinal as it crosses the yolk sac, the vitelline vein, is not very appropriate, because the vessels named vitelline veins in other fish have different connections (see Reib, 1973).  The common cardinal veins, at first very broad and not very well-defined, carry the blood ventrally across the yolk. As development continues the common cardinals become narrower channels, and relocate to the anterior side of the yolk.  	</p><p>
Finally, there is marked behavioral development.  Tactile sensitivity appears, and the flexions that occurred in uncoordinated individual myotomes during the late segmentation period become orchestrated into rhythmic bouts of swimming.</p><p>
<a href="phar_stgs.html">Detailed description of Pharyngula stages.</a>
</p><hr>
<a href="index.html">Return to Developmental Stages Contents</a>
<script>
  if (window.name=='popup'){
    call_close();
  }
</script>
<p>
</p></table></table></div>
</z:page>
