#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Marker app pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#
# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/marker_files

GENERICS = clonebox.apg crossview.apg curatornote.apg dnote_editor.apg \
	geneprddescription.apg gomodify.apg mappingdetail.apg markergoentry.apg \
	markergoview.apg markerselect.apg markerview.apg mrkrgenolist.apg \
	msegselect.apg newmrkrselect.apg nomeneditor.apg nomenview.apg refcrosslist.apg \
	scoresview.apg sequence.apg sequence_data_entry.apg snpview.apg wtanatlist.apg

STATICS =  dnote_new.apg goinferenceentry.apg do-oevdispupdate.apg showscores.apg \
	sequence_disclaimer.apg markerview_placeholder_note.apg snp_note.apg snpids.apg \
	snp_batch.apg marker_history_correction.apg attrib_check.apg sequence_tools.apg \
	markerrelationship.apg  markerrel_onetype.apg markerview_transcript_details.apg \
	chromoscripts.apg  cloneorderlink.apg do-goedit.apg do-markergoupdate.apg \
	do-markerupdate.apg gonotes.apg make_map.apg mapframe.apg markergovalidate.apg \
	markerupdate.apg orthoedit.apg ortholist.apg orthoview.apg orthoviewbrief.apg \
	orthoviewdetailed.apg scoresframe.apg searchform.apg snpdetails.apg 


# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules
