#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Marker app pages.
#
# $Source$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/marker_files

GENERICS = chromoscripts.apg crossview.apg do-markerupdate.apg \
	lgframe.apg make_map.apg mapframe.apg mapperselect.apg \
	mapview.apg markerselect.apg markerupdate.apg \
	markerview.apg orthoedit.apg refcrosslist.apg \
	scoresframe.apg scoresview.apg showscores.apg \
	mappingdetail.apg blastdata.apg genbank.apg \
	orthoview.apg ortholist.apg


# Use default rules for app page directories.

include $(TOP)/make.default.apg.rules

