-- Incrementally apply the freshly-recomputed *_temp tables onto the live
-- phenotype mart tables. The logic lives in the regen_phenotype_mart() plpgsql
-- function (lib/DB_functions/regen_phenotype_mart.sql) -- it matches on natural
-- keys so existing rows keep their bigint pg_id / psg_id, takes no
-- AccessExclusiveLock and no table swap (only row locks on the rows that
-- change), and RAISE NOTICEs the per-table insert/update/delete counts (which
-- regenPhenotypeMart.sh tees to the console).
--
-- runPhenotypeMart.sh does not wrap this file in begin/commit; the single
-- statement below is its own transaction, so the whole apply is atomic.
SELECT regen_phenotype_mart();
