#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Papers and other documents 
# describing the ZFIN Database.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/dbase/PAPERS

SUBDIRS = WWW6 Web97 Webnet97 ZFIN_DataModel sdb

# The only thing of value in this directory is the subdirectories.  The
# chi97_nav_workshop.html file is historic and not linked by anyone.



# ---------------  Production Rules  ------------------------------------


# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
