#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Papers and other documents 
# describing the ZFIN Database.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/dbase/PAPERS

SUBDIRS =  WWW6 Web97 Webnet97 sdb

# The chi97_nav_workshop.html file is historic and not linked by anyone.

STATICS = Doerry97a.pdf Doerry97b.pdf Doerry97c.pdf Sprague.pdf \
          Westerfield97.pdf



# ---------------  Production Rules  ------------------------------------


# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
