#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Zebrafish Book, low resolution 
# sketches of various stages.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/zfbook/stages/figs/low_res_sketches

STATICS = 0.2h.gif 0.75h.gif 1.0h.gif 1.25h.gif 1.5h.gif 1.75h.gif 10h.gif \
	11h.gif 12h.gif 14h.gif 160h.gif 16h.gif 18h.gif 19.5h.gif 2.0h.gif \
	2.25h.gif 2.5h.gif 2.75h.gif 22h.gif 25h.gif 3.0h.gif 3.3h.gif \
	3.7h.gif 31h.gif 35h.gif 4.0h.gif 4.3h.gif 4.7h.gif 42h.gif 48h.gif \
	5.3h.gif 5.7h.gif 60h.gif 6h.gif 72h.gif 8h.gif 9h.gif  


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
