#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, ZFIN Admin APP pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/ZFINadmn

SUBDIRS = DELETErecords

GENERICS = 

STATICS = do_direct.apg classify_pubs.apg mkdist_list.apg mkdist_list_usa.apg \
	mkdist_list_PI.apg mkmailmerge.apg

# Use default make rules for app page directories.

include $(TOP)/make.default.apg.rules

