#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Anatomy-72 hours Static web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/anatomy/72hrs

# All of the generics can be moved back under statics after the intial load.

STATICS = 72hrs.html S039.html S040.html S041.html S042.html S043.html \
	S044.html S045.html S046.html S047.html S048.html S049.html S050.html \
	S051.html S052.html S053.html S054.html S055.html S056.html S057.html
#GENERICS = 



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
