#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Anatomical disctionary browser Applet.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# This makefile has two target dirs.  The first is actually a staging dir
# where the work is done.  The second is the final target dir where the
# JAR gets put.

# ---------------  Variable Definitions  --------------------------------
ANT = /usr/local/apps/ant/bin/ant

default:  
	$(ANT) deploy

clean:
	$(ANT) clean

clobber:
	$(ANT) clean



