#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Database desciption Static web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/dbase

SUBDIRS = PAPERS

GENERICS = aim1.html aim2.html aims.html arch.html bib.html cont.html \
	cost.html data.html db.html imp1.html imp2.html mtgprop.html \
	mtgsum.html prob.html sig.html sum.html zfin-job1.html zfin-job2.html

STATICS = fig1.gif fig2.gif fig3.gif fig4.gif fig4a.gif fig4b.gif fig5.gif \
	fig6.gif fig7.gif fish_bgd.gif fish_net.gif zfin.gif


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
