#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Catch of the day Static web pages
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/catch

GENERICS = MCF_8_99.html RFA.html catch.html feb99.html fishman.html nih.html \
	oct98.html resources.html talbot.html zon.html BAC_library.html zebrafish_programs.html

STATICS = bkgrd.jpeg catch.gif fish.gif zfin.gif Zebrafish_disease_project.pdf



# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules

