#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, High resolution Anatomy Static 
# web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/anatomy/highres

STATICS = S001.jpeg S002.jpeg S003.jpeg S004.jpeg S005.jpeg S006.jpeg \
	S007.jpeg S008.jpeg S009.jpeg S010.jpeg S011.jpeg S012.jpeg S013.jpeg \
	S014.jpeg S015.jpeg S016.jpeg S017.jpeg S018.jpeg S019.jpeg S020.jpeg \
	S021.jpeg S022.jpeg S023.jpeg S024.jpeg S025.jpeg S026.jpeg S027.jpeg \
	S028.jpeg S029.jpeg S030.jpeg S031.jpeg S032.jpeg S033.jpeg S034.jpeg \
	S035.jpeg S036.jpeg S037.jpeg S038.jpeg S039.jpeg S040.jpeg S041.jpeg \
	S042.jpeg S043.jpeg S044.jpeg S045.jpeg S046.jpeg S047.jpeg S048.jpeg \
	S049.jpeg S050.jpeg S051.jpeg S052.jpeg S053.jpeg S054.jpeg S055.jpeg \
	S056.jpeg S057.jpeg S058.jpeg S059.jpeg S059_5.jpeg S060.jpeg \
	S061.jpeg S062.jpeg S063.jpeg S064.jpeg S065.jpeg S066.jpeg S067.jpeg \
	S068.jpeg S069.jpeg S070.jpeg S071.jpeg S072.jpeg S073.jpeg S074.jpeg \
	S075.jpeg S076.jpeg S077.jpeg


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
