#!/private/bin/perl -w

# user_comments.cgi
#
# submit comments from view.apg pages. 


# Script handles form input from users that have comments on the view pages.
# Send an email to the curators, confirm to the user that input was received.
# The relevant vars that are passed in, and composes into a nice email:
# Sender: The name of the person sending the request
# Email: The email of the person
# ZFIN_id: ID for the data item on the page the request is generated by
# Abbrev: abbreviated name for the data item


$mailprog = '/usr/lib/sendmail -t -oi -oem';

sub print_confirmation {
print <<EOA;
content-type: text/HTML\n\n
<HTML>
<BODY>
<script language="JavaScript" src="/javascript/header.js"></script>
Thank you for submitting comments. Your input has been emailed to ZFIN curators who may contact you if additional information is required. 
<p>
<form>
<input type=button value="Close Window" onClick="window.close()">
</form>
<script language="JavaScript" src="/javascript/footer.js"></script>
EOA
}



#parse user input
read(STDIN, $raw_data, $ENV{CONTENT_LENGTH});

$items = split('&', $raw_data);
for ($i = 0; $i < $items; $i++) {
  ($key,$value) = split('=', $_[$i]);
  $value =~ tr/+/ /;
  $value =~ s/%(..)/pack("C", hex($1))/eg;
  $data{"$key"} = $value;
}


#email input to curators
$email=$data{email};
if ($email eq 'Unknown') {$email=''};

open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP";
To: <!--|CURATORS_AT_ZFIN|-->
From: $email
Subject: $data{subject}

USER INPUT:

Name: $data{firstname} $data{lastname}
Contact Email: $data{email}
Institution: $data{institution}
Originating Page: $data{page_name}

Comments: $data{comments}

STOP
close(MAIL) || die "pipe exited $?";


#email 'thanks' to submitter
open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP1";
To: $email
From: <!--|CURATORS_AT_ZFIN|-->
Subject: ZFIN Thanks You For Your Input


Dear $data{firstname}:

Thank you for using ZFIN.  Your comments/suggestions are very important to us.
We will respond to them as soon as possible.

Your comments/suggestions are as follows: 
-----------------------------------------------------------------
$data{comments}
-----------------------------------------------------------------

Regards,
Zebrafish Information Network


STOP1
close(MAIL) || die "pipe exited $?";

&print_confirmation;

exit;
