#!/usr/local/bin/perl5
#
# user_comments.cgi
#
# # submit comments from view.apg pages.
#

# Script handles form input from users that have comments on the view pages.
# Send an email to the curators, confirm to the user that input was received.
# The relevant vars that are passed in, and composes into a nice email:
# Sender: The name of the person sending the request
# Email: The email of the person
# ZFIN_id: ID for the data item on the page the request is generated by
# Abbrev: abbreviated name for the data item


$mailprog = '/usr/lib/sendmail -t -oi -oem';

sub print_confirmation {
print <<EOA;
Content-type: text/HTML\n\n
<HTML>
<BODY bgcolor="#FFFFFF">
<h1 align=center>Confirmation</h1>
<b> Your comments have been emailed to ZFIN curators.</b> If you have given a contact email, you should receive a copy of this email and may be contacted for additional information.  <p>
<form>
<input type=button value="Close Window" onClick="window.close()">
</form>
</BODY></HTML>
EOA
}

read(STDIN, $raw_data, $ENV{CONTENT_LENGTH});

$items = split('&', $raw_data);
for ($i = 0; $i < $items; $i++) {
  ($key,$value) = split('=', $_[$i]);
  $value =~ tr/+/ /;
  $value =~ s/%(..)/pack("C", hex($1))/eg;
  $data{"$key"} = $value;
}

$email=$data{email};
if ($email eq 'Unknown') {$email=''};

open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP";
To: curators\@zfin.org
Cc: $email
From: $email
Subject: $data{subject}

USER INPUT for $data{page_id}. 

Name: $data{firstname} $data{lastname}
Contact Email: $data{email}
ZFIN_ID: $data{marker_id}
Marker Name: $data{marker_name}

Comments: $data{comments}

STOP
close(MAIL) || die "pipe exited $?";

&print_confirmation;

exit;














