#!/private/bin/perl -w
#
# user_comments.cgi
#
# submit comments from view.apg pages. 
#
#
# Script handles form input from users that have comments on the view pages.
# Send an email to the curators, confirm to the user that input was received.
# The relevant vars that are passed in, and composes into a nice email:
# Sender: The name of the person sending the request
# Email: The email of the person
# ZFIN_id: ID for the data item on the page the request is generated by
# Abbrev: abbreviated name for the data item


$mailprog = '/usr/lib/sendmail -t -oi -oem';

sub print_confirmation {
print <<EOA;
Content-type: text/HTML\n\n
<HTML>
<script language="JavaScript" src="/javascript/header.js"></script>

Thank you for your submission.  A confirmation email has been sent to you.  Your submission has been forwarded to the ZFIN nomenclature coordinator, who may contact you if additional information is required.
<p>
<script language="JavaScript" src="/javascript/footer.js"></script>

EOA
}

#parse user input
read(STDIN, $raw_data, $ENV{CONTENT_LENGTH});

@items = split(/&/, $raw_data);
foreach $item (@items) {
  ($key,$value) = split(/=/, $item);
  $value =~ tr/+/ /;
  $value =~ s/%(..)/pack("C", hex($1))/eg;
  $data{"$key"} = $value;
}

#email input to curators
$email=$data{email};
if ($email eq 'Unknown') {$email=''};

open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP";
To: <!--|NOMEN_COORDINATOR|-->
From: $email
Subject: Gene Submission: $data{gene_symbol}

USER INPUT:

Submitter's Name: $data{submitter_name}
Submitter's Email: $data{email}
Submitter's Lab: $data{lab_name}
Gene Name: $data{gene_fullname}
Gene Symbol: $data{gene_symbol}
Gene - Other Names: $data{gene_othername}
Publication Status: $data{pub_status}
Reservation Status: $data{reserv_status}
GenBank ID: $data{genbank_id}
Sequence: $data{sequence}
Linkage Group: $data{lg}
Homology-Species: $data{homol_sp_1}
Homology-Gene: $data{homol_gene_1}
Homology-Database Acc: $data{homol_id_1}
Homology-Species: $data{homol_sp_2}
Homology-Gene: $data{homol_gene_2}
Homology-Database Acc: $data{homol_id_2}
Homology-Species: $data{homol_sp_3}
Homology-Gene: $data{homol_gene_3}
Homology-Database Acc: $data{homol_id_3}
Comments: $data{comments}

STOP
close(MAIL) || die "pipe exited $?";


#email 'thanks' to submitter
open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP1";
To: $email
From: <!--|NOMEN_COORDINATOR|-->
Subject: Thank You For Your Submission


Dear $data{submitter_name}:

Thank you for your submission. The information you provided has been forwarded to the ZFIN nomenclature coordinator, who may contact you if additional information is required.

Regards,
The Zebrafish Nomenclature Committee
nomenclature\@zfin.org


Submitter's Name: $data{submitter_name}
Submitter's Email: $data{email}
Submitter's Lab: $data{lab_name}
Gene Name: $data{gene_fullname}
Gene Symbol: $data{gene_symbol}
Gene - Other Names: $data{gene_othername}
Publication Status: $data{pub_status}
Reservation Status: $data{reserv_status}
GenBank ID: $data{genbank_id}
Sequence: $data{sequence}
Linkage Group: $data{lg}
Homology-Species: $data{homol_sp_1}
Homology-Gene: $data{homol_gene_1}
Homology-Database Acc: $data{homol_id_1}
Homology-Species: $data{homol_sp_2}
Homology-Gene: $data{homol_gene_2}
Homology-Database Acc: $data{homol_id_2}
Homology-Species: $data{homol_sp_3}
Homology-Gene: $data{homol_gene_3}
Homology-Database Acc: $data{homol_id_3}
Comments: $data{comments}

STOP1
close(MAIL) || die "pipe exited $?";

&print_confirmation;

exit;
