#!/private/bin/perl -w
#
# user_comments.cgi
#
# submit comments from view.apg pages. 
#
#
# Script handles form input from users that have comments on the view pages.
# Send an email to the curators, confirm to the user that input was received.
# The relevant vars that are passed in, and composes into a nice email:
# Sender: The name of the person sending the request
# Email: The email of the person
# ZFIN_id: ID for the data item on the page the request is generated by
# Abbrev: abbreviated name for the data item


$mailprog = '/usr/lib/sendmail -t -oi -oem';

sub print_confirmation {
print <<EOA;
Content-type: text/HTML\n\n
<HTML>
<script language="JavaScript" src="http://<!--|DOMAIN_NAME|-->/header.js"></script>

Thank you for your submission.  A confirmation email has been sent to you.  Your submission has been forwarded to the ZFIN nomenclature coordinator, who may contact you if additional information is required.
<p>
<script language="JavaScript" src="http://<!--|DOMAIN_NAME|-->/footer.js"></script>

EOA
}

#parse user input
read(STDIN, $raw_data, $ENV{CONTENT_LENGTH});

$items = split('&', $raw_data);
for ($i = 0; $i < $items; $i++) {
  ($key,$value) = split('=', $_[$i]);
  $value =~ tr/+/ /;
  $value =~ s/%(..)/pack("C", hex($1))/eg;
  $data{"$key"} = $value;
}


#email input to curators
$email=$data{email};
if ($email eq 'Unknown') {$email=''};

open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP";
To: <!--|NOMEN_COORDINATOR|-->
From: $email
Subject: Mutant Submission: $data{lab_desig_1} $data{lab_desig_2} $data{lad_desig_3}


Submitter's Name: $data{submitter_name}
Submitter's Email: $data{email}
Submitter's Lab: $data{lab_name}
1.Gene/Locus/Construct Name: $data{feat_or_gene_name_1}
1.Gene/Locus Symbol: $data{gene_symbol_1}
1.Lab designation: $data{lab_desig_1}
2.Gene/Locus/Construct Name: $data{feat_or_gene_name_2}
2.Gene/Locus Symbol: $data{gene_symbol_2}
2.Lab designation: $data{lab_desig_2}
3.Gene/Locus/Construct Name: $data{feat_or_gene_name_3}
3.Gene/Locus Symbol: $data{gene_symbol_3}
3.Lab designation: $data{lab_desig_3}
Genetic Background: $data{background}
Publication Status: $data{pub_status}
Citation(s): $data{citations}
Reservation Status: $data{reserv_status}
Comments: $data{comments}

STOP
close(MAIL) || die "pipe exited $?";


#email 'thanks' to submitter
open(MAIL, "| $mailprog") || die "Content-type: text/plain\n\nCan't open mailprog $mailprog, stopped";
print MAIL <<"STOP1";
To: $email
From: <!--|NOMEN_COORDINATOR|-->
Subject: Thank You For Your Submission


Dear $data{submitter_name}:

Thank you for your submission. The information you provided has been forwarded to the ZFIN nomenclature coordinator, who may contact you if additional information is required.

Regards,
The Zebrafish Nomenclature Committee
nomenclature\@zfin.org


Submitter's Name: $data{submitter_name}
Submitter's Email: $data{email}
Submitter's Lab: $data{lab_name}
1.Gene/Locus/Construct Name: $data{feat_or_gene_name_1}
1.Gene/Locus Symbol: $data{gene_symbol_1}
1.Lab designation: $data{lab_desig_1}
2.Gene/Locus/Construct Name: $data{feat_or_gene_name_2}
2.Gene/Locus Symbol: $data{gene_symbol_2}
2.Lab designation: $data{lab_desig_2}
3.Gene/Locus/Construct Name: $data{feat_or_gene_name_3}
3.Gene/Locus Symbol: $data{gene_symbol_3}
3.Lab designation: $data{lab_desig_3}
Genetic Background: $data{background}
Publication Status: $data{pub_status}
Citation(s): $data{citations}
Reservation Status: $data{reserv_status}
Comments: $data{comments}

STOP1
close(MAIL) || die "pipe exited $?";

&print_confirmation;

exit;
