#!/private/bin/perl -wT 
# ----------------------------------------------------------------------
#  file name:  ZFIN_jump
#
#  Programmer:  Eck Doerry
#  Description: A simple script. Sets up one env variable 
# (just so the user doesn't have to type it in the URL) and fires off
# the Webdriver. This script is syntactic sugar to allow people to jump to
# internal ZFIN pages without a huge ugly URL to type. Note that "jump_to"
# also expects the variable "record"; users already place this in the 
# environment in the original URL.
#
# Modified by Arthur Kirkpatrick for Informix WebBlade 4.0.
# See SCRIPT_NAME variable below.

# Set up MIval variable
### $ENV{MIval}="aa-jump_to.apg";
#
# A security feature (?) of WebBlade 4.0: 
# If the SCRIPT_NAME variable is not set to the exact directory
# and file name that webdriver lives in, webdriver will simply
# return a 500 code and terminate.  We want the users to
# consistently use /cgi-bin/ZFIN_jump, regardless of the actual
# directory this function and webdriver are stored in.  Apache
# will put the name the USER used (cgi-bin) in its copy of
# SCRIPT_NAME before calling this script.  If we just pass
# Apache's value on to webdriver, webdriver will give us the
# old "500" error.  So force the SCRIPT_NAME variable to
# have the value webdriver expects.
### $ENV{SCRIPT_NAME}="/cgi-bin/webdriver";

# pass control to Webdriver
### exec("./webdriver");	# Invokes webdriver


### changes Dec 27 2000
### added -wt to perl line
### commented out previous version because D.C. wants webdriver only called via http
### added the following

{  ### mod it
use CGI  qw /:standard/;
use HTTP::Request::Common qw/POST/;
use LWP::UserAgent;

my $q = new CGI();
my $bot = LWP::UserAgent->new(); 
my $req = POST 'http://<!--|DOMAIN_NAME|-->/cgi-bin/webdriver',
	  [   MIval=> 'aa-jump_to.apg', record=>$q->param('record') ];
print "Content-Type: text/html; charset=ISO-8859-1 \r\n\r\n".
    $bot->request($req)->content;
}### ~mod it



