#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, WWW/home/ZFIN/Workgroup_dirs/AnatDict
# subdirectory
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
# This directory exists for one file:
#   meeting_sum.html
# and that file exists only because it is pointed to by an HTTP reference in 
#   zf_info/monitor/vol7.1/vol7.1.pdf
# AND, the meeting_sum file is duplicated in the FTP tree.  I don't know why.

# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/Workgroup_dirs/AnatDict

STATICS = meeting_sum.html


# --------------------------  Rules  ------------------------------------

# Use default rules

include $(TOP)/make.default.rules
