--liquibase formatted sql

-- ZFIN-10449 item 2: a "Phenotype images" upload section on the phenotype
-- form. Phenotypes had no attachment mechanism at all, so this mirrors
-- zirc.genotyping_assay_file (see 1182/0050) rather than inventing a second
-- storage layout. Column prefix pf_ per the convention in that file: first
-- letters of each word in the table name.
--
-- A parallel table, not one polymorphic zirc_file keyed by owner type. The
-- assay upload path works and is in use; generalising it would mean migrating
-- live rows and rewriting three endpoints for a feature that only asks for a
-- second owner. A third owner would justify the unification -- two does not.
--
-- Deliberately without the af_kind column. The assay table CHECKs kind against
-- four buckets (chromatogram / gel_image / result_image / melt_curve) because
-- an assay shows a different heading per assay type, and even there the
-- renderer collapsed them to one generic uploader. A phenotype has exactly one
-- bucket, so a kind column would only ever hold one value.
--
-- ON DELETE CASCADE matches every other internal FK in the submission tree:
-- deleting a submission removes its mutations, phenotypes and their file rows
-- in one statement. It does NOT remove anything from disk -- the service
-- unlinks files only on explicit per-file delete, so a cascaded submission
-- delete leaves orphaned bytes under
-- $TARGETROOT/server_apps/data_transfer/ZIRC/<submission>/. That is the
-- pre-existing behaviour for assay files; worth a cleanup job eventually, but
-- not a new problem introduced here.
--
-- Storage layout, constructed server-side and never taken from the client:
--   $TARGETROOT/server_apps/data_transfer/ZIRC/<submission zdb id>/
--     phenotype-<phenotype id>-<pf_id>-<sanitized original filename>

--changeset cmpich:ZFIN-10449-phenotype-file
CREATE TABLE IF NOT EXISTS zirc.phenotype_file (
    pf_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pf_phenotype_id      BIGINT NOT NULL
        REFERENCES zirc.phenotype(p_id) ON DELETE CASCADE,
    pf_original_filename TEXT NOT NULL,
    pf_stored_path       TEXT NOT NULL,
    pf_content_type      TEXT,
    pf_file_size         BIGINT,
    pf_uploaded_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    pf_uploaded_by       VARCHAR(50) REFERENCES person(zdb_id)
);
CREATE INDEX IF NOT EXISTS phenotype_file_phenotype_idx
    ON zirc.phenotype_file (pf_phenotype_id);
--rollback DROP TABLE IF EXISTS zirc.phenotype_file;
