#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Zebrafish Book, Stages figures 
# web pages.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/zfbook/stages/figs

SUBDIRS = big_images low_res_sketches

STATICS = fig10.gif fig11.gif fig12.gif fig13.gif fig14.gif \
	fig15a.gif fig15b.gif fig16.gif fig17.gif \
	fig18.gif  fig19.gif fig2.gif fig20.gif fig21.gif fig22.gif  \
	fig23.gif fig24.gif fig25.gif fig26.gif fig27.gif fig28.gif  \
	fig29a-c.gif fig29d-f.gif fig29g-i.gif fig3.gif  \
	fig30.gif fig31.gif fig32.gif fig33.gif fig34.gif fig35.gif  \
	fig36.gif fig37.gif fig38.gif fig39a.jpg fig39b.jpg fig4.gif fig40.gif \
	fig41.gif fig42.gif fig43.gif fig5.gif fig6.gif fig7.gif  \
	fig8.gif fig9.gif fig1.html fig10.html fig11.html fig12.html fig13.html fig14.html \
	fig15.html fig16.html fig17.html fig18.html fig19.html fig2.html  \
	fig20.html fig21.html fig22.html fig23.html fig24.html fig25.html \
	fig26.html fig27.html fig28.html fig29.html fig3.html  fig30.html \
	fig31.html fig32.html fig33.html fig34.html fig35.html fig36.html \
	fig37.html fig38.html fig39.html fig4.html  fig40.html fig41.html \
	fig42.html fig43.html fig5.html  fig6.html  fig7.html  fig8.html  \
	fig9.html  table1.html table2.html


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
