#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, App Pages hierarchy.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES

SUBDIRS = SQL_docs \
	ZFINadmn \
	accession \
	company_files \
	fish_files \
	gene_files \
	groupware \
	image_files \
	lab_files \
	locus_files \
	marker_files \
	misc_files \
	navigation_files \
	personbrowser \
	pubbrowser \
	security_files \
	selection \
	updating


# Use default rules.

include $(TOP)/make.default.rules
