#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, ZFIN Data Model Description.
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#



# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/dbase/PAPERS/ZFIN_DataModel

# data_model.html_complete and data_model_word are worth hanging onto, but
# are not part of the public web pages.  Don't copy them.


#GENERICS = 

STATICS = fig1.gif fig2.gif fig3.gif fig4.gif fig5.gif fig6.gif \
	fig7.gif fig8.gif fig9.gif data_model.html overview_1.html overview_2.html overview_3.html \
	overview_4.html sectioni.html sectioni_1.html sectioni_2.html \
	sectioni_3.html sectioni_4.html sectioni_5.html sectionii.html \
	sectionii_1.html sectionii_10.html sectionii_11.html \
	sectionii_12.html sectionii_13.html sectionii_14.html \
	sectionii_15.html sectionii_16.html sectionii_17.html \
	sectionii_18.html sectionii_2.html sectionii_3.html sectionii_4.html \
	sectionii_5.html sectionii_6.html sectionii_7.html sectionii_8.html \
	sectionii_9.html sectioniii.html sectioniii_1.html sectioniii_2.html \
	sectioniv.html sectioniv_1.html sectioniv_2.html sectioniv_3.html \
	sectioniv_4.html sectionv.html



# ---------------  Production Rules  ------------------------------------

# use default rules

include $(TOP)/make.default.rules
