package org.zfin.properties;

/**
 * Enum containing all ZFIN configuration property keys.
 *
 * Property values are loaded at runtime from zfin.properties via ZfinProperties.init().
 *
 * This file is generated by: gradle generatePropertiesEnum
 * 
 * #################################################
 * TODO: Replace ZfinPropertiesEnum with modern spring @ConfigurationProperties
 * Eg. Use a typed configuration class with Spring injection:
  @ConfigurationProperties(prefix = "")
  public class ZfinConfig {
      private String solrHost;
      private int solrPort;
      // ...
  }
 * #################################################
 * 
 * For now, to add a new property:
 * 1. Add the property to commons/env/all-properties.yml
 * 2. Run `ant rebuildProperties` to regenerate home/WEB-INF/zfin.properties
 * 3. Run `gradle generatePropertiesEnum` to regenerate this enum
 * 4. Commit both files
 */
public enum ZfinPropertiesEnum {
    ADAM_AMSTERDAM,
    ALLIANCE_CURATION_URL,
    ALL_FAILURE_REPORTS_EMAIL,
    ANT_HOME,
    ANT_OPTS,
    AO_EMAIL_CURATOR,
    AO_EMAIL_ERR,
    APACHE_PORT,
    APACHE_PORT_SECURE,
    APACHE_SERVER_NAME,
    APACHE_USER,
    BCRYPT_WORK_FACTOR,
    BLASTSCRIPT_TARGET_PATH,
    BLASTSERVER_BINARY_PATH,
    BLASTSERVER_BLAST_DATABASE_PATH,
    BLASTSERVER_DISTRIBUTED_QUERY_PATH,
    BLASTSERVER_FASTA_FILE_PATH,
    BLASTSERVER_XDFORMAT,
    BLASTSERVER_XDGET,
    BLAST_ACCESSION_TEMP_DIR,
    BLAST_CACHE_AT_STARTUP,
    BLAST_FILE_DIR,
    BLAST_SCRIPT_DIR,
    BUILD_EMAIL,
    CATALINA_BASE,
    CATALINA_HOME,
    CATALINA_PID,
    CGI_BIN_DIR_NAME,
    CLIENT_LOCALE,
    CONFIGURATION_DIRECTORY,
    CONVERT_BINARY_PATH,
    COOKIE_PATH,
    COUNT_PATO_ERR,
    COUNT_PATO_OUT,
    COUNT_THISSE_VEGA_ERR,
    COUNT_THISSE_VEGA_OUT,
    COUNT_VEGA_ERR,
    COUNT_VEGA_OUT,
    COUNT_ZGC_ERR,
    COUNT_ZGC_OUT,
    CURATION_DBNAME,
    CURATION_INSTANCE,
    CURATORS_AT_ZFIN,
    DATABASE_UNLOAD_DIRECTORY,
    DBNAME,
    DB_LOCALE,
    DB_NAME,
    DB_OWNER,
    DB_UNLOADS_PATH,
    DEBUGPORT,
    DEFAULT_EMAIL,
    DISABLE_SECURITY,
    DOI_EMAIL_REPORT,
    DOMAIN_NAME,
    DOWNLOAD_DIRECTORY,
    ELSEVIER_REPORT,
    EMAIL_SENDER_CLASS,
    ENVIRONMENT,
    FTPROOT_PATH,
    FTP_ROOT,
    GA4_ANALYTICS_ID,
    GA4_ANALYTICS_ID_PRODUCTION,
    GA4_ANALYTICS_ID_ZFINLABS,
    GBROWSE_DB,
    GBROWSE_DB_HOST,
    GBROWSE_GRCZ10_IMG_PATH_FROM_ROOT,
    GBROWSE_GRCZ10_PATH_FROM_ROOT,
    GBROWSE_IMG_PATH_FROM_ROOT,
    GBROWSE_PATH_FROM_ROOT,
    GBROWSE_ZV9_IMG_PATH_FROM_ROOT,
    GBROWSE_ZV9_PATH_FROM_ROOT,
    GC_LOGGING_OPTS,
    GENBANK_DAILY_EMAIL,
    GOOGLE_ANALYTICS_ID,
    GO_EMAIL_CURATOR,
    GO_EMAIL_ERR,
    GRADLE_USER_HOME,
    GROOVY_CLASSPATH,
    GROOVY_HOME,
    HAS_PARTNER,
    HIBERNATE_CONFIGURATION_DIRECTORY,
    IMAGE_LOAD,
    INDEXER_REPORT_EMAIL,
    INDEXER_UNLOAD_DIRECTORY,
    INDEXER_WIKI_HOSTNAME,
    INDEXER_WIKI_PASSWORD,
    INDEXER_WIKI_USERNAME,
    INSPECTLET_ID,
    INSTANCE,
    INTERNAL_BLAST_PATH,
    JAVA_HOME,
    JBROWSE_BASE_URL,
    JBROWSE_GRCZ10_PATH_FROM_ROOT,
    JBROWSE_GRCZ11_PATH_FROM_ROOT,
    JBROWSE_PATH_FROM_ROOT,
    JBROWSE_PROXY_BASE_URL,
    JBROWSE_USE_LOCAL_PROXY,
    JBROWSE_ZV9_PATH_FROM_ROOT,
    JDBC_DRIVER,
    JDBC_URL,
    JENKINS_HOME,
    JENKINS_PORT,
    JPDA_ADDRESS,
    JSD_EMAIL,
    LN54_CONTACT_EMAIL,
    LOADUP_FULL_PATH,
    LOAD_ONTOLOGIES_AT_STARTUP,
    LOCUS_REGISTRATION_EMAIL,
    LOG4J_FILE,
    LOG_FILE_MAX,
    LOG_FILE_PATTERN,
    LOG_FILE_SESSION,
    LOG_FILE_SIZE,
    MICROARRAY_EMAIL,
    MOVE_BLAST_FILES_TO_DEVELOPMENT,
    MUTANT_NAME,
    NCBI_LINKOUT_UPLOAD,
    NCBI_RELEASE_ARCHIVE_DIR,
    NEW_PUBLICATION_REPORT,
    NODE_ENV,
    NOMEN_COORDINATOR,
    NON_SECUREPORT,
    NON_SECURE_HTTP,
    ONTOLOGY_LOADER_EMAIL,
    PARTNER_DBNAME,
    PARTNER_INTERNAL_INSTANCE,
    PARTNER_SOURCEROOT,
    PATO_EMAIL_CURATOR,
    PDF_LOAD,
    PDF_PATH,
    PGBINDIR,
    PGDATA,
    PGDATABASE,
    PGHOST,
    PRIMARY_COLOR,
    PRODUCTION_NOTIFICATION_EMAIL,
    REQUEST_NEW_ANATOMY_EMAIL,
    ROOT_PATH,
    SCHEDULE_TRIGGER_FILES,
    SECUREPORT,
    SECURE_HTTP,
    SECURE_SERVER,
    SEND_AUTHOR_NOTIF_EMAIL,
    SHARED_DOMAIN_NAME,
    SHOW_SQL,
    SHUTDOWNPORT,
    SMTP_HOST,
    SOLR_CONTEXT,
    SOLR_CORE,
    SOLR_CREATE_BACKUPS,
    SOLR_HOME,
    SOLR_HOST,
    SOLR_MEMORY,
    SOLR_PORT,
    SOLR_UNLOADS_PATH,
    SOURCEROOT,
    SQLHOSTS_FILE,
    SQLHOSTS_HOST,
    SSH,
    SWISSPROT_EMAIL_CURATOR,
    SWISSPROT_EMAIL_ERR,
    SWISSPROT_EMAIL_REPORT,
    TARGETCGIBIN,
    TARGETFTPROOT,
    TARGETROOT,
    TARGETROOT_PREFIX,
    TECHNICAL_AT_ZFIN,
    UNIPROT_EC2GO_FILE_URL,
    UNIPROT_IP2GO_FILE_URL,
    UNIPROT_KW2GO_FILE_URL,
    UNIPROT_RELEASE_ARCHIVE_DIR,
    UNIPROT_SPROT_FILE_URL,
    UNIPROT_SPROT_FILE_URL_ALT1,
    UNIPROT_SPROT_FILE_URL_ALT2,
    UNIPROT_SPROT_FILE_URL_ALT3,
    UNIPROT_TREMBL_FILE_URL,
    UNIPROT_TREMBL_FILE_URL_ALT1,
    UNIPROT_TREMBL_FILE_URL_ALT2,
    UNIPROT_TREMBL_FILE_URL_ALT3,
    UNIPROT_URL_FOR_RELEASE_DATE,
    USER,
    USE_APACHE_FOR_SMOKE_TESTS,
    VALIDATION_EMAIL_AD,
    VALIDATION_EMAIL_CURATOR,
    VALIDATION_EMAIL_DBA,
    VALIDATION_EMAIL_EST,
    VALIDATION_EMAIL_GENE,
    VALIDATION_EMAIL_GENOCURATOR,
    VALIDATION_EMAIL_MORPHOLINO,
    VALIDATION_EMAIL_MUTANT,
    VALIDATION_EMAIL_OTHER,
    VALIDATION_EMAIL_TRANSCRIPT,
    VALIDATION_EMAIL_XPAT,
    VALID_SESSION_TIMEOUT_SECONDS,
    VIDEO_LOAD,
    WAREHOUSE_DUMP_DIR,
    WAREHOUSE_REGN_EMAIL,
    WAR_WEB_INF_DIR,
    WEBHOST_BINARY_PATH,
    WEBHOST_BLASTALL,
    WEBHOST_BLASTDB_CURL_PATH,
    WEBHOST_BLASTDB_TO_COPY,
    WEBHOST_BLAST_DATABASE_PATH,
    WEBHOST_DBNAME,
    WEBHOST_FASTA_FILE_PATH,
    WEBHOST_GENBANK_DAILY_FILES,
    WEBHOST_KEY_PATH,
    WEBHOST_MUTANT,
    WEBHOST_SOURCE,
    WEBHOST_USER,
    WEBHOST_XDFORMAT,
    WEBHOST_XDGET,
    WEBROOT_DIRECTORY,
    WEB_ADMIN_EMAIL,
    WIKI_HOST,
    WIKI_PASS,
    WIKI_PUSH_TO_WIKI,
    WIKI_USER,
    ZEBRASHARE_CURATORS,
    ZFIN_ADMIN,
    ZFIN_PROPERTIES_PATH,
    ;

    private String value;

    ZfinPropertiesEnum() {
        this.value = null;
    }

    /**
     * Get the property value.
     */
    public String value() {
        return this.value;
    }

    /**
     * Returns the property value (for compatibility with existing code that uses toString()).
     */
    @Override
    public String toString() {
        return this.value;
    }

    /**
     * Set the property value. Called by ZfinProperties.init() when loading properties.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Find an enum constant by matching its value.
     * @deprecated Use valueOf(name) instead for finding by enum name
     */
    @Deprecated
    public static ZfinPropertiesEnum getEnumByName(String name) {
        for (ZfinPropertiesEnum t : values()) {
            if (t.value() != null && t.value().equals(name.trim())) {
                return t;
            }
        }
        throw new RuntimeException("No enum with value '" + name + "' found.");
    }
}
