--liquibase formatted sql
--changeset rtaylor:ZFIN-7858

update journal set jrnl_isoabbrev = 'AAPS PharmSciTech',  jrnl_medabbrev = 'AAPS PharmSciTech' where jrnl_zdb_id='ZDB-JRNL-200403-1' ;
update journal set jrnl_isoabbrev = 'ACS Appl Bio Mater',  jrnl_medabbrev = 'ACS Appl Bio Mater' where jrnl_zdb_id='ZDB-JRNL-220111-1' ;
update journal set jrnl_isoabbrev = 'ACS Biomater Sci Eng',  jrnl_medabbrev = 'ACS Biomater Sci Eng' where jrnl_zdb_id='ZDB-JRNL-201216-1' ;
update journal set jrnl_isoabbrev = 'ACS Chem Neurosci',  jrnl_medabbrev = 'ACS Chem Neurosci' where jrnl_zdb_id='ZDB-JRNL-120223-2' ;
update journal set jrnl_isoabbrev = 'ACS Infect Dis',  jrnl_medabbrev = 'ACS Infect Dis' where jrnl_zdb_id='ZDB-JRNL-191223-1' ;
update journal set jrnl_isoabbrev = 'ACS Med Chem Lett',  jrnl_medabbrev = 'ACS Med Chem Lett' where jrnl_zdb_id='ZDB-JRNL-140325-1' ;
update journal set jrnl_isoabbrev = 'ACS Omega',  jrnl_medabbrev = 'ACS Omega' where jrnl_zdb_id='ZDB-JRNL-180720-1' ;
update journal set jrnl_isoabbrev = 'ACS Pharmacol Transl Sci',  jrnl_medabbrev = 'ACS Pharmacol Transl Sci' where jrnl_zdb_id='ZDB-JRNL-200825-1' ;
update journal set jrnl_isoabbrev = 'ACS Photonics',  jrnl_medabbrev = 'ACS Photonics' where jrnl_zdb_id='ZDB-JRNL-201219-1' ;
update journal set jrnl_isoabbrev = 'ACS Sens',  jrnl_medabbrev = 'ACS Sens' where jrnl_zdb_id='ZDB-JRNL-170827-1' ;
update journal set jrnl_isoabbrev = 'ACS Synth Biol',  jrnl_medabbrev = 'ACS Synth Biol' where jrnl_zdb_id='ZDB-JRNL-150325-1' ;
update journal set jrnl_isoabbrev = 'Acta Crystallogr D Struct Biol',  jrnl_medabbrev = 'Acta Crystallogr D Struct Biol' where jrnl_zdb_id='ZDB-JRNL-200606-1' ;
update journal set jrnl_isoabbrev = 'Acta Crystallogr Sect F Struct Biol Cryst Commun',  jrnl_medabbrev = 'Acta Crystallogr Sect F Struct Biol Cryst Commun' where jrnl_zdb_id='ZDB-JRNL-080825-2' ;
update journal set jrnl_isoabbrev = 'Acta Crystallogr F Struct Biol Commun',  jrnl_medabbrev = 'Acta Crystallogr F Struct Biol Commun' where jrnl_zdb_id='ZDB-JRNL-140710-1' ;
update journal set jrnl_isoabbrev = 'Acta Neuropathol Commun',  jrnl_medabbrev = 'Acta Neuropathol Commun' where jrnl_zdb_id='ZDB-JRNL-140716-1' ;
update journal set jrnl_isoabbrev = 'Acta Paediatr',  jrnl_medabbrev = 'Acta Paediatr' where jrnl_zdb_id='ZDB-JRNL-120830-2' ;
update journal set jrnl_isoabbrev = 'Adv Biosyst',  jrnl_medabbrev = 'Adv Biosyst' where jrnl_zdb_id='ZDB-JRNL-191218-1' ;
update journal set jrnl_isoabbrev = 'Adv Genet (Hoboken)',  jrnl_medabbrev = 'Adv Genet (Hoboken)' where jrnl_zdb_id='ZDB-JRNL-210824-1' ;
update journal set jrnl_isoabbrev = 'Adv Healthc Mater',  jrnl_medabbrev = 'Adv Healthc Mater' where jrnl_zdb_id='ZDB-JRNL-121206-1' ;
update journal set jrnl_isoabbrev = 'Adv Sci (Weinh)',  jrnl_medabbrev = 'Adv Sci (Weinh)' where jrnl_zdb_id='ZDB-JRNL-161011-1' ;
update journal set jrnl_isoabbrev = 'Adv Pharmacol Pharm Sci',  jrnl_medabbrev = 'Adv Pharmacol Pharm Sci' where jrnl_zdb_id='ZDB-JRNL-210515-1' ;
update journal set jrnl_isoabbrev = 'Afr J Biotechnol',  jrnl_medabbrev = 'Afr J Biotechnol' where jrnl_zdb_id='ZDB-JRNL-170213-1' ;
update journal set jrnl_isoabbrev = 'Aging Dis',  jrnl_medabbrev = 'Aging Dis' where jrnl_zdb_id='ZDB-JRNL-130903-1' ;
update journal set jrnl_isoabbrev = 'AIMS Mol Sci',  jrnl_medabbrev = 'AIMS Mol Sci' where jrnl_zdb_id='ZDB-JRNL-210310-1' ;
update journal set jrnl_isoabbrev = 'AMB Express',  jrnl_medabbrev = 'AMB Express' where jrnl_zdb_id='ZDB-JRNL-190220-1' ;
update journal set jrnl_isoabbrev = 'Am J Cancer Res',  jrnl_medabbrev = 'Am J Cancer Res' where jrnl_zdb_id='ZDB-JRNL-151223-1' ;
update journal set jrnl_isoabbrev = 'Am J Mol Biol',  jrnl_medabbrev = 'Am J Mol Biol' where jrnl_zdb_id='ZDB-JRNL-151112-1' ;
update journal set jrnl_isoabbrev = 'Am J Neurodegener Dis',  jrnl_medabbrev = 'Am J Neurodegener Dis' where jrnl_zdb_id='ZDB-JRNL-130221-1' ;
update journal set jrnl_isoabbrev = 'Am J Transl Res',  jrnl_medabbrev = 'Am J Transl Res' where jrnl_zdb_id='ZDB-JRNL-170704-1' ;
update journal set jrnl_isoabbrev = 'Anim Microbiome',  jrnl_medabbrev = 'Anim Microbiome' where jrnl_zdb_id='ZDB-JRNL-210128-1' ;
update journal set jrnl_isoabbrev = 'Animals (Basel)',  jrnl_medabbrev = 'Animals (Basel)' where jrnl_zdb_id='ZDB-JRNL-160827-1' ;
update journal set jrnl_isoabbrev = 'Ann Clin Transl Neurol',  jrnl_medabbrev = 'Ann Clin Transl Neurol' where jrnl_zdb_id='ZDB-JRNL-180516-1' ;
update journal set jrnl_isoabbrev = 'Annu Rev Biomed Eng',  jrnl_medabbrev = 'Annu Rev Biomed Eng' where jrnl_zdb_id='ZDB-JRNL-110719-2' ;
update journal set jrnl_isoabbrev = 'Antibiotics (Basel)',  jrnl_medabbrev = 'Antibiotics (Basel)' where jrnl_zdb_id='ZDB-JRNL-180509-1' ;
update journal set jrnl_isoabbrev = 'Antibodies (Basel)',  jrnl_medabbrev = 'Antibodies (Basel)' where jrnl_zdb_id='ZDB-JRNL-190924-1' ;
update journal set jrnl_isoabbrev = 'Antioxidants (Basel)',  jrnl_medabbrev = 'Antioxidants (Basel)' where jrnl_zdb_id='ZDB-JRNL-190424-1' ;
update journal set jrnl_isoabbrev = 'APL Bioeng',  jrnl_medabbrev = 'APL Bioeng' where jrnl_zdb_id='ZDB-JRNL-190510-1' ;
update journal set jrnl_isoabbrev = 'Appl Radiat Isot',  jrnl_medabbrev = 'Appl Radiat Isot' where jrnl_zdb_id='ZDB-JRNL-091023-7' ;
update journal set jrnl_isoabbrev = 'Arch Anim Breed',  jrnl_medabbrev = 'Arch Anim Breed' where jrnl_zdb_id='ZDB-JRNL-210605-1' ;
update journal set jrnl_isoabbrev = 'Arterioscler Thromb Vasc Biol',  jrnl_medabbrev = 'Arterioscler Thromb Vasc Biol' where jrnl_zdb_id='ZDB-JRNL-150422-3' ;
update journal set jrnl_isoabbrev = 'Asia Pac J Ophthalmol (Phila)',  jrnl_medabbrev = 'Asia Pac J Ophthalmol (Phila)' where jrnl_zdb_id='ZDB-JRNL-150626-1' ;
update journal set jrnl_isoabbrev = 'ASN Neuro',  jrnl_medabbrev = 'ASN Neuro' where jrnl_zdb_id='ZDB-JRNL-190712-1' ;
update journal set jrnl_isoabbrev = 'Austin J Pharmacol Ther',  jrnl_medabbrev = 'Austin J Pharmacol Ther' where jrnl_zdb_id='ZDB-JRNL-160203-1' ;
update journal set jrnl_isoabbrev = 'Aust J Basic Appl Sci',  jrnl_medabbrev = 'Aust J Basic Appl Sci' where jrnl_zdb_id='ZDB-JRNL-170502-6' ;
update journal set jrnl_isoabbrev = 'Behav Brain Funct',  jrnl_medabbrev = 'Behav Brain Funct' where jrnl_zdb_id='ZDB-JRNL-150920-1' ;
update journal set jrnl_isoabbrev = 'Behav Res Methods',  jrnl_medabbrev = 'Behav Res Methods' where jrnl_zdb_id='ZDB-JRNL-061229-4' ;
update journal set jrnl_isoabbrev = 'Beilstein J Nanotechnol',  jrnl_medabbrev = 'Beilstein J Nanotechnol' where jrnl_zdb_id='ZDB-JRNL-151002-1' ;
update journal set jrnl_isoabbrev = 'Beilstein J Org Chem',  jrnl_medabbrev = 'Beilstein J Org Chem' where jrnl_zdb_id='ZDB-JRNL-200125-1' ;
update journal set jrnl_isoabbrev = 'Bioact Mater',  jrnl_medabbrev = 'Bioact Mater' where jrnl_zdb_id='ZDB-JRNL-211129-1' ;
update journal set jrnl_isoabbrev = 'Biochem Biophys Rep',  jrnl_medabbrev = 'Biochem Biophys Rep' where jrnl_zdb_id='ZDB-JRNL-171113-1' ;
update journal set jrnl_isoabbrev = 'BioData Min',  jrnl_medabbrev = 'BioData Min' where jrnl_zdb_id='ZDB-JRNL-150623-1' ;
update journal set jrnl_isoabbrev = 'Bioinform Biol Insights',  jrnl_medabbrev = 'Bioinform Biol Insights' where jrnl_zdb_id='ZDB-JRNL-100211-5' ;
update journal set jrnl_isoabbrev = 'Bioinformation',  jrnl_medabbrev = 'Bioinformation' where jrnl_zdb_id='ZDB-JRNL-190711-1' ;
update journal set jrnl_isoabbrev = 'Biol Cybern',  jrnl_medabbrev = 'Biol Cybern' where jrnl_zdb_id='ZDB-JRNL-050907-5' ;
update journal set jrnl_isoabbrev = 'Biol Proced Online',  jrnl_medabbrev = 'Biol Proced Online' where jrnl_zdb_id='ZDB-JRNL-180307-1' ;
update journal set jrnl_isoabbrev = 'Biology (Basel)',  jrnl_medabbrev = 'Biology (Basel)' where jrnl_zdb_id='ZDB-JRNL-151117-1' ;
update journal set jrnl_isoabbrev = 'Biol Direct',  jrnl_medabbrev = 'Biol Direct' where jrnl_zdb_id='ZDB-JRNL-071129-3' ;
update journal set jrnl_isoabbrev = 'Biomedicines',  jrnl_medabbrev = 'Biomedicines' where jrnl_zdb_id='ZDB-JRNL-170815-1' ;
update journal set jrnl_isoabbrev = 'Biomicrofluidics',  jrnl_medabbrev = 'Biomicrofluidics' where jrnl_zdb_id='ZDB-JRNL-110803-2' ;
update journal set jrnl_isoabbrev = 'Biomolecules',  jrnl_medabbrev = 'Biomolecules' where jrnl_zdb_id='ZDB-JRNL-180515-1' ;
update journal set jrnl_isoabbrev = 'Biophysics (Oxf)',  jrnl_medabbrev = 'Biophysics (Oxf)' where jrnl_zdb_id='ZDB-JRNL-050621-354' ;
update journal set jrnl_isoabbrev = 'bioRxiv',  jrnl_medabbrev = 'bioRxiv' where jrnl_zdb_id='ZDB-JRNL-201120-1' ;
update journal set jrnl_isoabbrev = 'Biotechnol Rep (Amst)',  jrnl_medabbrev = 'Biotechnol Rep (Amst)' where jrnl_zdb_id='ZDB-JRNL-180713-1' ;
update journal set jrnl_isoabbrev = 'Birth Defects Res',  jrnl_medabbrev = 'Birth Defects Res' where jrnl_zdb_id='ZDB-JRNL-170707-1' ;
update journal set jrnl_isoabbrev = 'Blood Cancer J',  jrnl_medabbrev = 'Blood Cancer J' where jrnl_zdb_id='ZDB-JRNL-161008-1' ;
update journal set jrnl_isoabbrev = 'BMC Biochem',  jrnl_medabbrev = 'BMC Biochem' where jrnl_zdb_id='ZDB-JRNL-110207-2' ;
update journal set jrnl_isoabbrev = 'BMC Biol',  jrnl_medabbrev = 'BMC Biol' where jrnl_zdb_id='ZDB-JRNL-051031-3' ;
update journal set jrnl_isoabbrev = 'BMC Biotechnol',  jrnl_medabbrev = 'BMC Biotechnol' where jrnl_zdb_id='ZDB-JRNL-050621-35' ;
update journal set jrnl_isoabbrev = 'BMC Cancer',  jrnl_medabbrev = 'BMC Cancer' where jrnl_zdb_id='ZDB-JRNL-090505-1' ;
update journal set jrnl_isoabbrev = 'BMC Cell Biol',  jrnl_medabbrev = 'BMC Cell Biol' where jrnl_zdb_id='ZDB-JRNL-060623-3' ;
update journal set jrnl_isoabbrev = 'BMC Chem',  jrnl_medabbrev = 'BMC Chem' where jrnl_zdb_id='ZDB-JRNL-200130-1' ;
update journal set jrnl_isoabbrev = 'BMC Complement Altern Med',  jrnl_medabbrev = 'BMC Complement Altern Med' where jrnl_zdb_id='ZDB-JRNL-150501-1' ;
update journal set jrnl_isoabbrev = 'BMC Complement Med Ther',  jrnl_medabbrev = 'BMC Complement Med Ther' where jrnl_zdb_id='ZDB-JRNL-220109-1' ;
update journal set jrnl_isoabbrev = 'BMC Dev Biol',  jrnl_medabbrev = 'BMC Dev Biol' where jrnl_zdb_id='ZDB-JRNL-050621-307' ;
update journal set jrnl_isoabbrev = 'BMC Ecol Evol',  jrnl_medabbrev = 'BMC Ecol Evol' where jrnl_zdb_id='ZDB-JRNL-210319-1' ;
update journal set jrnl_isoabbrev = 'BMC Genet',  jrnl_medabbrev = 'BMC Genet' where jrnl_zdb_id='ZDB-JRNL-081121-1' ;
update journal set jrnl_isoabbrev = 'BMC Genomics',  jrnl_medabbrev = 'BMC Genomics' where jrnl_zdb_id='ZDB-JRNL-050621-54' ;
update journal set jrnl_isoabbrev = 'BMC Immunol',  jrnl_medabbrev = 'BMC Immunol' where jrnl_zdb_id='ZDB-JRNL-080630-4' ;
update journal set jrnl_isoabbrev = 'BMC Med Genet',  jrnl_medabbrev = 'BMC Med Genet' where jrnl_zdb_id='ZDB-JRNL-050810-2' ;
update journal set jrnl_isoabbrev = 'BMC Med Genomics',  jrnl_medabbrev = 'BMC Med Genomics' where jrnl_zdb_id='ZDB-JRNL-110602-1' ;
update journal set jrnl_isoabbrev = 'BMC Microbiol',  jrnl_medabbrev = 'BMC Microbiol' where jrnl_zdb_id='ZDB-JRNL-110425-1' ;
update journal set jrnl_isoabbrev = 'BMC Mol Cell Biol',  jrnl_medabbrev = 'BMC Mol Cell Biol' where jrnl_zdb_id='ZDB-JRNL-191130-1' ;
update journal set jrnl_isoabbrev = 'BMC Mol Biol',  jrnl_medabbrev = 'BMC Mol Biol' where jrnl_zdb_id='ZDB-JRNL-070523-6' ;
update journal set jrnl_isoabbrev = 'BMC Neurol',  jrnl_medabbrev = 'BMC Neurol' where jrnl_zdb_id='ZDB-JRNL-170909-1' ;
update journal set jrnl_isoabbrev = 'BMC Neurosci',  jrnl_medabbrev = 'BMC Neurosci' where jrnl_zdb_id='ZDB-JRNL-050621-72' ;
update journal set jrnl_isoabbrev = 'BMC Ophthalmol',  jrnl_medabbrev = 'BMC Ophthalmol' where jrnl_zdb_id='ZDB-JRNL-101101-2' ;
update journal set jrnl_isoabbrev = 'BMC Pediatr',  jrnl_medabbrev = 'BMC Pediatr' where jrnl_zdb_id='ZDB-JRNL-210401-1' ;
update journal set jrnl_isoabbrev = 'BMC Pharmacol',  jrnl_medabbrev = 'BMC Pharmacol' where jrnl_zdb_id='ZDB-JRNL-080610-1' ;
update journal set jrnl_isoabbrev = 'BMC Pharmacol Toxicol',  jrnl_medabbrev = 'BMC Pharmacol Toxicol' where jrnl_zdb_id='ZDB-JRNL-140513-3' ;
update journal set jrnl_isoabbrev = 'BMC Physiol',  jrnl_medabbrev = 'BMC Physiol' where jrnl_zdb_id='ZDB-JRNL-080227-1' ;
update journal set jrnl_isoabbrev = 'BMC Res Notes',  jrnl_medabbrev = 'BMC Res Notes' where jrnl_zdb_id='ZDB-JRNL-091120-5' ;
update journal set jrnl_isoabbrev = 'BMC Struct Biol',  jrnl_medabbrev = 'BMC Struct Biol' where jrnl_zdb_id='ZDB-JRNL-050621-86' ;
update journal set jrnl_isoabbrev = 'BMC Syst Biol',  jrnl_medabbrev = 'BMC Syst Biol' where jrnl_zdb_id='ZDB-JRNL-110214-2' ;
update journal set jrnl_isoabbrev = 'BMC Vet Res',  jrnl_medabbrev = 'BMC Vet Res' where jrnl_zdb_id='ZDB-JRNL-141026-1' ;
update journal set jrnl_isoabbrev = 'BMJ Open Diabetes Res Care',  jrnl_medabbrev = 'BMJ Open Diabetes Res Care' where jrnl_zdb_id='ZDB-JRNL-190924-2' ;
update journal set jrnl_isoabbrev = 'Bone Joint Res',  jrnl_medabbrev = 'Bone Joint Res' where jrnl_zdb_id='ZDB-JRNL-150705-1' ;
update journal set jrnl_isoabbrev = 'Bonekey Rep',  jrnl_medabbrev = 'Bonekey Rep' where jrnl_zdb_id='ZDB-JRNL-140318-1' ;
update journal set jrnl_isoabbrev = 'Bone Rep',  jrnl_medabbrev = 'Bone Rep' where jrnl_zdb_id='ZDB-JRNL-190808-1' ;
update journal set jrnl_isoabbrev = 'Brain Behav',  jrnl_medabbrev = 'Brain Behav' where jrnl_zdb_id='ZDB-JRNL-191022-1' ;
update journal set jrnl_isoabbrev = 'Brain Behav Immun Health',  jrnl_medabbrev = 'Brain Behav Immun Health' where jrnl_zdb_id='ZDB-JRNL-211001-1' ;
update journal set jrnl_isoabbrev = 'Brain Commun',  jrnl_medabbrev = 'Brain Commun' where jrnl_zdb_id='ZDB-JRNL-191102-1' ;
update journal set jrnl_isoabbrev = 'Br J Med Med Res',  jrnl_medabbrev = 'Br J Med Med Res' where jrnl_zdb_id='ZDB-JRNL-170214-5' ;
update journal set jrnl_isoabbrev = 'Cancer Cell Int',  jrnl_medabbrev = 'Cancer Cell Int' where jrnl_zdb_id='ZDB-JRNL-161110-1' ;
update journal set jrnl_isoabbrev = 'Cancer Commun (Lond)',  jrnl_medabbrev = 'Cancer Commun (Lond)' where jrnl_zdb_id='ZDB-JRNL-200822-1' ;
update journal set jrnl_isoabbrev = 'Cancer Drug Resist',  jrnl_medabbrev = 'Cancer Drug Resist' where jrnl_zdb_id='ZDB-JRNL-210728-1' ;
update journal set jrnl_isoabbrev = 'Cancer Manag Res',  jrnl_medabbrev = 'Cancer Manag Res' where jrnl_zdb_id='ZDB-JRNL-190227-1' ;
update journal set jrnl_isoabbrev = 'Cancer Med',  jrnl_medabbrev = 'Cancer Med' where jrnl_zdb_id='ZDB-JRNL-181118-1' ;
update journal set jrnl_isoabbrev = 'Cancer Rep (Hoboken)',  jrnl_medabbrev = 'Cancer Rep (Hoboken)' where jrnl_zdb_id='ZDB-JRNL-200729-1' ;
update journal set jrnl_isoabbrev = 'Carbon N Y',  jrnl_medabbrev = 'Carbon N Y' where jrnl_zdb_id='ZDB-JRNL-080825-1' ;
update journal set jrnl_isoabbrev = 'Cardiovasc Regen Med',  jrnl_medabbrev = 'Cardiovasc Regen Med' where jrnl_zdb_id='ZDB-JRNL-170214-7' ;
update journal set jrnl_isoabbrev = 'Cellbio (Irvine, Calif)',  jrnl_medabbrev = 'Cellbio (Irvine, Calif)' where jrnl_zdb_id='ZDB-JRNL-141209-3' ;
update journal set jrnl_isoabbrev = 'Cell Biosci',  jrnl_medabbrev = 'Cell Biosci' where jrnl_zdb_id='ZDB-JRNL-111011-4' ;
update journal set jrnl_isoabbrev = 'Cell Commun Signal',  jrnl_medabbrev = 'Cell Commun Signal' where jrnl_zdb_id='ZDB-JRNL-100621-1' ;
update journal set jrnl_isoabbrev = 'Cell Death Discov',  jrnl_medabbrev = 'Cell Death Discov' where jrnl_zdb_id='ZDB-JRNL-170829-1' ;
update journal set jrnl_isoabbrev = 'Cell Dev Biol',  jrnl_medabbrev = 'Cell Dev Biol' where jrnl_zdb_id='ZDB-JRNL-140524-1' ;
update journal set jrnl_isoabbrev = 'Cell Div',  jrnl_medabbrev = 'Cell Div' where jrnl_zdb_id='ZDB-JRNL-120928-2' ;
update journal set jrnl_isoabbrev = 'Cell Regen',  jrnl_medabbrev = 'Cell Regen' where jrnl_zdb_id='ZDB-JRNL-141120-1' ;
update journal set jrnl_isoabbrev = 'Cells',  jrnl_medabbrev = 'Cells' where jrnl_zdb_id='ZDB-JRNL-140513-10' ;
update journal set jrnl_isoabbrev = 'Cell Stress',  jrnl_medabbrev = 'Cell Stress' where jrnl_zdb_id='ZDB-JRNL-200618-1' ;
update journal set jrnl_isoabbrev = 'Cell Mol Gastroenterol Hepatol',  jrnl_medabbrev = 'Cell Mol Gastroenterol Hepatol' where jrnl_zdb_id='ZDB-JRNL-170504-1' ;
update journal set jrnl_isoabbrev = 'CEUR Workshop Proc',  jrnl_medabbrev = 'CEUR Workshop Proc' where jrnl_zdb_id='ZDB-JRNL-170222-1' ;
update journal set jrnl_isoabbrev = 'ChemistryOpen',  jrnl_medabbrev = 'ChemistryOpen' where jrnl_zdb_id='ZDB-JRNL-170209-1' ;
update journal set jrnl_isoabbrev = 'Chin J Nat Med',  jrnl_medabbrev = 'Chin J Nat Med' where jrnl_zdb_id='ZDB-JRNL-140404-2' ;
update journal set jrnl_isoabbrev = 'Chin Med',  jrnl_medabbrev = 'Chin Med' where jrnl_zdb_id='ZDB-JRNL-110518-6' ;
update journal set jrnl_isoabbrev = 'Cilia',  jrnl_medabbrev = 'Cilia' where jrnl_zdb_id='ZDB-JRNL-130206-1' ;
update journal set jrnl_isoabbrev = 'Circ Genom Precis Med',  jrnl_medabbrev = 'Circ Genom Precis Med' where jrnl_zdb_id='ZDB-JRNL-180316-1' ;
update journal set jrnl_isoabbrev = 'Clin Transl Med',  jrnl_medabbrev = 'Clin Transl Med' where jrnl_zdb_id='ZDB-JRNL-201201-1' ;
update journal set jrnl_isoabbrev = 'Clin Cosmet Investig Dermatol',  jrnl_medabbrev = 'Clin Cosmet Investig Dermatol' where jrnl_zdb_id='ZDB-JRNL-210914-1' ;
update journal set jrnl_isoabbrev = 'Clin Nephrol Res',  jrnl_medabbrev = 'Clin Nephrol Res' where jrnl_zdb_id='ZDB-JRNL-180321-1' ;
update journal set jrnl_isoabbrev = 'Clocks Sleep',  jrnl_medabbrev = 'Clocks Sleep' where jrnl_zdb_id='ZDB-JRNL-211224-1' ;
update journal set jrnl_isoabbrev = 'Cold Spring Harb Mol Case Stud',  jrnl_medabbrev = 'Cold Spring Harb Mol Case Stud' where jrnl_zdb_id='ZDB-JRNL-160506-1' ;
update journal set jrnl_isoabbrev = 'Cold Spring Harb Perspect Biol',  jrnl_medabbrev = 'Cold Spring Harb Perspect Biol' where jrnl_zdb_id='ZDB-JRNL-100322-3' ;
update journal set jrnl_isoabbrev = 'Cold Spring Harb Perspect Med',  jrnl_medabbrev = 'Cold Spring Harb Perspect Med' where jrnl_zdb_id='ZDB-JRNL-130603-1' ;
update journal set jrnl_isoabbrev = 'Cold Spring Harb Protoc',  jrnl_medabbrev = 'Cold Spring Harb Protoc' where jrnl_zdb_id='ZDB-JRNL-100726-3' ;
update journal set jrnl_isoabbrev = 'Commun Biol',  jrnl_medabbrev = 'Commun Biol' where jrnl_zdb_id='ZDB-JRNL-181003-1' ;
update journal set jrnl_isoabbrev = 'Commun Integr Biol',  jrnl_medabbrev = 'Commun Integr Biol' where jrnl_zdb_id='ZDB-JRNL-100830-2' ;
update journal set jrnl_isoabbrev = 'Compr Physiol',  jrnl_medabbrev = 'Compr Physiol' where jrnl_zdb_id='ZDB-JRNL-130816-4' ;
update journal set jrnl_isoabbrev = 'Compr Rev Food Sci Food Saf',  jrnl_medabbrev = 'Compr Rev Food Sci Food Saf' where jrnl_zdb_id='ZDB-JRNL-201230-1' ;
update journal set jrnl_isoabbrev = 'C R Acad Hebd Seances Acad Sci D',  jrnl_medabbrev = 'C R Acad Hebd Seances Acad Sci D' where jrnl_zdb_id='ZDB-JRNL-161129-2' ;
update journal set jrnl_isoabbrev = 'Comput Struct Biotechnol J',  jrnl_medabbrev = 'Comput Struct Biotechnol J' where jrnl_zdb_id='ZDB-JRNL-150225-1' ;
update journal set jrnl_isoabbrev = 'Comput Toxicol',  jrnl_medabbrev = 'Comput Toxicol' where jrnl_zdb_id='ZDB-JRNL-190906-1' ;
update journal set jrnl_isoabbrev = 'Conserv Physiol',  jrnl_medabbrev = 'Conserv Physiol' where jrnl_zdb_id='ZDB-JRNL-170110-1' ;
update journal set jrnl_isoabbrev = 'CPT Pharmacometrics Syst Pharmacol',  jrnl_medabbrev = 'CPT Pharmacometrics Syst Pharmacol' where jrnl_zdb_id='ZDB-JRNL-180426-1' ;
update journal set jrnl_isoabbrev = 'Crit Care',  jrnl_medabbrev = 'Crit Care' where jrnl_zdb_id='ZDB-JRNL-210224-1' ;
update journal set jrnl_isoabbrev = 'Curr Dev Nutr',  jrnl_medabbrev = 'Curr Dev Nutr' where jrnl_zdb_id='ZDB-JRNL-190622-1' ;
update journal set jrnl_isoabbrev = 'Curr Environ Health Rep',  jrnl_medabbrev = 'Curr Environ Health Rep' where jrnl_zdb_id='ZDB-JRNL-150214-1' ;
update journal set jrnl_isoabbrev = 'Curr Mol Biol Rep',  jrnl_medabbrev = 'Curr Mol Biol Rep' where jrnl_zdb_id='ZDB-JRNL-180630-1' ;
update journal set jrnl_isoabbrev = 'Curr Neurobiol',  jrnl_medabbrev = 'Curr Neurobiol' where jrnl_zdb_id='ZDB-JRNL-160812-3' ;
update journal set jrnl_isoabbrev = 'Curr Obes Rep',  jrnl_medabbrev = 'Curr Obes Rep' where jrnl_zdb_id='ZDB-JRNL-140722-2' ;
update journal set jrnl_isoabbrev = 'Curr Opin Physiol',  jrnl_medabbrev = 'Curr Opin Physiol' where jrnl_zdb_id='ZDB-JRNL-191206-1' ;
update journal set jrnl_isoabbrev = 'Curr Pathobiol Rep',  jrnl_medabbrev = 'Curr Pathobiol Rep' where jrnl_zdb_id='ZDB-JRNL-150301-1' ;
update journal set jrnl_isoabbrev = 'Curr Protoc',  jrnl_medabbrev = 'Curr Protoc' where jrnl_zdb_id='ZDB-JRNL-210209-1' ;
update journal set jrnl_isoabbrev = 'Curr Protoc Bioinformatics',  jrnl_medabbrev = 'Curr Protoc Bioinformatics' where jrnl_zdb_id='ZDB-JRNL-100929-1' ;
update journal set jrnl_isoabbrev = 'Curr Protoc Chem Biol',  jrnl_medabbrev = 'Curr Protoc Chem Biol' where jrnl_zdb_id='ZDB-JRNL-121004-3' ;
update journal set jrnl_isoabbrev = 'Curr Protoc Hum Genet',  jrnl_medabbrev = 'Curr Protoc Hum Genet' where jrnl_zdb_id='ZDB-JRNL-080429-1' ;
update journal set jrnl_isoabbrev = 'Curr Protoc Microbiol',  jrnl_medabbrev = 'Curr Protoc Microbiol' where jrnl_zdb_id='ZDB-JRNL-080908-1' ;
update journal set jrnl_isoabbrev = 'Curr Protoc Pharmacol',  jrnl_medabbrev = 'Curr Protoc Pharmacol' where jrnl_zdb_id='ZDB-JRNL-130322-2' ;
update journal set jrnl_isoabbrev = 'Curr Protoc Toxicol',  jrnl_medabbrev = 'Curr Protoc Toxicol' where jrnl_zdb_id='ZDB-JRNL-050712-1' ;
update journal set jrnl_isoabbrev = 'Curr Res Microb Sci',  jrnl_medabbrev = 'Curr Res Microb Sci' where jrnl_zdb_id='ZDB-JRNL-211130-1' ;
update journal set jrnl_isoabbrev = 'Curr Res Physiol',  jrnl_medabbrev = 'Curr Res Physiol' where jrnl_zdb_id='ZDB-JRNL-220208-1' ;
update journal set jrnl_isoabbrev = 'Curr Res Toxicol',  jrnl_medabbrev = 'Curr Res Toxicol' where jrnl_zdb_id='ZDB-JRNL-211214-2' ;
update journal set jrnl_isoabbrev = 'Curr Stem Cell Rep',  jrnl_medabbrev = 'Curr Stem Cell Rep' where jrnl_zdb_id='ZDB-JRNL-180622-1' ;
update journal set jrnl_isoabbrev = 'Database (Oxford)',  jrnl_medabbrev = 'Database (Oxford)' where jrnl_zdb_id='ZDB-JRNL-140513-15' ;
update journal set jrnl_isoabbrev = 'Data Brief',  jrnl_medabbrev = 'Data Brief' where jrnl_zdb_id='ZDB-JRNL-150729-2' ;
update journal set jrnl_isoabbrev = 'Dermatol Online J',  jrnl_medabbrev = 'Dermatol Online J' where jrnl_zdb_id='ZDB-JRNL-160913-1' ;
update journal set jrnl_isoabbrev = 'Diagnostics (Basel)',  jrnl_medabbrev = 'Diagnostics (Basel)' where jrnl_zdb_id='ZDB-JRNL-200615-2' ;
update journal set jrnl_isoabbrev = 'Diseases',  jrnl_medabbrev = 'Diseases' where jrnl_zdb_id='ZDB-JRNL-161120-1' ;
update journal set jrnl_isoabbrev = 'Dose Response',  jrnl_medabbrev = 'Dose Response' where jrnl_zdb_id='ZDB-JRNL-110103-1' ;
update journal set jrnl_isoabbrev = 'Drug Des Devel Ther',  jrnl_medabbrev = 'Drug Des Devel Ther' where jrnl_zdb_id='ZDB-JRNL-140830-1' ;
update journal set jrnl_isoabbrev = 'Drug Discov Today Technol',  jrnl_medabbrev = 'Drug Discov Today Technol' where jrnl_zdb_id='ZDB-JRNL-140706-2' ;
update journal set jrnl_isoabbrev = 'EBioMedicine',  jrnl_medabbrev = 'EBioMedicine' where jrnl_zdb_id='ZDB-JRNL-150619-1' ;
update journal set jrnl_isoabbrev = 'Ecol Evol',  jrnl_medabbrev = 'Ecol Evol' where jrnl_zdb_id='ZDB-JRNL-180711-1' ;
update journal set jrnl_isoabbrev = 'Emerg Microbes Infect',  jrnl_medabbrev = 'Emerg Microbes Infect' where jrnl_zdb_id='ZDB-JRNL-150604-1' ;
update journal set jrnl_isoabbrev = 'Endocr Connect',  jrnl_medabbrev = 'Endocr Connect' where jrnl_zdb_id='ZDB-JRNL-200207-1' ;
update journal set jrnl_isoabbrev = 'eNeuro',  jrnl_medabbrev = 'eNeuro' where jrnl_zdb_id='ZDB-JRNL-151016-4' ;
update journal set jrnl_isoabbrev = 'Environ Biotechnol',  jrnl_medabbrev = 'Environ Biotechnol' where jrnl_zdb_id='ZDB-JRNL-130131-1' ;
update journal set jrnl_isoabbrev = 'Environ Epigenet',  jrnl_medabbrev = 'Environ Epigenet' where jrnl_zdb_id='ZDB-JRNL-150817-1' ;
update journal set jrnl_isoabbrev = 'Environ Health Toxicol',  jrnl_medabbrev = 'Environ Health Toxicol' where jrnl_zdb_id='ZDB-JRNL-111130-1' ;
update journal set jrnl_isoabbrev = 'Environ Sci Technol Lett',  jrnl_medabbrev = 'Environ Sci Technol Lett' where jrnl_zdb_id='ZDB-JRNL-171011-1' ;
update journal set jrnl_isoabbrev = 'Epigenetics Chromatin',  jrnl_medabbrev = 'Epigenetics Chromatin' where jrnl_zdb_id='ZDB-JRNL-170418-1' ;
update journal set jrnl_isoabbrev = 'Epilepsia Open',  jrnl_medabbrev = 'Epilepsia Open' where jrnl_zdb_id='ZDB-JRNL-211022-1' ;
update journal set jrnl_isoabbrev = 'Eur Heart J',  jrnl_medabbrev = 'Eur Heart J' where jrnl_zdb_id='ZDB-JRNL-150724-1' ;
update journal set jrnl_isoabbrev = 'Evodevo',  jrnl_medabbrev = 'Evodevo' where jrnl_zdb_id='ZDB-JRNL-101108-1' ;
update journal set jrnl_isoabbrev = 'Evol Appl',  jrnl_medabbrev = 'Evol Appl' where jrnl_zdb_id='ZDB-JRNL-130710-2' ;
update journal set jrnl_isoabbrev = 'Evol Bioinform Online',  jrnl_medabbrev = 'Evol Bioinform Online' where jrnl_zdb_id='ZDB-JRNL-200403-3' ;
update journal set jrnl_isoabbrev = 'Evol Lett',  jrnl_medabbrev = 'Evol Lett' where jrnl_zdb_id='ZDB-JRNL-181220-1' ;
update journal set jrnl_isoabbrev = 'EXCLI J',  jrnl_medabbrev = 'EXCLI J' where jrnl_zdb_id='ZDB-JRNL-151125-1' ;
update journal set jrnl_isoabbrev = 'F1000Res',  jrnl_medabbrev = 'F1000Res' where jrnl_zdb_id='ZDB-JRNL-140731-1' ;
update journal set jrnl_isoabbrev = 'FASEB Bioadv',  jrnl_medabbrev = 'FASEB Bioadv' where jrnl_zdb_id='ZDB-JRNL-200304-1' ;
update journal set jrnl_isoabbrev = 'Fauna Flora',  jrnl_medabbrev = 'Fauna Flora' where jrnl_zdb_id='ZDB-JRNL-050621-591' ;
update journal set jrnl_isoabbrev = 'FEBS Open Bio',  jrnl_medabbrev = 'FEBS Open Bio' where jrnl_zdb_id='ZDB-JRNL-140101-5' ;
update journal set jrnl_isoabbrev = 'Fluids Barriers CNS',  jrnl_medabbrev = 'Fluids Barriers CNS' where jrnl_zdb_id='ZDB-JRNL-110316-6' ;
update journal set jrnl_isoabbrev = 'Folia Biol (Krakow)',  jrnl_medabbrev = 'Folia Biol (Krakow)' where jrnl_zdb_id='ZDB-JRNL-160121-1' ;
update journal set jrnl_isoabbrev = 'Folia Morphol (Praha)',  jrnl_medabbrev = 'Folia Morphol (Praha)' where jrnl_zdb_id='ZDB-JRNL-160227-1' ;
update journal set jrnl_isoabbrev = 'Foods',  jrnl_medabbrev = 'Foods' where jrnl_zdb_id='ZDB-JRNL-170915-1' ;
update journal set jrnl_isoabbrev = 'Food Sci Nutr',  jrnl_medabbrev = 'Food Sci Nutr' where jrnl_zdb_id='ZDB-JRNL-191030-1' ;
update journal set jrnl_isoabbrev = 'Front Aging Neurosci',  jrnl_medabbrev = 'Front Aging Neurosci' where jrnl_zdb_id='ZDB-JRNL-150108-1' ;
update journal set jrnl_isoabbrev = 'Front Bioeng Biotechnol',  jrnl_medabbrev = 'Front Bioeng Biotechnol' where jrnl_zdb_id='ZDB-JRNL-160730-1' ;
update journal set jrnl_isoabbrev = 'Front Cell Dev Biol',  jrnl_medabbrev = 'Front Cell Dev Biol' where jrnl_zdb_id='ZDB-JRNL-141105-1' ;
update journal set jrnl_isoabbrev = 'Front Cell Infect Microbiol',  jrnl_medabbrev = 'Front Cell Infect Microbiol' where jrnl_zdb_id='ZDB-JRNL-150130-1' ;
update journal set jrnl_isoabbrev = 'Front Chem',  jrnl_medabbrev = 'Front Chem' where jrnl_zdb_id='ZDB-JRNL-180622-2' ;
update journal set jrnl_isoabbrev = 'Front Comput Neurosci',  jrnl_medabbrev = 'Front Comput Neurosci' where jrnl_zdb_id='ZDB-JRNL-190314-2' ;
update journal set jrnl_isoabbrev = 'Front Endocrinol (Lausanne)',  jrnl_medabbrev = 'Front Endocrinol (Lausanne)' where jrnl_zdb_id='ZDB-JRNL-140917-1' ;
update journal set jrnl_isoabbrev = 'Front Environ Sci',  jrnl_medabbrev = 'Front Environ Sci' where jrnl_zdb_id='ZDB-JRNL-210730-1' ;
update journal set jrnl_isoabbrev = 'Front Genet',  jrnl_medabbrev = 'Front Genet' where jrnl_zdb_id='ZDB-JRNL-140523-1' ;
update journal set jrnl_isoabbrev = 'Front Immunol',  jrnl_medabbrev = 'Front Immunol' where jrnl_zdb_id='ZDB-JRNL-151210-1' ;
update journal set jrnl_isoabbrev = 'Front Integr Neurosci',  jrnl_medabbrev = 'Front Integr Neurosci' where jrnl_zdb_id='ZDB-JRNL-110907-4' ;
update journal set jrnl_isoabbrev = 'Front Med (Lausanne)',  jrnl_medabbrev = 'Front Med (Lausanne)' where jrnl_zdb_id='ZDB-JRNL-201006-1' ;
update journal set jrnl_isoabbrev = 'Front Microbiol',  jrnl_medabbrev = 'Front Microbiol' where jrnl_zdb_id='ZDB-JRNL-140612-1' ;
update journal set jrnl_isoabbrev = 'Front Mol Biosci',  jrnl_medabbrev = 'Front Mol Biosci' where jrnl_zdb_id='ZDB-JRNL-200522-1' ;
update journal set jrnl_isoabbrev = 'Front Neural Circuits',  jrnl_medabbrev = 'Front Neural Circuits' where jrnl_zdb_id='ZDB-JRNL-091101-1' ;
update journal set jrnl_isoabbrev = 'Front Neuroanat',  jrnl_medabbrev = 'Front Neuroanat' where jrnl_zdb_id='ZDB-JRNL-110524-2' ;
update journal set jrnl_isoabbrev = 'Front Neuroinform',  jrnl_medabbrev = 'Front Neuroinform' where jrnl_zdb_id='ZDB-JRNL-140415-4' ;
update journal set jrnl_isoabbrev = 'Front Neurol',  jrnl_medabbrev = 'Front Neurol' where jrnl_zdb_id='ZDB-JRNL-161130-1' ;
update journal set jrnl_isoabbrev = 'Front Nutr',  jrnl_medabbrev = 'Front Nutr' where jrnl_zdb_id='ZDB-JRNL-200717-2' ;
update journal set jrnl_isoabbrev = 'Front Oncol',  jrnl_medabbrev = 'Front Oncol' where jrnl_zdb_id='ZDB-JRNL-170913-1' ;
update journal set jrnl_isoabbrev = 'Front Pediatr',  jrnl_medabbrev = 'Front Pediatr' where jrnl_zdb_id='ZDB-JRNL-170407-1' ;
update journal set jrnl_isoabbrev = 'Front Pharmacol',  jrnl_medabbrev = 'Front Pharmacol' where jrnl_zdb_id='ZDB-JRNL-140513-20' ;
update journal set jrnl_isoabbrev = 'Front Physiol',  jrnl_medabbrev = 'Front Physiol' where jrnl_zdb_id='ZDB-JRNL-120301-2' ;
update journal set jrnl_isoabbrev = 'Front Psychiatry',  jrnl_medabbrev = 'Front Psychiatry' where jrnl_zdb_id='ZDB-JRNL-170901-1' ;
update journal set jrnl_isoabbrev = 'Front Psychol',  jrnl_medabbrev = 'Front Psychol' where jrnl_zdb_id='ZDB-JRNL-181218-1' ;
update journal set jrnl_isoabbrev = 'Front Public Health',  jrnl_medabbrev = 'Front Public Health' where jrnl_zdb_id='ZDB-JRNL-170510-1' ;
update journal set jrnl_isoabbrev = 'Front Robot AI',  jrnl_medabbrev = 'Front Robot AI' where jrnl_zdb_id='ZDB-JRNL-210128-2' ;
update journal set jrnl_isoabbrev = 'Front Synaptic Neurosci',  jrnl_medabbrev = 'Front Synaptic Neurosci' where jrnl_zdb_id='ZDB-JRNL-220205-1' ;
update journal set jrnl_isoabbrev = 'Front Syst Neurosci',  jrnl_medabbrev = 'Front Syst Neurosci' where jrnl_zdb_id='ZDB-JRNL-110920-1' ;
update journal set jrnl_isoabbrev = 'Front Vet Sci',  jrnl_medabbrev = 'Front Vet Sci' where jrnl_zdb_id='ZDB-JRNL-210209-2' ;
update journal set jrnl_isoabbrev = 'Front Zool',  jrnl_medabbrev = 'Front Zool' where jrnl_zdb_id='ZDB-JRNL-060323-1' ;
update journal set jrnl_isoabbrev = 'Gen Med (Los Angel)',  jrnl_medabbrev = 'Gen Med (Los Angel)' where jrnl_zdb_id='ZDB-JRNL-140513-21' ;
update journal set jrnl_isoabbrev = 'Gene Regul Syst Bio',  jrnl_medabbrev = 'Gene Regul Syst Bio' where jrnl_zdb_id='ZDB-JRNL-170622-1' ;
update journal set jrnl_isoabbrev = 'Genes (Basel)',  jrnl_medabbrev = 'Genes (Basel)' where jrnl_zdb_id='ZDB-JRNL-150626-2' ;
update journal set jrnl_isoabbrev = 'Genet Mol Res',  jrnl_medabbrev = 'Genet Mol Res' where jrnl_zdb_id='ZDB-JRNL-091221-3' ;
update journal set jrnl_isoabbrev = 'Genome Announc',  jrnl_medabbrev = 'Genome Announc' where jrnl_zdb_id='ZDB-JRNL-131108-3' ;
update journal set jrnl_isoabbrev = 'Genom Data',  jrnl_medabbrev = 'Genom Data' where jrnl_zdb_id='ZDB-JRNL-150623-2' ;
update journal set jrnl_isoabbrev = 'Gigascience',  jrnl_medabbrev = 'Gigascience' where jrnl_zdb_id='ZDB-JRNL-150320-1' ;
update journal set jrnl_isoabbrev = 'Glob Cardiol Sci Pract',  jrnl_medabbrev = 'Glob Cardiol Sci Pract' where jrnl_zdb_id='ZDB-JRNL-191206-2' ;
update journal set jrnl_isoabbrev = 'Gut Pathog',  jrnl_medabbrev = 'Gut Pathog' where jrnl_zdb_id='ZDB-JRNL-180321-2' ;
update journal set jrnl_isoabbrev = 'Hepatol Commun',  jrnl_medabbrev = 'Hepatol Commun' where jrnl_zdb_id='ZDB-JRNL-180207-1' ;
update journal set jrnl_isoabbrev = 'HGG Adv',  jrnl_medabbrev = 'HGG Adv' where jrnl_zdb_id='ZDB-JRNL-220121-1' ;
update journal set jrnl_isoabbrev = 'Hum Genome Var',  jrnl_medabbrev = 'Hum Genome Var' where jrnl_zdb_id='ZDB-JRNL-180531-2' ;
update journal set jrnl_isoabbrev = 'IBRO Rep',  jrnl_medabbrev = 'IBRO Rep' where jrnl_zdb_id='ZDB-JRNL-180825-1' ;
update journal set jrnl_isoabbrev = 'IEEE Trans Med Imaging',  jrnl_medabbrev = 'IEEE Trans Med Imaging' where jrnl_zdb_id='ZDB-JRNL-101011-1' ;
update journal set jrnl_isoabbrev = 'Immun Inflamm Dis',  jrnl_medabbrev = 'Immun Inflamm Dis' where jrnl_zdb_id='ZDB-JRNL-171222-2' ;
update journal set jrnl_isoabbrev = 'Immunohorizons',  jrnl_medabbrev = 'Immunohorizons' where jrnl_zdb_id='ZDB-JRNL-200810-1' ;
update journal set jrnl_isoabbrev = 'Inside Cell',  jrnl_medabbrev = 'Inside Cell' where jrnl_zdb_id='ZDB-JRNL-160429-1' ;
update journal set jrnl_isoabbrev = 'Integr Environ Assess Manag',  jrnl_medabbrev = 'Integr Environ Assess Manag' where jrnl_zdb_id='ZDB-JRNL-100910-3' ;
update journal set jrnl_isoabbrev = 'Integr Org Biol',  jrnl_medabbrev = 'Integr Org Biol' where jrnl_zdb_id='ZDB-JRNL-210402-1' ;
update journal set jrnl_isoabbrev = 'Interdiscip Toxicol',  jrnl_medabbrev = 'Interdiscip Toxicol' where jrnl_zdb_id='ZDB-JRNL-131202-1' ;
update journal set jrnl_isoabbrev = 'Int J Parasitol Drugs Drug Resist',  jrnl_medabbrev = 'Int J Parasitol Drugs Drug Resist' where jrnl_zdb_id='ZDB-JRNL-210525-1' ;
update journal set jrnl_isoabbrev = 'Int J Biol Sci',  jrnl_medabbrev = 'Int J Biol Sci' where jrnl_zdb_id='ZDB-JRNL-080922-2' ;
update journal set jrnl_isoabbrev = 'Int J Clin Exp Med',  jrnl_medabbrev = 'Int J Clin Exp Med' where jrnl_zdb_id='ZDB-JRNL-150918-1' ;
update journal set jrnl_isoabbrev = 'Int J Clin Exp Pathol',  jrnl_medabbrev = 'Int J Clin Exp Pathol' where jrnl_zdb_id='ZDB-JRNL-150721-1' ;
update journal set jrnl_isoabbrev = 'Int J Med Sci',  jrnl_medabbrev = 'Int J Med Sci' where jrnl_zdb_id='ZDB-JRNL-170822-1' ;
update journal set jrnl_isoabbrev = 'Int J Physiol Pathophysiol Pharmacol',  jrnl_medabbrev = 'Int J Physiol Pathophysiol Pharmacol' where jrnl_zdb_id='ZDB-JRNL-110719-4' ;
update journal set jrnl_isoabbrev = 'iScience',  jrnl_medabbrev = 'iScience' where jrnl_zdb_id='ZDB-JRNL-180612-1' ;
update journal set jrnl_isoabbrev = 'ISRN Hematol',  jrnl_medabbrev = 'ISRN Hematol' where jrnl_zdb_id='ZDB-JRNL-120807-1' ;
update journal set jrnl_isoabbrev = 'Ital J Pediatr',  jrnl_medabbrev = 'Ital J Pediatr' where jrnl_zdb_id='ZDB-JRNL-210723-1' ;
update journal set jrnl_isoabbrev = 'JACC Basic Transl Sci',  jrnl_medabbrev = 'JACC Basic Transl Sci' where jrnl_zdb_id='ZDB-JRNL-161224-1' ;
update journal set jrnl_isoabbrev = 'JAMA Netw Open',  jrnl_medabbrev = 'JAMA Netw Open' where jrnl_zdb_id='ZDB-JRNL-210113-1' ;
update journal set jrnl_isoabbrev = 'JBMR Plus',  jrnl_medabbrev = 'JBMR Plus' where jrnl_zdb_id='ZDB-JRNL-210223-1' ;
update journal set jrnl_isoabbrev = 'JCI Insight',  jrnl_medabbrev = 'JCI Insight' where jrnl_zdb_id='ZDB-JRNL-160514-1' ;
update journal set jrnl_isoabbrev = 'J Alzheimers Dis Rep',  jrnl_medabbrev = 'J Alzheimers Dis Rep' where jrnl_zdb_id='ZDB-JRNL-210701-1' ;
update journal set jrnl_isoabbrev = 'J Appl Aquac',  jrnl_medabbrev = 'J Appl Aquac' where jrnl_zdb_id='ZDB-JRNL-140403-2' ;
update journal set jrnl_isoabbrev = 'J Behav Neurosci Res',  jrnl_medabbrev = 'J Behav Neurosci Res' where jrnl_zdb_id='ZDB-JRNL-081201-1' ;
update journal set jrnl_isoabbrev = 'J Biol Methods',  jrnl_medabbrev = 'J Biol Methods' where jrnl_zdb_id='ZDB-JRNL-190828-1' ;
update journal set jrnl_isoabbrev = 'J Biomed Semantics',  jrnl_medabbrev = 'J Biomed Semantics' where jrnl_zdb_id='ZDB-JRNL-140513-27' ;
update journal set jrnl_isoabbrev = 'J Cancer',  jrnl_medabbrev = 'J Cancer' where jrnl_zdb_id='ZDB-JRNL-180119-1' ;
update journal set jrnl_isoabbrev = 'J Cannabis Res',  jrnl_medabbrev = 'J Cannabis Res' where jrnl_zdb_id='ZDB-JRNL-211003-1' ;
update journal set jrnl_isoabbrev = 'J Carcinog Mutagen',  jrnl_medabbrev = 'J Carcinog Mutagen' where jrnl_zdb_id='ZDB-JRNL-160812-6' ;
update journal set jrnl_isoabbrev = 'J Cardiovasc Dev Dis',  jrnl_medabbrev = 'J Cardiovasc Dev Dis' where jrnl_zdb_id='ZDB-JRNL-160506-2' ;
update journal set jrnl_isoabbrev = 'J Clin Transl Sci',  jrnl_medabbrev = 'J Clin Transl Sci' where jrnl_zdb_id='ZDB-JRNL-210824-2' ;
update journal set jrnl_isoabbrev = 'J Clin Med',  jrnl_medabbrev = 'J Clin Med' where jrnl_zdb_id='ZDB-JRNL-181215-1' ;
update journal set jrnl_isoabbrev = 'J Cosmet Dermatol',  jrnl_medabbrev = 'J Cosmet Dermatol' where jrnl_zdb_id='ZDB-JRNL-101011-4' ;
update journal set jrnl_isoabbrev = 'J Dev Biol',  jrnl_medabbrev = 'J Dev Biol' where jrnl_zdb_id='ZDB-JRNL-140614-1' ;
update journal set jrnl_isoabbrev = 'J Diabetes Metab Disord',  jrnl_medabbrev = 'J Diabetes Metab Disord' where jrnl_zdb_id='ZDB-JRNL-210209-3' ;
update journal set jrnl_isoabbrev = 'J Environ Anal Toxicol',  jrnl_medabbrev = 'J Environ Anal Toxicol' where jrnl_zdb_id='ZDB-JRNL-130109-1' ;
update journal set jrnl_isoabbrev = 'J Evid Based Integr Med',  jrnl_medabbrev = 'J Evid Based Integr Med' where jrnl_zdb_id='ZDB-JRNL-210429-1' ;
update journal set jrnl_isoabbrev = 'J Exp Neurosci',  jrnl_medabbrev = 'J Exp Neurosci' where jrnl_zdb_id='ZDB-JRNL-100830-1' ;
update journal set jrnl_isoabbrev = 'J Exp Pharmacol',  jrnl_medabbrev = 'J Exp Pharmacol' where jrnl_zdb_id='ZDB-JRNL-211214-3' ;
update journal set jrnl_isoabbrev = 'J Form Des Learn',  jrnl_medabbrev = 'J Form Des Learn' where jrnl_zdb_id='ZDB-JRNL-190903-1' ;
update journal set jrnl_isoabbrev = 'J Fungi (Basel)',  jrnl_medabbrev = 'J Fungi (Basel)' where jrnl_zdb_id='ZDB-JRNL-181216-1' ;
update journal set jrnl_isoabbrev = 'J Genomics',  jrnl_medabbrev = 'J Genomics' where jrnl_zdb_id='ZDB-JRNL-180102-1' ;
update journal set jrnl_isoabbrev = 'J Ichthyol',  jrnl_medabbrev = 'J Ichthyol' where jrnl_zdb_id='ZDB-JRNL-180815-2' ;
update journal set jrnl_isoabbrev = 'J Imaging',  jrnl_medabbrev = 'J Imaging' where jrnl_zdb_id='ZDB-JRNL-210902-2' ;
update journal set jrnl_isoabbrev = 'J Inflamm Res',  jrnl_medabbrev = 'J Inflamm Res' where jrnl_zdb_id='ZDB-JRNL-191108-1' ;
update journal set jrnl_isoabbrev = 'J Insect Sci',  jrnl_medabbrev = 'J Insect Sci' where jrnl_zdb_id='ZDB-JRNL-141202-2' ;
update journal set jrnl_isoabbrev = 'J Integr Bioinform',  jrnl_medabbrev = 'J Integr Bioinform' where jrnl_zdb_id='ZDB-JRNL-100420-1' ;
update journal set jrnl_isoabbrev = 'J Mater Chem',  jrnl_medabbrev = 'J Mater Chem' where jrnl_zdb_id='ZDB-JRNL-120222-1' ;
update journal set jrnl_isoabbrev = 'J Nanobiotechnology',  jrnl_medabbrev = 'J Nanobiotechnology' where jrnl_zdb_id='ZDB-JRNL-160822-1' ;
update journal set jrnl_isoabbrev = 'J Neuroinflammation',  jrnl_medabbrev = 'J Neuroinflammation' where jrnl_zdb_id='ZDB-JRNL-160821-1' ;
update journal set jrnl_isoabbrev = 'J Neurol Neuromedicine',  jrnl_medabbrev = 'J Neurol Neuromedicine' where jrnl_zdb_id='ZDB-JRNL-190614-2' ;
update journal set jrnl_isoabbrev = 'J Pers Med',  jrnl_medabbrev = 'J Pers Med' where jrnl_zdb_id='ZDB-JRNL-210407-1' ;
update journal set jrnl_isoabbrev = 'J Proteomics Bioinform',  jrnl_medabbrev = 'J Proteomics Bioinform' where jrnl_zdb_id='ZDB-JRNL-160812-4' ;
update journal set jrnl_isoabbrev = 'J Exp Anal Behav',  jrnl_medabbrev = 'J Exp Anal Behav' where jrnl_zdb_id='ZDB-JRNL-110502-1' ;
update journal set jrnl_isoabbrev = 'J S C Acad Sci',  jrnl_medabbrev = 'J S C Acad Sci' where jrnl_zdb_id='ZDB-JRNL-180630-2' ;
update journal set jrnl_isoabbrev = 'J Tradit Complement Med',  jrnl_medabbrev = 'J Tradit Complement Med' where jrnl_zdb_id='ZDB-JRNL-141108-1' ;
update journal set jrnl_isoabbrev = 'J Transl Med',  jrnl_medabbrev = 'J Transl Med' where jrnl_zdb_id='ZDB-JRNL-170405-1' ;
update journal set jrnl_isoabbrev = 'J Undergrad Neurosci Educ',  jrnl_medabbrev = 'J Undergrad Neurosci Educ' where jrnl_zdb_id='ZDB-JRNL-150108-2' ;
update journal set jrnl_isoabbrev = 'J Vis',  jrnl_medabbrev = 'J Vis' where jrnl_zdb_id='ZDB-JRNL-110520-1' ;
update journal set jrnl_isoabbrev = 'J Vis Exp',  jrnl_medabbrev = 'J Vis Exp' where jrnl_zdb_id='ZDB-JRNL-081008-3' ;
update journal set jrnl_isoabbrev = 'Kidney Int Rep',  jrnl_medabbrev = 'Kidney Int Rep' where jrnl_zdb_id='ZDB-JRNL-171117-1' ;
update journal set jrnl_isoabbrev = 'Life (Basel)',  jrnl_medabbrev = 'Life (Basel)' where jrnl_zdb_id='ZDB-JRNL-160812-2' ;
update journal set jrnl_isoabbrev = 'Life Sci Alliance',  jrnl_medabbrev = 'Life Sci Alliance' where jrnl_zdb_id='ZDB-JRNL-191011-1' ;
update journal set jrnl_isoabbrev = 'Lipids Health Dis',  jrnl_medabbrev = 'Lipids Health Dis' where jrnl_zdb_id='ZDB-JRNL-100614-2' ;
update journal set jrnl_isoabbrev = 'Mar Drugs',  jrnl_medabbrev = 'Mar Drugs' where jrnl_zdb_id='ZDB-JRNL-100719-8' ;
update journal set jrnl_isoabbrev = 'Materials (Basel)',  jrnl_medabbrev = 'Materials (Basel)' where jrnl_zdb_id='ZDB-JRNL-170806-1' ;
update journal set jrnl_isoabbrev = 'Mater Today Bio',  jrnl_medabbrev = 'Mater Today Bio' where jrnl_zdb_id='ZDB-JRNL-210831-1' ;
update journal set jrnl_isoabbrev = 'Matrix Biol Plus',  jrnl_medabbrev = 'Matrix Biol Plus' where jrnl_zdb_id='ZDB-JRNL-210207-1' ;
update journal set jrnl_isoabbrev = 'mBio',  jrnl_medabbrev = 'mBio' where jrnl_zdb_id='ZDB-JRNL-141218-1' ;
update journal set jrnl_isoabbrev = 'MedComm (2020)',  jrnl_medabbrev = 'MedComm (2020)' where jrnl_zdb_id='ZDB-JRNL-211116-1' ;
update journal set jrnl_isoabbrev = 'Med Image Comput Comput Assist Interv',  jrnl_medabbrev = 'Med Image Comput Comput Assist Interv' where jrnl_zdb_id='ZDB-JRNL-211230-1' ;
update journal set jrnl_isoabbrev = 'Medicina (B Aires)',  jrnl_medabbrev = 'Medicina (B Aires)' where jrnl_zdb_id='ZDB-JRNL-190206-1' ;
update journal set jrnl_isoabbrev = 'Medicine (Baltimore)',  jrnl_medabbrev = 'Medicine (Baltimore)' where jrnl_zdb_id='ZDB-JRNL-180615-1' ;
update journal set jrnl_isoabbrev = 'Medicines (Basel)',  jrnl_medabbrev = 'Medicines (Basel)' where jrnl_zdb_id='ZDB-JRNL-190604-1' ;
update journal set jrnl_isoabbrev = 'Metabolites',  jrnl_medabbrev = 'Metabolites' where jrnl_zdb_id='ZDB-JRNL-140626-1' ;
update journal set jrnl_isoabbrev = 'Meta Gene',  jrnl_medabbrev = 'Meta Gene' where jrnl_zdb_id='ZDB-JRNL-160216-2' ;
update journal set jrnl_isoabbrev = 'Methods Appl Fluoresc',  jrnl_medabbrev = 'Methods Appl Fluoresc' where jrnl_zdb_id='ZDB-JRNL-180510-1' ;
update journal set jrnl_isoabbrev = 'Methods Protoc',  jrnl_medabbrev = 'Methods Protoc' where jrnl_zdb_id='ZDB-JRNL-190707-1' ;
update journal set jrnl_isoabbrev = 'MethodsX',  jrnl_medabbrev = 'MethodsX' where jrnl_zdb_id='ZDB-JRNL-180727-2' ;
update journal set jrnl_isoabbrev = 'Microb Biotechnol',  jrnl_medabbrev = 'Microb Biotechnol' where jrnl_zdb_id='ZDB-JRNL-150429-1' ;
update journal set jrnl_isoabbrev = 'Microb Cell Fact',  jrnl_medabbrev = 'Microb Cell Fact' where jrnl_zdb_id='ZDB-JRNL-111111-2' ;
update journal set jrnl_isoabbrev = 'Microb Cell',  jrnl_medabbrev = 'Microb Cell' where jrnl_zdb_id='ZDB-JRNL-170401-1' ;
update journal set jrnl_isoabbrev = 'Microb Genom',  jrnl_medabbrev = 'Microb Genom' where jrnl_zdb_id='ZDB-JRNL-200724-1' ;
update journal set jrnl_isoabbrev = 'Microbiologyopen',  jrnl_medabbrev = 'Microbiologyopen' where jrnl_zdb_id='ZDB-JRNL-180327-2' ;
update journal set jrnl_isoabbrev = 'Microbiol Spectr',  jrnl_medabbrev = 'Microbiol Spectr' where jrnl_zdb_id='ZDB-JRNL-150422-2' ;
update journal set jrnl_isoabbrev = 'Microbiome',  jrnl_medabbrev = 'Microbiome' where jrnl_zdb_id='ZDB-JRNL-150331-3' ;
update journal set jrnl_isoabbrev = 'Micromachines (Basel)',  jrnl_medabbrev = 'Micromachines (Basel)' where jrnl_zdb_id='ZDB-JRNL-181110-1' ;
update journal set jrnl_isoabbrev = 'Microorganisms',  jrnl_medabbrev = 'Microorganisms' where jrnl_zdb_id='ZDB-JRNL-200422-5' ;
update journal set jrnl_isoabbrev = 'Mob DNA',  jrnl_medabbrev = 'Mob DNA' where jrnl_zdb_id='ZDB-JRNL-160211-1' ;
update journal set jrnl_isoabbrev = 'Mol Autism',  jrnl_medabbrev = 'Mol Autism' where jrnl_zdb_id='ZDB-JRNL-171013-1' ;
update journal set jrnl_isoabbrev = 'Mol Biomed',  jrnl_medabbrev = 'Mol Biomed' where jrnl_zdb_id='ZDB-JRNL-220111-2' ;
update journal set jrnl_isoabbrev = 'Mol Cancer',  jrnl_medabbrev = 'Mol Cancer' where jrnl_zdb_id='ZDB-JRNL-061108-1' ;
update journal set jrnl_isoabbrev = 'Mol Cytogenet',  jrnl_medabbrev = 'Mol Cytogenet' where jrnl_zdb_id='ZDB-JRNL-140619-1' ;
update journal set jrnl_isoabbrev = 'Mol Genet Metab Rep',  jrnl_medabbrev = 'Mol Genet Metab Rep' where jrnl_zdb_id='ZDB-JRNL-161203-1' ;
update journal set jrnl_isoabbrev = 'Mol Genet Genomic Med',  jrnl_medabbrev = 'Mol Genet Genomic Med' where jrnl_zdb_id='ZDB-JRNL-141022-1' ;
update journal set jrnl_isoabbrev = 'Mol Metab',  jrnl_medabbrev = 'Mol Metab' where jrnl_zdb_id='ZDB-JRNL-161108-1' ;
update journal set jrnl_isoabbrev = 'Mol Neurodegener',  jrnl_medabbrev = 'Mol Neurodegener' where jrnl_zdb_id='ZDB-JRNL-090302-1' ;
update journal set jrnl_isoabbrev = 'Mol Omics',  jrnl_medabbrev = 'Mol Omics' where jrnl_zdb_id='ZDB-JRNL-180421-1' ;
update journal set jrnl_isoabbrev = 'Mol Syst Biol',  jrnl_medabbrev = 'Mol Syst Biol' where jrnl_zdb_id='ZDB-JRNL-100128-1' ;
update journal set jrnl_isoabbrev = 'Mol Ther Methods Clin Dev',  jrnl_medabbrev = 'Mol Ther Methods Clin Dev' where jrnl_zdb_id='ZDB-JRNL-200529-1' ;
update journal set jrnl_isoabbrev = 'Mol Ther Nucleic Acids',  jrnl_medabbrev = 'Mol Ther Nucleic Acids' where jrnl_zdb_id='ZDB-JRNL-190724-1' ;
update journal set jrnl_isoabbrev = 'Mol Vis',  jrnl_medabbrev = 'Mol Vis' where jrnl_zdb_id='ZDB-JRNL-050621-1020' ;
update journal set jrnl_isoabbrev = 'Monoclon Antib Immunodiagn Immunother',  jrnl_medabbrev = 'Monoclon Antib Immunodiagn Immunother' where jrnl_zdb_id='ZDB-JRNL-161207-1' ;
update journal set jrnl_isoabbrev = 'mSphere',  jrnl_medabbrev = 'mSphere' where jrnl_zdb_id='ZDB-JRNL-160616-1' ;
update journal set jrnl_isoabbrev = 'mSystems',  jrnl_medabbrev = 'mSystems' where jrnl_zdb_id='ZDB-JRNL-210915-1' ;
update journal set jrnl_isoabbrev = 'Mycopathologia',  jrnl_medabbrev = 'Mycopathologia' where jrnl_zdb_id='ZDB-JRNL-190902-1' ;
update journal set jrnl_isoabbrev = 'NanoImpact',  jrnl_medabbrev = 'NanoImpact' where jrnl_zdb_id='ZDB-JRNL-200307-4' ;
update journal set jrnl_isoabbrev = 'Nanomaterials (Basel)',  jrnl_medabbrev = 'Nanomaterials (Basel)' where jrnl_zdb_id='ZDB-JRNL-150728-1' ;
update journal set jrnl_isoabbrev = 'Nanoscale Adv',  jrnl_medabbrev = 'Nanoscale Adv' where jrnl_zdb_id='ZDB-JRNL-210716-1' ;
update journal set jrnl_isoabbrev = 'NAR Genom Bioinform',  jrnl_medabbrev = 'NAR Genom Bioinform' where jrnl_zdb_id='ZDB-JRNL-210601-1' ;
update journal set jrnl_isoabbrev = 'Nat Biomed Eng',  jrnl_medabbrev = 'Nat Biomed Eng' where jrnl_zdb_id='ZDB-JRNL-201002-2' ;
update journal set jrnl_isoabbrev = 'Nat Biotechnol',  jrnl_medabbrev = 'Nat Biotechnol' where jrnl_zdb_id='ZDB-JRNL-160818-1' ;
update journal set jrnl_isoabbrev = 'Nat Cancer',  jrnl_medabbrev = 'Nat Cancer' where jrnl_zdb_id='ZDB-JRNL-200811-1' ;
update journal set jrnl_isoabbrev = 'Nat Ecol Evol',  jrnl_medabbrev = 'Nat Ecol Evol' where jrnl_zdb_id='ZDB-JRNL-180530-2' ;
update journal set jrnl_isoabbrev = 'Nat Metab',  jrnl_medabbrev = 'Nat Metab' where jrnl_zdb_id='ZDB-JRNL-200724-2' ;
update journal set jrnl_isoabbrev = 'Nat Microbiol',  jrnl_medabbrev = 'Nat Microbiol' where jrnl_zdb_id='ZDB-JRNL-160831-1' ;
update journal set jrnl_isoabbrev = 'Nephron',  jrnl_medabbrev = 'Nephron' where jrnl_zdb_id='ZDB-JRNL-170214-20' ;
update journal set jrnl_isoabbrev = 'Nephron Exp Nephrol',  jrnl_medabbrev = 'Nephron Exp Nephrol' where jrnl_zdb_id='ZDB-JRNL-141123-2' ;
update journal set jrnl_isoabbrev = 'Netw Neurosci',  jrnl_medabbrev = 'Netw Neurosci' where jrnl_zdb_id='ZDB-JRNL-200403-5' ;
update journal set jrnl_isoabbrev = 'Neural Dev',  jrnl_medabbrev = 'Neural Dev' where jrnl_zdb_id='ZDB-JRNL-061227-2' ;
update journal set jrnl_isoabbrev = 'Neurobiol Stress',  jrnl_medabbrev = 'Neurobiol Stress' where jrnl_zdb_id='ZDB-JRNL-211012-1' ;
update journal set jrnl_isoabbrev = 'Neurogenesis (Austin)',  jrnl_medabbrev = 'Neurogenesis (Austin)' where jrnl_zdb_id='ZDB-JRNL-160909-2' ;
update journal set jrnl_isoabbrev = 'Neurol Genet',  jrnl_medabbrev = 'Neurol Genet' where jrnl_zdb_id='ZDB-JRNL-160921-1' ;
update journal set jrnl_isoabbrev = 'Neuronal Signal',  jrnl_medabbrev = 'Neuronal Signal' where jrnl_zdb_id='ZDB-JRNL-200729-2' ;
update journal set jrnl_isoabbrev = 'New J Phys',  jrnl_medabbrev = 'New J Phys' where jrnl_zdb_id='ZDB-JRNL-170722-2' ;
update journal set jrnl_isoabbrev = 'Noncoding RNA',  jrnl_medabbrev = 'Noncoding RNA' where jrnl_zdb_id='ZDB-JRNL-190110-1' ;
update journal set jrnl_isoabbrev = 'Noncoding RNA Res',  jrnl_medabbrev = 'Noncoding RNA Res' where jrnl_zdb_id='ZDB-JRNL-180901-1' ;
update journal set jrnl_isoabbrev = 'NPJ Biofilms Microbiomes',  jrnl_medabbrev = 'NPJ Biofilms Microbiomes' where jrnl_zdb_id='ZDB-JRNL-210121-1' ;
update journal set jrnl_isoabbrev = 'NPJ Genom Med',  jrnl_medabbrev = 'NPJ Genom Med' where jrnl_zdb_id='ZDB-JRNL-171223-1' ;
update journal set jrnl_isoabbrev = 'NPJ Microgravity',  jrnl_medabbrev = 'NPJ Microgravity' where jrnl_zdb_id='ZDB-JRNL-170722-1' ;
update journal set jrnl_isoabbrev = 'NPJ Precis Oncol',  jrnl_medabbrev = 'NPJ Precis Oncol' where jrnl_zdb_id='ZDB-JRNL-180130-2' ;
update journal set jrnl_isoabbrev = 'NPJ Regen Med',  jrnl_medabbrev = 'NPJ Regen Med' where jrnl_zdb_id='ZDB-JRNL-170926-1' ;
update journal set jrnl_isoabbrev = 'NPJ Schizophr',  jrnl_medabbrev = 'NPJ Schizophr' where jrnl_zdb_id='ZDB-JRNL-200207-3' ;
update journal set jrnl_isoabbrev = 'Nucl Recept',  jrnl_medabbrev = 'Nucl Recept' where jrnl_zdb_id='ZDB-JRNL-051005-1' ;
update journal set jrnl_isoabbrev = 'Nucl Recept Signal',  jrnl_medabbrev = 'Nucl Recept Signal' where jrnl_zdb_id='ZDB-JRNL-090601-1' ;
update journal set jrnl_isoabbrev = 'Nutrients',  jrnl_medabbrev = 'Nutrients' where jrnl_zdb_id='ZDB-JRNL-170704-2' ;
update journal set jrnl_isoabbrev = 'Nutr Metab (Lond)',  jrnl_medabbrev = 'Nutr Metab (Lond)' where jrnl_zdb_id='ZDB-JRNL-080902-1' ;
update journal set jrnl_isoabbrev = 'Oncogenesis',  jrnl_medabbrev = 'Oncogenesis' where jrnl_zdb_id='ZDB-JRNL-140513-40' ;
update journal set jrnl_isoabbrev = 'Onco Targets Ther',  jrnl_medabbrev = 'Onco Targets Ther' where jrnl_zdb_id='ZDB-JRNL-140728-2' ;
update journal set jrnl_isoabbrev = 'Open Life Sci',  jrnl_medabbrev = 'Open Life Sci' where jrnl_zdb_id='ZDB-JRNL-210407-2' ;
update journal set jrnl_isoabbrev = 'Optica',  jrnl_medabbrev = 'Optica' where jrnl_zdb_id='ZDB-JRNL-141209-2' ;
update journal set jrnl_isoabbrev = 'Opt Express',  jrnl_medabbrev = 'Opt Express' where jrnl_zdb_id='ZDB-JRNL-080908-2' ;
update journal set jrnl_isoabbrev = 'Orphanet J Rare Dis',  jrnl_medabbrev = 'Orphanet J Rare Dis' where jrnl_zdb_id='ZDB-JRNL-140513-41' ;
update journal set jrnl_isoabbrev = 'Orthop Traumatol Surg Res',  jrnl_medabbrev = 'Orthop Traumatol Surg Res' where jrnl_zdb_id='ZDB-JRNL-190227-2' ;
update journal set jrnl_isoabbrev = 'Orthop Res Rev',  jrnl_medabbrev = 'Orthop Res Rev' where jrnl_zdb_id='ZDB-JRNL-190220-2' ;
update journal set jrnl_isoabbrev = 'Pap Phys',  jrnl_medabbrev = 'Pap Phys' where jrnl_zdb_id='ZDB-JRNL-210717-2' ;
update journal set jrnl_isoabbrev = 'Parasit Vectors',  jrnl_medabbrev = 'Parasit Vectors' where jrnl_zdb_id='ZDB-JRNL-170811-1' ;
update journal set jrnl_isoabbrev = 'Pathog Dis',  jrnl_medabbrev = 'Pathog Dis' where jrnl_zdb_id='ZDB-JRNL-180424-1' ;
update journal set jrnl_isoabbrev = 'Pathogens',  jrnl_medabbrev = 'Pathogens' where jrnl_zdb_id='ZDB-JRNL-141202-3' ;
update journal set jrnl_isoabbrev = 'PeerJ',  jrnl_medabbrev = 'PeerJ' where jrnl_zdb_id='ZDB-JRNL-130923-1' ;
update journal set jrnl_isoabbrev = 'PeerJ Comput Sci',  jrnl_medabbrev = 'PeerJ Comput Sci' where jrnl_zdb_id='ZDB-JRNL-160216-3' ;
update journal set jrnl_isoabbrev = 'Pharm Biol',  jrnl_medabbrev = 'Pharm Biol' where jrnl_zdb_id='ZDB-JRNL-161217-2' ;
update journal set jrnl_isoabbrev = 'Pharmaceuticals (Basel)',  jrnl_medabbrev = 'Pharmaceuticals (Basel)' where jrnl_zdb_id='ZDB-JRNL-190803-1' ;
update journal set jrnl_isoabbrev = 'Pharmaceutics',  jrnl_medabbrev = 'Pharmaceutics' where jrnl_zdb_id='ZDB-JRNL-200724-3' ;
update journal set jrnl_isoabbrev = 'Pharmacol Res Perspect',  jrnl_medabbrev = 'Pharmacol Res Perspect' where jrnl_zdb_id='ZDB-JRNL-160414-1' ;
update journal set jrnl_isoabbrev = 'Photoacoustics',  jrnl_medabbrev = 'Photoacoustics' where jrnl_zdb_id='ZDB-JRNL-180919-1' ;
update journal set jrnl_isoabbrev = 'Photobiomodul Photomed Laser Surg',  jrnl_medabbrev = 'Photobiomodul Photomed Laser Surg' where jrnl_zdb_id='ZDB-JRNL-190507-4' ;
update journal set jrnl_isoabbrev = 'Physiol Rep',  jrnl_medabbrev = 'Physiol Rep' where jrnl_zdb_id='ZDB-JRNL-140101-1' ;
update journal set jrnl_isoabbrev = 'Plants (Basel)',  jrnl_medabbrev = 'Plants (Basel)' where jrnl_zdb_id='ZDB-JRNL-180913-1' ;
update journal set jrnl_isoabbrev = 'Plast Reconstr Surg Glob Open',  jrnl_medabbrev = 'Plast Reconstr Surg Glob Open' where jrnl_zdb_id='ZDB-JRNL-180502-3' ;
update journal set jrnl_isoabbrev = 'PLoS Curr',  jrnl_medabbrev = 'PLoS Curr' where jrnl_zdb_id='ZDB-JRNL-111205-1' ;
update journal set jrnl_isoabbrev = 'Polymers (Basel)',  jrnl_medabbrev = 'Polymers (Basel)' where jrnl_zdb_id='ZDB-JRNL-190411-1' ;
update journal set jrnl_isoabbrev = 'Prog Neurobiol',  jrnl_medabbrev = 'Prog Neurobiol' where jrnl_zdb_id='ZDB-JRNL-210114-1' ;
update journal set jrnl_isoabbrev = 'Proteome Sci',  jrnl_medabbrev = 'Proteome Sci' where jrnl_zdb_id='ZDB-JRNL-100105-1' ;
update journal set jrnl_isoabbrev = 'Rare Dis',  jrnl_medabbrev = 'Rare Dis' where jrnl_zdb_id='ZDB-JRNL-140710-2' ;
update journal set jrnl_isoabbrev = 'Regeneration (Oxf)',  jrnl_medabbrev = 'Regeneration (Oxf)' where jrnl_zdb_id='ZDB-JRNL-161208-1' ;
update journal set jrnl_isoabbrev = 'Reprod Fertil',  jrnl_medabbrev = 'Reprod Fertil' where jrnl_zdb_id='ZDB-JRNL-210706-1' ;
update journal set jrnl_isoabbrev = 'Res Pract Thromb Haemost',  jrnl_medabbrev = 'Res Pract Thromb Haemost' where jrnl_zdb_id='ZDB-JRNL-201103-2' ;
update journal set jrnl_isoabbrev = 'Retrovirology',  jrnl_medabbrev = 'Retrovirology' where jrnl_zdb_id='ZDB-JRNL-100525-1' ;
update journal set jrnl_isoabbrev = 'R I Med J (2013)',  jrnl_medabbrev = 'R I Med J (2013)' where jrnl_zdb_id='ZDB-JRNL-210303-1' ;
update journal set jrnl_isoabbrev = 'R Soc Open Sci',  jrnl_medabbrev = 'R Soc Open Sci' where jrnl_zdb_id='ZDB-JRNL-150912-3' ;
update journal set jrnl_isoabbrev = 'RSC Adv',  jrnl_medabbrev = 'RSC Adv' where jrnl_zdb_id='ZDB-JRNL-130918-1' ;
update journal set jrnl_isoabbrev = 'Sci Adv',  jrnl_medabbrev = 'Sci Adv' where jrnl_zdb_id='ZDB-JRNL-151216-1' ;
update journal set jrnl_isoabbrev = 'Sci Bull (Beijing)',  jrnl_medabbrev = 'Sci Bull (Beijing)' where jrnl_zdb_id='ZDB-JRNL-190108-1' ;
update journal set jrnl_isoabbrev = 'Sci Immunol',  jrnl_medabbrev = 'Sci Immunol' where jrnl_zdb_id='ZDB-JRNL-181118-2' ;
update journal set jrnl_isoabbrev = 'Sci Robot',  jrnl_medabbrev = 'Sci Robot' where jrnl_zdb_id='ZDB-JRNL-201103-3' ;
update journal set jrnl_isoabbrev = 'Sci Signal',  jrnl_medabbrev = 'Sci Signal' where jrnl_zdb_id='ZDB-JRNL-081008-1' ;
update journal set jrnl_isoabbrev = 'Scientifica (Cairo)',  jrnl_medabbrev = 'Scientifica (Cairo)' where jrnl_zdb_id='ZDB-JRNL-200508-1' ;
update journal set jrnl_isoabbrev = 'Sci Data',  jrnl_medabbrev = 'Sci Data' where jrnl_zdb_id='ZDB-JRNL-161110-2' ;
update journal set jrnl_isoabbrev = 'Sensors (Basel)',  jrnl_medabbrev = 'Sensors (Basel)' where jrnl_zdb_id='ZDB-JRNL-150410-1' ;
update journal set jrnl_isoabbrev = 'Skelet Muscle',  jrnl_medabbrev = 'Skelet Muscle' where jrnl_zdb_id='ZDB-JRNL-150212-1' ;
update journal set jrnl_isoabbrev = 'SOJ Neurol',  jrnl_medabbrev = 'SOJ Neurol' where jrnl_zdb_id='ZDB-JRNL-210312-3' ;
update journal set jrnl_isoabbrev = 'Springerplus',  jrnl_medabbrev = 'Springerplus' where jrnl_zdb_id='ZDB-JRNL-150620-1' ;
update journal set jrnl_isoabbrev = 'STAR Protoc',  jrnl_medabbrev = 'STAR Protoc' where jrnl_zdb_id='ZDB-JRNL-200825-2' ;
update journal set jrnl_isoabbrev = 'Stembook',  jrnl_medabbrev = 'Stembook' where jrnl_zdb_id='ZDB-JRNL-100719-5' ;
update journal set jrnl_isoabbrev = 'Stem Cell Reports',  jrnl_medabbrev = 'Stem Cell Reports' where jrnl_zdb_id='ZDB-JRNL-131010-1' ;
update journal set jrnl_isoabbrev = 'Stem Cell Res Ther',  jrnl_medabbrev = 'Stem Cell Res Ther' where jrnl_zdb_id='ZDB-JRNL-110602-2' ;
update journal set jrnl_isoabbrev = 'Stem Cells',  jrnl_medabbrev = 'Stem Cells' where jrnl_zdb_id='ZDB-JRNL-050621-1306' ;
update journal set jrnl_isoabbrev = 'Stroke Vasc Neurol',  jrnl_medabbrev = 'Stroke Vasc Neurol' where jrnl_zdb_id='ZDB-JRNL-201130-1' ;
update journal set jrnl_isoabbrev = 'AAPS J',  jrnl_medabbrev = 'AAPS J' where jrnl_zdb_id='ZDB-JRNL-141022-2' ;
update journal set jrnl_isoabbrev = 'Am J Chin Med (Gard City N Y)',  jrnl_medabbrev = 'Am J Chin Med (Gard City N Y)' where jrnl_zdb_id='ZDB-JRNL-130816-2' ;
update journal set jrnl_isoabbrev = 'Open Rheumatol J',  jrnl_medabbrev = 'Open Rheumatol J' where jrnl_zdb_id='ZDB-JRNL-141021-1' ;
update journal set jrnl_isoabbrev = 'Open Virol J',  jrnl_medabbrev = 'Open Virol J' where jrnl_zdb_id='ZDB-JRNL-130208-1' ;
update journal set jrnl_isoabbrev = 'Theranostics',  jrnl_medabbrev = 'Theranostics' where jrnl_zdb_id='ZDB-JRNL-130429-1' ;
update journal set jrnl_isoabbrev = 'Thromb J',  jrnl_medabbrev = 'Thromb J' where jrnl_zdb_id='ZDB-JRNL-170314-1' ;
update journal set jrnl_isoabbrev = 'Toxicol Rep',  jrnl_medabbrev = 'Toxicol Rep' where jrnl_zdb_id='ZDB-JRNL-150602-1' ;
update journal set jrnl_isoabbrev = 'Toxics',  jrnl_medabbrev = 'Toxics' where jrnl_zdb_id='ZDB-JRNL-170411-1' ;
update journal set jrnl_isoabbrev = 'Toxins (Basel)',  jrnl_medabbrev = 'Toxins (Basel)' where jrnl_zdb_id='ZDB-JRNL-120724-3' ;
update journal set jrnl_isoabbrev = 'Transl Neurodegener',  jrnl_medabbrev = 'Transl Neurodegener' where jrnl_zdb_id='ZDB-JRNL-180324-3' ;
update journal set jrnl_isoabbrev = 'Transl Psychiatry',  jrnl_medabbrev = 'Transl Psychiatry' where jrnl_zdb_id='ZDB-JRNL-160525-1' ;
update journal set jrnl_isoabbrev = 'Transl Vis Sci Technol',  jrnl_medabbrev = 'Transl Vis Sci Technol' where jrnl_zdb_id='ZDB-JRNL-170411-2' ;
update journal set jrnl_isoabbrev = 'Tremor Other Hyperkinet Mov (N Y)',  jrnl_medabbrev = 'Tremor Other Hyperkinet Mov (N Y)' where jrnl_zdb_id='ZDB-JRNL-191212-1' ;
update journal set jrnl_isoabbrev = 'Tren Reprod Bio',  jrnl_medabbrev = 'Tren Reprod Bio' where jrnl_zdb_id='ZDB-JRNL-080616-1' ;
update journal set jrnl_isoabbrev = 'Turk J Fish Aquat Sci',  jrnl_medabbrev = 'Turk J Fish Aquat Sci' where jrnl_zdb_id='ZDB-JRNL-151029-1' ;
update journal set jrnl_isoabbrev = 'Vaccines (Basel)',  jrnl_medabbrev = 'Vaccines (Basel)' where jrnl_zdb_id='ZDB-JRNL-200430-2' ;
update journal set jrnl_isoabbrev = 'Vasc Biol',  jrnl_medabbrev = 'Vasc Biol' where jrnl_zdb_id='ZDB-JRNL-210916-1' ;
update journal set jrnl_isoabbrev = 'Vasc Cell',  jrnl_medabbrev = 'Vasc Cell' where jrnl_zdb_id='ZDB-JRNL-120227-1' ;
update journal set jrnl_isoabbrev = 'Vet Sci',  jrnl_medabbrev = 'Vet Sci' where jrnl_zdb_id='ZDB-JRNL-190320-2' ;
update journal set jrnl_isoabbrev = 'Viruses',  jrnl_medabbrev = 'Viruses' where jrnl_zdb_id='ZDB-JRNL-180613-2' ;
update journal set jrnl_isoabbrev = 'Wellcome Open Res',  jrnl_medabbrev = 'Wellcome Open Res' where jrnl_zdb_id='ZDB-JRNL-180209-1' ;
update journal set jrnl_isoabbrev = 'Wiley Interdiscip Rev Syst Biol Med',  jrnl_medabbrev = 'Wiley Interdiscip Rev Syst Biol Med' where jrnl_zdb_id='ZDB-JRNL-101011-3' ;
update journal set jrnl_isoabbrev = 'World J Clin Oncol',  jrnl_medabbrev = 'World J Clin Oncol' where jrnl_zdb_id='ZDB-JRNL-220126-1' ;
update journal set jrnl_isoabbrev = 'World J Exp Med',  jrnl_medabbrev = 'World J Exp Med' where jrnl_zdb_id='ZDB-JRNL-160302-1' ;
update journal set jrnl_isoabbrev = 'World J Hepatol',  jrnl_medabbrev = 'World J Hepatol' where jrnl_zdb_id='ZDB-JRNL-170331-1' ;
update journal set jrnl_isoabbrev = 'World J Psychiatry',  jrnl_medabbrev = 'World J Psychiatry' where jrnl_zdb_id='ZDB-JRNL-200828-2' ;
update journal set jrnl_isoabbrev = 'World J Stem Cells',  jrnl_medabbrev = 'World J Stem Cells' where jrnl_zdb_id='ZDB-JRNL-140927-2' ;
update journal set jrnl_isoabbrev = 'Zoological Lett',  jrnl_medabbrev = 'Zoological Lett' where jrnl_zdb_id='ZDB-JRNL-170308-1' ;