update mutation_detail_controlled_vocabulary set mdcv_term_order = 1
where mdcv_term_display_name = 'A>T';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 2
where mdcv_term_display_name = 'A>C';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 3
where mdcv_term_display_name = 'A>G';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 4
where mdcv_term_display_name = 'T>A';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 5
where mdcv_term_display_name = 'T>C';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 6
where mdcv_term_display_name = 'T>G';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 7
where mdcv_term_display_name = 'C>A';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 8
where mdcv_term_display_name = 'C>T';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 9
where mdcv_term_display_name = 'C>G';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 10
where mdcv_term_display_name = 'G>A';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 11
where mdcv_term_display_name = 'G>T';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 12
where mdcv_term_display_name = 'G>C';

update mutation_detail_controlled_vocabulary set mdcv_term_order = 1
where mdcv_term_display_name = 'exon';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 2
where mdcv_term_display_name = 'intron';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 3
where mdcv_term_display_name = 'donor splice site';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 4
where mdcv_term_display_name = 'acceptor splice site';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 5
where mdcv_term_display_name = 'splice junction';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 6
where mdcv_term_display_name = 'promoter';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 7
where mdcv_term_display_name = 'start codon';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 8
where mdcv_term_display_name = "5' UTR";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 9
where mdcv_term_display_name = "3' UTR";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 10
where mdcv_term_display_name = 'enhancer';


update mutation_detail_controlled_vocabulary set mdcv_term_order = 1
where mdcv_term_display_name = 'stop gain';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 2
where mdcv_term_display_name = 'missense';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 3
where mdcv_term_display_name = 'splicing variant';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 4
where mdcv_term_display_name = 'splice site variant';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 5
where mdcv_term_display_name = 'cryptic site variant';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 6
where mdcv_term_display_name = 'cryptic site acceptor';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 7
where mdcv_term_display_name = 'cryptic site donor';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 8
where mdcv_term_display_name = "intron gain";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 9
where mdcv_term_display_name = "exon loss";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 10
where mdcv_term_display_name = 'frameshift';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 11
where mdcv_term_display_name = 'frameshift truncation';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 12
where mdcv_term_display_name = 'inframe deletion';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 13
where mdcv_term_display_name = 'start loss';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 14
where mdcv_term_display_name = 'stop loss';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 15
where mdcv_term_display_name = "3' UTR variant";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 16
where mdcv_term_display_name = "5' UTR variant";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 17
where mdcv_term_display_name = 'nonsynonymous';

update mutation_detail_controlled_vocabulary set mdcv_term_order = 1
where mdcv_term_display_name = 'polypeptide truncation';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 2
where mdcv_term_display_name = 'amino acid substitution';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 3
where mdcv_term_display_name = 'amino acid deletion';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 4
where mdcv_term_display_name = 'amino acid insertion';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 5
where mdcv_term_display_name = 'non conservative amino acid substitution';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 6
where mdcv_term_display_name = 'elongated polypeptide';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 7
where mdcv_term_display_name = 'polypeptide fusion';


update mutation_detail_controlled_vocabulary set mdcv_term_order = 1
where mdcv_term_display_name = 'Ala';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 2
where mdcv_term_display_name = 'Arg';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 3
where mdcv_term_display_name = 'Asn';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 4
where mdcv_term_display_name = 'Asp';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 5
where mdcv_term_display_name = 'Cys';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 6
where mdcv_term_display_name = 'Gln';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 7
where mdcv_term_display_name = 'Glu';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 8
where mdcv_term_display_name = "Bly";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 9
where mdcv_term_display_name = "Dci";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 10
where mdcv_term_display_name = 'Ile';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 11
where mdcv_term_display_name = 'Leu';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 12
where mdcv_term_display_name = 'Lys';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 13
where mdcv_term_display_name = 'Met';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 14
where mdcv_term_display_name = 'Phe';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 15
where mdcv_term_display_name = "Pro";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 16
where mdcv_term_display_name = "Pyl";
update mutation_detail_controlled_vocabulary set mdcv_term_order = 17
where mdcv_term_display_name = 'Sec';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 18
where mdcv_term_display_name = 'Ser';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 19
where mdcv_term_display_name = 'Thr';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 20
where mdcv_term_display_name = 'Trp';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 21
where mdcv_term_display_name = 'Tyr';
update mutation_detail_controlled_vocabulary set mdcv_term_order = 22
where mdcv_term_display_name = 'Val';


