#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Lab app pages.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/ZFIN/APP_PAGES/lab_files

GENERICS = do-labupdate.apg labselect.apg \
	labupdate.apg labview.apg new_lab.apg process-lab.apg
STATICS = labprintable.apg setup-new-lab.apg update-lab.apg

# Use default rules for app page directories

include $(TOP)/make.default.apg.rules

