---------------------------------------------------------------------
-- Generate a FR#/EU# to ZFIN gene and EST/cDNA translatin table
-- for Thisse. This is specific for Fast Release data, and it need to 
-- load from a file, thus we have it separate from the function.
-- We started out with only FR#, EU# is added upon later. We kept
-- old temp table names but changed input/output file names to minimize
-- confusion.
-- 
-- INPUT:
--     accession.unl: generated by parseThisse.pl
-- OUTPUT:
--     thisseName_ZfinMarker.txt: FR#/EU# to ZFIN gene and EST/cDNA translation table
--
----------------------------------------------------------------------

begin work;

-- FR_GENE_TMP --
--------------------------

create temp table fr_acc_tmp ( 
	fracc_fr	varchar(10) not null,
	fracc_acc   	varchar(30) not null
)with no log;

load from './accession.unl' insert into fr_acc_tmp; 

create temp table fr_gene_tmp ( 
	frgn_fr			varchar(10) not null,
	frgn_gene_zdb_id	varchar(50) not null,
	frgn_gene_symbol	varchar(50) not null,
	frgn_est_zdb_id		varchar(50) not null,
	frgn_est_name 		varchar(50) not null
)with no log;

-- FR# load and EU# load are exclusive. Thus instead of 
-- adding a parameter and condition clause, we simply 
-- update this sql to look for either. 
insert into fr_gene_tmp 
	select fracc_fr, g.mrkr_zdb_id, g.mrkr_abbrev, 
	       c.mrkr_zdb_id, c.mrkr_name
	  from fr_acc_tmp, marker g, marker c, db_link,
	       expression_experiment
     	 where fracc_acc = dblink_acc_num
	   and dblink_linked_recid = xpatex_probe_feature_zdb_id
	   and xpatex_direct_submission_date = TODAY
	   and (xpatex_source_zdb_id = "ZDB-PUB-040907-1"
		or xpatex_source_zdb_id = "ZDB-PUB-051025-1" ) 
	   and xpatex_probe_feature_zdb_id = c.mrkr_zdb_id
	   and xpatex_gene_zdb_id = g.mrkr_zdb_id;

unload to 'thisseName_ZfinMarker.txt'
	select *
      	  from fr_gene_tmp
      order by frgn_gene_symbol; 

commit work;