---------------------------------------------------------------------
-- Generate a FR# to ZFIN gene and EST/cDNA translatin table
-- for Thisse. Since this is specific, and need to load from 
-- file, we have it separately.
--
-- INPUT:
--       frAcc.unl: generated by parseThisse.pl
-- OUTPUT:
--       fr_gene.txt: FR# to ZFIN gene and EST/cDNA translation table
--
----------------------------------------------------------------------

begin work;

-- FR_GENE_TMP --
--------------------------

create temp table fr_acc_tmp ( 
	fracc_fr	varchar(10) not null,
	fracc_acc   	varchar(30) not null primary key
)with no log;

load from './frAcc.unl' insert into fr_acc_tmp; 

create temp table fr_gene_tmp ( 
	frgn_fr			varchar(10) not null,
	frgn_gene_zdb_id	varchar(50) not null,
	frgn_gene_symbol	varchar(50) not null,
	frgn_est_zdb_id		varchar(50) not null,
	frgn_est_name 		varchar(50) not null
)with no log;

insert into fr_gene_tmp 
	select fracc_fr, g.mrkr_zdb_id, g.mrkr_abbrev, 
	       c.mrkr_zdb_id, c.mrkr_name
	  from fr_acc_tmp, marker g, marker c, db_link,
	       expression_experiment
     	 where fracc_acc = dblink_acc_num
	   and dblink_linked_recid = xpatex_probe_feature_zdb_id
	   and xpatex_direct_submission_date = TODAY
	   and xpatex_source_zdb_id = "ZDB-PUB-040907-1"
	   and xpatex_probe_feature_zdb_id = c.mrkr_zdb_id
	   and xpatex_gene_zdb_id = g.mrkr_zdb_id;

unload to 'fr_gene.txt'
	select *
      	  from fr_gene_tmp
      order by frgn_gene_symbol; 

commit work;