#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Low resolution Anatomy Static 
# web pages
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/anatomy/lowres

STATICS =  120hrsdorsal.gif 120hrslateral.gif \
	24hrsdorsal.gif 24hrslateral.gif \
	48hrsdorsal.gif 48hrslateral.gif \
	72hrsdorsal.gif 72hrslateral.gif \
	S001.gif S002.gif S003.gif S004.gif S005.gif \
	S006.gif S007.gif S008.gif S009.gif S010.gif S011.gif S012.gif \
	S013.gif S014.gif S015.gif S016.gif S017.gif S018.gif S019.gif \
	S020.gif S021.gif S022.gif S023.gif S024.gif S025.gif S026.gif \
	S027.gif S028.gif S029.gif S030.gif S031.gif S032.gif S033.gif \
	S034.gif S035.gif S036.gif S037.gif S038.gif S039.gif S040.gif \
	S041.gif S042.gif S043.gif S044.gif S045.gif S045M.gif S046.gif \
	S047.gif S048.gif S049.gif S050.gif S051.gif S052.gif S053.gif \
	S054.gif S055.gif S056.gif S057.gif S058.gif S059.gif S059_5.gif \
	S060.gif S061.gif S062.gif S063.gif S064.gif S065.gif S066.gif \
	S067.gif S068.gif S069.gif S070.gif S071.gif S072.gif S073.gif \
	S074.gif S075.gif S076.gif S077.gif


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
