
drop index 
construct_search_temp_all_names_bts_index;

drop index
construct_component_search_temp_all_promoter_names_bts_index;

drop index
construct_component_search_temp_all_coding_names_bts_index;

drop index
construct_component_search_temp_all_engineered_names_bts_index;

drop index
construct_gene_feature_result_view_temp_all_allele_gene_names_bts_index;

drop index
figure_term_construct_search_temp_bts_index;

delete from construct_gene_feature_result_view_temp;
delete from construct_search_temp;
delete from construct_component_search_temp;
delete from construct_gene_feature_result_view_temp;
delete from figure_term_Construct_search_temp;

delete from construct_gene_feature_result_view_backup;
delete from construct_search_backup;
delete from construct_component_search_backup;
delete from construct_gene_feature_result_view_backup;
delete from figure_term_Construct_search_backup;