

drop index construct_search_temp_all_names_bts_index;
drop index construct_component_search_temp_all_promoter_names_bts_index;
drop index construct_component_search_temp_all_coding_names_bts_index;
drop index construct_component_search_temp_all_engineered_names_bts_index;
drop index construct_gene_feature_result_view_temp_all_allele_gene_names_bts_index;
drop index figure_term_construct_search_temp_bts_index;

delete from construct_search_Temp;

delete from construct_component_search_temp;

delete from construct_gene_feature_result_View_temp;

delete from figure_Term_construct_search_temp;


delete from construct_component_search_temp;

delete from construct_gene_feature_result_View_temp;

delete from figure_Term_construct_search_temp;
