--liquibase formatted sql

-- ZIRC line submission schema (consolidated).
--
-- Originally landed across 19 migrations (0050..0230); collapsed into a
-- single script before merge since none of the intermediate states ever
-- existed in any non-dev environment. The shape below is the cumulative
-- end state — anything an earlier ALTER added has been folded into the
-- CREATE; anything later DROPped is simply absent.
--
-- All tables live in the dedicated PostgreSQL schema `zirc`. Cross-zirc
-- FKs are qualified (e.g. zirc.line_submission). FKs out to existing
-- ZFIN tables (person, marker) live in public — left unqualified,
-- resolved via search_path.
--
-- Naming convention: every column is prefixed with the first letters
-- of each word in the table name (line_submission -> ls_,
-- line_submission_linked_feature -> lslf_, genotyping_assay -> ga_,
-- genotyping_assay_file -> af_). Single-word tables get the first
-- letter (m_, g_, l_, p_).
--
-- Internal FKs (within the submission tree) are ON DELETE CASCADE so
-- removing a submission removes its mutations / lesions / assays /
-- phenotypes / publications / linked-feature pairs / file rows in one
-- shot. FKs out to person and marker are RESTRICT.

--changeset rtaylor:zirc-line-submission-schema
CREATE SCHEMA IF NOT EXISTS zirc;

-- ─── Root: line_submission ────────────────────────────────────────────
--
-- ls_zdb_id is a ZFIN-style ZDB ID (ZDB-LINESUBMISSION-YYmmdd-NN)
-- generated by org.zfin.database.ZdbIdGenerator at insert time; the
-- generator also inserts the matching row in zdb_active_data, which
-- satisfies the FK below.
--
-- ls_reasons / ls_reasons_other: acceptance reasons are a CHECKBOX_GROUP
-- with an "Other" option. The list of canonical snake_case values lives
-- in TEXT[]; the free-text Other answer lives in its own column.
--
-- ls_is_draft / ls_submitted_at / ls_deleted_at: lifecycle state. New
-- submissions start as drafts (ls_is_draft = TRUE); curators flip the
-- draft flag and set ls_submitted_at on submission. Soft-delete uses
-- ls_deleted_at rather than removing the row outright.
CREATE TABLE zirc.line_submission (
    ls_zdb_id                        TEXT         PRIMARY KEY
                                                  CONSTRAINT line_submission_zdb_id_active_data_fk
                                                  REFERENCES zdb_active_data(zactvd_zdb_id)
                                                  ON UPDATE RESTRICT ON DELETE CASCADE,
    ls_name                          VARCHAR(255),
    ls_abbreviation                  VARCHAR(255),
    ls_previous_names                VARCHAR(255),
    ls_maternal_background           VARCHAR(255),
    ls_paternal_background           VARCHAR(255),
    ls_background_changeable         BOOLEAN,
    ls_background_change_concerns    TEXT,
    ls_unreported_features_details   TEXT,
    ls_additional_info               TEXT,
    ls_single_allelic                BOOLEAN,
    ls_husbandry_info                TEXT,
    ls_reasons                       TEXT[]       NOT NULL DEFAULT '{}',
    ls_reasons_other                 TEXT,
    ls_is_draft                      BOOLEAN      NOT NULL DEFAULT TRUE,
    ls_deleted_at                    TIMESTAMP,
    ls_submitted_at                  TIMESTAMP,
    ls_created_at                    TIMESTAMP    NOT NULL DEFAULT now(),
    ls_updated_at                    TIMESTAMP    NOT NULL DEFAULT now()
);

-- BEFORE UPDATE trigger keeps ls_updated_at current. The function is in
-- the zirc schema rather than public so it's clearly co-owned.
CREATE OR REPLACE FUNCTION zirc.line_submission_auto_timestamp()
RETURNS TRIGGER AS '
BEGIN
    NEW.ls_updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
' LANGUAGE plpgsql;

CREATE TRIGGER trg_line_submission_auto_timestamp
BEFORE UPDATE ON zirc.line_submission
FOR EACH ROW
EXECUTE FUNCTION zirc.line_submission_auto_timestamp();

-- Submitters / contacts / PIs / contributors.
CREATE TABLE zirc.line_submission_person (
    lsp_line_submission_id TEXT        NOT NULL
        CONSTRAINT fk_line_submission_person_submission
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    lsp_person_zdb_id      TEXT        NOT NULL
        CONSTRAINT fk_line_submission_person_person
            REFERENCES person(zdb_id),
    lsp_role               VARCHAR(50) NOT NULL,
    lsp_sort_order         INTEGER     NOT NULL,
    lsp_created_at         TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT line_submission_person_pk
        PRIMARY KEY (lsp_line_submission_id, lsp_person_zdb_id, lsp_role)
);

-- ─── Mutation: per-line, with its own children ────────────────────────
--
-- m_allele_in_zfin: did the curator pick an existing ZFIN marker for the
-- allele, or enter a new free-text designation? Drives the form's
-- autocomplete-vs-text-field toggle.
--
-- m_mutagenesis_stage / m_mutagenesis_protocol / m_mutagenesis_protocol_other:
-- mutagenesis is split into a life-stage dropdown and a protocol
-- dropdown; the protocol additionally allows an "Other" free-text
-- companion.
CREATE TABLE zirc.mutation (
    m_id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    m_line_submission_id           TEXT   NOT NULL
        CONSTRAINT fk_mutation_line_submission
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    m_sort_order                   INTEGER NOT NULL,
    m_allele_designation           VARCHAR(255),
    m_allele_in_zfin               BOOLEAN NOT NULL DEFAULT FALSE,
    m_mutagenesis_stage            VARCHAR(50),
    m_mutagenesis_protocol         VARCHAR(255),
    m_mutagenesis_protocol_other   TEXT,
    m_molecularly_characterized    BOOLEAN,
    m_mutation_type                VARCHAR(255),
    m_homozygous_lethal            BOOLEAN,
    m_lethality_stage_typical      VARCHAR(255),
    m_lethality_specific_timepoint VARCHAR(255),
    m_lethality_window_start       VARCHAR(255),
    m_lethality_window_end         VARCHAR(255),
    m_lethality_additional_info    TEXT,
    m_zfin_record_established      BOOLEAN,
    m_cell_genomic_feature         VARCHAR(255),
    m_mutation_discoverer          VARCHAR(255),
    m_mutation_institution         VARCHAR(255)
);

-- Publications: a flat ordered list of free-text references attached to
-- one mutation. 1000 chars is generous enough for a fuller citation
-- (full author list + journal) while a ZFIN pub ID has not yet been
-- minted.
CREATE TABLE zirc.mutation_publication (
    mp_mutation_id BIGINT        NOT NULL
        CONSTRAINT fk_mutation_publication_parent
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    mp_publication VARCHAR(1000) NOT NULL,
    mp_sort_order  INTEGER       NOT NULL,
    CONSTRAINT mutation_publication_pk
        PRIMARY KEY (mp_mutation_id, mp_sort_order)
);

-- ─── Per-mutation single-row children ─────────────────────────────────
CREATE TABLE zirc.gene (
    g_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    g_mutation_id         BIGINT NOT NULL
        CONSTRAINT fk_gene_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    g_sort_order          INTEGER NOT NULL,
    g_mutated_gene        TEXT
        CONSTRAINT fk_gene_mutated_gene_marker
            REFERENCES marker(mrkr_zdb_id),
    g_linkage_group       VARCHAR(10),
    g_genbank_genomic_dna VARCHAR(255),
    g_genbank_cdna        VARCHAR(255)
);

-- Lesion: column set mirrors the xlsx field matrix
-- (more-product-specs/Field summary of Molecular nature of the
-- mutation.xlsx). l_lesion_size_bp is reused as the deletion-side size
-- for Indel rows; l_insertion_size_bp captures the insertion side.
-- l_5prime_flank / l_3prime_flank surface when l_has_large_variant is
-- true (deletion/insertion/indel) and for the Transgene type.
-- l_mutated_amino_acids holds the natural-language note;
-- l_mutated_amino_acids_hgvs holds the formal HGVS.P nomenclature.
CREATE TABLE zirc.lesion (
    l_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    l_mutation_id              BIGINT NOT NULL
        CONSTRAINT fk_lesion_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    l_sort_order               INTEGER NOT NULL,
    l_lesion_type              VARCHAR(255),
    l_lesion_size_bp           INTEGER,
    l_insertion_size_bp        INTEGER,
    l_nucleotide_change        TEXT,
    l_deleted_sequence         TEXT,
    l_inserted_sequence        TEXT,
    l_transgene_sequence       TEXT,
    l_location_inline          TEXT,
    l_5prime_flank             TEXT,
    l_3prime_flank             TEXT,
    l_has_large_variant        BOOLEAN,
    l_mutated_amino_acids      TEXT,
    l_mutated_amino_acids_hgvs TEXT,
    l_additional_info          TEXT
);

-- Genotyping assay: type-specific columns live alongside the shared
-- primer / PCR-product columns. ga_enzyme_cleaves is text[] because the
-- curator may mark both WT and MUT when the enzyme cleaves either
-- template. ga_restriction_enzyme is split into name + catalog.
CREATE TABLE zirc.genotyping_assay (
    ga_id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ga_mutation_id                 BIGINT NOT NULL
        CONSTRAINT fk_genotyping_assay_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    ga_sort_order                  INTEGER NOT NULL,
    ga_assay_type                  VARCHAR(255),
    ga_forward_primer              TEXT,
    ga_reverse_primer              TEXT,
    ga_expected_wt_pcr             TEXT,
    ga_expected_mut_pcr            TEXT,
    ga_sequencing_primer           TEXT,
    ga_dcaps_mismatch_primer       TEXT,
    ga_wt_specific_primer          TEXT,
    ga_mut_specific_primer         TEXT,
    ga_common_primer               TEXT,
    ga_kasp_genomic_sequence       TEXT,
    ga_restriction_enzyme_name     TEXT,
    ga_restriction_enzyme_catalog  TEXT,
    ga_enzyme_cleaves              TEXT[]  NOT NULL DEFAULT '{}',
    ga_expected_wt_digest          TEXT,
    ga_expected_mut_digest         TEXT,
    ga_sslp_marker_name            TEXT,
    ga_sslp_distance               TEXT,
    ga_sslp_genomic_location       TEXT,
    ga_sslp_induced_background     TEXT,
    ga_sslp_outcrossed_background  TEXT,
    ga_sslp_induced_pcr            TEXT,
    ga_sslp_outcrossed_pcr         TEXT,
    ga_additional_info             TEXT
);

-- File uploads attached to a genotyping assay. Storage layout:
-- $TARGETROOT/server_apps/data_transfer/ZIRC/<submission zdb id>/
--   assay-<assay id>-<af_id>-<sanitized original filename>. The
-- server constructs the path; never trust the client.
CREATE TABLE zirc.genotyping_assay_file (
    af_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    af_assay_id          BIGINT NOT NULL
        REFERENCES zirc.genotyping_assay(ga_id) ON DELETE CASCADE,
    af_kind              TEXT NOT NULL
        CHECK (af_kind IN ('chromatogram', 'gel_image', 'result_image', 'melt_curve')),
    af_original_filename TEXT NOT NULL,
    af_stored_path       TEXT NOT NULL,
    af_content_type      TEXT,
    af_file_size         BIGINT,
    af_uploaded_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    af_uploaded_by       VARCHAR(50) REFERENCES person(zdb_id)
);

-- Phenotype timing is a single point (start, no end) or a range (start
-- + end). The hpf vs dpf unit toggle lives on the client; storage is
-- always integer hpf, and dpf-entered values are multiplied by 24
-- before commit. p_stage is a server-managed cache derived from
-- p_hpf_start via the STAGE table — the client renders it read-only.
-- p_zfin_image_permission and p_zirc_image_permission are independent
-- Yes/No questions per the spec ("publish on ZFIN" and "publish on
-- ZIRC" are different consent decisions).
CREATE TABLE zirc.phenotype (
    p_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_mutation_id              BIGINT NOT NULL
        CONSTRAINT fk_phenotype_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    p_sort_order               INTEGER NOT NULL,
    p_description              TEXT,
    p_hpf_start                INTEGER,
    p_hpf_end                  INTEGER,
    p_stage                    VARCHAR(255),
    p_zfin_image_permission    BOOLEAN,
    p_zirc_image_permission    BOOLEAN,
    p_non_mendelian_percentage DOUBLE PRECISION,
    p_non_mendelian_comment    TEXT,
    p_segregation              TEXT[],
    p_type                     TEXT[]
);

-- Linked features: a pairwise linkage between two mutations submitted on
-- the *same* submission. The CHECK enforces distinctness (a != b) and
-- symmetric dedup (a < b) so (mutation_5, mutation_3) and
-- (mutation_3, mutation_5) can't both exist.
CREATE TABLE zirc.line_submission_linked_feature (
    lslf_line_submission_id    TEXT             NOT NULL
        CONSTRAINT fk_line_submission_linked_feature_parent
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    lslf_mutation_a_id         BIGINT           NOT NULL
        CONSTRAINT fk_lslf_mutation_a
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    lslf_mutation_b_id         BIGINT           NOT NULL
        CONSTRAINT fk_lslf_mutation_b
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    lslf_distance_known        BOOLEAN,
    lslf_distance_centimorgans DOUBLE PRECISION,
    lslf_distance_megabases    DOUBLE PRECISION,
    lslf_additional_info       TEXT,
    CONSTRAINT line_submission_linked_feature_pk
        PRIMARY KEY (lslf_line_submission_id, lslf_mutation_a_id, lslf_mutation_b_id),
    CONSTRAINT lslf_normalized_pair
        CHECK (lslf_mutation_a_id < lslf_mutation_b_id)
);

-- ─── Indexes ─────────────────────────────────────────────────────────
-- FK columns that aren't already the leading PK column. lslf_mutation_b
-- has its own entry so ON DELETE CASCADE doesn't have to seq-scan.
CREATE INDEX mutation_line_submission_idx      ON zirc.mutation                       (m_line_submission_id);
CREATE INDEX gene_mutation_idx                 ON zirc.gene                           (g_mutation_id);
CREATE INDEX gene_mutated_gene_idx             ON zirc.gene                           (g_mutated_gene);
CREATE INDEX lesion_mutation_idx               ON zirc.lesion                         (l_mutation_id);
CREATE INDEX genotyping_assay_mutation_idx     ON zirc.genotyping_assay               (ga_mutation_id);
CREATE INDEX genotyping_assay_file_assay_idx   ON zirc.genotyping_assay_file          (af_assay_id);
CREATE INDEX phenotype_mutation_idx            ON zirc.phenotype                      (p_mutation_id);
CREATE INDEX line_submission_person_person_idx ON zirc.line_submission_person         (lsp_person_zdb_id);
CREATE INDEX lslf_mutation_b_idx               ON zirc.line_submission_linked_feature (lslf_mutation_b_id);


-- ─── ZDB ID wiring for LINESUBMISSION ────────────────────────────────
--
-- get_id('LINESUBMISSION') needs both a row in zdb_object_type and a
-- matching <type>_seq sequence; without these the ZdbIdGenerator throws
-- at the SQL level. The home_table lives in the zirc schema, so
-- zobjtype_home_schema must be set explicitly (the column was added by
-- the earlier 0010-ZFIN-10162-zdb-object-type-home-schema.sql migration).
--
-- runOnChange:true so environments that applied an older variant of
-- this row re-run with the corrected body — the ON CONFLICT clause
-- makes the re-run idempotent.
--changeset rtaylor:zirc-line-submission-id-wiring runOnChange:true
INSERT INTO zdb_object_type (
    zobjtype_name, zobjtype_day, zobjtype_home_schema, zobjtype_home_table,
    zobjtype_home_zdb_id_column, zobjtype_is_data, zobjtype_is_source)
VALUES ('LINESUBMISSION', current_date - 1, 'zirc', 'line_submission',
        'ls_zdb_id', true, false)
ON CONFLICT (zobjtype_name) DO UPDATE SET
    zobjtype_home_schema = EXCLUDED.zobjtype_home_schema,
    zobjtype_home_table = EXCLUDED.zobjtype_home_table,
    zobjtype_home_zdb_id_column = EXCLUDED.zobjtype_home_zdb_id_column;

CREATE SEQUENCE IF NOT EXISTS linesubmission_seq START 1;
