--liquibase formatted sql

-- B8e: actual file uploads attached to genotyping assays.
--
-- One child table per parent type. 100% of currently-scoped file uploads
-- attach to a genotyping_assay (chromatograms / gel images / result
-- images / melt curves — varies by assay type per the xlsx matrix).
-- Phenotype images and chromosome diagrams are deferred; when they
-- arrive they'll get their own narrowly-scoped sibling tables rather
-- than a polymorphic owner_type/id pair.
--
-- Storage layout: $TARGETROOT/server_apps/data_transfer/ZIRC/<submission
-- zdb id>/assay-<assay id>-<af_id>-<sanitized original filename>. The
-- server constructs the path; never trust the client.
--
-- The four ga_*_files_available booleans from B8c become redundant —
-- "are gel images available?" is a JOIN COUNT(*) > 0 away. Drop them so
-- there's a single source of truth.

--changeset rtaylor:zirc-b8e-genotyping-assay-file
ALTER TABLE zirc.genotyping_assay
    DROP COLUMN ga_chromatogram_files_available,
    DROP COLUMN ga_gel_images_available,
    DROP COLUMN ga_result_images_available,
    DROP COLUMN ga_melt_curve_files_available;

CREATE TABLE zirc.genotyping_assay_file (
    af_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    af_assay_id          BIGINT NOT NULL
        REFERENCES zirc.genotyping_assay(ga_id) ON DELETE CASCADE,
    -- Which logical kind of file this is in the form's terms.
    -- Constrained to the four kinds the xlsx matrix calls out. New
    -- kinds (gel-image variants, etc.) require a one-line CHECK update.
    af_kind              TEXT NOT NULL
        CHECK (af_kind IN ('chromatogram', 'gel_image', 'result_image', 'melt_curve')),
    af_original_filename TEXT NOT NULL,
    -- Path under $TARGETROOT/server_apps/data_transfer/ZIRC/, server-generated.
    af_stored_path       TEXT NOT NULL,
    af_content_type      TEXT,
    af_file_size         BIGINT,
    af_uploaded_at       TIMESTAMP NOT NULL DEFAULT NOW(),
    af_uploaded_by       VARCHAR(50) REFERENCES person(zdb_id)
);

CREATE INDEX genotyping_assay_file_assay_idx ON zirc.genotyping_assay_file(af_assay_id);
