--liquibase formatted sql

-- ZIRC line submission schema.
-- Source ER diagram: image-20260327-204843.png.
-- Schema review notes: ZFIN-10162 (Ryan Taylor, 2026-04-27 meeting).
--
-- All tables live in the dedicated PostgreSQL schema `zirc`. Cross-zirc FKs are
-- qualified (e.g. zirc.line_submission). FKs out to existing ZFIN tables (person,
-- marker) live in public — left unqualified, resolved via search_path.
--
-- Naming convention: every column is prefixed with the first letters of each word
-- in the table name (line_submission -> ls_, line_submission_linked_feature -> lslf_,
-- genotyping_assay -> ga_). Single-word tables get the first letter (m_, g_, l_, p_).
--
-- Decisions applied (per ZFIN-10162):
--   - line_submission ↔ person association table (zirc.line_submission_person)
--   - ls_name globally unique  (revisit if multi-submitter same-name is desired)
--   - features_linked metadata moved per-feature: distance / cM / Mb / additional_info
--     now on line_submission_linked_feature, not the root
--   - dropped the "unreported_features" gate; kept only ls_unreported_features_details
--   - g_mutated_gene FK'd to public.marker(mrkr_zdb_id)
--   - g_linkage_group is varchar(10) since "NT" is a valid value
--   - p_segregation / p_type are native text[] columns (replaced child tables)
--   - long-text columns are TEXT (no varchar caps)
--   - typo fix: l_index_insertion_size
--   - line_submission PK is a ZFIN-style ZDB ID (text, ZDB-LINESUBMISSION-YYmmdd-NN)
--     generated by org.zfin.database.ZdbIdGenerator at insert time; child PKs are
--     bigint IDENTITY (auto-generated)
--   - all submission-internal FKs ON DELETE CASCADE; FKs to person/marker are RESTRICT
--
-- Still open (pending mockup review):
--   - sister "_other" columns wherever a form field offers "Other"
--   - status column (pending/approved/rejected) and updated_at trigger
--   - versioning / history / comments table

--changeset cmpich:ZIRC-line-submission
CREATE SCHEMA IF NOT EXISTS zirc;

-- Root table. ls_zdb_id is a ZFIN-style ZDB ID (e.g. ZDB-LINESUBMISSION-YYmmdd-NN)
-- generated by org.zfin.database.ZdbIdGenerator at insert time. The generator also
-- inserts the matching row into zdb_active_data, satisfying the FK below.
CREATE TABLE zirc.line_submission (
    ls_zdb_id                        TEXT         PRIMARY KEY
                                                  CONSTRAINT line_submission_zdb_id_active_data_fk
                                                  REFERENCES zdb_active_data(zactvd_zdb_id)
                                                  ON UPDATE RESTRICT ON DELETE CASCADE,
    ls_name                          VARCHAR(255) CONSTRAINT line_submission_name_unique UNIQUE,
    ls_abbreviation                  VARCHAR(255),
    ls_previous_names                VARCHAR(255),
    ls_features_linked               BOOLEAN,
    ls_maternal_background           VARCHAR(255),
    ls_paternal_background           VARCHAR(255),
    ls_background_changeable         BOOLEAN,
    ls_background_change_concerns    TEXT,
    ls_unreported_features_details   TEXT,
    ls_additional_info               TEXT,
    ls_created_at                    TIMESTAMP    NOT NULL DEFAULT now(),
    ls_updated_at                    TIMESTAMP    NOT NULL DEFAULT now()
);

-- Submitters / contacts / PIs / contributors
CREATE TABLE zirc.line_submission_person (
    lsp_line_submission_id TEXT        NOT NULL
        CONSTRAINT fk_line_submission_person_submission
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    lsp_person_zdb_id      TEXT        NOT NULL
        CONSTRAINT fk_line_submission_person_person
            REFERENCES person(zdb_id),
    lsp_role               VARCHAR(50) NOT NULL,
    lsp_sort_order         INTEGER     NOT NULL,
    lsp_created_at         TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT line_submission_person_pk
        PRIMARY KEY (lsp_line_submission_id, lsp_person_zdb_id, lsp_role)
);

-- Multi-row child of line_submission: acceptance reasons
CREATE TABLE zirc.line_submission_reason (
    lsr_line_submission_id TEXT         NOT NULL
        CONSTRAINT fk_line_submission_reason_parent
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    lsr_reason             VARCHAR(255) NOT NULL,
    lsr_sort_order         INTEGER      NOT NULL,
    CONSTRAINT line_submission_reason_pk
        PRIMARY KEY (lsr_line_submission_id, lsr_sort_order)
);

-- Linked features: distance metadata is per-feature, not on the root.
CREATE TABLE zirc.line_submission_linked_feature (
    lslf_line_submission_id    TEXT         NOT NULL
        CONSTRAINT fk_line_submission_linked_feature_parent
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    lslf_feature               VARCHAR(255) NOT NULL,
    lslf_distance_known        BOOLEAN,
    lslf_distance_centimorgans DOUBLE PRECISION,
    lslf_distance_megabases    DOUBLE PRECISION,
    lslf_additional_info       TEXT,
    CONSTRAINT line_submission_linked_feature_pk
        PRIMARY KEY (lslf_line_submission_id, lslf_feature)
);

-- Mutation: per-line, has its own children
CREATE TABLE zirc.mutation (
    m_id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    m_line_submission_id           TEXT   NOT NULL
        CONSTRAINT fk_mutation_line_submission
            REFERENCES zirc.line_submission(ls_zdb_id) ON DELETE CASCADE,
    m_sort_order                   INTEGER NOT NULL,
    m_allele_designation           VARCHAR(255),
    m_mutagenesis_protocol         VARCHAR(255),
    m_molecularly_characterized    BOOLEAN,
    m_mutation_type                VARCHAR(255),
    m_homozygous_lethal            BOOLEAN,
    m_lethality_stage_typical      VARCHAR(255),
    m_lethality_specific_timepoint VARCHAR(255),
    m_lethality_window_start       VARCHAR(255),
    m_lethality_window_end         VARCHAR(255),
    m_lethality_additional_info    TEXT,
    m_zfin_record_established      BOOLEAN,
    m_cell_genomic_feature         VARCHAR(255),
    m_mutation_discoverer          VARCHAR(255),
    m_mutation_institution         VARCHAR(255)
);

-- Multi-row child of mutation
CREATE TABLE zirc.mutation_publication (
    mp_mutation_id BIGINT       NOT NULL
        CONSTRAINT fk_mutation_publication_parent
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    mp_publication VARCHAR(255) NOT NULL,
    mp_sort_order  INTEGER      NOT NULL,
    CONSTRAINT mutation_publication_pk
        PRIMARY KEY (mp_mutation_id, mp_sort_order)
);

-- Per-mutation single-row children
CREATE TABLE zirc.gene (
    g_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    g_mutation_id       BIGINT NOT NULL
        CONSTRAINT fk_gene_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    g_sort_order        INTEGER NOT NULL,
    g_mutated_gene      TEXT
        CONSTRAINT fk_gene_mutated_gene_marker
            REFERENCES marker(mrkr_zdb_id),
    g_linkage_group     VARCHAR(10),
    g_genbank_genomic_dna VARCHAR(255),
    g_genbank_cdna      VARCHAR(255)
);

CREATE TABLE zirc.lesion (
    l_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    l_mutation_id         BIGINT NOT NULL
        CONSTRAINT fk_lesion_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    l_sort_order          INTEGER NOT NULL,
    l_lesion_type         VARCHAR(255),
    l_index_deletion_pos  INTEGER,
    l_index_insertion_size INTEGER,
    l_deleted_base_pairs  TEXT,
    l_inserted_base_pairs TEXT,
    l_wt_genomic_sequence TEXT,
    l_mutated_amino_acids TEXT,
    l_additional_info     TEXT
);

CREATE TABLE zirc.genotyping_assay (
    ga_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ga_mutation_id         BIGINT NOT NULL
        CONSTRAINT fk_genotyping_assay_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    ga_sort_order          INTEGER NOT NULL,
    ga_assay_type          VARCHAR(255),
    ga_forward_primer      TEXT,
    ga_reverse_primer      TEXT,
    ga_expected_wt_pcr     TEXT,
    ga_expected_mut_pcr    TEXT,
    ga_restriction_enzyme  VARCHAR(255),
    ga_enzyme_cleaves      VARCHAR(255),
    ga_expected_wt_digest  TEXT,
    ga_expected_mut_digest TEXT,
    ga_additional_info     TEXT
);

-- Phenotype: p_segregation and p_type are native text[] arrays.
CREATE TABLE zirc.phenotype (
    p_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_mutation_id              BIGINT NOT NULL
        CONSTRAINT fk_phenotype_mutation
            REFERENCES zirc.mutation(m_id) ON DELETE CASCADE,
    p_sort_order               INTEGER NOT NULL,
    p_description              TEXT,
    p_hours_post_fertilization INTEGER,
    p_stage                    VARCHAR(255),
    p_zfin_image_permission    BOOLEAN,
    p_non_mendelian_percentage DOUBLE PRECISION,
    p_segregation              TEXT[],
    p_type                     TEXT[]
);

-- Indexes on FKs that aren't already the leading PK column
CREATE INDEX mutation_line_submission_idx          ON zirc.mutation              (m_line_submission_id);
CREATE INDEX gene_mutation_idx                     ON zirc.gene                  (g_mutation_id);
CREATE INDEX gene_mutated_gene_idx                 ON zirc.gene                  (g_mutated_gene);
CREATE INDEX lesion_mutation_idx                   ON zirc.lesion                (l_mutation_id);
CREATE INDEX genotyping_assay_mutation_idx         ON zirc.genotyping_assay      (ga_mutation_id);
CREATE INDEX phenotype_mutation_idx                ON zirc.phenotype             (p_mutation_id);
CREATE INDEX line_submission_person_person_idx     ON zirc.line_submission_person (lsp_person_zdb_id);
