#------------------------------------------------------------------------
#
# Makefile for ZFIN_WWW CVS Project, Zebrafish Book, Stages figures, 
# really big images.
#
# $Source$
# $Id$
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !! See $(TOP)/Makfile and $(TOP)/make.include for a full explanation !!
# !! of the makefile hierarchy this makefile is a part of, and of the  !!
# !! format and conventions used in this makefile.                     !!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#


# ---------------  Variable Definitions  --------------------------------

TOP = ../../../../../..
include $(TOP)/make.include

TARGETDIR = $(TARGETROOT)/home/zf_info/zfbook/stages/figs/big_images

STATICS = fig._15.1 fig._15.2 fig._29.1 fig._29.2 fig._29.3 fig._3 fig._30 \
	fig._31 fig._4 fig._41 fig._8 fig10.big fig11.big fig12.big fig13.big \
	fig14.big fig15a.big fig15b.big fig16.big fig17.big fig18.big \
	fig19.big fig1a.gif fig1b.gif fig1c.gif fig1d.gif fig2.big fig20.big \
	fig21.big fig22.big fig23.big fig24.big fig25.big fig26.big fig27.big \
	fig28.big fig29a.big fig29d-f.big fig29g-i.big fig3.big fig30.big \
	fig31.big fig32.big fig33.big fig34.big fig35.big fig36.big \
	fig37.big fig38.big fig39.1.eps fig39.2.eps fig39a.gif fig39b.gif \
	fig4.big fig40.big fig41.big fig42.big fig43.big fig5.big fig6.big \
	fig8.big fig9.big fig_11 fig_13


# ---------------  Production Rules  ------------------------------------

# Use default rules for directories without app pages in them.

include $(TOP)/make.default.rules
