-- Sample data for zirc.line_submission.
--
-- Intentionally NOT in the migrations/ directory — the master changelog's
-- <includeAll path=".../1182/migrations/"/> only picks up that subdirectory,
-- so this file is not auto-applied by Liquibase. Run manually when you want
-- to seed the dashboard with example rows.
--
-- Apply with:
--   psql -h 127.0.0.1 -p 5444 -U postgres -d zfindb \
--        -f source/org/zfin/db/postGmakePostloaddb/1182/zirc-line-submission-sample-data.sql
--
-- ls_zdb_id values are generated by the standard ZFIN get_id() function — same
-- path the Java ZdbIdGenerator uses at runtime. get_id() prepends 'ZDB-' itself,
-- so we pass the bare type name 'LINESUBMISSION'. It does NOT insert into
-- zdb_active_data, so we do that explicitly per row to satisfy the FK from
-- zirc.line_submission(ls_zdb_id) -> zdb_active_data(zactvd_zdb_id).
--
-- Idempotent on ls_name: rows are skipped if already present, so no IDs are
-- wasted on re-runs.

-- Prerequisites for get_id('LINESUBMISSION'): the type must exist in
-- zdb_object_type and have a matching <type>_seq sequence. Both are created
-- here so this seed is self-contained.
-- The trigger on zdb_object_type validates the home-table name against
-- pg_tables.tablename (unqualified). Pass just 'line_submission'; it resolves
-- to zirc.line_submission via pg_tables regardless of schema.
INSERT INTO zdb_object_type (
    zobjtype_name, zobjtype_day, zobjtype_home_table,
    zobjtype_home_zdb_id_column, zobjtype_is_data, zobjtype_is_source)
VALUES ('LINESUBMISSION', current_date - 1, 'line_submission',
        'ls_zdb_id', true, false)
ON CONFLICT (zobjtype_name) DO NOTHING;

CREATE SEQUENCE IF NOT EXISTS linesubmission_seq START 1;

-- Insert sample rows. For each missing ls_name, generate a fresh ZDB ID,
-- record it in zdb_active_data, then insert the line_submission row and an
-- "owner" line_submission_person row.
-- ZDB-PERS-251006-1 = "A, Dharani" — substitute another person if needed.
DO $$
DECLARE
    v_zdb_id text;
    rec      record;
BEGIN
    FOR rec IN
        SELECT *
        FROM (VALUES
            ('myh7 CRISPR knockout', 'myh7-ko', 'myh7-cr-001', false,
             'AB', 'AB', true, NULL, NULL,
             'Generated via Cas9 RNP injection at 1-cell stage; founders confirmed by HRMA.'),

            ('tbx5a hypomorph allele', 'tbx5a-hy', NULL, false,
             'TL', 'AB', false,
             'Cardiac phenotype is sensitive to background — please retain TL/AB cross.',
             NULL,
             'Adult heterozygotes show mild cardiac edema; homozygotes embryonic lethal at ~72 hpf.'),

            ('Tg(myl7:GFP) reporter', 'Tg(myl7:GFP)', 'myl7-GFP-line-A', false,
             'AB', 'AB', true, NULL, NULL,
             'Stable transgenic line; GFP visible in cardiomyocytes from 24 hpf.'),

            ('cdh2 / N-cadherin null', 'cdh2-null', 'parachute', false,
             'AB', 'AB', true, NULL, NULL,
             'Originally isolated by ENU mutagenesis; re-derived on AB background. Embryonic lethal homozygous.'),

            ('fgf8a;ace double mutant', 'fgf8a;ace', NULL, true,
             'AB', 'AB', false,
             'Two linked features — distance metadata captured in line_submission_linked_feature.',
             NULL,
             'Genetic interaction study; distance between loci ~3.2 cM.'),

            ('myod1 deletion line (incomplete)', 'myod1-del', NULL, NULL,
             NULL, NULL, NULL, NULL,
             'Submission in progress — waiting on lab to confirm background and lethality.',
             NULL)
        ) AS v(ls_name, ls_abbreviation, ls_previous_names, ls_features_linked,
               ls_maternal_background, ls_paternal_background, ls_background_changeable,
               ls_background_change_concerns, ls_unreported_features_details, ls_additional_info)
        WHERE NOT EXISTS (
            SELECT 1 FROM zirc.line_submission ex WHERE ex.ls_name = v.ls_name
        )
    LOOP
        v_zdb_id := get_id('LINESUBMISSION');

        INSERT INTO zdb_active_data (zactvd_zdb_id) VALUES (v_zdb_id);

        INSERT INTO zirc.line_submission (
            ls_zdb_id, ls_name, ls_abbreviation, ls_previous_names, ls_features_linked,
            ls_maternal_background, ls_paternal_background, ls_background_changeable,
            ls_background_change_concerns, ls_unreported_features_details, ls_additional_info)
        VALUES (
            v_zdb_id, rec.ls_name, rec.ls_abbreviation, rec.ls_previous_names, rec.ls_features_linked,
            rec.ls_maternal_background, rec.ls_paternal_background, rec.ls_background_changeable,
            rec.ls_background_change_concerns, rec.ls_unreported_features_details, rec.ls_additional_info);

        INSERT INTO zirc.line_submission_person (
            lsp_line_submission_id, lsp_person_zdb_id, lsp_role, lsp_sort_order)
        VALUES (v_zdb_id, 'ZDB-PERS-251006-1', 'owner', 1);
    END LOOP;
END $$;

-- Show what's in the table after seeding
\echo === zirc.line_submission contents (with owner) ===
SELECT ls.ls_zdb_id,
       ls.ls_name,
       ls.ls_abbreviation,
       ls.ls_features_linked,
       ls.ls_created_at::date AS created,
       p.full_name AS owner
FROM zirc.line_submission ls
LEFT JOIN zirc.line_submission_person lsp
    ON lsp.lsp_line_submission_id = ls.ls_zdb_id AND lsp.lsp_role = 'owner'
LEFT JOIN person p ON p.zdb_id = lsp.lsp_person_zdb_id
ORDER BY ls.ls_zdb_id;
