--liquibase formatted sql
--changeset sierra:removeConstructMart

drop index construct_search_all_names_bts_index;
drop index construct_component_search_all_coding_names_bts_index;
drop index construct_component_search_all_engineered_names_bts_index;
drop index construct_component_search_all_promoter_names_bts_index;

drop index construct_gene_feature_result_view_all_allele_gene_names_bts_index;
drop index figure_term_construct_search_bts_index;

drop index construct_search_temp_all_names_bts_index;
drop index construct_component_search_temp_all_coding_names_bts_index;
drop index construct_component_search_temp_all_engineered_names_bts_index;
drop index construct_component_search_temp_all_promoter_names_bts_index;

drop index construct_gene_feature_result_view_temp_all_allele_gene_names_bts_index;
drop index figure_term_construct_search_temp_bts_index;

alter table person
 drop snapshot;

alter table company
 drop snapshot;

alter table lab
 drop snapshot;

drop table construct_gene_feature_result_view;

drop table construct_gene_feature_result_view_backup;

drop table construct_gene_feature_result_view_temp;

drop table construct_group;

drop table construct_search;

drop table construct_search_backup;

drop table construct_search_temp;


